### ISSUE TITLE
gluster plugin does not capture logrotated files

### ISSUE THREAD

**Issue by nbalacha** [sosreport/sos#1003]
if limit:
            for f in (glob.glob("/var/log/glusterfs/*log") +
                      glob.glob("/var/log/glusterfs/*/*log") +
                      glob.glob("/var/log/glusterfs/geo-replication/*/*log")):
                self.add_copy_spec(f, limit)
        else: 

Will not include log rotated files (*.log-<date> ) even if the limits have not been reached.

**Comment by bmr-cymru** [comment]
It's not suppsed to.

If you read the lines that come immediately before, and after, the block that you have quoted you will see that that branch is taken only in case the global `--all-logs` option was not given: in this case, `sos` plugins are only supposed to collect non-rotated logs.

If `--all-logs` **is** given, then the `else` branch you skipped will be taken, and the entire `/var/log/glusterfs` will be collected:

```python
        # collect logs - apply log_size for any individual file
        # all_logs takes precedence over logsize
        if not self.get_option("all_logs"):
            limit = self.get_option("log_size")
        else:
            limit = 0

        if limit:
            for f in (glob.glob("/var/log/glusterfs/*log") +
                      glob.glob("/var/log/glusterfs/*/*log") +
                      glob.glob("/var/log/glusterfs/geo-replication/*/*log")):
                self.add_copy_spec(f, limit)
        else:
            self.add_copy_spec("/var/log/glusterfs")
```

**Comment by nbalacha** [comment]
"in this case, sos plugins are only supposed to collect non-rotated logs."

Why should this be the case? The limit is not necessarily hit with a single log and we have seen issues with sos reports not containing useful logs because the log rotated ones are not captured.

**Comment by nbalacha** [comment]
This is also widely differing behaviour compared to older sos report utilities. The man page:
--all-logs
              Tell plugins to collect all possible log data ignoring any size limits and including logs in non-default locations. This option may significantly increase the size of reports

However this does not specify that log-rotated files (in the same location) are not captured without this option.

**Comment by bmr-cymru** [comment]
> This is also widely differing behaviour compared to older sos report utilities.

That is because the gluster plugin was buggy and did not correctly implement the global `log-size` and `all-logs` options.

> Why should this be the case? The limit is not necessarily hit with a single log and we have seen issues with sos reports not containing useful logs because the log rotated ones are not captured.

If you need rotated logs you should ask users to specify `--all-logs`.
