### ISSUE TITLE
[ceph] /var/lib/ceph/tmp path not excluded

### ISSUE THREAD

**Issue by haklein** [sosreport/sos#1006]
/var/lib/ceph/tmp is not added as forbidden path. ceph disk activation first mounts the OSD filesystem below this tmp before it later mounts it on the final place. If this remount fails, the OSD filesystem is still mounted below the tmp path. Hence sosreport tries to collect all the OSD data files. The following additional forbidden path will avoid this:

```python
self.add_forbidden_path("/var/lib/ceph/tmp/*")
```

**Comment by battlemidget** [comment]
This PR was opened for this bug https://github.com/sosreport/sos/pull/1005
