### ISSUE TITLE
Enable sos to capture kernel crash report/summary

### ISSUE THREAD

**Issue by ankitkumar2391** [sosreport/sos#1020]
Pull request : https://github.com/sosreport/sos/pull/1019

Idea is to enable sosreport to run crash tool on latest kernel dump and generate summary from kernel dump (Mostly it contains kernel calltrace, stack info, etc,).  In our experience with this summary we are able to debug ~60% of the issues.

Advantage :
    With single sosreport output we will be able to debug most of the kernel issues as well.
    We can possibly avoid shipping kernel dump from customer site

Limitations :
    crash tool needs debug kernel on running system. So if debug kernel is not installed we just come out with error message.
    Running crash tool on kernel dump takes some time

**Comment by TurboTurtle** [comment]
Closing per #1028 - again, if this functionality is still needed by support teams, please update the changes to be based on the current `master` branch and open a new PR for a fresh review cycle.
