### ISSUE TITLE
add github pr template

### ISSUE THREAD

**Issue by battlemidget** [sosreport/sos#1021]
A lot of PR's are created that are unaware of our contributor guidelines. Should we utilize githubs pr and issue template to help alleviate some of this?

https://github.com/blog/2111-issue-and-pull-request-templates

@bmr-cymru thoughts?

**Comment by bmr-cymru** [comment]
👍 I like it!

I've seen some projects using a bot for this, which I've avoided because it seemed like massive overkill for something so simple.

This seems to strike a nice balance.
