### ISSUE TITLE
change the way we handle approving PR's

### ISSUE THREAD

**Issue by battlemidget** [sosreport/sos#1022]
Previously we'd utilize the tags for indicating that a PR was ready for merge. Now that GitHub has its own review process should we switch to having 2 reviewers attached to a PR and a required signoff from them both? The tags made it easy to see which one's needed a second review and would like to hear everyone elses thoughts.

**Comment by bmr-cymru** [comment]
Ack: I think this makes a bunch of sense.

We can still use the tags for cases that aren't represented in the GH review system (e.g. "Missing DCO"), but we can use the review mechanism for the primary accept/reject processing.

**Comment by bmr-cymru** [comment]
/me adds the "Needs second ACK" tag :-D :-D

**Comment by battlemidget** [comment]
\o/, I'll write some documentation on the wiki to cover that new process and will close this out once that's reviewed and ready.

**Comment by bmr-cymru** [comment]
Sweet, thanks!

**Comment by battlemidget** [comment]
I updated the wiki here https://github.com/sosreport/sos/wiki/Contribution-Guidelines#maintainers 

I feel like it could use some more information there but I suck at writing :) @bmr-cymru lemme know what you think and we can close this out then

**Comment by BryanQuigley** [comment]
Docs have been updated over time, closing this issue.
