### ISSUE TITLE
sos D-Bus interface

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#105]
Sos currently provides only a command-line interface. Several components already call sosreport from programs via shelling out (e.g. RHEV logCollector, ABRT).

Interaction with these components would be simplified by providing a basic interface to sosreport functionality via D-Bus.

The interface should allow:
- set ticket number
- set customer name
- set configuration path
- enumerate module set and options
- enable and disable modules
- specify module options
- specify log verbosity
- receive log stream
- set tmp directory
- enable / disable reporting
- obtain tarball path or receive content as stream

**Comment by TurboTurtle** [comment]
Perhaps I'm missing something here, but wouldn't this require a constantly listening process for sos on the bus? As far as I've personally ever dug into D-Bus, I thought it didn't provide for ad-hoc command execution directly?

As in, even if we created a d-bus interface for sos, _something_ would need to be listening on that bus to trigger the execution, even if that something were a bash script looping on `dbus-listen`? If that is in fact the case, how were we looking to implement this?

**Comment by TurboTurtle** [comment]
Ok, so following an IRC conversation with @bmr-cymru the question is - is this worth it?

This could be done via systemd socket activation via dbus, but that would still mean we'd want a local API implemented first. That's a lot of work, and at the moment there are only a couple use cases that come to mind:

1. Report generating from non-root processes
2. Potentially cleaner way for `sos collect` to generate reports on the remote node

However, with point 2, there'd still need to be something to talk to dbus on the remote nodes. Again, this all points back to probably needing/wanting a local python API for sos.

So let's talk this out a bit more -

1. Is this something we still want to pursue, or should we just close this out?
2. If we do want to pursue it, what are our targeted use cases?
3. Further, what does a local API look like for us?


We'll give this some more time to remain open for discussion before making a call on if this is something we want to implement or not.

**Comment by bmr-cymru** [comment]
I was thinking about this some more and I wondered if the current interest was more in a DBus interface that would accept an `sos report` command line, and proceed from there? That's a heck of a lot quicker to implement than a true programmatic interface/API and perhaps it does solve some useful problems - it's not the case that I was thinking of when I filed this issue, but that's >7 years ago now and things move on.

**Comment by TurboTurtle** [comment]
That wasn't exactly my thought here, but it does have some apparent advantages in terms of time-to-implement.

However, at that point is it even really worth providing that kind of interface if consumers still need to generate a command line invocation?

**Comment by TurboTurtle** [comment]
I think at this point, we can put a lid on this one. If there is renewed interest in a d-bus interface in the future, please feel free to re-open this Issue or open a new one.
