### ISSUE TITLE
[openstack_horizon] Enhance plugin to gather enabled dashboard

### ISSUE THREAD

**Issue by iranzo** [sosreport/sos#1055]
Include output of `ls -la  /usr/share/openstack-dashboard/openstack_dashboard/local/enabled/`

**Comment by psachin** [comment]
We are copying files from `/etc/openstack-dashboard` and I see `/etc/openstack-dashboard/enabled/` has files symlink to `/usr/share/openstack-dashboard/openstack_dashboard/local/enabled/`

**Comment by iranzo** [comment]
Closing this one then
