### ISSUE TITLE
[grub2] should grub2-mkconfig be called with system environment

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#1070]
Right now when running `grub2` we substitute an environment that contains *only* the `GRUB_DISABLE_OS_PROBER` variable:

```python
        # call grub2-mkconfig with GRUB_DISABLE_OS_PROBER=true to prevent
        # possible unwanted loading of some kernel modules
        env = {}
        env['GRUB_DISABLE_OS_PROBER'] = 'true'
        self.add_command_output("grub2-mkconfig", env=env)
```

It's possible this will yield different behaviour than when run with the existing environment plus the `GRUB_DISABLE_OS_PROBER` value.

**Comment by TurboTurtle** [comment]
As of fb72623, the env vars used to run a command are now always a fresh copy of the existing `os.environ`, and new keys are added to that, rather than replacing it.

So I think this is no longer an issue? Unless I'm seriously misunderstanding something.

**Comment by bmr-cymru** [comment]
No, I think you're right: the plugin could be tidied up though to do something like:

```python
    self.add_command_output("grub2-mkconfig", env={'GRUB_DISABLE_OS_PROBER':'true'})
```

Although it's not a big deal.
