### ISSUE TITLE
SystemContainer Plugin

### ISSUE THREAD

**Issue by sferich888** [sosreport/sos#1072]
With the advent of System containers (http://www.projectatomic.io/blog/2016/09/intro-to-system-containers/) it would be prudent of sos to include a plugin that genericly pulls data from any installed system containers. 

As an overview of what should be collected, I think the following works as an outline: 

- /var/lib/containers/atomic/$NAME.0/config.json
- /var/lib/containers/atomic/$NAME.0/manifest.json
- /etc/systemd/system/$NAME.service
- /var/lib/containers/atomic/$NAME.0/tmpfiles

These links will be symlinks from /var/lib/containers/atomic/$NAME.0/ to /var/lib/containers/atomic/$NAME/  where $NAME denotes the latest or active version. 

The plugin should also collect: 

journalctl output for logs (likely collected by [logs plugin](https://github.com/sosreport/sos/blob/master/sos/plugins/logs.py))
systemd status for container status (likely collected by [systemd plugin](https://github.com/sosreport/sos/blob/master/sos/plugins/systemd.py))

data from the “root file system”: /var/lib/containers/$NAME/rootfs

mount information from inside the container: 
```
nsenter -m -u -i -n -t $PID_OF_DOCKERFILE_CMD $CMD_TO_RUN_IN_THE_NAMESPACE
```
- This same technique can be used to get other information from the specific container. 

Whats not clear at this point is if this should be 1 generic plugin that finds, system containers on a system, and collects this information, or if specific plugins for specific containers need to be created (looking for advice).

**Comment by TurboTurtle** [comment]
My understanding is that system containers as described have been abandoned. Closing this out, feel free to re-open this if I am mistaken.
