### ISSUE TITLE
Sync naming from ironic-discoverd to ironic-inspector

### ISSUE THREAD

**Issue by dparalen** [sosreport/sos#1073]
The [ironic-discoverd was renamed to ironic-inspector](https://docs.openstack.org/ironic-inspector/latest/#introduction) back in Liberty, however, the SOS report doesn't support the newer name; see e.g [the openstack_ironic](https://github.com/sosreport/sos/blob/master/sos/plugins/openstack_ironic.py#L93,#L109) plugin.

Preferably, the issue would be resolved in a backwards-compatible fashion as there are still people using the older service versions.

**Comment by bmr-cymru** [comment]
What is the status of the rename? I.e. are there still deployed systems using the old naming?

**Comment by dparalen** [comment]
That is the case actually, at least for Red Hat.

**Comment by bmr-cymru** [comment]
Then we cannot replace the old versions yet.

**Comment by dparalen** [comment]
I've updated the issue description, I hope it makes more sense this way ;)

Thanks,
milan

**Comment by TurboTurtle** [comment]
Closing, as this appears to have been addressed in #1129
