### ISSUE TITLE
[ovirt] Passwords are not obfuscated for backup copies of config files

### ISSUE THREAD

**Issue by TurboTurtle** [sosreport/sos#1074]
If a system has a copy of a config file under /etc/ovirt-engine that is of the same name with an added string (e.g. `/etc/ovirt-engine/engine.conf.d/10-setup-pki.conf` and `/etc/ovirt-engine/engine.conf.d/10-setup-pki.conf.20170819`) then the copy does not have the passwords obfuscated.

For example:

```
[root@rhev40dbv1 engine.conf.d]# pwd
/root/sostest/sosreport-rhev40dbv1.gsslab.rdu2.redhat.com-20170820131931/etc/ovirt-engine/engine.conf.d

[root@rhev40dbv1 engine.conf.d]# ls
10-rhevm-doc.conf           10-setup-jboss.conf            11-setup-sso.conf
10-setup-database.conf      10-setup-pki.conf              20-branding-rhev.conf
10-setup-dwh-database.conf  10-setup-pki.conf.20170819tmp  50-ovirt-engine-extension-aaa-jdbc.conf
10-setup-java.conf          10-setup-protocols.conf        README


[root@rhev40dbv1 engine.conf.d]# grep -i password 10-setup-pki.conf
ENGINE_PKI_TRUST_STORE_PASSWORD=********
ENGINE_PKI_ENGINE_STORE_PASSWORD=********
ENGINE_HTTPS_PKI_TRUST_STORE_PASSWORD="${ENGINE_PKI_TRUST_STORE_PASSWORD}"
[root@rhev40dbv1 engine.conf.d]# grep -i password 10-setup-pki.conf.20170819tmp 
ENGINE_PKI_TRUST_STORE_PASSWORD="mypass"
ENGINE_PKI_ENGINE_STORE_PASSWORD="mypass"
ENGINE_HTTPS_PKI_TRUST_STORE_PASSWORD="${ENGINE_PKI_TRUST_STORE_PASSWORD}"
```

**Comment by bmr-cymru** [comment]
What are these 'backup' files created by, and are they of any use in the report? IoW: are they created by some part of oVirt itself, or were these made by an administrator?

We can tighten the copy spec to only collect `.conf` if they are not useful. If they are and the extension varies then we'll have to do a regex replace on  everything `.*\.conf.*`.

**Comment by sandrobonazzola** [comment]
@bmr-cymru backup of config files are generated when engine-setup is executed and it changes existing file. They're  generated for rollback purpose and for keeping an history of the configuration of the system.
I think it's ok to include them but we should filter the with the same regex used by the .conf file.

**Comment by bmr-cymru** [comment]
> backup of config files are generated when engine-setup is executed 

That's entirely at odds with what @TurboTurtle said in pull #1075 (that these are "entirely user created.").

That matters, and it seems there is some confusion over this - before I commit to anything I would really like to see confirmation of both the fact that they are automated artefacts created by the component itself, and what the naming convention(s) used are (either a documentation or code link would be adequate).

**Comment by TurboTurtle** [comment]
@bmr-cymru since @sandrobonazzola is an actual dev for ovirt, I would defer to his knowledge on this one. I have not personally ever seen engine-setup created backup files land in /etc/ovirt-engine (other directories yes, but not there), so perhaps there is a bug there.
