### ISSUE TITLE
[origin] collect stats data on nodes 

### ISSUE THREAD

**Issue by sferich888** [sosreport/sos#1076]
It is sometimes important to have data on what information is being collected (by components) of openshift/origin, to debug if those components are working correctly. 

https://docs.openshift.com/container-platform/latest/admin_guide/allocating_node_resources.html#system-resources-reported-by-node
https://access.redhat.com/node/3158241/ 

It would be good if we had the option / ability to collect data, about the metrics reported from the nodes (cadvisor), included with the sosreport data collected by this plugin.

**Comment by codificat** [comment]
This probably belongs more to the kubernetes plugin than the origin plugin...

A `kubectl get --raw /metrics' should give you metrics from the master, where `kubectl get --raw /api/v1/nodes/NODE/proxy/metrics` would collect them for a specific `NODE`. The first (master) is straightforward to add to the kubernetes plugin; the latter is more involved and would require processing the list of nodes. Do we want to always collect this info from all nodes in the cluster?

**Comment by TurboTurtle** [comment]
Closing this issue.

The `kubernetes` plugin currently collects metrics from the master node as of #1099, and for the past 2+ years there has been no indication here or elsewhere that metrics from the nodes are needed/desired.
