### ISSUE TITLE
disable plugins from a plugin

### ISSUE THREAD

**Issue by brianjmurrell** [sosreport/sos#1091]
If I wanted to write a plugin that collected information of use to me, but disabled collecting information of no use to me (i.e. from other plugins), can I do this from a plugin?

IOW, can I write my plugin in a way as to enable and disable other plugins?

**Comment by pmoravec** [comment]
That is not possible and IMHO not desired.

Not possible since plugins are being enabled in one shot, by simple rules "does the system contain a package from the plugin's list `packages`? Or does it contain a file from the plugin's list `files`?". Plugins are independent on each other.

Not desired: it would be impossible to resolve enable/disable dependencies among plugins. Assume plugin A (once enabled) wants to enable plugin B that (once enabled) wants to disable plugin A - shall be plugin B enabled? (I guess there is even more controversial / unfeasible dependencies example).

**Comment by pmoravec** [comment]
Maybe if you describe your user story (or devel story, rather) why one plugin needs to enable or disable another one, to better understand what you try to achieve?

**Comment by brianjmurrell** [comment]
Well, it's simply a case of an example _sosreport_ tarfile from my F26 machine, even _xz_ compressed is 40MB full of stuff that I am not really interested in.

Probably an alternate configuration file is what I am after.

**Comment by pmoravec** [comment]
If you know you are (not) interested in some data collected, you can use these command line options:

    sosreport --help
    ..
      -l, --list-plugins    list plugins and available plugin options
      -n NOPLUGINS, --skip-plugins=NOPLUGINS
                            disable these plugins
    ..
      -e ENABLEPLUGINS, --enable-plugins=ENABLEPLUGINS
                            enable these plugins
      -o ONLYPLUGINS, --only-plugins=ONLYPLUGINS
                            enable these plugins only
      -k PLUGOPTS, --plugin-option=PLUGOPTS
                            plugin options in plugname.option=value format (see
                            -l)

**Comment by brianjmurrell** [comment]
@pmoravec Indeed.  But I'm also not looking to ask my users to type in command lines of hundreds of characters long.  I could wrap in a script I suppose.  But an alternate config file seems just as easy.

Thanks for the suggestions.

**Comment by bmr-cymru** [comment]
Please check out plugin profiles and see if they could meet your needs. A profile is just a name to which individual plugins can attach themselves. If the user selects a profile on the command line then only plugins that are a member of that profile will be executed.

For e.g. there are currently built-in profile definitions for `boot`, `cluster`, `debug`, `desktop`, `gpu`, `hardware`, `identity`, `java`, `kernel`, `memory`, `mrg`, `network`, `nfs`, `openshift`, `packagemanager`, `performance`, `perl`, `security`, `services`, `storage`, `sysmgmt`, `system`, `virt`, and `webserver` that select plugins relevant to those areas.

We have previously disucssed adding a mechanism for "user profiles" (and equivalently "distribution profiles", defined by the packager of `sos), which would allow a user to define additional named profiles and the plugins they correspond to.

Pavel is correct in that a mechanism to disable other plugins is not something we would want to add to the plugin API: for one thing it would force us to establish some kind of ordering and precedence between plugins (what if two plugins try to mutually disable one another?), but also it breaks the model of plugins being independent units of execution in sos.

If either the existing profile mechanism, or a future user defined profile feature would help then that's something that we can act on.

**Comment by bmr-cymru** [comment]
> Well, it's simply a case of an example sosreport tarfile from my F26 machine, even xz compressed is 40MB
> full of stuff that I am not really interested in.

I'd be interested to know what's inflating the size of your reports - I don't expect them to be that large in a typical installation. For comparison on an ageing f24 box with around 4000 packages installed and with some logs going back over a year I see a compressed report of around 20MiB and runtime in the 1m30 region.

If you're willing to share some details from the reports (we probably don't need any of the actual data) we may be able to come up with some more sensible defaults to get that down a bit.

**Comment by brianjmurrell** [comment]
> I'd be interested to know what's inflating the size of your reports

```
-rw-r--r-- root/root 581705688 2017-09-06 10:46 sosreport-pc.example.com-20170906104317/sos_commands/logs/journalctl_--no-pager_--all_--boot_--output_verbose
```

**Comment by bmr-cymru** [comment]
OK. That's a potentially straightforward fix in that case; I added this command at Lennart Poettering's request when we first added `journald` support to sos. Although I don't see it inflating too badly on test systems here this isn't the first report I've received of it getting large, and it's really not that interesting for most cases - I'll canvass around at Red Hat to see if anyone has any objections, but I'm inclined to move this behind the `--all-logs` switch: it's really the kind of lengthy/verbose data that belongs to that mode.

We already collect `--this-boot` data, as well as the last three days of journal output on Fedora systems so I think pulling this in by default is genuinely overkill.

**Comment by pmoravec** [comment]
+1 to put the verbose log under --all-logs option only. `journalctl_--no-pager_--boot` is great and IMHO sufficient for default use.

**Comment by bmr-cymru** [comment]
I spoke to a few folks in different areas of product support and there seemed to be general agreement - for Red Hat at least, for now the most important journal logs are those collected explicitly in various plugins via the `add_journal()` interface. We may need to look again when the entire distribution switches to `journald` (not until whatever comes after seven may be ;) but I think this will just pull in the Fedora changes which we already handle in `RedHatLogs`.

**Comment by TurboTurtle** [comment]
Closing this due to the stated functionality not being in sos' design, and the motivation behind the request being solved a while back with regards to that specific journal command and the improved size limiting we have today.
