### ISSUE TITLE
Support specifying command as list of arguments instead of string

### ISSUE THREAD

**Issue by nirs** [sosreport/sos#1101]
sos_get_command_output is assuming that command is a string, spiting the string to list of arguments using shelx.split and calling Popen with the list of arguments.

In vdsm sos plugin we have to call lvm commands with a complex configuration like:

```
LVM_CONF = 'devices { filter=[ "a|^/dev/mapper/.*|", "r|.*|" ] }'
```

This is trivial using list of arguments. We append this configuration to several lvm commands like this:

```
command = ["lvs", "-o", "+tags"]
...
command.extend(("--config", LVM_CONF))
```

Adding timeout command for this is also trivial:

     command = ["timeout", "%d" % timeout] + command

When working with strings, this becomes more tricky - we need to do internal quoting:

```
command = "lvs -o +tags" + " --config \'%s\'" % LVM_CONF
```

Next string manipulation on this may break the quoting, this is not maintainable.

We need a way to specify a command as list of arguments, same way as Popen.__init__.

When a list of arguments is provided, I don't think there should be any processing of the arguments as done today:

```
142     # Expand arguments that are wildcard paths.
143     expanded_args = []
144     for arg in args:
145         expanded_arg = glob.glob(arg)
146         if expanded_arg:
147             expanded_args.extend(expanded_arg)
148         else:
149             expanded_args.append(arg)

```

This kind of magic is probably not expected by users and may break user command.

**Comment by bmr-cymru** [comment]
> This kind of magic is probably not expected by users and may break user command.

Actually this is deliberate, and is not likely to change (although we will try to make it work with list/string arg forms).

This is partly historic, and partly based on common plugin behaviour.

Many years ago `sos` ran all commands under a shell. Apart from being inefficient this exposed the tool to potential security problems through shell expansion and environmental controls. When we disabled the use of a shell we retained the expansion of glob expressions in arguments to simplify plugin development and to allow behaviour that was then (and now) relied on by many plugins.

We've never had reports of this causing problems to date, but if it does there are ways that we can approach that. I'd rather not force all plugins executing commands to explicitly glob-expand all arguments first. For one thing it would require a lot of edits to ~200 plugins. We could offer a mechanism  to disable it for particular calls where it is not desired (or where escaping characters that would be mistaken for globs is tedious).

Btw the vdsm plugin does not currently disable the shell when calling `Popen` so depending on the way it is run may be subject to some of the same shell related problems.

**Comment by nirs** [comment]
Vdsm plugin does not disable the shell since it is disabled by default.

**Comment by bmr-cymru** [comment]
Duh, of course it is. We just left the `shell=False` in utilities to make it clear that it's intended.

**Comment by nirs** [comment]
I opened #1102 for the glob issues.

**Comment by TurboTurtle** [comment]
Closing this per Bryn's comments above.
