### ISSUE TITLE
Improve "How to Write a Plugin" wiki page

### ISSUE THREAD

**Issue by kgaillot** [sosreport/sos#1105]
(This is a low priority request ...)

"The bare minimum": For newbies like myself, it would be nice to have a short description of what a tagging superclass is. For example, "Tagging superclasses do not provide any functionality of their own, but determine what plugins are used for the '--list-plugins' and '--alloptions' options" or whatever they do. Maybe also list the available tagging superclasses (or how to find them in the code).

A brief description of what "profiles" are would be helpful

"Cross Platform Plugins": The correct member is "plugin_name", not "name"

A new section for "Options" (like the option_list comment/example in example.py) would be helpful. Also what effect slow vs fast has

**Comment by bmr-cymru** [comment]
For plugin options, please see the [plugin options](https://github.com/sosreport/sos/wiki/Plugin-options) wiki entry - this covers both plugin options (`-k/--plugin-option`), and the newer global plugin options (`--log-size`, `--all-logs` etc). It should have a link from the main plugin page though - I'd rather not merge them together though as the plugin guide is already quite lengthy.

We can add an explanation of tagging superclasses - it's pretty simple (I guess when Jesse wrote that he felt it was obvious from the usage, but it definitely doesn't hurt to give a bit more explanation, especially as the policies are a bit more complex these days). Tagging classes connect plugin classes to policies: a policy defines a set of acceptable tagging classes (usually one of the Red Hat or Debian distro families), and when it is active restricts the set of loadable plugins to those that include the specified tagging class. It's used both to enable a plugin for a distribution, and to allow differentiation in the case that the same plugin needs to behave differently according to the active policy (i.e. where there is a separate class definition for e.g. `RedHatPlugin` and `DebianPlugin`).

For profiles the man page and the original commit message probably provide the most complete documentation: we can add this to the wiki as well. It's just a mechanism that allows plugins to declare that they should be enabled if a particular named "profile" is active:

```
commit 01564fb0130168e2718eaf56d1dc722910fabded
Author: Bryn M. Reeves <bmr@redhat.com>
Date:   Sun Sep 14 11:28:31 2014 +0100

    [plugins] add initial profile tags to all plugins
    
    Add an initial profile tag list to each plugin base class. A tag
    list is a tuple of strings indicating the set of profiles that
    should select this plugin, e.g.:
    
        plugin_name = "qux"
        profiles = ('system', 'storage', 'foo)
    
    A follow up patch will add infrastructure to use these tag lists
    to allow the user to select a logically-related set of plugins by
    specifying a profile on the command line:
    
        # sosreport -v --batch --profile=storage
```

The `--profile` and `--list-profiles` switches are documented in `sosreport(8)`:

```
       --list-profiles
              Display a list of available profiles and the plugins that they enable.

       -p, --profile NAME
              Only run plugins that correspond to the given profile. Multple profiles may
              be specified as a comma-separated list; the set of plugins executed is the
              union of each of  the  profile's  plugin sets.  Currently  defined  profiles
              include: boot, cluster, desktop, debug, hardware, identity, network, openstack,
              packagemanager, security, services, storage, sysmgmt, system, performance,
              virt, and webserver.

> Also what effect slow vs fast has

None at all. It's a half-baked and very old feature that was never well thought out. We plan to remove it in a future release.

We'll get the other errors in the plugin guide you mention fixed up.

**Comment by TurboTurtle** [comment]
Closing this as related to #2290 - recently updated the plugin wiki page specifically.
