### ISSUE TITLE
Request for BTRFS plugin

### ISSUE THREAD

**Issue by KellenRenshaw** [sosreport/sos#1112]
It would be helpful if btrfs collected information on BTRFS filesystems (if present).

Some commands that would be useful (in no particular order):
btrfs filesystem usage <mount point>
btrfs fi show <mount point>
btrfs qgroup show -pcre <mount point>
btrfs subvolume list -a <mount point>

There may well be others that are useful as well.

@BryanQuigley

**Comment by BryanQuigley** [comment]
@KellenRenshaw 
Am I missing it or do some btrfs commands need you to specify a path and other don't?  Would the commands in the commit above have captured what you needed?

**Comment by KellenRenshaw** [comment]
Oops, I failed to see that my formatting got eaten.
`btrfs filesystem usage <mount point>
btrfs fi show <mount point>
btrfs qgroup show -pcre <mount point>
btrfs subvolume list -a <mount point>`

Those should all have a mount point specified. I was think something that grabbed all the mounted btrfs filesystems from /proc/mounts and running those commands on them.

**Comment by BryanQuigley** [comment]
I haven't figured out how I would want to parse /proc/mounts... without more advanced logic.

A fresh install creates in /proc/mounts:
/dev/vda1 / btrfs rw,relatime,space_cache,subvolid=257,subvol=/@ 0 0
/dev/vda1 /home btrfs rw,relatime,space_cache,subvolid=258,subvol=/@home 0 0

With subvolumes, I'd need to make some more logic to only run the commands for /.  (Current strategy uses regex).

# btrfs filesystem show works no matter what, but I can't figure out something that will output what mountpoints have btrfs on them
Label: none  uuid: 9c835b8a-36d1-411e-9717-23428857e890
	Total devices 1 FS bytes used 3.93GiB
	devid    1 size 15.00GiB used 6.02GiB path /dev/vda1

**Comment by bmr-cymru** [comment]
```
# dd if=/dev/zero of=/var/tmp/img0 bs=1M count=100
100+0 records in
100+0 records out
104857600 bytes (105 MB, 100 MiB) copied, 0.0435322 s, 2.4 GB/s
# losetup /dev/loop0 /var/tmp/img0 
# mkfs.btrfs /dev/loop0
btrfs-progs v4.5.2
See http://btrfs.wiki.kernel.org for more information.

Performing full device TRIM (100.00MiB) ...
Label:              (null)
UUID:               1ef02bd3-42e5-4318-8f15-b3fc8b298ff7
Node size:          16384
Sector size:        4096
Filesystem size:    100.00MiB
Block group profiles:
  Data:             single            8.00MiB
  Metadata:         DUP              40.00MiB
  System:           DUP              12.00MiB
SSD detected:       no
Incompat features:  extref, skinny-metadata
Number of devices:  1
Devices:
   ID        SIZE  PATH
    1   100.00MiB  /dev/loop0

# mount /dev/loop0 /mnt/
# findmnt -t btrfs
TARGET SOURCE     FSTYPE OPTIONS
/mnt   /dev/loop0 btrfs  rw,relatime,seclabel,space_cache,subvolid=5,subvol=/
```

?

If you just want to find a particular mount point (if it uses btrfs), and only print the device, then it's:

```
# findmnt -t btrfs /mnt -osource --noheadings
/dev/loop0
```

**Comment by bmr-cymru** [comment]
(although we're already `findmnt`ing in the `filesys` plugin, so is this btrfs-specific data actually getting us anything new and useful?

**Comment by BryanQuigley** [comment]
It does, cause btrfs doesn't let normal file system usage utilizes work.  findmnt would still create duplicates because of how btrfs subvolumes work.

On reevaluating, `btrfs filesystem show` works without any flags and captures a good portion of the data we would want.

**Comment by bmr-cymru** [comment]
Oh yeah, I forgot BTRFS is broken :-/

**Comment by BryanQuigley** [comment]
Simplifying to collect enough to show btrfs is used any where. 

Latest one works and tested on RedHatPlugin too (tested Fedora27).  

Sample Output - Simple Fedora 27 setup:
# cat sos_commands/btrfs/btrfs_version 
btrfs-progs v4.11.1

# cat sos_commands/btrfs/btrfs_filesystem_show 
Label: 'fedora_localhost-live'  uuid: 5e4c088c-4a47-4e9a-ab0e-23bea4c4daca
	Total devices 1 FS bytes used 5.81GiB
	devid    1 size 19.02GiB used 9.02GiB path /dev/vda2

Sample Output - Complicated Ubuntu 17.10 setup (many btrfs partitions):
# cat sos_commands/btrfs/btrfs_version 
btrfs-progs v4.12

# cat sos_commands/btrfs/btrfs_filesystem_show 
Label: none  uuid: dae369b6-be5d-41b8-aca4-f6e88bf390c9
	Total devices 1 FS bytes used 804.55MiB
	devid    1 size 4.75GiB used 1.47GiB path /dev/vda1

Label: none  uuid: 30479470-e928-4533-90a9-2ba0ea528bd6
	Total devices 1 FS bytes used 2.37GiB
	devid    1 size 3.73GiB used 3.02GiB path /dev/vda12

Label: none  uuid: 035e2ebc-8cd8-479a-baa4-4d261c899808
	Total devices 1 FS bytes used 128.00KiB
	devid    1 size 953.00MiB used 119.25MiB path /dev/vda6

Label: none  uuid: 036784a9-7afc-4601-9c15-fa733e974107
	Total devices 1 FS bytes used 128.00KiB
	devid    1 size 953.00MiB used 119.25MiB path /dev/vda10

Label: none  uuid: c1bbb251-c790-4ff0-bf6a-010f70cf6887
	Total devices 1 FS bytes used 128.00KiB
	devid    1 size 953.00MiB used 119.25MiB path /dev/vda9

Label: none  uuid: 44e1c226-d955-46d8-a667-766fa5977b2f
	Total devices 1 FS bytes used 128.00KiB
	devid    1 size 953.00MiB used 119.25MiB path /dev/vda8

Label: none  uuid: c73d6f80-0d31-430b-8c5f-57f7146a45a4
	Total devices 1 FS bytes used 128.00KiB
	devid    1 size 951.00MiB used 119.00MiB path /dev/vda11

Label: none  uuid: a5f26175-3b3c-45cc-86a3-d73ccae75d1d
	Total devices 1 FS bytes used 374.90MiB
	devid    1 size 953.00MiB used 599.25MiB path /dev/vda7

Label: none  uuid: 47d82501-2ee8-4bb9-94b7-d38fdc065a50
	Total devices 1 FS bytes used 32.50MiB
	devid    1 size 953.00MiB used 215.25MiB path /dev/vda5

I think just collecting this is still very useful.  To truly find free space on btrfs subvolumes you will need more, but this provided at least a starting point.
