### ISSUE TITLE
haproxy uses py2 specific urlparse import

### ISSUE THREAD

**Issue by karibou** [sosreport/sos#1137]
New changes in the haproxy plugin (commit 6cf81bed12f119c580f9d3a0231aa46b2b165929) uses the python2 specific import syntax for urlparse. The plugin fails to load when run in python3.

**Comment by bmr-cymru** [comment]
How come this didn't pop on any of the Travis builds? Afaik everything was passing.

**Comment by karibou** [comment]
Well, it only shows up in my autopkgtests when running 'sosreport -l' as non-root. No error is triggered when it is run as root but I do see the same error : 

# sosreport --batch
                           
sosreport (version 3.5)          
                        
plugin haproxy does not install, skipping: No module named 'urlparse'
This command will collect system configuration and diagnostic
information from this Debian system. An archive containing the collected
information will be generated in /tmp/sos.4ba9j0h3.

**Comment by bmr-cymru** [comment]
Got it - it's because nothing in the test suite actually loads every plugin. We should probably look at fixing that.

**Comment by karibou** [comment]
Well, I think that I should propose the autopkgtests scripts for inclusion somewhere upstream. Let's discuss that on the ML

**Comment by bmr-cymru** [comment]
Both have value I think.
