### ISSUE TITLE
[RFE] origin (OpenShift) plugin to collect statistics information

### ISSUE THREAD

**Issue by sferich888** [sosreport/sos#1165]
https://docs.openshift.com/container-platform/latest/admin_guide/monitoring_images.html#monitoring-images-view-images

**Comment by TurboTurtle** [comment]
@sferich888 we need a little bit more than a doc link to go on.

Do you just need `oc adm top (images|imagestreams)`? 
Are there more options to give to top that would make the output more useful?  
Does this produce point-in-time output, or real time output that we need to restrict to a single poll interval (like we do in the `docker` plugin for `docker stats`)?
