### ISSUE TITLE
[RFE] origin (OpenShift) plugin should check certificate validity

### ISSUE THREAD

**Issue by sferich888** [sosreport/sos#1166]
https://docs.openshift.com/container-platform/3.7/install_config/redeploying_certificates.html#install-config-cert-expiry

**Comment by brenton** [comment]
FYI, the debug.sh script is being ported to the openshift-ansible diagnostics framework:
https://trello.com/c/Qqp6zDR2/32-5-demo-port-the-sdn-data-collection-scripts

If you'd like to see it in action take a look at the last group 3 sprint demo recording.

**Comment by brenton** [comment]
Definitely take a look at https://docs.openshift.com/container-platform/3.5/install_config/redeploying_certificates.html#install-config-cert-expiry if it could be used.

**Comment by TurboTurtle** [comment]
@sferich888 the doc links to an ansible role, which sos wouldn't use. 

Does simply collecting the output of something like `openssl x509 -in $cert -text -noout` work for you? Which cert(s) need to be checked?

**Comment by TurboTurtle** [comment]
It's been over a year with no response or clarification of what the ask for sos to additionally collect is, closing this issue.

If the `origin` plugin still needs changes please consolidate those into actual actionable list of items for sos to collect and open a new issue.
