### ISSUE TITLE
[RFE] origin (OpenShift) plugin should collect networking diagnostics that oadm diagnostics cant

### ISSUE THREAD

**Issue by sferich888** [sosreport/sos#1167]
Running commands like https://github.com/openshift/openshift-sdn/tree/master/hack

**Comment by brenton** [comment]
FYI, the debug.sh script is being ported to the openshift-ansible diagnostics framework:
https://trello.com/c/Qqp6zDR2/32-5-demo-port-the-sdn-data-collection-scripts

If you'd like to see it in action take a look at the last group 3 sprint demo recording.

**Comment by sferich888** [comment]
That's GREAT we already run diagnostics as part of the plugin so, if you work it into that, then we should get that for free (with out changes to the sos plugin).

**Comment by TurboTurtle** [comment]
It's been over a year with no response or clarification of what the ask for sos to additionally collect is, closing this issue.

If the `origin` plugin still needs changes please consolidate those into actual actionable list of items for sos to collect and open a new issue.
