### ISSUE TITLE
[utilities] collecting binary data removes "non-UTF-8 bytes"

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#1169]
Collecting literally any command output assumes the data are a valid UTF-8 string and the extra bytes are silently ignored. Usually, this is OK.

But sosreport collects also tarballs, at least on 2 places (`postgresql` and `lvm2` plugins) where ignoring the bytes causes sosreport stores an invalid file (i.e. stores tarball that cant restore its content).

There can be workaround in storing the binary output file somewhere and call `add_copy_spec`, but ideally `add_cmd_output` should be extended by some option like "treat_binary" to prevent ignoring the "non-UTF-8 bytes".

**Comment by pmoravec** [comment]
Workaround for `postgresql`:

    diff --git a/sos/plugins/postgresql.py b/sos/plugins/postgresql.py
    index 9ba696be..071b24e4 100644
    --- a/sos/plugins/postgresql.py
    +++ b/sos/plugins/postgresql.py
    @@ -20,6 +20,7 @@
     
     import os
     import tempfile
    +from shutil import rmtree
     
     from sos.plugins import (Plugin, RedHatPlugin, UbuntuPlugin, DebianPlugin,
                              SCLPlugin)
    @@ -45,6 +46,8 @@ class PostgreSQL(Plugin):
             ('dbport', 'database server port number', '', '5432')
         ]
     
    +    tmpdirs = []
    +
         def do_pg_dump(self, scl=None, filename="pgdump.tar"):
             if self.get_option("dbname"):
                 if self.get_option("password") or "PGPASSWORD" in os.environ:
    @@ -54,22 +57,38 @@ class PostgreSQL(Plugin):
                     if self.get_option("password") is not False:
                         os.environ["PGPASSWORD"] = str(self.get_option("password"))
     
    +                # workaround to add_cmd_output for non UTF-8 binary output:
    +                # create the tarball file and copy it instead of collecting
    +                # its string output. Need to remove temp.dir(s) afterwards
    +                tmp_dir = tempfile.mkdtemp()
    +                self.tmpdirs.append(tmp_dir)
    +                dest_file = os.path.join(tmp_dir, filename)
    +
                     if self.get_option("dbhost"):
    -                    cmd = "pg_dump -U %s -h %s -p %s -w -F t %s" % (
    +                    cmd = "pg_dump -U %s -h %s -p %s -w -f %s -F t %s" % (
                             self.get_option("username"),
                             self.get_option("dbhost"),
                             self.get_option("dbport"),
    +                        dest_file,
                             self.get_option("dbname")
                         )
                     else:
    -                    cmd = "pg_dump -C -U %s -w -F t %s " % (
    +                    cmd = "pg_dump -C -U %s -w -f %s -F t %s " % (
                             self.get_option("username"),
    +                        dest_file,
                             self.get_option("dbname")
                         )
     
                     if scl is not None:
                         cmd = self.convert_cmd_scl(scl, cmd)
    -                self.add_cmd_output(cmd, suggest_filename=filename)
    +                result = self.call_ext_prog(cmd)
    +                if (result['status'] == 0):
    +                    self.add_copy_spec(dest_file)
    +                else:
    +                    self._log_info(
    +                        "Unable to execute pg_dump. Error(%s)" %
    +                        (result['output'])
    +                    )
                 else:  # no password in env or options
                     self.soslog.warning(
                         "password must be supplied to dump a database."
    @@ -81,6 +100,10 @@ class PostgreSQL(Plugin):
         def setup(self):
             self.do_pg_dump()
     
    +    def postproc(self):
    +        for tmp_dir in self.tmpdirs:
    +            rmtree(tmp_dir)
    +
     
     class RedHatPostgreSQL(PostgreSQL, SCLPlugin):

**Comment by bmr-cymru** [comment]
> There can be workaround in storing the binary output file somewhere and call add_copy_spec,

Please don't...

I understand the problem but this needs some careful thought: we support substitution for command output and that can only work for textual data. We at least need some mechanism to indicate this and to prevent use of the command substitution methods when handling binary data.
