### ISSUE TITLE
Collect Ansible Playbook Logs (for Origin/OpenShift)

### ISSUE THREAD

**Issue by sferich888** [sosreport/sos#1173]
In conjunction with https://bugzilla.redhat.com/show_bug.cgi?id=1458018 we should have the origin plugin collect ansible logs (so we can see what maintenance errors / install errors) might have happened on this host (the host where ansible was run).

**Comment by pmoravec** [comment]
What the logs path/filename is/are? Do they contain some sensitive information to scrub (I dont think so)? Collecting them should be triggered exactly when `origin` plugin is enabled?

**Comment by ryansb** [comment]
Ansible has builtin `nolog` features for password/secret parameters, so they shouldn't be showing up in the logs Ansible writes out. A second scrub in sosreport is probably unnecessary.

**Comment by TurboTurtle** [comment]
@sferich888 is this relevant at all for OCP 4.x?
