### ISSUE TITLE
sos should report a command execution failed

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#1182]
sosreport should print to ui.log or a similar logfile what commands failed to be executed.

Currently, we collect stdout, ignore stderr and return value (that just affects if/what to collect). It can be usefull to know why some commands outputs is empty - because the command failed.

Particular (evident) example: `autofs` plugin collects `"/etc/init.d/autofs status"` that fails on a `systemd` machines. Knowing the fact the cmd return value was nonzero and (if nonzero then) collecting stderr might be helpful.

**Comment by TurboTurtle** [comment]
This is now recorded in `sos_reports/manifest.json` as of `sos-4.0`.
