### ISSUE TITLE
The etcd plugin will grab private keys on OpenShift etcd hosts.  

### ISSUE THREAD

**Issue by rjhowe** [sosreport/sos#1193]
The etcd plugin will grab all sub directories under /etc/etcd/ 

When running OpenShift, the installer will create a /etc/etcd/ca directory that contains the openssl conf file and CA keys  and server private keys for the certs that are created for TLS communication between etcd node.  

sosreport should not collect this information  

  /etc/etcd/ca/*

**Comment by rjhowe** [comment]
@TurboTurtle

**Comment by TurboTurtle** [comment]
Well that's not good.

Trivial fix though, since we should just blacklist the entire directory.

**Comment by TurboTurtle** [comment]
Closing per b9ace27
