### ISSUE TITLE
[distupgrade] NoneType object is not iterable

### ISSUE THREAD

**Issue by chr0mag** [sosreport/sos#1197]
distro: Arch Linux ([policy file](https://github.com/sosreport/sos/files/1676367/arch.py.txt))
release: master, v3.5

When I run: `sudo sosreport --alloptions` the following traceback is written to _sos_logs/distupgrade-plugin-errors.txt_
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/sos/sosreport.py", line 1252, in setup
    plug.setup()
  File "/usr/lib/python3.6/site-packages/sos/plugins/__init__.py", line 956, in setup
    self.add_copy_spec(list(self.files))
TypeError: 'NoneType' object is not iterable
```
The _files_ class variable is already initialized correctly (as an empty tuple) in the base Plugin class so there is no need to initilize it in a derived plugin unless it will actually contain data. Removing the offending `files = None` line from _distupgrade.py_ fixes this issue.

**Comment by bmr-cymru** [comment]
This is a bug in the out-of-tree policy (it is allowing abstract Plugin classes to be loaded). Please submit it for review (following the [Contribution Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines) and we can work from there.

**Comment by bmr-cymru** [comment]
```python
class ArchPolicy(LinuxPolicy):

    distro = "Arch Linux"
    vendor = "Arch Linux"
    vendor_url = "https://www.archlinux.org/"
    vendor_text = ""
    # package_manager = PackageManager(
    #   "pacman --query | awk 'BEGIN {OFS = \"|\"} {print $1,$2}'")
    valid_subclasses = [Plugin]
```

You can't do this: the plugin mechanism in sos uses a potentially abstract base class (`Plugin`), and sets of *tagging classes* to identify those plugins that are compatible with a particular policy. By stating that your policy is compatible with `Plugin` you are saying it will work with any possible plugin class when that cannot be the case.

Please take a look at the [policy writer's guide](https://github.com/sosreport/sos/wiki/How-to-Write-a-Policy).

You need to either also define a new tagging class, and then modify plugins that can work on Arch to inherit from it, or state that your policy is compatible with one or more existing tagging classes.

```python
class Pacman(PackageManager):
    # this subclass is only needed because sos_get_command_output()
    # in utilities.py sets shell=False so the pipe to awk in the
    # command below used to format pacman output does not work
    # pacman --query | awk 'BEGIN {OFS = \"|\"} {print $1,$2}'
```

This comment is kinda bogus: we set `shell=False` for good reasons and this has been the case for a long time. The real reason this is needed is that the `pacman` package manager does not seem to support the use of format strings to structure the results (unlike RPM and Deb).

In any case: it's not a big deal. This is done once at startup. I'd be happy to add extra helpers for package managers with this behaviour but it's not down to a limitation in sos (although we should rename `shell_out()` to `call_out()`, or simply remove it entirely: it's not widely used).
