### ISSUE TITLE
Add required files to detect pip installs on system

### ISSUE THREAD

**Issue by iranzo** [sosreport/sos#1200]
As we don't have rpm -V $(python-files) on the sosreport we cannot tell if a file was installed outside of the rpm package management

Alternativelly we could use:

~~~
It's not a perfect solution, but if installed-files.txt exists in the .egg-info for a library, it was most likely installed by pip. Won't catch easy_install or things installed via wheels, but it would be one more datapoint?
~~~

As suggested by cjones, but we will need to collect or report that presence of files in the sosreport

**Comment by bmr-cymru** [comment]
Really?
```
$ rpm -qf /usr/lib64/python2.7/site-packages/cffi-1.9.1-py2.7.egg-info/installed-files.txt
python2-cffi-1.9.1-2.fc26.x86_64
```

**Comment by bmr-cymru** [comment]
> As we don't have rpm -V $(python-files) on the sosreport we cannot tell if a file was installed outside of the rpm 

Why not add a verify list to the python plugin, and ask your users to run `sosreport --verify`? It's what it's for ;)

But anyway: this still won't do what you asked for. It will show you *packaged* files, but it's not going to report anything for *unpackaged* files at all. You'd need to take a global file list and subtract everything from the RPM data (and there are more efficient RPM options than --verify for this).

**Comment by bmr-cymru** [comment]
Surely if a module is installed and is not in `installed-rpms.txt` then you know that it is either PIP or a local installation, isn't that sufficient?

Failing that then either `pip freeze` or `python -c 'help("modules")'` followed by comparison to the RPM data.

**Comment by iranzo** [comment]
Will this be covered too with https://github.com/sosreport/sos/pull/1323 ?

**Comment by bmr-cymru** [comment]
Not really: python packages still need to be on a verify list to be checked (unless `rpm.rpmva` is set).

I think the work @pierg75 was doing in #1066 is probably more of a solution for this.

**Comment by TurboTurtle** [comment]
Between the `unpackaged` plugin, and the option to generate hashes for pyfiles in the `python` plugin (which can serve as a measure of validation), I'm considering this covered, and closing.
