### ISSUE TITLE
The documentation link in README.md is not working properly

### ISSUE THREAD

**Issue by jwizion** [sosreport/sos#1202]
Hi

the link goes to "http://sos.readthedocs.org/", then you end up to "http://sos.readthedocs.io/"
from here the documentation is empty : try "http://sos.readthedocs.io/en/latest/plugins.html"

I found the doc here "http://sosreport.readthedocs.io/en/latest/plugins.html"

**Comment by bmr-cymru** [comment]
The link is correct: there's something wrong with the default build that should appear at that address.

**Comment by battlemidget** [comment]
Yea I need to generate it locally to see what's going on, those modules should have documentation generated for them automatically.

**Comment by TurboTurtle** [comment]
RTD has been updated and now points to the master branch, and the generated docs have recently been validated.
