### ISSUE TITLE
Run --verify by default to be 'on' and move current argument to --no-verify

### ISSUE THREAD

**Issue by iranzo** [sosreport/sos#1208]
Run verify by default so that we've detailed plugin data and rpm package modification for detected plugins and include an option to disable it if not wanted.

**Comment by bmr-cymru** [comment]
Like I said on IRC, we will need performance numbers to evaluate the suitability of this change. You can help the PR to progress by preparing some: we'd need the number of packages installed (a package list would also help, esp. for any found corner cases), and the runtimes for `sos` with and without `--verify`.

**Comment by iranzo** [comment]
@bmr-cymru do you think we could also include a timestamp inside sosreport so when generated, it wil include it?

We do something like that in citellus generated json for each plugin plus the total time (I will raise another issue if you think it's ok, as this could benefit other calculations in the future)

**Comment by bmr-cymru** [comment]
We've had built-in profiling for plugins and command execution for literally years now... Just search for messages like:

```
[plugin:sar] collected output of 'sadf' in 0.007418632507324219
...
[plugin:psacct] collected plugin 'psacct' in 0.0055577754974365234
```

**Comment by iranzo** [comment]
On collab-shell with 3.4-13.el7
time sosreport --batch
~~~
real	1m18.853s
user	0m15.281s
sys	0m5.649s
~~~

time sosreport --batch --verify
~~~
real	0m48.590s
user	0m19.361s
sys	0m4.898s
~~~

I guess it's because of caching of tiles by the FS

**Comment by iranzo** [comment]
On undercloud-0, a VM inside openstack01 baremetal host

time sosreport --batch
~~~
real	10m21.760s
user	3m29.253s
sys	1m26.285s

~~~

time sosreport --batch --verify
~~~

real	11m16.479s
user	6m32.532s
sys	1m13.579s

~~~

**Comment by iranzo** [comment]
Probably could be closed by: https://github.com/sosreport/sos/pull/1323

**Comment by BryanQuigley** [comment]
Closing per last comment
