### ISSUE TITLE
ZFS plugin does not run

### ISSUE THREAD

**Issue by utopiabound** [sosreport/sos#1213]
With ZFS installed (from http://zfsonlinux.org/), the zfs plugin fails to run.

The zfs plugin is looking for zfsutils-linux which is an Ubuntu package, but the common ZFS packages for RedHat/CentOS are not listed.

**Comment by bmr-cymru** [comment]
Dupe of #1201 - not much point having a PR and an issue open for this. We'll get the pull merged before 3.6.
