### ISSUE TITLE
suppress journalctl_--no-pager_--all_--boot_--output_verbose

### ISSUE THREAD

**Issue by brianjmurrell** [sosreport/sos#1225]
It would be nice to have an option to suppress the `journalctl_--no-pager_--all_--boot_--output_verbose` copy of the journal from sosreports.  `journalctl_--no-pager_--boot` usually suffices and the former is usually quite big compared to the latter.

**Comment by bmr-cymru** [comment]
This is one of the commands the journald guys asked us to add with the initial support: I'd have no real objection to putting it behind `--all-logs`.

**Comment by pmoravec** [comment]
+1, I use the non-verbose file frequently, but havent used the verbose yet - until one is concerned about details of logs, it seems redundant.

**Comment by bmr-cymru** [comment]
The motion is carried...

**Comment by valleedelisle** [comment]
Well, I used this file to get precise timestamps and I found that there's some custom libvirt variable defined in the verbose output that is not showing up anywhere else.

Sorry, I'm late to the party, I just realized that this happened.
