### ISSUE TITLE
Rabbitmq logs are not archived in extractable/readable format.

### ISSUE THREAD

**Issue by links84** [sosreport/sos#1242]
I notice the rabbitmq rotated log file is a link to tailed gz, which i can read using less or extract using gz .

var/log/rabbitmq/rabbit@overcloud-controller-2.log-20171126.gz -> ../../../sos_strings/rabbitmq/var.log.rabbitmq.rabbit@overcloud-controller-2.log-20171126.gz.tailed

**Comment by bmr-cymru** [comment]
Fixed in 3.5 (#1111).

**Comment by links84** [comment]
cool thanks. sorry missed to find this while searching. was using an older version.

**Comment by bmr-cymru** [comment]
np: 2.5 is still pretty new & not in many distros yet.
