### ISSUE TITLE
[make po] Error with missing sos_en.properties

### ISSUE THREAD

**Issue by ghost** [sosreport/sos#1250]
Hi,

The Makfile tries to copy sos_en.properties but it looks like `en.po` was removed in commit [e83d8f6](https://github.com/sosreport/sos/commit/e83d8f6d55242c82014836dd7548b5ab5926e6d6#diff-f6122c971aeb03476bf01623b09ddfd4).

```
for po in `ls po/*.po`; do \
	msgcat -p -o dist-build/sdist/sos/po/sos_$(basename $po | awk -F. '{print $1}').properties $po; \
done; \

cp dist-build/sdist/sos/po/sos_en.properties dist-build/sdist/sos/po/sos_en_US.properties
cp: cannot stat 'dist-build/sdist/sos/po/sos_en.properties': No such file or directory
make: *** [Makefile:90: po] Error 1
```

**Comment by bmr-cymru** [comment]
Wonder if @battlemidget could take a look at this? If not I'll try to dig into it sometime.

**Comment by TurboTurtle** [comment]
Closing, as we no long use `make` in sos.
