### ISSUE TITLE
[policies] add policies for missing RH rebuild distros

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#1264]
Currently we report as RHEL/Red Hat on distributions like CentOS, Scientific Linux etc. Fix this by adding policy subclasses for these builds and overriding the appropriate properties from the base RHEL class.

**Comment by mangelajo** [comment]
Oh, yes, it's handled in packaging here: 

https://git.centos.org/blob/rpms!sos.git/c7/SOURCES!sos-3.4-centos-branding.patch

But it's really painful to discover this through a 2h debugging session when your devel env of sos (under CentOS) does not recognize your system, and returns an empty list of plugins after filtering...

**Comment by bmr-cymru** [comment]
I reached out to the CentOS folks some years ago (both before and after the Red Hat join up), and there was not much interest in working on a CentOS policy at the time, and it was also cumbersome for me to get maintainer access to the sos SRPM in order to fix it myself.

I have not enquired in a long time, so maybe now is a good time to get back to this. No distro should be patching policy files downstream, unless it is to address actual bugs in released `sos` versions.

**Comment by bmr-cymru** [comment]
Right: that patch is exactly what Oracle were doing a few years back. It's not the best approach. Better to either add to the `redhat` file, or make a new one and `import sos.policied.redhat`. Then you either add the `RedHatPlugin` tagging class to the new policy, or better yet, subclass the existing ones and modify the instance variables to suit. This is easier and a lot more maintainable.

**Comment by mangelajo** [comment]
@bmr-cymru there you have it, I hope the patch looks good :)

**Comment by TurboTurtle** [comment]
Closing this as the CentOS policy is now defined in master alongside other Red Hat family distros, see #1447
