### ISSUE TITLE
/etc/sudoers is not collected 

### ISSUE THREAD

**Issue by iranzo** [sosreport/sos#1276]
Sometimes includedir /etc/sudoers.d is missing but we cannot check in sosreport as it is not included by default

**Comment by iranzo** [comment]
Ideally this should do proper cleanup of passwords, etc and grab the full file

**Comment by jcastill** [comment]
Pablo, I think we already collect this in the latest version upstream, via sudo.py.

    def setup(self):
        self.add_copy_spec("/etc/sudo*")

And we also strip passwords as far as I know:

    def postproc(self):
        regexp = r"(\s*bindpw\s*)\S+"
        self.do_file_sub("/etc/sudo-ldap.conf", regexp, r"\1********")

This new plugin was added on August 23  by Pavel (commit 9143de40bdfeae840f27b362b410ca15f41d7a85 ) So I guess we can close this?

**Comment by iranzo** [comment]
Yes please!

**Comment by bmr-cymru** [comment]
I'm sure we went through this before, but nothing in `/etc/sudoers.d` requires postprocessing, right?
