### ISSUE TITLE
[kernel,system] warnings on stdout about Permission denied in python3

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#1299]
Running sosreport under python3, I see:

      Running 1/2: kernel...
    [archive:TarFileArchive] Unable to add '/var/tmp/sos.d0dqtohj/sosreport-hostname-2018-05-18-sboruce/sys/kernel/debug/tracing/trace_marker_raw' to FileCacheArchive: [Errno 13] Permission denied: '/var/tmp/sos.d0dqtohj/sosreport-hostname-2018-05-18-sboruce/sys/kernel/debug/tracing/trace_marker_raw'
    [archive:TarFileArchive] Unable to add '/var/tmp/sos.d0dqtohj/sosreport-hostname-2018-05-18-sboruce/sys/kernel/debug/tracing/free_buffer' to FileCacheArchive: [Errno 13] Permission denied: '/var/tmp/sos.d0dqtohj/sosreport-hostname-2018-05-18-sboruce/sys/kernel/debug/tracing/free_buffer'
    [archive:TarFileArchive] Unable to add '/var/tmp/sos.d0dqtohj/sosreport-hostname-2018-05-18-sboruce/sys/kernel/debug/tracing/trace_marker' to FileCacheArchive: [Errno 13] Permission denied: '/var/tmp/sos.d0dqtohj/sosreport-hostname-2018-05-18-sboruce/sys/kernel/debug/tracing/trace_marker'
      Running 2/2: system...    
    [archive:TarFileArchive] Unable to add '/var/tmp/sos.d0dqtohj/sosreport-hostname-2018-05-18-sboruce/proc/sys/net/ipv4/route/flush' to FileCacheArchive: [Errno 13] Permission denied: '/var/tmp/sos.d0dqtohj/sosreport-hostname-2018-05-18-sboruce/proc/sys/net/ipv4/route/flush'
    [archive:TarFileArchive] Unable to add '/var/tmp/sos.d0dqtohj/sosreport-hostname-2018-05-18-sboruce/proc/sys/net/ipv6/route/flush' to FileCacheArchive: [Errno 13] Permission denied: '/var/tmp/sos.d0dqtohj/sosreport-hostname-2018-05-18-sboruce/proc/sys/net/ipv6/route/flush'

python2 does not exhibit those errors, because py3 newly raises the error when `shutil.copystat` is called to a file without read permissions.

And really:

    # ll /sys/kernel/debug/tracing/free_buffer /sys/kernel/debug/tracing/trace_marker /sys/kernel/debug/tracing/trace_marker_raw  /proc/sys/net/ipv4/route/flush /proc/sys/net/ipv6/route/flush
    --w-------. 1 root root 0 May 17 08:54 /proc/sys/net/ipv4/route/flush
    --w-------. 1 root root 0 May 17 08:54 /proc/sys/net/ipv6/route/flush
    --w-------. 1 root root 0 May 16 13:23 /sys/kernel/debug/tracing/free_buffer
    --w--w----. 1 root root 0 May 16 13:23 /sys/kernel/debug/tracing/trace_marker
    --w--w----. 1 root root 0 May 16 13:23 /sys/kernel/debug/tracing/trace_marker_raw
    # 

These files are empty and meant to write to them to command kernel, so there is no reason to collect them by sosreport. So I suggest adding them to forbidden path (what will cause the copystat wont be called and the error logs wont pop up).

Anyway, I expect there can be more such files we dont need to bother collect, so some review what all files we shall newly forbid in collecting would be welcomed.

**Comment by bmr-cymru** [comment]
I can think of a few options here (in fact, we've never dealt with these method invocation files in `/proc` and `/sys` well - another possible application of global blacklists).

The immediate solution is probably just to add these new path patterns to the forbidden paths list for the plugin.

Longer term there are other approaches we can explore other solutions. One is the global blacklist (issue open somewhere I think), another would be to filter these out at the archive level (we already stat everything, directly or indirectly, and it makes no sense to try to collect a file with mode 0200 from either `/proc` or `/sys` (although it does for regular files, since Linux still allows root to bust through the read perms).

**Comment by TurboTurtle** [comment]
Closing this out, as it should have closed with 5528ccb
