### ISSUE TITLE
LXD needs a packages list

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#1306]
```python
class LXD(Plugin, UbuntuPlugin):
    """LXD is a containers hypervisor.
    """
    plugin_name = 'lxd'
    profiles = ('container',)

```

Result: ENOPACKAGES.

**Comment by slashdd** [comment]
Will update this PR shortly since LXD with recent release of Ubuntu can be installed from standard deb package (dpkg, apt, ... and family) or as a snap. I'll take benefit of this request to adapt the plugin for snap as well.
