### ISSUE TITLE
Kill sos/__init__.py.in

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#1321]
We use a `.in` file to generate `sos/__init__.py` in order to update the version string. This worked well in the past when the build was only make-based, but is now more of a pain than a help: editing the `.in` and then updating the python source is tedious and error prone (and this gets worse as we move more global definitions into the file).

Kill it off and have the maintainer manually update the version at release time (patch on branch bmr-product).

**Comment by TurboTurtle** [comment]
Closing per 8c54555
