### ISSUE TITLE
sosreport to trigger on snap packages

### ISSUE THREAD

**Issue by slashdd** [sosreport/sos#1324]
As discussed in PR: #1313 , with recent version of Ubuntu some project can be installed from :

- Either deb package or snap. (**lxd** is available as a deb package and snap.)
- Only be installed as a snap. (**canonical-livepatch** is only available as a snap.)

As suggested by @bmr-cymru 
`Should we think about adding support for triggering on snaps? Either as a new snaps member to Plugin, or as an extension to the Ubuntu policies to allow these to be recognised as packages (i.e. PackageManager will merge the two sources of package data).`

Until we add the snap support, the only options that I can think of would be to use 
`packages = <DEB_PKG>` along with `files = ('/snap/bin/<DESIRED_BINARY>')` if project is available in both, and only use `files = ('/snap/bin/<DESIRED_BINARY>')` if only available as a snap, just like `canonical_livepatch.py` plugin does at the moment.

**Comment by slashdd** [comment]
I started to do a preliminary look as of how I could have the expected package install list in the following format : `package name|major.minor.bugfix version\n` . There is none for snap so far, unless we do `snap `list with some tail, sed, awk and family magic. I have contacted a colleague working on snappy, and he said he might be able to implement a `snap list --format={name}|{version}` which would mimic what dpkg-query does.

**Comment by slashdd** [comment]
The `snap list --format `query PR : https://github.com/snapcore/snapd/pull/5234
Ubuntu whishlist bug: https://bugs.launchpad.net/bugs/1773842

As soon as it is present in Ubuntu, we can start looking at how to integrate snap as a packagemanager for Ubuntu.

**Comment by slashdd** [comment]
@bmr-cymru would you have any piece of advise in how to proceed to add a policy or append the existing ubuntu policy to detect both DEB and SNAP. Snap is more and more coming a thing in the Ubuntu world at every new release.

**Comment by bmr-cymru** [comment]
> Snaps can also be installed on RHEL.. just like flatpaks can be installed on Ubuntu.

This is why I think we should aim for something that is general, and can support the various different bits.

The `PackageManager` has been creaking along with more and more holes showing for a long time, and I would be happy to see some clean up to that along with this work.

I'm imagining something like new classes in `sos.policies`, say `AddOnPackageManager`, with subclasses for the different systems, and that a concrete `Policy` subclass can instantiate to extend the system package data with the add-on provided packages. This puts all the path handling in one place where it already is, and avoids the need for so many plugin changes (e.g. by letting us continue to use the "executable name only" convention and not include binary paths).

**Comment by slashdd** [comment]
Also tried to include both policies in the same and already existing class `UbuntuPolicy` instead of having both `UbuntuPolicy` and `SnapUbuntuPolicy` still without success so far.

```
--- a/sos/policies/ubuntu.py
+++ b/sos/policies/ubuntu.py
@@ -1,17 +1,18 @@
 from __future__ import with_statement
 
-from sos.plugins import UbuntuPlugin, DebianPlugin
+from sos.plugins import UbuntuPlugin, DebianPlugin, SnapPlugin
 from sos.policies.debian import DebianPolicy
+from sos.policies.snap import SnapPolicy
 
 
-class UbuntuPolicy(DebianPolicy):
+class UbuntuPolicy(DebianPolicy, SnapPolicy):
     distro = "Ubuntu"
     vendor = "Ubuntu"
     vendor_url = "http://www.ubuntu.com/"
 
     def __init__(self, sysroot=None):
         super(UbuntuPolicy, self).__init__(sysroot=sysroot)
-        self.valid_subclasses = [UbuntuPlugin, DebianPlugin]
+        self.valid_subclasses = [UbuntuPlugin, DebianPlugin, SnapPlugin]
 
     @classmethod
     def check(cls):
```

**Comment by bmr-cymru** [comment]
That's how policies work - there can only be one active policy at a time. Take a look at how the `PackageManager` class works now (and please use `InitialCaps` for class names!). It's a class shared among distros, that is initialised using a set of command template strings *by the policy classes*. I think that any new aux package manager should work in a similar way - a generic implementation, initialised to distro specifics by policies.

This might use a factory like pattern to build a concrete instance of either Snap or some other system (Flatpak e.g.), and then provide a uniform instance to the extra package data - possibly (ideally, if it can work) merged with the existing `PackageManager` interface.

This might involve a lot of surgery - I am fine with that - the current `PackageManager` API has been knocking around for years and is suboptimal in a lot of ways. I am very open to improvements to that.

**Comment by bmr-cymru** [comment]
```diff
+from sos.plugins import UbuntuPlugin, DebianPlugin, SnapPlugin
```

This doesn't seem the way to go to me - it means that we must modify every plugin for every aux package manager. This is going to be painful to maintain. We want e.g. `DebianPolicy` to enable the Snap package data source when it is available, and to make that available (along with `PATH` modifications) to the standard `Plugin.check_enabled()` methods.

**Comment by BryanQuigley** [comment]
We're thinking it makes sense to fully separate out Package Management from OS definitions.  So creating a distinct snap policy that triggers whenever the snap binary exists, ditto for debs, ditto for rpms.  We do have people who install rpms on Ubuntu.

In that case we could create a brand new API for package management and then slowly switch over to it.  Thoughts?

**Comment by bmr-cymru** [comment]
Well. Historically they are closely tied because of the close relationship between distro and packaging: every policy initialises its `PackageManager` slightly differently.

If you have a proposal for a unified API that would separate out the differences cleanly then go for it - I'd suggest posting the API itself (functions, classes, methods) before spending time on the implementation so that folks can provide feedback.

My gut feeling is they will still have a close relation though (effectively `PackageManager` is a policy class for package manegers - it could be better, but I haven't seen a way yet for us to get away from that entirely).

**Comment by slashdd** [comment]
closing this issue for now. We have a viable workaround in place for Canonical snap product (lxd, juju, and canonical-livepatch)
