### ISSUE TITLE
[RFE][openshift] Collect output of oc get nodes in openshift controller

### ISSUE THREAD

**Issue by mvazquezc** [sosreport/sos#1331]
Collect output of oc get nodes command in an openshift controller.

"oc get nodes" can be used to check the status of the different nodes in the cluster.

Reference : https://docs.openshift.com/container-platform/3.9/admin_guide/manage_nodes.html#listing-nodes

**Comment by TurboTurtle** [comment]
This should be the exact same output as `kubectl get nodes` from the `kubernetes` plugin that will always run on OCP environments, wouldn't it?

**Comment by mvazquezc** [comment]
Hello @TurboTurtle,

You're right. The output from sos_commands/kubernetes/kubectl_get_-o_json_nodes is perfect.

Closing the issue.
