### ISSUE TITLE
[sosreport] log command size output limiting

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#1332]
Make sure that the user is aware that command output has been size limited by either:

* Logging a message indicating limits have been exceeded (once only)

Or:

* Placing the limited output in a file named like `command_--options.tailed` with a symbolic link from `command_--options`

**Comment by knoha-rh** [comment]
From support side, we would like to know whether the output are truncated/size-limited by sos.
To make it clear, I'd like to vote to the filename which describes that the file is truncated/size-limited.

**Comment by k-hagio** [comment]
I also think that the filename approach is good because of ease to notice it and consistency with `add_copy_spec()`, and it is better to have both the ways to describe it more clearly if possible.

**Comment by jcastill** [comment]
I think logging a message so customer sees that a size limit has been exceeded (perhaps with a suggestion to attach the file separately, or how to call sos with an increase log size?), plus adding a filename as knoha-rh suggests, like messages.truncated, will be very useful for customers and support.
