### ISSUE TITLE
[plugin] Add Elasticsearch plugins support

### ISSUE THREAD

**Issue by Amitgb14** [sosreport/sos#1334]
Support SOS tool to collect Elasticsearch services logs and config files.

**Comment by pmoravec** [comment]
Could you please elaborate more? Like what is the location of ES logs and configs? What should automatically trigger collection of those (some file, installed package etc.)? Could some config or log contain some sensitive information (password, SSL private key,..) we should obfuscate?

**Comment by Amitgb14** [comment]
@pmoravec , thanks for the response, I'm try to figure out what kind of add into this plugins. Collecting config and logs is normal but also include health, nodes, shards etc. Official config log not contains any username and password but in some users added extra plugins and they mention some credentials in same ES config files.
