### ISSUE TITLE
3.6: incorrect-fsf-address

### ISSUE THREAD

**Issue by sandrobonazzola** [sosreport/sos#1365]
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.6/site-packages/sos/plugins/unpackaged.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.6/site-packages/sos/plugins/watchdog.py

**Comment by bmr-cymru** [comment]
Ugh.. people copying old plugins: most of these got fixed on the way into the tree. I'll fix these up in master (we are no longer including the full GPL verbiage in every source file: just a statement that the file is part of the `sos` project, and to refer to the full license file for details).
