### ISSUE TITLE
[archive] regexp substitution fails due to _check_path returning None

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#1370]
No call of `self.do_path_regex_sub` really applies the substitution now. The reason is because:

- `self.archive.add_string(..)` is called in `do_file_sub` to update the content
- `_check_path` verifies if the path is a valid file
- path is wrongly detected as already copied due to https://github.com/sosreport/sos/blob/master/sos/archive.py#L224-L225, so https://github.com/sosreport/sos/blob/master/sos/archive.py#L234-L235 is executed

The "Path has already been copied: skip" is required to prevent overwriting files concurrently collected by other plugins. We can weaken this for calls from `do_file_sub`, but then there still might be a race "error" when two plugins will substitute the same file in a different manner (although this sounds improbable).

I suggest skipping the `if not dest: return` when called from `do_file_sub` with the above possible drawback, since I dont see a better fix.

**Comment by pmoravec** [comment]
(btw we really *need* automated tests for such a basic functionality :( )

**Comment by pmoravec** [comment]
Fixed by b96bdab.

**Comment by bmr-cymru** [comment]
> (btw we really need automated tests for such a basic functionality :( )
