### ISSUE TITLE
[cluster] /etc/pacemaker/authkey 'hash'

### ISSUE THREAD

**Issue by iranzo** [sosreport/sos#1378]
There are some issues at cluster communication if the authkey is not equal across nodes.

As grabbing the key into sosreport will probably incur into security issues, could we get an sha or md5 sum (or whatever) so that we can compare across sosreports from the same environment??

Think of OSP controllers +  computes with InstanceHA

**Comment by bmr-cymru** [comment]
It's simple enough to add, but what other use cases are there? I'd be a bit loath to add this to the plugin class for just one single purpose.

```python
        def add_file_checksum(self, path, hash="md5"):
            """Add a file containing the checksum of a file from the host file system.

                :param path: the path to be checksummed
                :param hash: an optional hash identifier
            """
```

**Comment by iranzo** [comment]
In the [tool that shall not be named](https://citellus.org), we do check other md5sums in files like policy.json available in openstack deployments, by default in sosreport we collect the file, so we can calculate it, but I do see this useful for other files like certificates in 'OCP', etc where we can add md5 of the keyfile as a way to compare it across sosreports and still keep the privacy .


So use cases: any secret key file (for example .ssh/, apache certificate, etc) that should be equal across systems to ensure smooth interaction between them.

**Comment by TurboTurtle** [comment]
I think now that `collect` is available within sos natively, collecting file hashes makes a bit more sense as you'd have an easier time comparing hashes collected at the same time across multiple nodes.

I'll try and get something worked up for this shortly.

**Comment by TurboTurtle** [comment]
@iranzo I'm cycling back through old/stale issues. This one slipped through last time, but it's trivial to add. My question is, do we have specific use cases that exist today that this could be used for (i.e. adding the collection at the same time as adding the functionality)?

If so, I'll go ahead and get something posted for this. If not, I think we close this out at this point.

**Comment by iranzo** [comment]
The idea was to be able to compare the hashes across hosts to detect failures in hosts pertaining to the same cluster to find issues that could be affecting them. (without having to know the password itself)

**Comment by TurboTurtle** [comment]
Right, but do you have specific examples of what files would be useful to hash with this?

**Comment by iranzo** [comment]
- Passwords that should be equal across hosts
- Configuration files (like cluster configuration) that must be identical across them
- dc-version in pacemaker
- rhel-release across cluster
- OpenStack policy bundles
- Ceilometer pipeline yaml
- iptables config across OpenStack hosts with same role

Opposite, files that should be different:
- iSCSI initiator name
- machine-id


(the ones we used at that time)

**Comment by iranzo** [comment]
The file list that I have as of today:
/etc/machine-id /etc/iscsi/initiatorname.iscsi /etc/cluster/cluster.conf /etc/aodh/policy.json /etc/ceilometer/policy.json /etc/cinder/policy.json /etc/containers/policy.json /etc/glance/policy.json /etc/gnocchi/policy.json /etc/heat/policy.json /etc/ironic/policy.json /etc/keystone/policy.json /etc/manila/policy.json /etc/mistral/policy.json /etc/neutron/policy.json /etc/nova/policy.json /etc/panko/policy.json /etc/sahara/policy.json /etc/zaqar/policy.json /etc/ceilometer/pipeline.yaml /etc/sysconfig/iptables /etc/redhat-release

**Comment by TurboTurtle** [comment]
> /etc/machine-id
> /etc/redhat-release
> /etc/sysconfig/iptables

Why would you need hashes of these files? There is nothing sensitive in these, and the first two are collected outright in sos already.

> /etc/*/policy.json

We collect `/etc/keystone/policy.json` today - but not for the other OSP components. Does it make more sense to collect these "normally" for the other components? What is in here that we couldn't handle with our normal `postproc()` approach?

**Comment by iranzo** [comment]
Well, it has been 3 years since I was working in the SBR, the idea is that all components should have policies in sync.

If there's another way to grab them, I trust your judgement here

**Comment by TurboTurtle** [comment]
Chewing on this a bit more, and consulting with some of the Insights folks, I'm not of the opinion that this would be used in practice.

Of course, if there is or starts to be a solid practical use case, I'm not fundamentally opposed to adding such functionality but at this time I don't think it is necessary.
