### ISSUE TITLE
Incomplete parsing of rsyslog config

### ISSUE THREAD

**Issue by mason-redhat** [sosreport/sos#1384]
Description of problem:

sosreport doesn't parse rsyslog's IncludeConfig directive, and also fails to
read config from /etc/rsyslog.d/ when it runs, even if --all-logs is specified.

Steps to Reproduce:

cat > /etc/rsyslog.d/sosreport-test.conf <<END
kern.info     /var/log/test1
daemon.info   /var/log/test2
auth.info     /var/log/test3
authpriv.info /var/log/test3
cron.debug    /var/log/test4
syslog.debug  /var/log/test5
local6.info   /var/log/test6
local7.debug  /var/log/test7
END
service rsyslog restart
sleep 60
sosreport
sosreport --all-logs

Actual results:

Custom logs not included in either sosreport.

Expected results:

Custom logs included, regardless of --all-logs being used or not.

**Comment by bmr-cymru** [comment]
What version (and release, if it is a packaged installation) are you running?

**Comment by mason-redhat** [comment]
Hi there.

As packaged by Red Hat:

sos-3.2-63.el6.noarch

I believe it also affects the version shipped in RHEL 7, but I'll double-check that.

sos-3.5-9.el7_5.noarch

**Comment by mason-redhat** [comment]
Confirmed. Even with --all-logs, sos-3.5-9.el7_5.noarch just doesn't have the code to parse rsyslog.conf.

**Comment by bmr-cymru** [comment]
OK. In that case you'll need to wait for the next RHEL update - this support was only added back in January, and is in `3.5.1` and `3.6`, but not earlier releases.

I've also just noticed a couple of bugs in the version that was originally committed. i'm testing fixes for those now and I'll push a branch that you can test with if you like. There aren't any changes outside the plugin for this fix, and I don't think `logs` uses any new APIs added after `3.5`, so you should be able to just drop the one file into `/usr/lib/python2.7/site-packages/sos/plugins` for `3.5` (can't swear that's true for `3.2` without checking).

**Comment by bmr-cymru** [comment]
I think the changes on [bmr-logs-parseconf](https://github.com/sosreport/sos/commits/bmr-logs-parseconf) should address this. There are three variations of the directive that need to be handled separately, and on at least some builds the `$IncludeConfig` for `/etc/rsyslog.d` is implicit (compiled in).

You'll also want the preceding four commits as the changes won't apply without them. They are mostly just cleanups as well as a new `logs.nojournal` option that completely switches off journal collection. It's mainly for testing as the long runtimes get kinda annoying when running the plugin repeatedly.

**Comment by BryanQuigley** [comment]
As noted previously this was fixed in 3.5.1 (and then improved in newer releases)
