### ISSUE TITLE
Confidential etcd data is captured in sosreports

### ISSUE THREAD

**Issue by brandisher** [sosreport/sos#1403]
Under [sosreport]/etc/etcd/, various confidential pieces information are captured (*.key, *.crt, *.csr).  These should not be captured by default.

```
$ pwd
/home/user/Downloads/sosreport/etc/etcd/
$ ls
etcd.conf
peer.crt
peer.csr
peer.key
server.crt
server.csr
server.key
```

**Comment by TurboTurtle** [comment]
So we had this come up before, in #1194. The response from the openshift support team was that the *.crt and *.csr files are needed and that the only secret bits that should be stripped are under `/etc/etcd/ca`, which we blacklist now.

The *.key files should get aded to the blacklist though, at a minimum.

**Comment by brandisher** [comment]
Blacklisting the keys sounds like a good idea to me.  Do you need anything from me to kick that off?

**Comment by TurboTurtle** [comment]
No, it's a trivial fix - I just want to make sure we nail this down so we don't have to re-visit it yet again later on.

So we're good with keeping the `*.crt` and `*.csr` files, and only blacklisting the `*.key` files, right? Is there anything else we potentially need to review with what the etcd plugin grabs today?

**Comment by brandisher** [comment]
> So we're good with keeping the *.crt and *.csr files, and only blacklisting the *.key files, right?
Correct.

> Is there anything else we potentially need to review with what the etcd plugin grabs today?
Not to my knowledge.
