### ISSUE TITLE
[utilities] command returncode can be None in some cases

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#1417]
When subprocess we invoke via the pipe sends EOF to stdout but does not terminate immediately, pipe's returncode is None. This causes some data are not collected as we test for command status (that equals to pipe's returncode) being equal to zero. Particular example: `grep -q %s /proc/modules` called at https://github.com/sosreport/sos/blob/master/sos/plugins/networking.py#L97 returns something, but `check_ext_prog` returns `False` so we dont collect `iptables`.

`sos_get_command_output` method simply has to wait till subprocess really terminates, and even then it can return pipe's returncode.

There are several options:

1) `p.wait()` before (or even instead of) `p.poll()`, to wait till the process terminates. That is recommended in https://github.com/sosreport/sos/commit/2fcf5f09e0e809124aeb5e262eeecbe446824efc#r30410300 / https://bugs.python.org/issue34566 . There are doubts this could cause deadlocks.

2) call `p.poll` in a loop till it returns `None` that should have the same effect. This is CPU intensive in case of (busy) waiting.

3) call `run` directly as suggested in https://github.com/sosreport/sos/commit/2fcf5f09e0e809124aeb5e262eeecbe446824efc#r30410336 ?

I have tested 1) and 2) vastly on:
- RHEL7 (several architectures)
- upstream Fedora
- F28
- Ubuntu 16.04

and found no issue - no deadlock, no skipped file (as far as I compared).

**Comment by TurboTurtle** [comment]
Is looping on `p.poll()` really CPU intensive, or just more intensive than `p.wait()`?

The concern for deadlocks is primarily driven from systems with large persistent journals (e.g. pacemaker clusters, or Openshift clusters) when run with `--all-logs`. Where you able to test with significantly sized journals?

**Comment by pmoravec** [comment]
> Where you able to test with significantly sized journals?

The biggest system included in my test had 1.7GB `journalctl_--no-pager_--all_--boot_--output_verbose` file collected and collecting this took 3 minutes - that sounds appropriate testing, no?
