### ISSUE TITLE
symlinks not collected if the target is directory

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#1428]
Reproducer:

- Let `sosreport` to collect `/bar`, e.g. by modifying some plugin:

    sed "s/\\/var\\/log\\/cumin/\\/bar/g" sos/plugins/qpid.py

- create `/bar` as a symlink to `/foo/bar` that contains some file:

    mkdir -p /foo/bar
    date > /foo/bar/qux
    ln -s /foo/bar /bar

- collect `qpid` plugin:

    sosreport -o qpid --batch --build -v -v -v --debug
    ..
    [plugin:qpid] link '/foo/bar' is a directory, skipping...

- check the sosreport build tree does not contain `qux` file (due to the `.. is a directory, skipping...`)

This is **not** a (recent) regression, i.e. 3.5.1 is behaving the same.

**Comment by bmr-cymru** [comment]
Very long standing known issue, back to at least sos-2.2:

```
<bmr> It's a long standing problem, that I think we can only resolve by redesign (but who knows,
      maybe 3.7)
<bmr> in the past, to collect a symlinked directory and content, you add to add_copy_spec("/bar/")
<bmr> I haven't tested that case lately, but I think we are not any worse than we were before,
<bmr> and slightly better, in that the empty directory structure _is_ created.
<bmr> If you look at the cdevN links on s390 that were broken, they contain the same effect
<bmr> the final directory symlink in the css0/... chain points to an empty directory.
<bmr> So I _think_ this is fine for now, unless someone can find a genuine problem case.
```

It used to be possible to force this for an explicit copy spec by writing `add_copy_spec("/link/dir/")`, i.e. with a trailing slash to force it to be treated as the target directory. I haven't tested this lately, but it's still a bit of a hack and does not help for directory paths that have intermediate symlink components.

**Comment by TurboTurtle** [comment]
I _think_ this is no longer a problem with the redesign that went into how we expand copyspec globbing? Has this been seen recently?

**Comment by pmoravec** [comment]
I can confirm this to be fixed / working well in current upstream.
