### ISSUE TITLE
Better fibrechannel data collection

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#143]
We need to collect better info on the rport:name:device mappings. Scooping up all the relevant bits of sys gets the raw data but in the past we relied on systool for formatted output.

Since systool is going away (it will not be installed by default on RHEL7 or other modern distros) we need to move to something else.

A new FC plug-in can capture formatted udevadm info data for relevant devices and rports until we have a better abstraction over the raw sysfs data.

**Comment by pierg75** [comment]
Hi Bryn...is the general sys collector still needed? 
I see currently we use the add_copy_spec() to collect sysfs data.

**Comment by bmr-cymru** [comment]
We talked about something like JSON for `/sys`, but really it's not the file entry cost (or not just), but the cost of trawling through everything. We made some big fixes to the tree copying code a couple of years ago that means it's no longer hazardous to use on sysfs paths: so far this has meant we haven't tried to come up with anything more elaborate for handling this data.

The one thing you need to be aware of copying from `/sys` is that symlinks that point to directories do not automatically copy the target. This means that if you are copying a tree (e.g. `/sys/block`) that references things in another tree (e.g. `/sys/devices`) then you need to explicitly copy both if you need the symlink targets to be included.

**Comment by pierg75** [comment]
I was trying to come up with something when I realised that it was probably already fixed.
I have some very small code that should lists all the files starting from a base path and avoid following the symlinks loops. I'll do a couple of tests and compare the results. If it doesn't improve anything I'll ditch it.

**Comment by pierg75** [comment]
Am I doing something wrong?
This from the latest upstream:
```
# time sosreport/sosreport --batch -o scsi
...
real    0m1.126s
user    0m1.051s
sys     0m0.099s
```
Very quick but:
```
# tar xvf sosreport-fed-home-20170916192205.tar.xz
# cd sosreport-fed-home-20170916192205
# cd sys/bus/scsi/devices/host0
-bash: cd: sys/bus/scsi/devices/host0: No such file or directory
# cd sys/class/scsi_disk/0\:0\:0\:0 
-bash: cd: sys/class/scsi_disk/0:0:0:0: No such file or directory

```
It seems all the symlinks are broken.

**Comment by bmr-cymru** [comment]
Not collecting the `/sys/devices` sub-tree?

**Comment by bmr-cymru** [comment]
```
lrwxrwxrwx. 1 root root 0 Aug 31 13:00 /sys/bus/scsi/devices/host0 -> ../../../devices/pci0000:00/0000:00:17.0/ata1/host0
```

**Comment by TurboTurtle** [comment]
Closing per add8b12
