### ISSUE TITLE
[archive] maximum recursion depth exceeded when following broken symlink cycle

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#1430]
set-up 1:

    cd /etc/yum.repos.d
    ln -s a.repo b.repo
    ln b.repo a.repo

or set-up 2:

    cd /etc/yum.repos.d
    ln -s c.repo c.repo

and reproducer: `sosreport -o yum`

raises plugin exception:

      File "/usr/lib/python2.7/site-packages/sos/archive.py", line 437, in add_link
        self.add_link(source, link_name)
      File "/usr/lib/python2.7/site-packages/sos/archive.py", line 437, in add_link
        self.add_link(source, link_name)
      File "/usr/lib/python2.7/site-packages/sos/archive.py", line 437, in add_link
        self.add_link(source, link_name)
      File "/usr/lib/python2.7/site-packages/sos/archive.py", line 437, in add_link
        self.add_link(source, link_name)
      File "/usr/lib/python2.7/site-packages/sos/archive.py", line 423, in add_link
        host_path_name = os.path.realpath(os.path.join(source_dir, source))
      File "/usr/lib64/python2.7/posixpath.py", line 367, in realpath
        path, ok = _joinrealpath('', filename, {})
      File "/usr/lib64/python2.7/posixpath.py", line 406, in _joinrealpath
        path, ok = _joinrealpath(path, os.readlink(newpath), seen)
      File "/usr/lib64/python2.7/posixpath.py", line 406, in _joinrealpath
        path, ok = _joinrealpath(path, os.readlink(newpath), seen)
      File "/usr/lib64/python2.7/posixpath.py", line 392, in _joinrealpath
        if not islink(newpath):
      File "/usr/lib64/python2.7/posixpath.py", line 145, in islink
        return stat.S_ISLNK(st.st_mode)
      File "/usr/lib64/python2.7/stat.py", line 56, in S_ISLNK
        return S_IFMT(mode) == S_IFLNK
    RuntimeError: maximum recursion depth exceeded

as we are trying to collect link target in an infinite loop.

In 3.5, set-up 2 was working fine and "just" set-up 1 was failing. But both are instances of same problem.

Idea of fix: don't examinate broken symlink target, examinate it conditionally only when `os.path.exists() == True`

**Comment by bmr-cymru** [comment]
Tested with both simple ('a'->'a') and indirect ('a'->'b'->'a').

**Comment by pmoravec** [comment]
Nice; since the `os.stat` detects also "a -> a" symlink loop, doesnt it make sense to simplify the `is_loop` function to:

        def is_loop(link_name):
            """Return ``True`` if the symbolic link ``link_name`` is part
                of a file system loop, or ``False`` otherwise.
            """
            link_name = os.path.realpath(link_name)

            # Find direct (a->a) and also indirect loops (a->b-a) by
            # stat()ing the first step in the symlink chain
            try:
                os.stat(link_name)
            except OSError as e:
                if e.errno == 40:
                    return True
                raise
            return False

?

(reopening just to decide this simplification)

**Comment by bmr-cymru** [comment]
It is an optimisation: a simple string comparison vs. an actual syscall into the kernel / file system. So no, I don't think we should remove it.

**Comment by pmoravec** [comment]
Ah right, havent realized this, great then!

**Comment by bmr-cymru** [comment]
It may be not that important, I didn't do any real benchmarking - it just seemed an obvious "1st check" - if the strings are the same, we know for sure it's a loop without bothering the kernel.
