### ISSUE TITLE
[sosreport,utilities] sosreport can hang on timeouted plugin

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#1446]
In particular scenarios, sosreport can hang infinitely when waiting to shutdown a thread for timeouted plugin, with backtrace (of the only "running" process that time):

    /usr/lib64/python2.7/threading.py, line 362, in wait
    /usr/lib64/python2.7/threading.py, line 954, in join
    /usr/lib/python2.7/site-packages/concurrent/futures/thread.py, line 148, in shutdown
    /root/sos-master/sos/sosreport.py, line 1077, in collect

We must react on timeouted plugin in better way.

Particular reproducer: https://github.com/sosreport/sos/pull/1445#issuecomment-427761038 (optionally decrease plugin's timeout in https://github.com/sosreport/sos/blob/master/sos/plugins/__init__.py#L130 to lower value to see the problem faster).

**Comment by pmoravec** [comment]
@TurboTurtle , any idea?

**Comment by TurboTurtle** [comment]
IIRC this (only?) happens when a command we're collecting enters D-state, right?

I'm not immediately aware of a way to force-kill a thread in that state, but I want to properly scope what we're looking at here. Are there any other scenarios you've found where this could happen?

**Comment by TurboTurtle** [comment]
As mentioned in PR #1492, I found that this was because `shutdown()` only cancels pending jobs, not running ones. To cancel running jobs we need to use `_threads.clear()` on the threadpool.
