### ISSUE TITLE
New plugin for Container-native virtualization (CNV)

### ISSUE THREAD

**Issue by vakhanna** [sosreport/sos#1455]
New plugin for Container-native virtualization (CNV), an add-on to OCP. CNV is based on project kubevirt and it enables VMs to run alongside containers in OCP.
This plugin mainly runs commands and collects output related to several cluster wide general resources and CNV specific data, pods description/logs etc. (providing options for this) as below:

1. cnv.virt-control: services, pods collections related to cnv controllers
2. cnv.storage:  services, pods collections related to cnv specific storage
3. cnv.vm: collect data related to VMs. this is enabled by passing VM name as an argument to option eg: cnv.vm=<instance name>
4. cnv.network: networking pods. this is similar to VM option above, takes node name as an arument. eg: cnv.network=<node hostname>

The plugin development is currently ongoing locally. Whats the best way to bring it upstream for early review and feedback?
Also, for options with parameters ( as in 3 and 4 above), we would like to enable multiple parameters (multiple VMs for example in 3). Can we use any delimiter to separate them or is there any guidance/recommended way to enable this functionality?

**Comment by vakhanna** [comment]
Thanks for the guidance and sorry for a delayed response. We were evaluating the ways to reduce number of options. I have reduced the options to one for now, potentially we may plan to add another one in future.
Regarding the node data collection, its not a cross-node operation. All the node related data is pulled from the master node where the plugin runs. No SSH needed.

I am having hard time pushing the code to a branch upstream, tried both https and ssh. Could you please help ensure I have right access?

**Comment by bmr-cymru** [comment]
> I am having hard time pushing the code to a branch upstream, tried both https and ssh. Could you please help ensure I have right access?

You need to push it to a branch in your own repository, then reference it in a pull request or a comment.

**Comment by vakhanna** [comment]
Created a PR.
[cnv] new sos plugin for Container-native virtualization #1462
https://github.com/sosreport/sos/pull/1462

**Comment by TurboTurtle** [comment]
Closing this as cnv collection was added in #1599.

If there are missing cnv-related collection points that should be added, please open a new issue/PR to add them.
