### ISSUE TITLE
[openvswitch] Add "ovs-appctl dpctl/dump-flows"

### ISSUE THREAD

**Issue by andreaskaris** [sosreport/sos#1467]
Hi,

Can we add ovs-appctl dpctl/dump-flows to the openvswitch plugin?

Something along these lines:

```diff
commit bd8689f409e978a17b0390cb0a833315483721d7 (HEAD -> ovs_dpctl_dumpflows)
Author: Andreas Karis <akaris@redhat.com>
Date:   Tue Oct 30 13:35:07 2018 -0400

    [openvswitch] Capture additional datapath flows
    
    Capture additional datapath flows for the OVS
    netdev datapath with: ovs-appctl dpctl/dump-flows
    
    Signed-off-by: Andreas Karis <akaris@redhat.com>

diff --git a/sos/plugins/openvswitch.py b/sos/plugins/openvswitch.py
index 23a47e4f..682c9a1f 100644
--- a/sos/plugins/openvswitch.py
+++ b/sos/plugins/openvswitch.py
@@ -83,6 +83,8 @@ class OpenVSwitch(Plugin):
             "ovs-vsctl list Open_vSwitch",
             # Capture DPDK datapath packet counters and config
             "ovs-appctl dpctl/show -s",
+            # Capture DPDK datapath flows
+            "ovs-appctl dpctl/dump-flows",
             # Capture DPDK queue to pmd mapping
             "ovs-appctl dpif-netdev/pmd-rxq-show",
             # Capture DPDK pmd stats
```

**Comment by bmr-cymru** [comment]
What's the difference between `ovs-appctl dpctl/dump-flows` and this command we already collect?

```
            # Capture the in-kernel flow information if it exists
            "ovs-dpctl dump-flows -m",
```

Happy to add it, just want to make sure we aren't duplicating anything or collecting redundant copies.

**Comment by andreaskaris** [comment]
Hi!

It doesn't capture flows for the DPDK datapath which requires a different
command, unfortunately:

http://www.openvswitch.org/support/dist-docs/ovs-dpctl.8.txt
(...)
       This program works only with datapaths that are implemented outside  of
       ovs-vswitchd  itself,  such as the Linux and Windows kernel-based data‐
       paths.  To manage datapaths that are integrated into ovs-vswitchd, such
       as  the  userspace  (netdev)  datapath, use ovs-appctl(8) to invoke the
       dpctl/* commands, which are documented in ovs-vswitchd(8).

(...)


Regards,


Andreas

**Comment by TurboTurtle** [comment]
This command is currently captured by the `openvswitch` plugin in the `master` branch.
