### ISSUE TITLE
Iterator abstractions (hbas, disks, cpus, network interfaces, bridges, etc.)

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#148]
Iterate over $some_system_objects is becoming a fairly common idiom in sos plug-in code. E.g. the filesys and block plug-ins contain very similar code for iterating over whole-disk block devices as found in /sys/block:

``` python
        if os.path.isdir("/sys/block"):
            for disk in os.listdir("/sys/block"):
                if disk in [ ".",  ".." ] or disk.startswith("ram"):
                    continue
                disk_path = os.path.join('/dev/', disk)
                self.add_cmd_output("udevadm info -ap /sys/block/%s" % (disk))
                self.add_cmd_output("parted -s %s print" % (disk_path))
                self.add_cmd_output("fdisk -l %s" % disk_path)
```

and:

``` python
        if os.path.isdir(sys_block):
            for disk in os.listdir(sys_block):
                if disk.startswith("sd") or disk.startswith("hd"):
                    disk_path = os.path.join(dev_path, disk)
                    self.add_cmd_output("hdparm %s" % disk_path)
                    self.add_cmd_output("smartctl -a %s" % disk_path)
```

These two especially are doing essentially the same thing: iterating over all entries in /sys/block and filtering by name.

It seems like it would be useful to provide a common abstraction for these uses rather than allowing multiple hand-rolled versions to proliferate.

**Comment by TurboTurtle** [comment]
This is generally handled by a2720ae - which today has support for block devices and the framework for other devices. We'd just need to expand this as we see fit going forward for E.G. NICs.
