### ISSUE TITLE
[plugin] get_option doesnt work well for options being prefixes of other options - in python3

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#1498]
Use case:

    sosreport -o lvm2 --batch -k lvm2.lvmdump-am=on --build -v

does not collect `lvmdump -a -m ..` when using `python3`, while it properly does in `python2`.

The cause is tricky:
- 'str' class in python3 has newly `__iter__` attribute, so https://github.com/sosreport/sos/blob/master/sos/plugins/__init__.py#L535  is evaluated to `True` - this is the bad decision
- then `lvmdump in lvmdump-am` i.e. `True` is returned
- so `get_option` *thinks* `lvmdump-am` option is "enabled" via `lvmdump` option
- so for `lvmdump-am`, it takes value of `lvmdump` option instead, that is by default `False`
- so `self.get_option('lvmdump-am')` is evaluated to `False` (or in general to `self.get_option('lvmdump')`)

Dirty patch I dont like:  extend `if hasattr(optionname, "__iter__"):` by condition "and optionname isnt type 'str'"

**Comment by pmoravec** [comment]
Can't be there just test `if isinstance(optionname, list):` instead?

Or from a bit broader perspective: we compare option names here. How an option name can be a _list_ (or dict or so)? Can't be there simple `return key == optionname` (or doesnt it make sense to get rid of the method completely and replace `if _check(name):` by `if name == optionname:`)?

**Comment by bmr-cymru** [comment]
Using `isinstance()` may have other problems - a tuple is not an instance of `list` for e.g.

How about using the presence of an `encode` method?

```diff
diff --git a/sos/plugins/__init__.py b/sos/plugins/__init__.py
index 3abe29db..a305ef3d 100644
--- a/sos/plugins/__init__.py
+++ b/sos/plugins/__init__.py
@@ -532,10 +532,10 @@ class Plugin(object):
             return getattr(self.commons['cmdlineopts'], optionname)
 
         def _check(key):
-            if hasattr(optionname, "__iter__"):
-                return key in optionname
-            else:
+            if hasattr(optionname, "encode"):
                 return key == optionname
+            else:
+                return key in optionname
 
         for name, parms in zip(self.opt_names, self.opt_parms):
             if _check(name):
```

**Comment by bmr-cymru** [comment]
This works for me on both 2 & 3.

**Comment by bmr-cymru** [comment]
> Can't be there just test if isinstance(optionname, list): instead?

We can't tell without following all the possibilities through the code - I am not sure from a quick glance (but the encode check is still better & works).

The reason is that this is another blob of code that tracks back to everyone's favourite giant hairball commit:

```
commit 6ea48cbbc85d007dfefd1f254db66ff2e0a9cec5
Author: Jesse Jaggars <jhjaggars@gmail.com>
Date:   Wed Dec 14 16:05:59 2011 -0600

    Major updates to most of SoSReport
    
    Code reorganization
    Cross platform support for Windows, OS X and Linux
    Dynamically loaded policies
    Support for loading plugins from multiple locations
      via __path__ modification of sos.plugins
    Support for running via Jython
    Support for executing from a jarfile
    Support for json based reporting infrastructure
      - Previous reporting methods still exist
    Support for other checksum algorithms (determined by policy)
    Support for other compression algorithms (determined by policy)
    New plugin API for writing arbitrary information in a new file inside
        the report archive.
    New plugin API for modifying files that have been added to the
        archive.
    Added API for global plugin options
      - external interface is unavailable at this time
    Many small bugfixes
```

:-/

**Comment by pmoravec** [comment]
Nice, thanks!
