### ISSUE TITLE
Large command outputs should not be completely stored in memory

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#1506]
Despite memory utilization improvements done in past year, there is still one(?) principal bottleneck causing whole outputs of commands are kept in memory in one chunk:

https://github.com/sosreport/sos/blob/master/sos/utilities.py#L246

This implies that e.g. on OpenStack, due to RHOSP preset and --all-logs option enabled by default, journalctl verbosed output is collected (usually the biggest output I have seen in a sosreport). This requires few-to-many GB of memory, usually. And it can easily cause OOM killer stopping sosreport execution.

Sosreport should handle (big or all?) command outputs either:

- in memory by smaller batches (this can be problematic for regexp substitution when the regexp to be matched is spread over few batches processed independently)
- or write them to the disk (and apply regexp sub on the file)

Several options are here:
- keep in memory just small batches OR write everything to the disk
- apply this change just to outputs bigger than some threshold OR to all outputs (as there is a performance penalty behind this change)

What also plays a role: we need to keep the output in memory just for the sake of possible regexp substitution. In other cases, we can simply write the output to the disk without storing it completely in memory.

(my deduction/opinion): This fact suggests we shall write everything directly to a file (so AsyncReader should do so, all chunks of self.dequeue in a row) - ideally to the final destination within the sosreport build tree - and then regexp sub to be applied on the file.

**Comment by bmr-cymru** [comment]
Yeah. That kinda defeats the entire object. I think the answer here is to refactor that as a method as a generator, *but* I don't think that really solves the problem: it's the straw that breaks the camel's back. I didn't check in detail but my guess what's happening here is `sizelimit` is disabled, the entire command output is pulled into memory, and then we do the join and format another giant string - it's this 2nd allocation that takes us down the OOM route.

If that is the case then we need to find a way to stream output to the file from the pipeline. I'll try to look properly later on once I've got outstanding PRs done.

**Comment by bmr-cymru** [comment]
> in memory by smaller batches

Long term I think that's the only answer. Do we have many multi-line regexes (or regexes that address single lines that may be excessively large)? I'm not sure that's the case.

**Comment by pmoravec** [comment]
> Do we have many multi-line regexes (or regexes that address single lines that may be excessively large)? I'm not sure that's the case.

IMHO "just" scrubbing of SSL certs belong to this.

**Comment by pmoravec** [comment]
Just as a cross-reference: this issue is planned to be resolved in sos 4.0, see #1959 and "IO improvements".
