### ISSUE TITLE
[soundcard] should add arecord

### ISSUE THREAD

**Issue by ycheng** [sosreport/sos#1515]
there are
aplay -l
aplay -L

we also need
arecord -l
arecord -L

**Comment by jcastill** [comment]
Can we expect to have arecord display a different output to aplay? In the man page, they say:

>       arecord is a command-line soundfile recorder for the ALSA soundcard driver. It supports several file formats and multiple soundcards with multiple devices. If recording with interleaved mode samples
>        the file is automatically split before the 2GB filesize.
> 
>        aplay is much the same, only it plays instead of recording. For supported soundfile formats, the sampling rate, bit depth, and so forth can be automatically determined from the soundfile header.
> 

And for the options listed, it seems that both options should show the same output for aplay/arecord:

>        -l, --list-devices
>               List all soundcards and digital audio devices
> 
>        -L, --list-pcms
>               List all PCMs defined

**Comment by TurboTurtle** [comment]
Across a couple of systems I'm seeing no new information in `arecord` compared to `aplay`. In fact `aplay` has all the same information as `arecord` in addition to some output that is not in `arecord`.

Closing this, as I do not see an added benefit of capturing `arecord`. If you can provide example output of where `arecord` provides additional information that is not included in `aplay` output, please feel free to re-open this request.
