### ISSUE TITLE
lvm2 plugin use locking_type=0, may corrupt lvm on shared storage

### ISSUE THREAD

**Issue by nirs** [sosreport/sos#1533]
lvm2 plugin contains this note:

    # use locking_type 0 (no locks) when running LVM2 commands,
    # from lvm.conf:
    # Turn locking off by setting to 0 (dangerous: risks metadata
    # corruption if LVM2 commands get run concurrently).
    # None of the commands issued by sos ever modify metadata and this
    # avoids the possibility of hanging lvm commands when another process
    # or node holds a conflicting lock.

And then it use this config:

    --config 'global { locking_type= 0 }'

To run vgscan, pvscan, pvs, vgs, lvs.

According to David Teigland, *any* lvm command may attempt to recover VG metadata, so running
the lvm2 plugin on oVirt hypervisor is risky. In oVirt, same VG is accessed from multiple hosts. Only 
one host is allowed to do metadata changes, so other hosts must always use locking_type=4.

oVirt recommends setting up lvm filter hiding all shared storage from local lvm commands. A host with
such lvm is safe, but since lvm filter is not enforced yet by oVirt, we cannot rely on having proper lvm
filter.

Here is a related bug about corrupted VG metadata caused by "read-only" commands such as
"lvchange --refresh" with locking_type=1.
https://bugzilla.redhat.com/1553133

I think we should replace the config with:

    --config "global { locking_type=4 wait_for_locks=0 }"

At least when running on oVirt hypervisor, or maybe sosreport user should disable lvm2 plugin when
running on oVirt hypervisor?

vdsm plugin already collect lvm output from pvs, vgs, and lvs. We can enhance it to collect more info
collected by lvm2 plugin.

**Comment by bmr-cymru** [comment]
We need resolution of the questions on the LVM side before we can do anything here: it's a bit daft that there is no way to prevent silent metadata modifications, or to use the tools in a truly read-only fashion (even when LVM locking is broken).

**Comment by bmr-cymru** [comment]
On Thu, Jan 10, 2019 at 03:27:55PM -0800, Nir Soffer wrote:
> This may work better - avoiding locking issues, and getting all data in case of errors:
> 
>     --config 'global {locking_type=0  metadata_read_only = 0}'
> 
> It works for pvscan, vgscan, pvs, vgs, and lvs.

Thanks - that looks much more appealing.
 
> Regarding duplicate collection, I would happily delete lvm commands from vdsm plugin if it was possible,
> but it is not. With a proper lvm filter as oVirt recommends, lvm.conf has filter like:
> 
>     filter = ["a|^/dev/vda2$|", "r|.*|"]
> 
> Hiding all devices from lvm, except the devices required by the host. This is critical to avoid  auto
> activation issues, or even accidental deletion of oVirt logical volumes.
> See https://ovirt.org/blog/2017/12/lvm-configuration-the-easy-way.html

Right; we do get this, which is why we're happy to consider an exception
for now.

There's some other work going on at the moment that I think may allow us
to revisit this in future, but it's not yet close to being ready for
master.

Regards,
Bryn.
