### ISSUE TITLE
Have sosreport collect /etc/environment.

### ISSUE THREAD

**Issue by alexmcan** [sosreport/sos#1550]

**Comment by BryanQuigley** [comment]
or systemctl show-environment, any idea which is more useful?

**Comment by alexmcan** [comment]
systemctl show-environment doesn't show what's in in /etc/environment

`ubuntu@ldscert:~$ cat /etc/environment
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
no_proxy=127.0.0.1,localhost
NO_PROXY=127.0.0.1,localhost

ubuntu@ldscert:~$ systemctl show-environment
LANG=en_US.UTF-8
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
