### ISSUE TITLE
[RFE] add cloud-init config files 

### ISSUE THREAD

**Issue by shatadru** [sosreport/sos#1584]
We collect cloud-init log files after 5a72961 however we don't collect config files.

I propose a separate plug-in for cloud-init to copy /etc/cloud/ and /var/lib/cloud/ also collect /var/log/cloud-init via this plugin

**Comment by bmr-cymru** [comment]
Ack (although that's the wrong commit reference - it's actually commit 36efd32ab01df2c076c3271543d674a515094375 in master). This should never have been added to the `logs` plugin in the first place - that is only for system logs, like (r)syslog and the journal.

**Comment by shatadru** [comment]
Exactly, I can send a pull request for the same.

**Comment by bmr-cymru** [comment]
Thanks - can just send a PR in future, if you have a proposed fix, no need for a separate issue.
