### ISSUE TITLE
[plugins] plugin timeout does not kill the timeouted plugin

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#1590]
Plugin timeout does not terminate the timeouted plugin. Particular reproducer: on a system with a bigger `yum` history, call:

    sosreport --plugin-timeout=30 -k yum.yum-history-info=yes -o yum --batch --build

output:

     Setting up archive ...
     Setting up plugins ...
     Running plugins. Please wait ...
    
      Starting 1/1   yum             [Running: yum]
    
     Plugin yum timed out

and the `sosreport` process seems to be hung forever with backtrace:

    Thread 4 
    #4  /usr/lib64/python2.7/threading.py, line 362, in wait 
    #8  /usr/lib64/python2.7/threading.py, line 962, in join 
    #12 /usr/lib/python2.7/site-packages/concurrent/futures/thread.py, line 148, in shutdown 
    #16 /root/sos-master/sos/sosreport.py, line 1081, in collect 
    #19 /root/sos-master/sos/sosreport.py, line 1476, in execute 
    #22 /root/sos-master/sos/sosreport.py, line 1503, in main 
    Thread 3 
    #6  /root/sos-master/sos/utilities.py, line 232, in run 
    #10 /usr/lib64/python2.7/threading.py, line 812, in __bootstrap_inner 
    #13 /usr/lib64/python2.7/threading.py, line 785, in __bootstrap 
    Thread 2 
    #7  /usr/lib64/python2.7/threading.py, line 339, in wait 
    #11 /usr/lib64/python2.7/threading.py, line 951, in join 
    #15 /root/sos-master/sos/utilities.py, line 219, in __init__ 
    #26 /root/sos-master/sos/utilities.py, line 156, in sos_get_command_output 
    #30 /root/sos-master/sos/plugins/__init__.py, line 666, in get_command_output 
    #34 /root/sos-master/sos/plugins/__init__.py, line 798, in get_cmd_output_now 
    #38 /root/sos-master/sos/plugins/__init__.py, line 980, in _collect_cmd_output 
    #42 /root/sos-master/sos/plugins/__init__.py, line 1004, in collect 
    #46 /root/sos-master/sos/sosreport.py, line 1123, in collect_plugin 
    #51 /usr/lib/python2.7/site-packages/concurrent/futures/thread.py, line 62, in run 
    #54 /usr/lib/python2.7/site-packages/concurrent/futures/thread.py, line 74, in _worker 
    #59 /usr/lib64/python2.7/threading.py, line 765, in run 
    #62 /usr/lib64/python2.7/threading.py, line 812, in __bootstrap_inner 
    #65 /usr/lib64/python2.7/threading.py, line 785, in __bootstrap 
    Thread 1 
    #4  /usr/lib64/python2.7/threading.py, line 362, in wait 
    #8  /usr/lib64/python2.7/threading.py, line 962, in join 
    #12 /usr/lib/python2.7/site-packages/concurrent/futures/thread.py, line 148, in shutdown 
    #16 /usr/lib/python2.7/site-packages/concurrent/futures/_base.py, line 630, in __exit__ 
    #23 0x00007f2296ae62d4 in /root/sos-master/sos/sosreport.py, line 1106, in _collect_plugin 
    #28 /usr/lib/python2.7/site-packages/concurrent/futures/thread.py, line 62, in run 
    #31 /usr/lib/python2.7/site-packages/concurrent/futures/thread.py, line 74, in _worker 
    #36 /usr/lib64/python2.7/threading.py, line 765, in run 
    #39 /usr/lib64/python2.7/threading.py, line 812, in __bootstrap_inner 
    #42 /usr/lib64/python2.7/threading.py, line 785, in __bootstrap 

In fact, the plugin itself uninterruptedly continues in its execution (`ps` shows `timeout 300s yum history info XX` for `XX` evolving in time).

More specific and minimalistic reproducer: have a `sleep` plugin:

    from sos.plugins import Plugin, RedHatPlugin, UbuntuPlugin, DebianPlugin
    
    class Sleep(Plugin, RedHatPlugin, UbuntuPlugin, DebianPlugin):
        """Sleep test"""
        plugin_name = "sleep"
    
        def setup(self):
            for t in [6, 7, 8, 9, 10]:
                self.add_cmd_output("sleep %s" % t)
    
and call it as follows:

    # time ./sosreport --plugin-timeout=3 -o sleep --batch --build
    
    sosreport (version 3.6)
    
    ..
    
     Running plugins. Please wait ...
    
      Starting 1/1   sleep           [Running: sleep]
    
     Plugin sleep timed out
    
    
      Finished running plugins
    
    
    sosreport build tree is located at : /var/tmp/sosreport-localhost-2019-03-18-ahaolyq
    
    
    
    real	0m49.806s
    user	0m5.796s
    sys	0m4.748s
    # find /var/tmp/sosreport-localhost-2019-03-18-ahaolyq | grep sleep
    /var/tmp/sosreport-localhost-2019-03-18-ahaolyq/sos_commands/sleep
    /var/tmp/sosreport-localhost-2019-03-18-ahaolyq/sos_commands/sleep/sleep_6
    /var/tmp/sosreport-localhost-2019-03-18-ahaolyq/sos_commands/sleep/sleep_7
    /var/tmp/sosreport-localhost-2019-03-18-ahaolyq/sos_commands/sleep/sleep_8
    /var/tmp/sosreport-localhost-2019-03-18-ahaolyq/sos_commands/sleep/sleep_9
    /var/tmp/sosreport-localhost-2019-03-18-ahaolyq/sos_commands/sleep/sleep_10
    #

All "sleep .." were collected, despite started to be called after the plugin timeouted.

**Comment by pmoravec** [comment]
Btw. it is *not* a regression from `--plugin-timeout` implementation (commit 031ff48) - the same behaviour is observed prior this commit (when I replace `timeout = 300` by `timeout = 3` in `sos/plugins/__init__.py`).

**Comment by bmr-cymru** [comment]
> despite started to be called after the plugin timeouted.

Obviously there's a bug here, but I'm unclear on this - the plugin *started* after it had timed out? How does that happen?

**Comment by pmoravec** [comment]
No, just commands from the plugin started after plugin timeout was detected. I.e. if I run my `sleep` plugin alone, it starts immediatelly, calls "sleep 6", get timeouted, finishes "sleep 6", calls "sleep 7" (this is the "started after timeout), etc.

**Comment by pmoravec** [comment]
(as tested, 3.6 release exhibit the same behaviour as well)

**Comment by pmoravec** [comment]
OK, code change from #1492 does terminate the plugin / thread, it just raises a red herring:

    caught exception in plugin method "sleep.collect()"
    writing traceback to sos_logs/sleep-plugin-errors.txt

while no such file is in the tarball. (just insufficient catchup of some exception, I guess?)
