### ISSUE TITLE
[docker] Predicate needs to be set later in the plugin

### ISSUE THREAD

**Issue by TurboTurtle** [sosreport/sos#1617]
The `docker` plugin predicate is set immediately inside `setup()`, however it should be set later in the plugin, after the `add_copy_spec()` and `add_journal()` calls so that even if the daemon is stopped, we can still get those bits.

However, in creating a PR for this, it seems that `SoSPredicate` needs to be initialized with `owner=self`, e.g. `self.set_cmd_predicate(SoSPredicate(owner=self, services=["docker"]))`.

I'm not sure if this is intentional in design and whenever we create a `SoSPredicate()` we need to pass `self` (and thus the invocation in the docker plugin as written is incorrect) or if it is written as intended in the docker plugin, and `owner` needs to be set internally.

**Comment by bmr-cymru** [comment]
Just a bug - I didn't really re-review this patch, and it's wrong in a couple of ways. Sets too early, and it's missing owner assignments.
