### ISSUE TITLE
3.7: sosreport -a crash on npm plugin

### ISSUE THREAD

**Issue by sandrobonazzola** [sosreport/sos#1625]
Built sos from 3.7 tag.

$ sosreport -a

sosreport (version 3.7)

This command will collect system configuration and diagnostic
information from this Fedora system. An archive containing the collected
information will be generated in /var/tmp/sos.xl5u5erk.

For more information on the Fedora Project visit:

  https://fedoraproject.org/

The generated archive may contain data considered sensitive and its
content should be reviewed by the originating organization before being
passed to any third party.

No changes will be made to system configuration.

Premere INVIO per continuare, o CTRL-C per usicre.

Please enter the case id that you are generating this report for []: 

 Setting up archive ...
 Setting up plugins ...
 Running plugins. Please wait ...

  Starting 1/1   npm             [Running: npm]                                           caught exception in plugin method "npm.collect()"
writing traceback to sos_logs/npm-plugin-errors.txt

Creazione di un archivio compresso, in corso ...

Your sosreport has been generated and saved in:
  /var/tmp/sosreport-sbonazzo-2019-03-28-dezsecu.tar.xz

The checksum is: 5fb7a55e341fad7a690be6d84b90038e

Please send this file to your support representative.

Traceback is:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/sos/sosreport.py", line 1020, in collect_plugin
    plug.collect()
  File "/usr/lib/python3.7/site-packages/sos/plugins/__init__.py", line 1206, in collect
    self._collect_cmd_output()
  File "/usr/lib/python3.7/site-packages/sos/plugins/__init__.py", line 1182, in _collect_cmd_output
    sizelimit=sizelimit)
  File "/usr/lib/python3.7/site-packages/sos/plugins/__init__.py", line 986, in _get_cmd_output_now
    sizelimit=sizelimit)
  File "/usr/lib/python3.7/site-packages/sos/plugins/__init__.py", line 841, in get_command_output
    poller=self.check_timeout)
  File "/usr/lib/python3.7/site-packages/sos/utilities.py", line 153, in sos_get_command_output
    preexec_fn=_child_prep_fn)
  File "/usr/lib64/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.7/subprocess.py", line 1523, in _execute_child
    raise child_exception_type(err_msg)
subprocess.SubprocessError: Exception occurred in preexec_fn.

**Comment by pmoravec** [comment]
It would be interesting to have the sosreport tarball itself, but.. why sos fails in Popen (https://github.com/sosreport/sos/blob/master/sos/utilities.py#L150-L153)? Some ulimit problem? Non-admin user related?

**Comment by pmoravec** [comment]
Oh, ok, seems bit generic problem - on a Fedora28 on a freshly new user (not root), I can get the same via:

    /usr/libexec/system-python ./sosreport -o npm --batch --build

**Comment by bmr-cymru** [comment]
OK so this is my fault - I allowed the `required_root = False` in `npm` even though we didn't have the rest of the infrastructure for it at the time. We should probably just yank that out until we are really ready to deal with it.
