### ISSUE TITLE
[sar] drop collecting sadf xml reports

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#1627]
`sar` plugin also collects `sadf -x /var/log/sa/saXY`, basically for all `saXY` files. Since we generate `sarXY` for most files for human-readable format and the `xml` report contains only CPU usage and we also collect binary `saXY` files, I think the `xml` files are redundant to collect - sometimes it is even confusing to have them.

If one needs some such data, (s)he can generate them locally via `sadf` command either way.

Does it sound reasonable to drop https://github.com/sosreport/sos/blob/master/sos/plugins/sar.py#L67-L68 ?

**Comment by bmr-cymru** [comment]
This was requested by the PCP folks - @portante ?

**Comment by portante** [comment]
Not sure about who is really asking for this, but I believe running `sadf -x` command allows one to use the proper `sadf` command over the data files with the version of `sysstat` that generated those data files.

If you remove collecting the `sadf -x` output, you then have to invest in making sure an older sosreport with `saXY` files (or `saYYYYMMDD` files) can be read by a newer sysstat version (compatibility has always been dicey).

**Comment by bmr-cymru** [comment]
> If one needs some such data, (s)he can generate them locally via sadf command either way.

@pmoravec what's the motivation for dropping them?

**Comment by bmr-cymru** [comment]
> the xml report contains only CPU usage

Really? I expected them to reflect the full data set. Are we not using the right options?

**Comment by pmoravec** [comment]
Some my colleagues in support were confused by those files containing really only CPU data, like:

    # cat sos_commands/sar/sa31.xml
    ..
		<statistics>
			<timestamp date="2019-03-31" time="04:10:01" interval="600">
				<cpu-load>
					<cpu number="all" user="0.41" nice="0.00" system="0.11" iowait="0.01" steal="0.00" idle="99.46"/>
				</cpu-load>
			</timestamp>
    ..
			<timestamp date="2019-04-01" time="03:50:01" interval="599">
				<cpu-load>
					<cpu number="all" user="0.42" nice="0.00" system="0.11" iowait="0.01" steal="0.00" idle="99.46"/>
				</cpu-load>
			</timestamp>
		</statistics>
    ..
    #

To output all data, we shall append "-- -A" to the command (`sadf` prints same default data like `sar`, i.e. CPU only until we add `-A` or similar). Then we will collect both "sarXY" human readable and `sadf` xml output formats, i.e. bit duplicate data, but for a very low cost so I am fine with that.

If the xml files are required, I suggest adding "-- -A" to generate really all `sar` stats.

**Comment by bmr-cymru** [comment]
Hmm. We added these for a specific request.. so does that mean it has been broken ever since?

**Comment by pmoravec** [comment]
The argument "one needs specific version of sysstat to process the binary files" sounds valid to me as well, though I dont like mush we generate *two* similar text processing outputs of the data (sar and sadf) - is either of format preferred? Is it ok to drop either of them or should we spend the extra very few seconds for generating both text output formats?

**Comment by TurboTurtle** [comment]
Closing this alongside #1741/#2895. `sadf` collection is desired and "cheap", and it does currently use `-A` as suggested previously.
