### ISSUE TITLE
Reports inappropriate status while running a single plugin with -o option

### ISSUE THREAD

**Issue by sourabhjains** [sosreport/sos#1638]
While running a single plugin which needs root access and if runs it without giving the root access, sosreport say the plugin is not present.

Sample output:
./sosreport -o yum

sosreport (version 3.6)

a non-existing plugin (yum) was specified in the command line

Would be better if we print something like **_requires root access to run the plugin._**.

**Comment by bmr-cymru** [comment]
We don't currently support non-root use of `sosreport`. There is some infrastructure to allow this, but the work is incomplete and has never been announced as a supported feature in any release.

We can add a warning message to note this (or complete the work to support non-root), but for now what you are seeing is expected behaviour.

**Comment by sourabhjains** [comment]
IMO the error message depicted can mislead the users.

Is there any pull request that adds support for non-root use of sosreport?

**Comment by hegdevasant** [comment]
If non-root user is running then I think we should exit gracefully. How about something like below?

diff --git a/sos/sosreport.py b/sos/sosreport.py
index 11cae530..0d2e373b 100644
--- a/sos/sosreport.py
+++ b/sos/sosreport.py
@@ -315,6 +315,10 @@ class SoSReport(object):
             self._exit(0)
         self._is_root = self.policy.is_root()
 
+        if not self._is_root:
+            print("Please run as root user")
+            self._exit(0)
+
         # user specified command line preset
         if self.opts.preset != _arg_defaults["preset"]:
             self.preset = self.policy.find_preset(self.opts.preset)



-Vasant

**Comment by BryanQuigley** [comment]
This is a another issue better covered by #164 which will be discussed as part of 4.0
