### ISSUE TITLE
Root required

### ISSUE THREAD

**Issue by pierg75** [sosreport/sos#164]
Does sosreport require completely root privileges to run?
The problem came when I tried to run sosreport from a normal user and I got the message:

"no valid plugins were enabled"

This is because I think all the plugins inherit the "requires_root = True".

Changing this in plugins/**init**.py  to False, I could still run sosreport as normal user (even though many plugins failed).

Should sos run always as root (and maybe add a better message when run as normal user) or should it give the possibility to run as normal user (and then granularly change the  requires_root for every plugin)?

**Comment by TurboTurtle** [comment]
Tagging this with `4.0` so we can discuss if, with a new major version, we want to support non-root runs or not.

**Comment by TurboTurtle** [comment]
We have decided with 4.0 that we will be dropping the non-root framework. To be clear, this means that for 4.0+ it is expected to only run `sosreport` (or `sos report`) as root.
