### ISSUE TITLE
Edit wiki access?

### ISSUE THREAD

**Issue by BryanQuigley** [sosreport/sos#1646]
I'd like to add a page for end users to understand how to understand the basics of what a sosreport is collecting.

Walk them through looking at say sos_remports html to see what files have been collected/commands have been run.

I don't seem to have access to edit/create new wiki articles

**Comment by battlemidget** [comment]
Another thing would be nice to fix the Sphinx docs on rtfd.org, and start getting some more complete documentation out there

**Comment by bmr-cymru** [comment]
I'll look into the permissions. Docs improvements on the list.. just a matter of time, or someone else beating me too it :-D

**Comment by BryanQuigley** [comment]
Adding as a maintainer fixed this, will be adding wiki page.
