### ISSUE TITLE
[juju] juju plugins stop/start juju-db and mongod

### ISSUE THREAD

**Issue by slashdd** [sosreport/sos#1653]
The juju.py plugin need refactoring, IMHO, the plugin shouldn't try to stop/start the mongo database from the state/controller server such as juju-db, mongod.

If the process is stop/failed mode, ..., then exit or skip it. 
I don't think it's the responsibility of the juju plugin to take action on this.

Also juju-db is only found in the state-server AFAIK. Current plugin tries to stop/start juju-db on all machines where juju plugin is trigger by finding the juju binary which raise exception.

**Restart of mongod after a sosreport run:**
```
# pidof mongod
12622
# sosreport -a
# pidof mongod
1381
```

**Exception:**
```
Traceback (most recent call last):
  File "/usr/share/sosreport/sos/plugins/juju.py", line 22, in wrapped_f
    raise Exception("Cannot stop {0} service".format(service))
Exception: Cannot stop juju-db service
```

**Comment by pmoravec** [comment]
Indeed; `sosreport` shouldn't restart a service and imho even start one. So whole https://github.com/sosreport/sos/blob/master/sos/plugins/juju.py#L16-L31 shall be imho removed, together with places where it is called (https://github.com/sosreport/sos/blob/master/sos/plugins/juju.py#L61). Rather, this restart command might be replaced by "`service juju-db status`" to let a user to understand why mongo exports failed (if db was down).

I will file PR for this, anyway I know nothing about `juju`. So some functional review from a domain expert would be welcomed.
