### ISSUE TITLE
[kvm] should we block on qemu/kvm packages being installed?

### ISSUE THREAD

**Issue by BryanQuigley** [sosreport/sos#1657]
Seems kvm.py runs everywhere.. 

On LXD containers it reports:
[plugin:kvm] debugfs not mounted and mount attempt failed

**Comment by slashdd** [comment]
I haven't read the kvm plugin yet, but if the plugin is meant to run on both hypervisor and guest. Then we could trigger the plugin to run based on some detection pattern. For the hypervisor if `/usr/bin/kvm` exist and KVM guest using `systemd-detect-virt` if return qemu.

**Comment by TurboTurtle** [comment]
The error message should be cleaned up in #1807.

However, looking at the plugin - I think it's right to enable it on the `kvm` kernel module being loaded rather than packages, since we're only grabbing `/sys/module` files right now.

**Comment by BryanQuigley** [comment]
Agreed, we have the correct approach today.  Thanks!
