### ISSUE TITLE
[vdsm] presence of vdsm disallowing efficient LVM2 data collection

### ISSUE THREAD

**Issue by jtpittman195** [sosreport/sos#1665]
When vdsm is enabled on a system, it does not allow sosreport to efficiently gather LVM2 data.

The presence of the filter in var/run/vdsm/lvm prevents the lvm2 plugin from grabbing any usable data:
~~~
[john@host]$ cat sos_commands/lvm2/* | grep regex
        /dev/sda: Skipping (regex)
        /dev/mapper/rhvh-pool00_tmeta: Skipping (regex)
        /dev/sda1: Skipping (regex)
        /dev/mapper/rhvh-pool00_tdata: Skipping (regex)
        /dev/sda2: Skipping (regex)
...snip

[john@host]$ cat var/run/vdsm/lvm/lvm.conf 
 devices { preferred_names = ["^/dev/mapper/"] ignore_suspended_devices=1 write_cache_state=0 disable_after_error_count=3 filter = [ 'r|.*|' ] }  global {  locking_type=1  prioritise_write_locks=1  wait_for_locks=1  use_lvmetad=0 }  backup {  retain_min = 50  retain_days = 0 }
~~~

This has been the case for some time I believe, and to get around that filter, the vdsm plugin runs lvm commands and adds them to sos_commands/vdsm.  However, these vdsm-run lvm commands are executed with a filter as well.  In RHEL levels they're run only accepting /dev/mapper and in upstream only accepting mpath devices.

In the case where I ran into issues, the end user had a RHHI setup.  

https://access.redhat.com/documentation/en-us/red_hat_hyperconverged_infrastructure_for_virtualization/1.5/html-single/1.5_release_notes/index

They had a cachepool+thinpool LVM setup; the VG beneath built from 2 PVs, one a VDO device (/dev/mapper/vdo) and the other a sd device (/dev/sdc).  Normally, with vdsm, multipath is enabled.  It was disabled on this system.  So, in this setup, the lvm plugin does not give us any info due to vdsm, and vdsm will reject both devices in upstream sos and sdc in RHEL sos.

I've tried to think of a reasonable solution to this issue; but have been unsuccessful so far.

**Comment by bmr-cymru** [comment]
> In RHEL levels they're run only accepting /dev/mapper 

That version of the plugin has never been upstream - you need to contact the RHV folks for that.

> upstream only accepting mpath devices.

That's exactly what the developers of the (very recent) `vdsm` plugin asked for - I understand that this is deliberate, so I'll need to hear from them as to why it should or shouldn't be changed.

If I understand what you're looking for, you want LVM data from the regular system set of devices? If that's the case then why not get it from the regular `lvm2` plugin, and not the `vdsm` one, which as you have seen uses LVM in a very particular way?

**Comment by bmr-cymru** [comment]
> in this setup, the lvm plugin does not give us any info due to vdsm

Can you expand on that? Why isn't it getting data? Is there a pre-configured `/etc/lvm/lvm.conf` that excludes this?

**Comment by jtpittman195** [comment]
> Can you expand on that? Why isn't it getting data? Is there a pre-configured `/etc/lvm/lvm.conf` that excludes this?

Hey Bryn, thanks a lot for looking.  It seems everything is filtered out via the filter in var/run/vdsm/lvm/lvm.conf
~~~
[john@host]$ cat var/run/vdsm/lvm/lvm.conf 
 devices { preferred_names = ["^/dev/mapper/"] ignore_suspended_devices=1 write_cache_state=0 disable_after_error_count=3 filter = [ 'r|.*|' ] }  global {  locking_type=1  prioritise_write_locks=1  wait_for_locks=1  use_lvmetad=0 }  backup {  retain_min = 50  retain_days = 0 } 

[john@host]$ grep -r vdsm sos_commands/lvm2/
sos_commands/lvm2/vgscan_-vvv_--config_global_locking_type_0:      Loading config file: /var/run/vdsm/lvm/lvm.conf
sos_commands/lvm2/vgscan_-vvv_--config_global_locking_type_0:        Opened /var/run/vdsm/lvm/lvm.conf RO
sos_commands/lvm2/vgscan_-vvv_--config_global_locking_type_0:        Closed /var/run/vdsm/lvm/lvm.conf
sos_commands/lvm2/vgscan_-vvv_--config_global_locking_type_0:      Loading config file: /var/run/vdsm/lvm/lvm.conf
sos_commands/lvm2/vgscan_-vvv_--config_global_locking_type_0:        Opened /var/run/vdsm/lvm/lvm.conf RO
sos_commands/lvm2/vgscan_-vvv_--config_global_locking_type_0:        Closed /var/run/vdsm/lvm/lvm.conf
sos_commands/lvm2/vgdisplay_-vv_--config_global_locking_type_0:      Loading config file: /var/run/vdsm/lvm/lvm.conf
sos_commands/lvm2/vgdisplay_-vv_--config_global_locking_type_0:      Loading config file: /var/run/vdsm/lvm/lvm.conf
~~~

I can't tell what's directing lvm to check /var/run/vdsm/lvm/lvm.conf though.
~~~
[john@host]$ grep -r vdsm etc/lvm/
etc/lvm/lvmlocal.conf:#   revision    used by vdsm during upgrad to determine file revision
etc/lvm/lvmlocal.conf:#   private     if set to YES, vdsm will never upgrade this file
~~~

Briefly, I had thought it would be ok to just run the commands in the lvm plugin with a "--config 'devices{ filter = [ "a|.*|" ] }'", but that would pose issues because when we look in sos_commands/lvm we generally need to see the devices as the customer or end user sees them.

**Comment by bmr-cymru** [comment]
That's curious, but the answer should be in those `-vvv` output files somewhere - that's definitely not the normal LVM system configuration directory, unless VDSM is adding some extra magic to things.

**Comment by TurboTurtle** [comment]
This actually seems to be related to gluster, not vdsm.

Running sosreport on a RHV 4.2 hypervisor is sos-3.6, both the `lvm2` and `vdsm` plugins capture the correct lvs/vgs/etc.. output.

@jtpittman195 mentioned RHHI, so I ran a test sosreport on a RHHI-V environment I have access to and sure enough I get nothing in `lvm2`.


On a clean install of a RHV 4.2 (no RHHI-V), my `/var/run/vdsm/lvm/lvm.conf` looks like this:

```
 devices { preferred_names = ["^/dev/mapper/"] ignore_suspended_devices=1 write_cache_state=0 disable_after_error_count=3 filter = [ 'a|/dev/mapper/364cd98f038abe10024509d76121424b0|/dev/mapper/36742b0f00000084c0000000000009412|/dev/mapper/36742b0f00000084c0000000000009414|', 'r|.*|' ] }  global {  locking_type=1  prioritise_write_locks=1  wait_for_locks=1  use_lvmetad=0 }  backup {  retain_min = 50  retain_days = 0 }
```

Whereas on a RHHI-V node, I see this:

```
 devices { preferred_names = ["^/dev/mapper/"] ignore_suspended_devices=1 write_cache_state=0 disable_after_error_count=3 filter = [ 'r|.*|' ] }  global {  locking_type=1  prioritise_write_locks=1  wait_for_locks=1  use_lvmetad=0 }  backup {  retain_min = 50  retain_days = 0 }
```


So it seems gluster is messing with the vdsm filter.

**Comment by jtpittman195** [comment]
To add to Jake's comment, from the CLI, the same LVM commands use the lvm.conf in /etc/lvm and the LVM stack is printed out as normal.

**Comment by jmagrini** [comment]
It looks like vdsm is the culprit, which gluster storage installs vdsm and vdsm-gluster.  The lib/vdsm/storage/lvm.env.in sets up the /var/run/vdsm/lvm subdir: 
#
# source this into your shell to gain vdsm's view of lvm.
#
export LVM_SYSTEM_DIR=@VDSMRUNDIR@/lvm

**Comment by jmagrini** [comment]
Created stap script to watch /var/run/vdsm/lvm/lvm.conf and we can see sosreport applies the filter from this directory: 
# stat -c '%D %i' /var/run/vdsm/lvm/lvm.conf
14 20931195

# stap -v /tmp/file.stp 0x0 0x14 20931195
sosreport(6189) vfs_read 0x14/20931195
sosreport(6189) vfs_read 0x14/20931195
sosreport(6189) vfs_read 0x14/20931195

Still trying to narrow down which plugin.

**Comment by jmagrini** [comment]
It is vdsm, running sosreport with -o vdsm,lvm2 I am able to replicate it.  
sosreport -o vdsm
[..]
 Running plugins. Please wait ...

  Running 1/2: lvm2...        
  Running 2/2: vdsm...     

The stap script shows sos plugin accessing this file: 
sosreport(21287) vfs_read 0x14/20931195
sosreport(21287) vfs_read 0x14/20931195
sosreport(21287) vfs_read 0x14/20931195

./sos_commands/lvm commands are empty.

**Comment by jmagrini** [comment]
vdsm.py

    def setup(self):
        os.environ["LVM_SYSTEM_DIR"] = "/var/run/vdsm/lvm"

**Comment by TurboTurtle** [comment]
@jmagrini that doesn't address however why this only affects RHHI-V, and not straight RHV deployments. The only difference is gluster - the same vdsm plugin runs regardless and the vdsm plugin does nothing different in the presence of gluster integration.


That being said, the current vdsm plugin (recent added to native sos - before it was being provided by vdsm) does not set the env var. @jtpittman195 can you test using the current master branch and see if you get standard LVM data or not?

**Comment by jmagrini** [comment]
@TurboTurtle RHHI is what creates the lvm.conf inside of /var/run/vdsm/lvm from what I can tell.  Then the vdsm plugin picks it up.

**Comment by jtpittman195** [comment]
Jake, Jon, I tested the latest pulled from https://github.com/sosreport/sos/archive/master.zip a short time ago, and I am not able to reproduce.  Bryn, would you like me to open a rhel7 RH bug for this issue?  We see it on sos-3.6-17.el7_6.

**Comment by jtpittman195** [comment]
Thanks for the help Bryn, Jon, Jake.  Opened RH [BZ1706060](https://bugzilla.redhat.com/show_bug.cgi?id=1706060) to get the update into RHEL.  Closing.

**Comment by bmr-cymru** [comment]
> The stap script shows sos plugin accessing this file:
> sosreport(21287) vfs_read 0x14/20931195
> sosreport(21287) vfs_read 0x14/20931195
> sosreport(21287) vfs_read 0x14/20931195

Well, sure it does. We collect that entire directory:
        self.add_copy_spec([
            '/var/run/vdsm/*',
            '/usr/libexec/vdsm/hooks',
            '/var/lib/vdsm'
        ])

**Comment by bmr-cymru** [comment]
> The stap script shows sos plugin accessing this file:
> sosreport(21287) vfs_read 0x14/20931195
> sosreport(21287) vfs_read 0x14/20931195
> sosreport(21287) vfs_read 0x14/20931195

Well, sure it does. We collect that entire directory:
```python
        self.add_copy_spec([
            '/var/run/vdsm/*',
            '/usr/libexec/vdsm/hooks',
            '/var/lib/vdsm'
        ])
```

The problem reported with the older version is specific to the non-upstream VDSM plugin: we've never shipped that in an sos release, or in an sos package for RHEL. We can "fix" this by getting rid of the `vdsm` plugin shipped in the RHV packages, and replacing it with the upstream one, but that needs bugs against multiple components.
