### ISSUE TITLE
change sosreport manpage section from 1 to 8

### ISSUE THREAD

**Issue by slashdd** [sosreport/sos#1674]
Currently sosreport is inside section 1 in man.

``` 
 1   Executable programs or shell commands
```
I think it might be more suitable for section 8.
```
8   System administration commands (usually only for root)
```
Just like APT(8), ... and other system administration command which requires super privileges.

**Comment by pmoravec** [comment]
I see this as a border line - `sosreport` does not *administer* a system, "just" collects some system facts. But it is (usually/only supported) run by `root` and it's purpose is to further administer the system to mitigate a problem spotted there.

Any thoughts, @TurboTurtle or @bmr-cymru ?

**Comment by bmr-cymru** [comment]
Nack. It's been in `1` for many years, and this would create potential confusion for users, as well as extra aggravation for distributions and packagers.

It's also not strictly true that `sos` is only for root - many of the things it does need no special privilege and the only reason that non-root support isn't better developed is that it hasn't been a priority. There's already infrastructure to allow this and that could be extended and turned into a supported feature quite easily - at which point we would have to move it back to `1` again!
