### ISSUE TITLE
[Autocomplete] at wrong place

### ISSUE THREAD

**Issue by tianyao1000** [sosreport/sos#1675]
I am reporting two bugs regarding autocomplete function in Jupyter when I was using SOS.

The first one, when the **hinterland** function is **disabled** in nbextension.
As shown in the following image
![autocomplet bug 1](https://user-images.githubusercontent.com/25381950/57443270-40336080-7280-11e9-9ee6-85b7535090dc.png)
basically, when I tried to use the autocomplete, the first time it works fine (as shown in step 1 and 2). However, for the second time, the autocomplete inserted the code at the wrong place (as highlighted by the red rectangle)

The second is still related to autocomplete function, but this time, I turned on **hinterland** in nbextension. As shown in the following image, the autocomplete function adds an addition letter to the end of the code (instead of **ggplot**, the code becomes **ggplotp**)
![bug report 2](https://user-images.githubusercontent.com/25381950/57444077-f3508980-7281-11e9-9547-a094027d966a.png)

**Comment by bmr-cymru** [comment]
Sorry, but I've been working on `sos` for over ten years, and I have literally no idea what you are talking about. The `sos` project develops a set of tools for support data acquisition and packaging - it has nothing to do with autocompletion at all. Perhaps you have mistaken this project for something else with a similar name?

Perhaps you were thinking of vatlab's [SoS](https://github.com/vatlab/SoS)?
