### ISSUE TITLE
sosreport does not collect all cloud-init logs

### ISSUE THREAD

**Issue by shoshin71** [sosreport/sos#1681]
sosreport currently does not collect cloud-init logs from /var/lib/cloud, and those have to be collected separately via "cloud-init collect-logs".

On systems where cloud-init is present, I would think that sosreport should collect those logs.

**Comment by TurboTurtle** [comment]
#1630 is adding a cloud-init plugin, which captures from `/var/lib/cloud` as well as a few other locations.

What does `cloud-init collect-logs` generate? Is there anything aside from what's included in the PR we should grab in sos?

**Comment by shoshin71** [comment]
It looks like cloud-init collect-logs collects all of /run/cloud-init, whereas #1630 only collects /run/cloud-init/cloud-init-generator.log. #1630 does collect all of /var/lib/cloud.

**Comment by TurboTurtle** [comment]
I'll admit I'm not super well versed in `cloud-init` - what else ends up under `/run/cloud-init` that we should grab? Is there the potential for sensitive data in there? If not, we can probably just capture the whole thing. If there is, we'd need to obfuscate it in postproc.

**Comment by shoshin71** [comment]
I am still investigating this. It looks like the #1630 may need to be revised, as it collects all of /var/lib/cloud. I have discovered that /var/lib/cloud/instances/.../user-data.txt contains sensitive information that should probably not be shared with an external support provider.

ssh_keys: {dsa_private: '-----BEGIN DSA PRIVATE KEY-----

', ecdsa_private: '-----BEGIN EC PRIVATE KEY-----

', ed25519_private: '-----BEGIN OPENSSH PRIVATE KEY-----

and so forth. I am trying to determine what it might be acceptable/safe to collect.

**Comment by TurboTurtle** [comment]
We can scrub keys and certs and the like, that's no issue. We just need to know the relevant paths. Would it just be `/var/lib/cloud/instances/*/user-data.txt` (or maybe a broader `/var/lib/cloud/*user-data*`?)

**Comment by BryanQuigley** [comment]
I think this has been fixed in #1630, obviously a new Issue should be created if we find we're collecting too much info.
