### ISSUE TITLE
[RFE] collect better stats for the scheduled emulator threads with taskset

### ISSUE THREAD

**Issue by bogdando** [sosreport/sos#1709]
See https://access.redhat.com/solutions/3384881 for details.

It may be useful for debugging to get additional info in the collected commands, e.g.:

```
[root@overcloud-compute-0 ~]# taskset -a -c -p `pgrep -f instance-00000009`
pid 364936's current affinity list: 1-3
pid 364946's current affinity list: 1-3
pid 364952's current affinity list: 1
pid 364953's current affinity list: 2
pid 364954's current affinity list: 3
pid 364956's current affinity list: 1-3
[root@overcloud-compute-0 ~]# ps -Tp `pgrep -f instance-00000009`
    PID    SPID TTY          TIME CMD
 364936  364936 ?        00:00:02 qemu-kvm
 364936  364946 ?        00:00:00 qemu-kvm
 364936  364952 ?        00:00:51 CPU 0/KVM
 364936  364953 ?        00:00:26 CPU 1/KVM
 364936  364954 ?        00:00:30 CPU 2/KVM
 364936  364956 ?        00:00:00 vnc_worker
[root@overcloud-compute-0 ~]# pgrep -f vhost- | xargs -I {} taskset -a -c -p {}
pid 364948's current affinity list: 1-3
pid 364949's current affinity list: 1-3
pid 364950's current affinity list: 1-3
[root@overcloud-compute-0 ~]# 
```

**Comment by jcastill** [comment]
@bogdando , is the pattern always "instance-NNNN" with NNNN being a number?

**Comment by bogdando** [comment]
@jcastill I believe it is, unsure about possible variations of length of {N,} though

**Comment by TurboTurtle** [comment]
Coming back around on this, would it be desirable to get this information for every VM reported by `virsh list --all` instead of just for OpenStack deployments? @bogdando 

We could make it more consumable by nesting this collection, and the existing `virsh -r *` collections, under new subdirs for each VM on the host?

**Comment by jcastill** [comment]
@bogdando if this is still relevant (and I imagine it is, the KCS is still up and updated recently) could you reply to @TurboTurtle 's question?

**Comment by bogdando** [comment]
sorry, I don't have plans to resume working on that
