### ISSUE TITLE
[sosreport] format of reports (plain/html/json?)

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#1713]
Currently, sosreport generates plaintext and HTML reports about data collected. That is a sort of duplicate work that "only" makes the report more human-readable (i.e. by opening in web browser).

Doesn't it make sense to merge these reports into one in JSON format? That is both:
- human readable (in textual form and also in web browsers)
- parse-able for automatic processing

Moreover, `json` class inPython can take care of formatting/printing/encoding part of the report.

Your thoughts?

**Comment by TurboTurtle** [comment]
+1 to json reports and ditching HTML reports.

**Comment by pmoravec** [comment]
My idea was also to drop text reports together with HTML ones, and have just JSON reports.

**Comment by pmoravec** [comment]
Note to myself (or who-ever will implement the change): the (JSON) report generation must be fast. Current HTML report takes hours to generate in case a plugin collects hundreds of thousands of files.

**Comment by pmoravec** [comment]
Just JSON format isn't sufficient replacement of HTML, since it does not contain hyperlink references to the files and commands outputs collected - that is the main feature to browse sosreport via html report in browser, accessing individual files just by clicking there.

Anyway, the HTML format can be easily obtained by extending PlainTextReport class. Here I made few decisions mainly based on different content of text and HTML reports - anything from them, as well as particular formatting or wording, anything could be changed. Here are the differences from current text+html reports:

- plugin list added to text report (as it is in html report as a good summary)
- html report does not further list all alerts at the begining (text report does not generate them either and I dont see much rationale for it - but no prob. to add it there back)
- both formats list (for each plugin):
  - commands collected as first
  - then copied files
  - then created files (tailed files)
  - then alerts
  - then additional notes
  (originally, html format collected files, then commands, and didnt list created files, that is the change)
- html format does not further prints info that the collected file is a symlink. It just prints "I collected F", that _is_ proper symlink. But explicit printing info "F is symlink" is imho not important.

Additionally, I decided to add generating JSON report as well, since 1) it is very fast (fractions of seconds every time), 2) can be automatically parsed.

**Comment by pmoravec** [comment]
Self-commenting my proposal:

- ordering of the sections can be arbitrary, different per type report. But imho it makes sense to unify ordering of sections ("commands executed", "files collected" etc.) between text and HTML formats - to have unified user epxerience when traversing both formats
- maybe best ordering (from the most important to the least ones) of plugin subsections should be:
  - alerts (a headsup warning that explains why the plugin didnt collect something)
  - files collected (the very first purpose of sos is to collect files, imho)
  - files created (should be just after files collected, relevant to it)
  - commands executed (could be also before files collected but imho fits here better)
  - additional notes

**Comment by pmoravec** [comment]
Originally, I explored possibility to generate the HTML report purely in web browser via a javascript included in `sos.html`, like:

    class JSONReport(object):
        """Will generate a JSON report from a top_level Report object"""
    
        def unicode(self):
            output = json.dumps(self.report_node.data, indent=4, ensure_ascii=False)
    
            if six.PY3:
                return output
            else:
                return output.encode('utf8')
    
    class HTMLReport(JSONReport):
        """Will generate a JSON report from a top_level Report object"""
    
        def unicode(self):
    	header = \
    '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">\n\
    <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">\n\
    <head>\n\
      <link rel="stylesheet" type="text/css" media="screen" href="donot.css" />\n\
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />\n\
      <title>Sos System Report</title>\n\
    </head>\n\
    \n\
    <body>\n\
    <div id="plugList"></div>\n\
    <div id="alerts"></div>\n\
    <div id="plugins"></div>\n\
    <script>\n\
    var data = '
    	jsondata = super(HTMLReport, self).unicode()
    	jscript = \
    '\n\n\
    var pluginSectionNames = {\n\
            "commands": "Commands Executed:",\n\
            "copied_files": "Files copied:",\n\
    	"created_files": "Files created:",\n\
            "alerts": "Alerts:",\n\
            "custom_text": "Additional Information:"\n\
    }\n\
    var sectionsWithLinks = ["commands", "copied_files", "created_files"]\n\
    \n\
    var plugins = []\n\
    for (plugin in data) {\n\
            plugins.push(plugin)\n\
    }\n\
    plugins = plugins.sort()\n\
    \n\
    var outPlugList = "<h3>Loaded Plugins:</h3><table><tr>\\n"\n\
    var outPlugin = ""\n\
    var outAlerts = ""\n\
    \n\
    for (i in plugins) {\n\
            plugin = plugins[i]\n\
            outPlugList += "<td><a href=#" + plugin + ">" + plugin + "</a></td>\\n"\n\
            outPlugin += "<hr/><a name=\\"" + plugin + "\\"></a><h2>Plugin <em>" + plugin + "</em></h2>\\n"\n\
            var plugData = data[plugin]\n\
            for (section in plugData) {\n\
                    outPlugin += "<p>" + pluginSectionNames[section] + "<br><ul>\\n"\n\
                    for (i in plugData[section]) {\n\
                            item = plugData[section][i]\n\
                            if (sectionsWithLinks.includes(section)) {\n\
                                    outPlugin += "<li><a href=\\"" + item.href + "\\">" + item.name + "</a></li>\\n"\n\
                            }\n\
                            else {\n\
                                    outPlugin += "<li>" + item + "</li>\\n"\n\
                            }\n\
                    }\n\
                    outPlugin += "</ul></p>\\n\\n"\n\
                    if (section === "alerts") {\n\
                            outAlerts += "<li><a href=#" + plugin + ">" + plugin + "</a>:" + plugData["alerts"] + "</li>"\n\
                    }\n\
            }\n\
    }\n\
    \n\
    outPlugList += "</tr></table>\\n"\n\
    document.getElementById("plugList").innerHTML = outPlugList\n\
    document.getElementById("plugins").innerHTML = outPlugin\n\
    if (outAlerts != "") {\n\
            document.getElementById("alerts").innerHTML = "<hr/><h3>Alerts:</h3><ul>" + outAlerts + "</ul>"\n\
    }\n\
    </script>\n\
    </body>\n\
    </html>\n'
            return header + jsondata + jscript

The script renders a sos report with 100k items within a second, so performance is good. But the solution from PR seems to me better - very quick to generate and to render, easy to follow even the html source, dont rely on any other scripting language but pure html.

**Comment by pmoravec** [comment]
Some times from a scaled test where a plugin was collecting 300k files (and few other plugins collected some snippets):

- current upstream: 770m34.779s (almost 13 hours)
- proposed implementation (with txt, html and json reports): 28m54.545s
- `--no-report`: 28m15.566s

So in the scaled test, the old HTML generation took over 12 hours, while the new one took around 20 seconds.

**Comment by pmoravec** [comment]
Updated the PR a bit to fix txt+html reports having nonASCII content.
