### ISSUE TITLE
sos fails on non existing files/directories in abrt directory if collection is done while abrt report is being generated

### ISSUE THREAD

**Issue by sandrobonazzola** [sosreport/sos#1717]
Initially reported on https://bugzilla.redhat.com/show_bug.cgi?id=1644646
if sos report is being generated while an abrt report is being generated sos fails due to missing files/directories which are most probably temporary ones.

**Comment by pmoravec** [comment]
I failed to reproduce this and I dont see much way how sosreport could fail that way. Are you sure it wasn't abrtd or ovirt-log-collector who accidentally deleted the files/dirs from sos working dir?

**Comment by pmoravec** [comment]
It was identified as a flaw of ovirt-log-collector and not a sosreport bug. Therefore closing.
