### ISSUE TITLE
[sosreport] option to ignore unknown plugins

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#1723]
Automation tools running sosreport nowadays need to distinguish among sos minor versions (or do other tricks) to identify what plugins the sosreport knows. Otherwise, "-o new_plugin" will cause

    a non-existing plugin (new_plugin) was specified in the command line

halt of older sosreport execution.

We should have an option to suppress this behaviour and to simply ignore plugins the (older) sosreport is not aware of. (well that option wont help to older sos versions, but can help to future).

**Comment by BryanQuigley** [comment]
Why not just grep the list of plugins first, this seems to gets a list of plugins (with a couple bits to ignore)
sudo python3 sosreport -l | cut -d' ' -f2

If needed, a more machine-readable version of this list would be my preference (could be reused for travis QA checks as well).
