### ISSUE TITLE
[last] soscleaner would benefit to have a better user filtering when obfuscating them

### ISSUE THREAD

**Issue by slashdd** [sosreport/sos#1743]
soscleaner is a project to perform sanitation against an existing sosreport.
The user obfuscation inside soscleaner is currently relying on `sos_commands/last/lastlog` from the sosreport it is run against but this generate too much false positives as soscleaner try to obfuscate everything found in there.

https://github.com/soscleaner/soscleaner/blob/master/soscleaner/soscleaner.py#L97

Current workaround is to maintain a ignored_user list
https://github.com/soscleaner/soscleaner/blob/master/soscleaner/soscleaner.py#L512-L563

which works well but is not ideal.

Would it be reasonable to incorporate in last plugin 

```
         self.add_cmd_output([
+          "lastlog -u 1000-60000"
```

so that soscleaner can rely on this file instead of lastlog. The goal is not to obfuscate all users such as well publicly know ('bin', 'sys', 'ubuntu', 'reboot', ....) but try to limit them to users created by users, this will benefit soscleaner user obfuscation a lot and limit the amount of false positives and avoid us to maintain a list of Linux base user such as https://salsa.debian.org/debian/base-passwd/blob/master/passwd.master and more.

For instance user 'bin' can be a user, part of a package name, a path, a file, ...

sosreport already provide a complete lastlog output, what I would like to see is in addition to that having a smaller list to make the obfuscation easier for soscleaner benefit.

**Comment by slashdd** [comment]
Looking in `/etc/login.defs` on Ubuntu Bionic
```
UID_MIN			 1000
UID_MAX	         60000
```

**Comment by slashdd** [comment]
@TurboTurtle @pmoravec 
Would you be okay with that proposal change in order to help user obfuscation inside SOSCleaner ?

**Comment by pmoravec** [comment]
Do I get it right that current behaviour makes problems to `soscleaner` that wants to obfuscate usernames (for (all?) users with UID>1000) but `lastlog` contains a mix of system and regular users?

How the #1770 can help then, if full `lastlog` (mixing users to scrub and to show) will still be collected? Shall not we modify `sos` here to collect `lastlog -u 0-999` and `lastlog -u 1000-60000`?

**Comment by slashdd** [comment]
@pmoravec  The idea was not to touch lastlog (as it is already there) in case one needs the full list by creating another lastlog (`lastlog -u 1000-60000`) file. That file would specifically be created to serve SOScleaner purpose so that it can rely on `./sos_commands/last/lastlog_-u_1000-60000` instead of `./sos_commands/last/lastlog`. I'll be fine with your approach to split it up `lastlog -u 0-999` and `lastlog -u 1000-60000` but that won't catch the users for UID higher than 60000, as I think the highest UID number that Linux can get is `65536` (tbd).

So this will imply at least:
```
"lastlog -u 0-999",
"lastlog -u 1000-60000",
"lastlog -u 60001-65536",
```
If you are okay to have sosreport producing lastlog split into multiple files and no longer have a single file that contains everything, I'll be glad to adapt my PR accordingly.

**Comment by slashdd** [comment]
@pmoravec 
After reconsideration, the more I think about it, the more I think that splitting this up might end up missing some users for potential corner case situation. I would personally be tempted to keep a full `lastlog` copy (which will contains all the user regardless of their UID) and have an additional one to serve SOSCleaner purpose `lastlog -u 1000-60000`.

**Comment by slashdd** [comment]
https://en.wikipedia.org/wiki/User_identifier
`The majority of modern Unix-like systems (e.g., Solaris-2.0 in 1990, Linux 2.4 in 2001) have switched to 32-bit UIDs, allowing 4,294,967,296 (232) unique IDs.`

What about this so we have both the entire file and the split ones:
```
"lastlog", # Keep the entire list
"lastlog -u 0-999", # Reserves the range 100-999 for dynamically allocated system users and groups
"lastlog -u 1000-60000", # Min/max values for automatic uid selection in useradd (Soscleaner benefit)
"lastlog -u 60001-65536", #Centrally and statically allocates users and groups
"lastlog -u 65537-4294967296"
```
or just split everything as follow:
```
"lastlog -u 0-999", # Reserves the range 100-999 for dynamically allocated system users and groups
"lastlog -u 1000-60000", # Min/max values for automatic uid selection in useradd (Soscleaner benefit)
"lastlog -u 60001-65536",  #Centrally and statically allocates users and groups
"lastlog -u 65537-4294967296"
```

Test on my Ubuntu machine to validate the maximum UID value possible:
```
# useradd --uid 4294967294 test1
# useradd --uid 4294967295 test2
useradd: invalid user ID '4294967295'
# useradd --uid 4294967296 test3
useradd: invalid user ID '4294967296'
```

**Comment by slashdd** [comment]
Splitting files per UID range may also benefit SOSCleaner long term, even if current goal is to rely on 1000-60000 file. I could see SOSCleaner expanding the research into more than one file in some cases if needed, and that will make thing easier for use to select what range we need to obfuscate or not.

**Comment by bmr-cymru** [comment]
I think the approach of keeping `lastlog` and adding split ranges is best for now. It doesn't seem to be excessively costly for typical systems.

**Comment by slashdd** [comment]
@bmr-cymru thanks that's exactly what my most recent PR does, including both approaches via commit: 42d5da6

**Comment by slashdd** [comment]
@bmr-cymru far from me the intention to rush thing. I'm just curious if there is a chance to get that change approved anytime soon ? so that I can continue with the SOSCleaner required changes ?

Thanks in advance !
