### ISSUE TITLE
[Plugin] document add_cmd_output() arguments

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#1754]
We currently don't have docstrings for the `add_cmd_output()` arguments:

```Python
    def add_cmd_output(self, cmds, suggest_filename=None,
                       root_symlink=None, timeout=300, stderr=True,
                       chroot=True, runat=None, env=None, binary=False,
                       sizelimit=None, pred=None, subdir=None,
                       allow_changes=False):
        """Run a program or a list of programs and collect the output"""
```

Most are quite obvious by name, but e.g. the new `changes` argument (which means that the running the command may alter system configuration, and to warn the user of this if the conditions for running the command are not met) would benefit from more explanation for plugin authors.

**Comment by TurboTurtle** [comment]
Closing per #1807. The descriptions are in `_collect_cmd_output()` rather than `add_cmd_output()`, but they are present now.
