### ISSUE TITLE
[SoSPredicate] allow service predicates to override kmods?

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#1755]
Currently if any of an `SoSPredicate` objects requirements are met, the predicate evaluates true. This means that for e.g. if a predicate specifies a list of kmods, and a service, it will execute if any one of the kernel modules are present.

For some cases, e.g. where a service is missing causing a long command timeout this behaviour may be undesirable. Right now there are no uses of predicates that would suffer this problem (they all check for either kernel modules ORservices), but this could be an issue with future predicate use.

There are a couple of options:

* Change predicate evaluation so that *all* requirements must be met. This avoids the above problem but is inflexible: in some cases "any" evaluation may be useful for predicate users.

* Add additional predicate control flags, e.g.:
  - all_kmods -> all kernel modules must be present
  - all_services -> all services must be present
  - all -> both kmods and services must be present

**Comment by TurboTurtle** [comment]
What if we did something like this:

```python
# require all given objects to evaluate True
my_pred = SoSPredicate(kmods=['mod1', 'mod2'], services=['svc1', 'svc2'], required='all')

# Only one needs to evaluate True (default)
my_pred = SoSPredicate(kmods=['mod1', 'mod2'], services=['svc1', 'svc2'], required='any')

# Any number of kmods, all services
my_pred = SosPredicate(kmods=['mod1', 'mod2'], services=['svc1', 'svc2'],
                       required_kmods='any', required_services='all')
```

By having the various `required` args default to `any`, we maintain the default/current behavior and provide a good deal of flexibility. Another option could be something like:

```python
my_pred = SoSPredicate(kmods=['mod1', 'mod2'], services=['svc1', 'svc2'],
                       required={'kmods': 'any', 'services': 'all'})
```

which at first glance would be a bit easier to extend in the future if we need to add more things for predicates to evaluate.

**Comment by bmr-cymru** [comment]
Yeah that looks like a good approach.
