### ISSUE TITLE
Request to be maintainer

### ISSUE THREAD

**Issue by BryanQuigley** [sosreport/sos#1784]
I'd like to request access to be a new maintainer of sosreport.   

I'd only be focusing on 
 - plugins - happy to restrict this to just Ubuntu Plugins only if you'd prefer, but would hope to help do more plugin reviews outside as well
 - general cleanup - like closing out some of the old no longer relevant pull requests
 - writing new documentation like previously mentioned in #1646 .

I would not:
 - be focusing on sosreport core code
 - approve my own commits

I'm happy to follow any rules (in addition to what we already have), like waiting a predefined time before committing so others get to review.

The Canonical support organization very much depends on sosreport and we have some technologies that are only used on Ubuntu.  I'm the Tech Lead on the support team in the Americas with a focus on our tools and processes.  Two example PR I'd be focusing on are:
 - https://github.com/sosreport/sos/pull/1659 (Ubuntu only fix to LXD plugin)
 - https://github.com/sosreport/sos/pull/1670 (We are currently blocked from updating to sosreport 3.8 due to current juju plugin restarting services).

Thanks for approving my 46 commits over the years - I've learned a lot and expect to learn even more coming up :).

**Comment by slashdd** [comment]
FWIW, I strongly support @BryanQuigley application. Having a Canonicaler upstream maintainer with a very solid support background as he got including Bryan's Ubuntu best interests at heart would be very beneficial. Bryan is attentive to details. He will definitely be a great asset helping to share the burden of reviewing PR(s). Wearing my sosreport maintainer hat in debian & ubuntu, I see a lot of benefits of having someone "assigned" to Ubuntu specifics/subset inside sosreport to collaborate with.

Regards,
Eric

**Comment by ddstreet** [comment]
It would be great to see @BryanQuigley accepted as a maintainer!

**Comment by pmoravec** [comment]
+1.

**Comment by cjohnston1158** [comment]
+1, it would be great to have an additional maintainer to assist with Ubuntu related PRs.

**Comment by bboymimi** [comment]
+1. Ubuntu has many specific ideas and tools. It's great to have Bryan to maintain and contribute to the perspectives.

**Comment by sombrafam** [comment]
+1

**Comment by dnegreira** [comment]
+1, having @BryanQuigley as a maintainer would be great. Having someone with his knowledge about Ubuntu and its tooling will definitely be a good step on improving current and future plugins

**Comment by nivseg2** [comment]
+1 on Bryan becoming a maintainer. Bryan has a front seat to all of the use of sosreport and has seen it all. It would be a great help to have him get upstream maintainer status.

**Comment by battlemidget** [comment]
+1 to Bryan as well, glad to see so many contributions across all these organizations, @bmr-cymru about time for a SOSconf 🎉

**Comment by BryanQuigley** [comment]
Thanks all!  I've been added :).  Will start small.
