### ISSUE TITLE
sosreport run via sudo creates root-owned files in ~/.config

### ISSUE THREAD

**Issue by srs5694** [sosreport/sos#1787]
On a fresh Ubuntu 18.04 server installation, running sosreport creates root-owned files in ~/.config. Specifically, I'm using the following command:

sudo sosreport --batch --tmp-dir /tmp/

Prior to running this command, ~/.config did not exist. After running the command, ~/.config exists and is owned by root, with a lxd subdirectory:

$ sudo ls -lR .config
.config:
total 4
drwxr-x--- 2 root root 4096 Sep 19 12:16 lxc

.config/lxc:
total 8
-rw-r--r-- 1 root root 188 Sep 19 12:16 config.yml
-rw------- 1 root root   5 Sep 19 12:16 cookies

This root ownership of ~/.config and ~/.config/lxd causes problems for subsequent programs run without sudo.

**Comment by srs5694** [comment]
I forgot the sosreport version number:

$ apt-cache policy sosreport
sosreport:
  Installed: 3.6-1ubuntu0.18.04.3
  Candidate: 3.6-1ubuntu0.18.04.3
  Version table:
 *** 3.6-1ubuntu0.18.04.3 500
        500 http://us.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     3.5-1ubuntu3 500
        500 http://us.archive.ubuntu.com/ubuntu bionic/main amd64 Packages

**Comment by bmr-cymru** [comment]
Does this also happen when running the `lxc` commands the plugin runs using sudo?

I.e.:

```
$ sudo lxc list
$ sudo lxc profile list
$ sudo lxc image list
```

The `lxc` command has logic to detect when it's being run as root, and to create configuration files in the user's home directory when this is not the case (`src/lxc/initutils.c`).

**Comment by BryanQuigley** [comment]
It is indeed caused by the lxd plugin.   Adding sudo doesn't help.

Confusingly those lxc commands are actually from lxd, not from the source referenced.

**Comment by BryanQuigley** [comment]
I can reproduce this without sosreport, so I believe it's a lxd bug.

**Comment by bmr-cymru** [comment]
Ugh, yeah that's super confusing - the `lxc` source actually gets this **right** - in that it uses `geteuid()` to determine whether it's running as root, and only uses the home directory configuration paths if that is not the case.

The `lxc` command provided by `lxd` on the other hand just does this:

```go
        // Figure out the config directory and config path
        var configDir string
        if os.Getenv("LXD_CONF") != "" {
                configDir = os.Getenv("LXD_CONF")
        } else if os.Getenv("HOME") != "" {
                configDir = path.Join(os.Getenv("HOME"), ".config", "lxc")
        } else {
                user, err := user.Current()
                if err != nil {
                        return err
                }

                configDir = path.Join(user.HomeDir, ".config", "lxc")
        }
```

It's not clear from this whether this is a bug or a feature in the `lxd` sources - the intent isn't clear from the comments, but it looks inconsistent with the `lxc` project's use of this path, and it should be reported to the two projects for their consideration.

**Comment by BryanQuigley** [comment]
FYI (this is not an sosreport bug, here's hoping it stays closed)

Further testing indicates this is Ubuntu 18.04 LTS specific - the newer snap package of LXD doesn't do this.

Changed Ubuntu package-sosreport bug for this purpose - https://bugs.launchpad.net/ubuntu/+source/lxd/+bug/1844663.
