### ISSUE TITLE
Including 'login.defs' in default sosreport might help for security compliance checks

### ISSUE THREAD

**Issue by iranzo** [sosreport/sos#1808]
login.defs is not included by default in sosreport so most of them are missing it and it's useful to check security compliance configuration

**Comment by iranzo** [comment]
Commit https://github.com/sosreport/sos/commit/6d623ceb2bc973a603c2abb1c8c64f2980667a0d is unrelated to this Issue, it should be reopened @bmr-cymru

**Comment by bmr-cymru** [comment]
Typo in the commit message from @pmoravec - re-opened.

**Comment by pmoravec** [comment]
Ah sorry for the typo - overlooked PR number :man_facepalming:
