### ISSUE TITLE
[networking] Python2 specific failure

### ISSUE THREAD

**Issue by BryanQuigley** [sosreport/sos#1839]
Networking errors from travis (2.7).  They don't show up in Python3 series.

For the record, Ubuntu/Debian are python3 only for all supported versions of sosreport 

:
Setting up archive ...

 Setting up plugins ...

[plugin:networking] skipped command 'ip6tables -t nat -nvL': required kernel modules or services not present (kmods=[ip6table_nat] services=[]).

[plugin:networking] skipped command 'ip6tables -t mangle -nvL': required kernel modules or services not present (kmods=[ip6table_mangle] services=[]).

[plugin:networking] skipped command 'ip6tables -t filter -nvL': required kernel modules or services not present (kmods=[ip6table_filter] services=[]).

[plugin:networking] skipped command 'nft list ruleset': required kernel modules or services not present (kmods=[nf_tables] services=[]).

[plugin:networking] skipped command 'ip -s macsec show': required kernel modules or services not present (kmods=[macsec] services=[]). Use '--allow-system-changes' to enable collection.

[plugin:networking] skipped command 'ss -peaonmi': required kernel modules or services not present (kmods=[tcp_diag,udp_diag,inet_diag,unix_diag,netlink_diag,af_packet_diag] services=[]). Use '--allow-system-changes' to enable collection.

[plugin:networking] skipped command 'ip6tables -vnxL': required kernel modules or services not present (kmods=[ip6table_filter] services=[]).

 Running plugins. Please wait ...

**Comment by pmoravec** [comment]
Why *errors*? That sounds false alarm.

In case the system running `sosreport` does not have `ip6table_nat` kernel module loaded, `ip6tables -t nat -nvL` can't be executed as that would load the kernel module. The warning printed seems legit, to warn user something usually collected is skipped now.

So I would rather fix the travis test (or wait until we drop python2 support).

**Comment by bmr-cymru** [comment]
But if they only show up in the Python2 test runs that's suspicious - I think that's what @BryanQuigley is saying, right?

Presumably these tests all run on similarly configured systems so it would be a bit odd if all the Py3 test runs had those modules loaded, and all Py2 did not - it sounds like the predicate is evaluating wrongly on Py2 and failing the kmod test incorrectly.

**Comment by TurboTurtle** [comment]
Hmm, that does seem to be the case, failing on `macsec` detection, but it is infact loaded.

```shell
$ sudo python2 ./sosreport --batch -o networking
[sudo] password for jake: 

sosreport (version 3.8)

 Setting up archive ...
 Setting up plugins ...
[plugin:networking] skipped command 'ip -s macsec show': required kernel modules or services not present (kmods=[macsec] services=[]). Use '--allow-system-changes' to enable collection.
[plugin:networking] skipped command 'ss -peaonmi': required kernel modules or services not present (kmods=[tcp_diag,udp_diag,inet_diag,unix_diag,netlink_diag,af_packet_diag] services=[]). Use '--allow-system-changes' to enable collection.
 Running plugins. Please wait ...

  Starting 1/1   networking      [Running: networking]





$  sudo python3 ./sosreport --batch -o networking

sosreport (version 3.8)

 Setting up archive ...
 Setting up plugins ...
 Running plugins. Please wait ...

  Starting 1/1   networking      [Running: networking]


$ grep macsec /proc/modules 
macsec 49152 0 - Live 0x0000000000000000

```

**Comment by TurboTurtle** [comment]
Probing this a bit further, it looks like this is actually the opposite occurring.

Python2 is properly checking the predicate, but on python3 the predicate is never actually evaluated. This all happens in `test_predicate()`:

```python
    def test_predicate(self, cmd=False, pred=None):
        """Test the current predicate and return its value.

            :param cmd: ``True`` if the predicate is gating a command or
                        ``False`` otherwise.
            :param pred: An optional predicate to override the current
                         ``Plugin`` or command predicate.
        """
        pred = self.get_predicate(cmd=cmd, pred=pred)
        if pred is not None:
            return bool(pred)
        return False
```


The key here is the ` if pred is not None` check. On py2, this calls `SoSPredicate.__nonzero__()` which runs the evaluation for us. On py3 however, it seems `__nonzero__()` is actually an explicit check comparing the *class* of the object to `NoneType`. Since this is obviously not the case, pred is in fact not None, and we then return `bool(pred)` for which, on py3, there is no override and defaults to returning `True`.


We could solve this by overriding `__bool__()` and have it wrap `__nonzero__()`
```python
    def __bool__(self):
        return self.__nonzero__()
```


But I'm not yet sure if there are better approaches. Open to suggestions here.
