### ISSUE TITLE
[plugins] --since option different impact on logfiles and journal logs

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#1848]
In `sosreport` help:

      --since SINCE         Escapes archived files older than date. This will also
                            affect --all-logs. Format: YYYYMMDD[HHMMSS]

Apart of the heuristic problems per #1847, the behaviour is quite confusing with respect to collecting (log)files and journal logs (command output). As `--since` option causes that

- older logs are NOT collected (regardless of `--all-logs` option)
- `add_journal` for a unit is still collected completely (e.g. when a plugin wants its own journal)
- `add_journal` for `this` and `last` boot is still collected completely
  - BUT when adding `--all-logs` option, a *new* verbose journalctl of this boot *with since* is collected, BUT also verbose journalctl of prev boot *without* since is collected. So we apply `--since` only to newer logs.

I see there two counter-intuitive behaviour:
- logs apply to `--since` but journal logs dont
- with `--all-logs`, `--since` is applied to current boot but not the prev one

Doesn't it make sense to unify this? E.g.:

    diff --git a/sos/plugins/__init__.py b/sos/plugins/__init__.py
    index 1a1464c1..af45d47d 100644
    --- a/sos/plugins/__init__.py
    +++ b/sos/plugins/__init__.py
    @@ -1366,6 +1366,7 @@ class Plugin(object):
     
             journal_size = 100
             all_logs = self.get_option("all_logs")
    +        since = since or self.get_option("since")
             log_size = sizelimit or self.get_option("log_size")
             log_size = max(log_size, journal_size) if not all_logs else 0
     
    diff --git a/sos/plugins/logs.py b/sos/plugins/logs.py
    index 77e2da85..538ffb62 100644
    --- a/sos/plugins/logs.py
    +++ b/sos/plugins/logs.py
    @@ -51,8 +51,7 @@ class Logs(Plugin):
                     self.add_copy_spec(i)
     
             if self.get_option('all_logs'):
    -            self.add_journal(boot="this", since=self.get_option("since"),
    -                             allfields=True, output="verbose")
    +            self.add_journal(boot="this", allfields=True, output="verbose")
                 self.add_journal(boot="last", allfields=True, output="verbose")
     
         def postproc(self):

?

**Comment by pmoravec** [comment]
Closing in favour of #1822.

**Comment by TurboTurtle** [comment]
Re-closing this given comment history.
