### ISSUE TITLE
[pulp] Json syntax is broken while replacing sensitive data 

### ISSUE THREAD

**Issue by Rohan21Lobo** [sosreport/sos#1878]
Two Issues : 

* While collecting etc/pulp/server/plugins.conf.d/*json files., Sensitive data is replaced by ******* which is an invalid json value.
```
[root@sat65 sosreport-sat65-2019-12-05-rvpjhzq]# cat etc/pulp/server/plugins.conf.d/docker_importer.json 
{
    
    "proxy_host": null,
    
    
    "proxy_port": null,
    
    
    "proxy_username": null,
    
    
    "proxy_password": ********
    
}
[root@sat65 sosreport-sat65-2019-12-05-rvpjhzq]# json_reformat < etc/pulp/server/plugins.conf.d/docker_importer.json
lexical error: invalid char in json text.
                                        {          "proxy_host": null,
                     (right here) ------^
```

It should be replaced by some valid json value. Porbbaly some text with quotes like "*******" or "Filtered"

* regex also consumes the "," which also breaks the json syntax
```
cat etc/pulp/server/plugins.conf.d/yum_importer.json
{
    
    "proxy_host": null,
    
    
    "proxy_port": null,
    
    
    "proxy_username": null,
    
    
    "proxy_password": ********   <=== Regex consumed , from here
    
    
    "max_speed": null,
    
    "gpg_sign_metadata": false
}
```

**Comment by pmoravec** [comment]
Originally, `foreman-debug` collected that (and sos report collected f-d) with content like:

~~~
    "proxy_password": +FILTERED+
~~~

But that is not a valid JSON syntax either - it requires `null` or `false` or similar, or a quoted value (please correct me if also something else, I am not an expert to JSON syntax). So I suggest to replace there:

~~~
    "proxy_password": "SOS_FILTERED"
~~~

(or is `SOS_OBFUSCATED` more explicit? cf. with #1877 but just `FILTERED` might be mis-understood as a real password..?)
