### ISSUE TITLE
[tests] Automated testing against more than Ubuntu

### ISSUE THREAD

**Issue by BryanQuigley** [sosreport/sos#1885]
I broke RH with #1881,  Figure out how to get at least one RH/Fedora/CentOS test in automation somehow.

Ideally we run the same tests against both.

**Comment by slashdd** [comment]
Nevermind, I mistakenly added the wrong issue # in my PR.
Sorry about that.

**Comment by BryanQuigley** [comment]
Couldn't get it to work with LXD, will try with Docker next as others have gotten that to work:
https://github.com/brianmario/mysql2/blob/master/.travis_Dockerfile_centos

https://github.com/junaruga/rpm-py-installer/blob/master/.travis.yml (may also have an interesting way to organize travis CI file..
