### ISSUE TITLE
[networking] options to limit namespaces to traverse

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#1916]
There are few use cases where `networking` plugin timeouts due to the number of networking namespaces on the system and the number of commands to collect per each such namespace. That causes further commands are not collected, in favour of namespaces-related commands that one will most probably never use. Typically:

- many hundreds to thousands of namespaces on the system, where taking 12 commands per each takes too much time altogether; while most of the data collected wont be reviewed any time (who *usually* checks each and every of thousands of namespaces details?)
- `sosreport` collects `ethtool` per namespace (https://github.com/sosreport/sos/blob/master/sos/plugins/networking.py#L242-L247) that is not required on OpenStack (per my colleagues from technical support of OSP)

Several plugin options that can help here (both option names and default values are subject to discussion, of course):
- plugin option `inspect_namespaces` with default value 100 (where 0 means "unlimited"?), that limits number of namespaces **as returned by `ip netns` command** to iterate through
- plugin option `all_namespaces` to collect all namespaces details
- plugin option `namespaces=eth*,ens*,lo*` that contains reg.exps. of namespaces to take details for (only)
- plugin option `ethtool_namespaces` to skip `ethtool` commands per namespace

My proposal:
- `inspect_namespaces` with default 100, where 0 means unlimited
- `ethtool_namespaces` with default `True` and OpenStack preset amended with `networking.ethtool_namespaces=False`

An alternative proposal:
- `all_namespaces` with default `False`, and taking details of (hardcoded) 100 namespaces
- `namespaces` to list namespaces to traverse through (additionally to default behaviour, OR *only* these)

(to make the options complete, #1585 is an alternative approach that did not raise much attention)

Any other proposal?

Cc @TurboTurtle and @bmr-cymru for kick-off, and also @slashdd for Ubuntu+Openstack feedback.

**Comment by MrStupnikov** [comment]
@pmoravec I would like to ask you to not change default behavior and provide an option to users with huge amount of network namespaces to turn off any namespace-related operations if it is needed. You can put a warning message to stdout if it looks like user's environment doesn't fit default options.

If it will not work for you, then please consider increasing limit to 200.

Thanks, Alex.

**Comment by pmoravec** [comment]
Increasing the limit is no problem at all (seen some proposal of 500 also, though cant that already hit the plugin timeout? dunno).

Not changing default behaviour: That is the Sophie's choice: to restrict collection of all namespaces details on some systems we need all the data, or improve running times in *hours* on larger OpenStack deployments. Proposed `ethtool_namespaces` via OpenStack preset helps to some extent only. But maybe `inspect_namespaces` can have default 0 (unlimited), and just OpenStack preset changes it to e.g. 200?

**Comment by jjansky1** [comment]
I am inclining to 

- `inspect_namespaces` = 0 (unlimited) which will not change default behavior, for OpenStack will be by default = 200
- `all_namespaces` is not needed as inspect_namespaces will be 0 all or limited
- `ethtool_namespaces` = True which will again take everything as before, but for OpenStack will be by default set to False as they claimed those are not needed by them.
- `namespaces`=['eth*','ens*','lo*'] which will override inspect_namespaces and take only namespaces which correspond with defined regexps 

i have prepared my branch with commit [
ed50e24](https://github.com/jjansky1/sos/commit/ed50e24e790d8673a9a1d8638bfb13e0ddc3b936)

Tested just basic functions so far but seems it could be it.

@bmr-cymru @pmoravec @TurboTurtle @slashdd any ideas about this commit will be appreciated.

**Comment by pmoravec** [comment]
This alternative approach is OK to me. Wrt. the commit https://github.com/jjansky1/sos/commit/ed50e24e790d8673a9a1d8638bfb13e0ddc3b936 : I just think variables `namespaces` / `inspect_namespaces` and `ethtool_namespaces` are redundant (we can always refer to the `get_option` and we dont fetch the value too often to store it in more local variable).

+1 for PR from the commit (ideally with removed the 3 loc.variables)
