### ISSUE TITLE
ceph plugin split for each individuals services

### ISSUE THREAD

**Issue by slashdd** [sosreport/sos#1945]
Might be good to eventually split ceph services into their own individuals plugin (osd, mgr, mon, radosgw, ...)

**Comment by slashdd** [comment]
@hillpd

**Comment by hillpd** [comment]
This would be a clean way to capture daemon-specific output (e.g. perf dump and the new dump_osd_network).

**Comment by slashdd** [comment]
@hillpd let's talk this week about the ceph plugin split layout proposal:

ceph_osd.py
ceph_mgr.py
ceph_mds.py
ceph_mon.py
ceph_radosgw.py
and so on ....

The above copies the actual layout used for Openstack: `openstack_$OPENSTACK_COMPONENT.py`

Let's see how we can split the work together to make it happens for 4.0 (release due for this August IIRC)

**Comment by slashdd** [comment]
@BryanQuigley any objections, at maintainer pov, if @hillpd starts working at splitting things up in ceph like we currently do for Openstack ?

**Comment by hillpd** [comment]
@bmr-cymru I'm going to start work on splitting out the ceph plug-in per-service. The first iteration will provide in-place replacement of functionality. Then I want to add daemon-specific commands for better debug/troubleshooting. Let me know if you have any concerns with this approach.

**Comment by slashdd** [comment]
A colleague of mine and @hillpd  is currently working on a patch for this particular issue. 
Expectations are to have a patch ready in a couple of weeks.

**Comment by nkshirsagar** [comment]
I'm working on this issue with help from @hillpd @slashdd @pponnuvel . Shall sent out a patch for review once the changes are ready and tested.
