### ISSUE TITLE
test suite failling on Ubuntu where python3 is the default

### ISSUE THREAD

**Issue by slashdd** [sosreport/sos#1949]
While trying to build sosreport today in Ubuntu Focal/20.04LTS, we noticed the test suite failed a 2 tests as follows:

```
$ nosetests3 -v --with-cover --cover-package=sos --cover-html
....
======================================================================
FAIL: test_output (utilities_tests.ExecutableTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/sos/tests/utilities_tests.py", line 62, in test_output
    self.assertEquals(result['status'], 0)
AssertionError: 127 != 0

======================================================================
FAIL: test_shell_out (utilities_tests.ExecutableTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/sos/tests/utilities_tests.py", line 80, in test_shell_out
    self.assertEquals("executed\n", shell_out(path))
AssertionError: 'executed\n' != ''
- executed
```

Both test have one thing in common, they both use `test_exe.py`:
```
tests/test_exe.py 
-bash: tests/test_exe.py: /usr/bin/python: bad interpreter: No such file or directory
```
On a default Ubuntu Focal installation, python binary is called python3:

```
$ lsb_release -cs
focal

$ which python
<none>

$ which python3
/usr/bin/python3
```

Converting the `test_exe.py` from python to python3 resolved the situation.

```
$ nosetests3 -v --with-cover --cover-package=sos --cover-html

test_output (utilities_tests.ExecutableTest) ... ok
test_shell_out (utilities_tests.ExecutableTest) ... ok
```

**Comment by slashdd** [comment]
The only 2 options in Ubuntu focal are:

```
$ ls -altr /usr/bin/python2
lrwxrwxrwx 1 root root 9 Feb  8 06:18 /usr/bin/python2 -> python2.X
```

or 

```
$ ls -altr /usr/bin/python3
lrwxrwxrwx 1 root root 9 Oct 18 11:23 /usr/bin/python3 -> python3.X
```

Calling python directly doesn't seems to be an option anymore:

```
$ ls -altr /usr/bin/python
ls: cannot access '/usr/bin/python': No such file or directory
```

**Comment by slashdd** [comment]
Just noticed in your travis logs that you guys run:
`nosetests -v --with-cover --cover-package=sos --cover-html`
instead of 'nosetests3' with success.

Note that both `nosetests` and `nosetests3` fails the same way for us on Ubuntu Focal.

**Comment by BryanQuigley** [comment]
This was fixed and then re-introduced for some reason: https://github.com/sosreport/sos/issues/690

**Comment by bmr-cymru** [comment]
I've pushed a branch (bmr-py2less-tests) which should help with this. It eliminates all calls to a Python script with a shebang line, removes `test_exe.py` and cleans up a couple of minor problems that these changes revealed. Let me know how this works for you and I'll get it merged.

**Comment by BryanQuigley** [comment]
The fix landed a bit ago, and we only support python3 now
