### ISSUE TITLE
[yum|dnf] review duplicates and consider merging

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#1954]
When the DNF plugin was merged in 2016 there was a plan to replace `yum` and deprecate the interface. In practice in the time since then the `yum` interface has been maintained (originally in Red Hat Enterprise Linux and now also in Fedora). This has led to a level of duplication between the two plugins both of which collect commands that are potentially costly.

Review the files and commands collected by the plugin and consider merging the two, or moving functionality between the plugins to reduce duplicated effort during collection.

**Comment by TurboTurtle** [comment]
Would it make any sense to extend `SoSPredicate` to allow _negative_ checks? I.E. "only run if X is not present".

**Comment by bmr-cymru** [comment]
That'd be easy enough to do but I think this is a bit more complicated because it's a case where one command may or may not partially emulate the features of another. It could be part of a solution for this but I think we'll still need to consider moving some functionality between plugins to straighten this out.

I'll try to have a look this week and make some suggestions and we can see what we can come up with.
