### ISSUE TITLE
Why 3.9 re-introduces python2 dependency?

### ISSUE THREAD

**Issue by jameslao** [sosreport/sos#1957]
I've just upgraded to sosreport 3.9 in Ubuntu focal and see that it automatically installs python 2.7. Is there any reason that we need python 2 at this point?...

**Comment by bmr-cymru** [comment]
How did you install it? The project has allowed use with Python2 or Python3 for years, but which runtime to use is a decision that has to be actively taken when packaging the code for a given distribution.

**Comment by slashdd** [comment]
Its my bad I'll fix it right away.

**Comment by bmr-cymru** [comment]
Np - we'll sort out the remaining bits with the test suite in time for the next release so this isn't a headache for packagers any more.

**Comment by slashdd** [comment]
-Depends: ${python3:Depends}, ${misc:Depends}, python3-six, python-concurrent.futures
+Depends: ${python3:Depends}, ${misc:Depends}, python3-six

**Comment by slashdd** [comment]
Currently buliding in Focal:
https://launchpad.net/ubuntu/+source/sosreport/3.9-1ubuntu1

**Comment by slashdd** [comment]
So as sosreport 3.9-2 version in Debian which got approved a few minutes ago.

@jameslao if anyting Ubuntu sosreport related, please file a bug here:
https://bugs.launchpad.net/ubuntu/+source/sosreport/+filebug

**Comment by slashdd** [comment]
@bmr-cymru  This issue can be closed. I can't seem to be able to close it by myself.
