### ISSUE TITLE
--upload user/password

### ISSUE THREAD

**Issue by slashdd** [sosreport/sos#1968]
Instead of enforcing credentials directly inside the distribution/vendors policy.

https://github.com/sosreport/sos/blob/master/sos/policies/ubuntu.py#L16-L17
https://github.com/sosreport/sos/blob/master/sos/policies/redhat.py#L48

Would it be better to offer the use of these as settings in a configurable fashion inside sos.conf instead ?

https://github.com/sosreport/sos/blob/master/sos.conf

I would  rather leave the decision to package maintainer to decide or not to use that functionnality. 

That also means that one would require a specific "authorized/approved" package from the vendor for one to be granted to upload to a vendor's ftp, which will limit the amount of ppl with upload capability to vendor's FTP. At least it will add an extra layer.

It will also limit the visibility of the credentials. It's too late for current credentials but I don't like to see clear password in the upstream code, and I requesting a user/password change upstream doesn't make sense to me.

At the moment, its open to anyone who use the `--upload` under RHEL or Ubuntu directly after a `git clone` command.

I really do think that should be a maintainer offering, and sosreport should only offer the functionnality, but not the credentials out of the box.

**Comment by slashdd** [comment]
I see a couple of things that could go wrong here. I'm not going to list then to give ppl ideas, but let's say I have concern with the current implementation of --upload in term of credentials "openess".

The current setup assume that everybody is "trustworthy' implicilty.

**Comment by TurboTurtle** [comment]
I'd say this is a per-policy decision to be made by downstreams.

For Red Hat, our FTP fallback is already publicly open with well known credentials that anyone can find - RH customer or not. For uploads to our Customer Portal, it's gated behind authentication that is user-specific and not included in the default settings.

The options should be configurable via sos.conf today, so if Ubuntu wants to go that route, it is no issue to drop the credentials in `UbuntuPolicy`, but from a RH angle we intentionally have it the way it is today for the RHEL policy.

**Comment by slashdd** [comment]
Thanks @TurboTurtle, will look at it then.

**Comment by slashdd** [comment]
@BryanQuigley FYI ^

**Comment by slashdd** [comment]
Closing the issue, had a talk internally with @BryanQuigley about it and I discovered new facts I wasn't aware of.

Thanks.

**Comment by bmr-cymru** [comment]
I think if we're going to use an approach like this it would be best to put it in a new file. Unfortunately we don't historically have an `/etc/sos` directory, or I'd suggest `/etc/sos/upload.conf`, but `/etc/sos-upload.conf` doesn't seem to bad if we did go in that direction. That way it's separate from the rest of the configuration and easier to skip/strip in our own collection etc.

I'd also like to see support for these arguments to be passed in the environment to avoid either having to expose them in `ps` output or use interactive mode (makes life much easier for scripts).

**Comment by pmoravec** [comment]
I tend to have `--store-pass` option removed. Apart of the "ps" leak, we currently can expose its value into an archive as well:

    # grep upload /etc/sos.conf
    upload-pass = mojeHeslo
    # ./sosreport -o host --batch --build -vvv
    ..
    [sos.sosreport:setup] loaded options from config file: --upload-pass mojeHeslo'
    ..
    sos.sosreport:setup] effective options now: --batch --build --onlyplugins host --threads 4 --upload-pass mojeHeslo -vvv
    #

The same is printed to `sos_logs/sos.log` and `host` plugin collects plain `/etc/sos.conf`.

We must ignore `store-pass` being an option when:
- printing options dump like `effective options now: ..`
- when collecting `/etc/sos.conf` - even if we move the option to a dedicated file lie `/etc/sos/upload.conf`, we should disallow having it in `/etc/sos.conf`

So I vote for removing `store-pass` from `self.opts`/`SoSOptions` and populating it only in policy.
