### ISSUE TITLE
Smart proxy list

### ISSUE THREAD

**Issue by waldirio** [sosreport/sos#1972]
Generate the complete list of smart_proxies servers
```
# echo "select id,name,created_at,updated_at,puppet_path,download_policy from smart_proxies" | su - postgres -c "psql foreman"
```

**Comment by TurboTurtle** [comment]
We can add a collection for this info, but it needs to not use bash. The `foreman` plugin has support for building these queries correctly via the `build_query_cmd()` method, so this should be as simple as

```python
query = self.build_query_cmd('select id,name,created_at,updated_at,puppet_path,download_policy from smart_proxies')
self.add_cmd_output(query)
```
