### ISSUE TITLE
[4.0] Add soscleaner functionality into sos natively

### ISSUE THREAD

**Issue by TurboTurtle** [sosreport/sos#1987]
This issue is to track inclusion of `soscleaner` directly in the project for `4.0`, as both a subcommand (`sos clean`) and as an option to `report` (as `--clean`).

Not only should this subcommand match the functionality of the existing `soscleaner` project in terms of obfuscation, it should also provide a mapping of obfuscated items to the end-users which is _not_ included in the final archive. This is so the end user can quickly and reliably translate obfuscated addresses back to their environment, without actually divulging the potentially sensitive information to outside sources such as support representatives.

This will depend on the work in #1986 being completed.

**Comment by slashdd** [comment]
@jduncan-rva
Do you have any update on the porting of soscleaner to py3 ? 
That will most likely be one of the criterias for the inclusion.

**Comment by BryanQuigley** [comment]
It doesn't seem likely that we will try to import the code collector style.  This would like have to be a rewrite - let's talk about the requirements more.  I don't believe matching the full functionality of soscleaner for the first implementation is critical

Soscleaner currently "cleans"
MAC (pattern based)
IPv4  (pattern based)
IPv6  (pattern based)
domain (mixed results, sometimes cleans *.example.com and sometimes not)
hostnames (just clean the machine itself)
usernames (1000 - 6000 UID range)
user provided keywords

It goes through all files looking for items that match those patterns to remove. It also removes archives (instead of re-parsing them) - possible optimization here?
 
We also need a good disclaimer that masking/cleaning isn't perfect.

How should we do consistent naming patterns between runs on the same machine (different machines?)?
1. Require customers make their own naming file
2. Generate one for them and store
3. Some sort of key based/salted? - less secure theoretically

We also discussed other terms besides clean and liked the term [mask](https://en.wikipedia.org/wiki/Data_masking), so it could be something like
sos mask networking (which does hostnames, IPs, etc)

**Comment by TurboTurtle** [comment]
I am imagining we can lift the bulk of the actual scrubbing methods, but we'll have to work it into the new framework for components from the ground up.

>  It also removes archives (instead of re-parsing them) - possible optimization here?

My initial thought is to make this a toggle, between the current functionality of removing them and recursively unpacking, sanitizing, and repacking. Recursive archive scrubbing could get messy pretty quick for anything beyond simple gzipped text files.

> We also need a good disclaimer that masking/cleaning isn't perfect.

Right, that part is easy enough. We have pretty solid disclaimers today, so we're used to determining the verbiage.

> How should we do consistent naming patterns between runs on the same machine (different machines?)?

I would think we don't. Each run should be independent of outside factors, including previous runs. If we have consistent obfuscation patterns that can, potentially, expose us to easy 'decoding'.

One item I'm digging my heels into specifically for this integration is the mapping file mentioned above - a key for the end user to know what's what in a particular archive without divulging that information within the archive itself or to unnecessary contacts (as determined solely by the end user). This mapping should serve as the authoritative point of 'decoding' and should be on a 1-to-1 mapping-to-archive basis in my opinion.

> We also discussed other terms besides clean and liked the term mask, so it could be something like
sos mask networking (which does hostnames, IPs, etc)

An alias for `mask` would be fine by me. I think we should absolutely keep `clean` in the vernacular here though given the historical precedent users already have from `soscleaner`.

I'm not sure what we'd gain by breaking out the obfuscation items though. The default run would already be `networking` (based on current behavior), and just optionally adding user specified terms. Non-networking information is (or should) already be handled by report plugins' `postproc()`.

**Comment by pmoravec** [comment]
> > How should we do consistent naming patterns between runs on the same machine (different machines?)?
> 
> I would think we don't. Each run should be independent of outside factors, including previous runs. If we have consistent obfuscation patterns that can, potentially, expose us to easy 'decoding'.

I would vote for at least option (even by default on) to have same mapping for subsequent runs of `sos clean`. This will simplify comparing the sosreports and identifying changes - both for `sos compare` and for a support associative comparing more sosreports and knowing some problematic IP address to focus on was masked to A1.B2.C3.D4 specifically.

E.g. we can store the mapping file in some dedicated default location. If the file will be already present, let use it (and optionally enhance by new items to mask). If not, use a new mapping and store there. With an option to drop the mapping file / its content.

**Comment by slashdd** [comment]
Additionnally, we also discussed that we should NOT recommend user to run `sos mask` on the same impacted (and/or same sosreport generated) system, but preferably on a jumphost.

That way we avoid taking ressources from for instance a production and possibly problematic/risky system.
1) Generate a sosreport
2) Transfert the archive to a jumphost
3) Obfuscate the archive from the jumphost

**Comment by slashdd** [comment]
@arif-ali you might be interested in this topic.

**Comment by arif-ali** [comment]
> @arif-ali you might be interested in this topic.

I've been following this topic in the background, thanks @slashdd 

I have a customer who needs to use some kind of cleaning method, so that all items like these need to be masked before they are handed over to support personnel.

I've had some thought on this, and what about we can use `sos report`, and mask the relevant bits in flight. This way, each of the plugins in sos.plugins will have their own way of masking, and the person developing said plugins will understand better on the masking. This will enhance overall user experience.

If this is not an option, then I would propose a plugin for each of the items as per `sos report`. We have an interface of what can be obfuscated, and the plugin will extend this to how things would be obfuscated with the said plugin

With the action of masking/cleaning afterwards, it's another action a customer has to do, and then also on another machine. I know this has caused annoyance on the customer part

Those are my initial thoughts

**Comment by TurboTurtle** [comment]
> I've had some thought on this, and what about we can use `sos report`, and mask the relevant bits in flight. This way, each of the plugins in sos.plugins will have their own way of masking, and the person developing said plugins will understand better on the masking. This will enhance overall user experience.
> 
Plugins already have a `postproc()` method that should be used to obfuscate any sensitive data related to the component/package/etc that that plugin collects for.

Where that falls short, is the fact that plugins are distinct, non-interoperable objects so we cannot maintain consistency on larger items, such as IP addresses, that will likely appear across many, perhaps dozens, of plugins. `pluginA` obfuscating 192.168.1.1 to 10.11.12.13 when `pluginB` obfuscates that same IP address to 34.23.12.1 causes more problems than it solves.

> If this is not an option, then I would propose a plugin for each of the items as per `sos report`. We have an interface of what can be obfuscated, and the plugin will extend this to how things would be obfuscated with the said plugin
> 
I'm not sure I follow what you mean here

> With the action of masking/cleaning afterwards, it's another action a customer has to do, and then also on another machine. I know this has caused annoyance on the customer part
> 

Right, it has always been a goal for this to be extended to report runs via a `--clean` option. This would run the collected data through whatever implementation we come up with prior to the archive being closed. I.E. we will provide both the ability to clean the data during a normal `sos report` run, and against previously generated archives.

**Comment by BryanQuigley** [comment]
The jumphost cleaning is our recommendation with the current soscleaner tool.  I think that can change for the new implementation.

I feel like this is an opportunity to be clearer in what we provide - and if needed customers can always do more with their keyword defined list.

I also absolutely like the idea that a customer could define that XYZ is always turned into ABC for giving to us.  That way they can have full knowledge for answering questions

I'm unsure if this makes sense to try to spec out via GH issues. I've created a strawman proposal in Google docs: https://docs.google.com/document/d/1UNPvj1DN4Sh4l95S_6pjihsnKuOf2rMOs5IH2nGuef8/edit

**Comment by TurboTurtle** [comment]
I have a working implementation done locally that has support for IPv4 address and IPv4/6 MAC addresses. IPv4 addresses maintain their relationships within subnets, I.E. hosts within the same subnet will be in the same obfuscated subnet and the broadcast address will be the broadcast address of the obfuscated subnet as well. The basic design flow is this:

* The component gets handed a target path, and determines if it is a directory, archive, or archive of archives. From that, it instantiates an object for each archive that represents standardized ways to manipulate the structure and get file listings

* Each file in each archive/directory is iterated through on a line-by-line basis, handing the lines to a number of parsers, each responsible for identifying a piece of data for obfuscation via regexes. For example, there is an IP parser, MAC parser, etc..

* Each parser holds a "map" object, which like the parser is representative of one type of data to obfuscate. The maps provide the sanitization functions, as well as storing the mapping of previously encountered items with their obfuscated counterparts.

* When a parser parses a line, all matches that it looks for are fed into the map to get an obfuscated result, which is then replaced in the line.

* Lines are written to a temp file and the number of substitutions is tracked. If this number is greater than 0, then the tempfile overwrites the file on disk in the archive/directory. If it is 0, the tempfile is simply removed.

* Once every file has been processed, we repack any archives. If we were working on a directory, then we do not do any packing (the idea here being that if we hook into this from `report`, the obfuscation is done before we compress the archive)

Mappings discovered during a run are saved to disk, and on future runs of the component those mappings are read into the parser maps so that consistency is maintained between runs. With this design, extending obfuscation functionality is just a matter of providing a parser (which is really just a dressed-up set of regexes) and a map to handle how to obfuscate that particular type of data.

I have some cleanup to do and need to flesh out the final bullet above, but I wanted to get an initial ack/nack to that design.

**Comment by pmoravec** [comment]
The design sounds good to me. Just some comments / questions:

> (the idea here being that if we hook into this from report, the obfuscation is done before we compress the archive)

Good point. This will need some hook inside `report` (to apply some external code (the cleaner) after `report` auxiliary directory is fully built).

> extending obfuscation functionality is just a matter of

Does the design count with missing map for just some of handlers? E.g. assume a use case where I run some sos clean, then updated sos that adds some handler. Now, a new sos clean run should handle existing maps of "old" handlers and empty map(s) of the new handler(s).

**Comment by TurboTurtle** [comment]
> Does the design count with missing map for just some of handlers? E.g. assume a use case where I run some sos clean, then updated sos that adds some handler. Now, a new sos clean run should handle existing maps of "old" handlers and empty map(s) of the new handler(s).

Yes, the old maps would be loaded into the "old" parsers, and then after the first run of an updated `sos clean` with a new parser that additional mapping information would be saved.
