### ISSUE TITLE
[4.0] Create and save metadata about report runs in archive

### ISSUE THREAD

**Issue by TurboTurtle** [sosreport/sos#1990]
Following #1959, sos should save metadata information and save it in the final archive. This metadata can be used by both the sos developers and downstream organizations to assist with ongoing maintenance and trend analysis.

**Comment by TurboTurtle** [comment]
I've mocked up an example of what I envision the layout of this to look like:

```
{'version': 4.0
 'cmdline': 'sos report --blah'
 'start_time': 'some_datestamp'
 'end_time': 'some_other_datestamp'
 'components':
	# each subcommand sos supports would have an element here if it ran
	'report':
		'plugins_run': [] # a list of plugin names for those that ran
		'plugins_disabled': [] # list of explicitly disabled plugins
		'plugins_enabled': [] # list of explicitly enabled plugins
		'plugins':
			# one entry per plugin
			'kernel':
				'options': [] # list of enabled plugin options
				'commands': [
					{'command': 'foo', 'parameters': ['bar', '--foobar'], 'exec': 'foo bar --foobar', 'filepath': 'sos_commands/kernel/foo_bar_--foobar', 'exit_status': 0, 'run_time': '12.345s', tags=['tag1','foo_bar']}
				]
				'files': [
		        		{'specification': '/etc/some/*.conf', 'files_copied': ['/etc/some/1.conf', '/etc/some/other.conf'], tags=['some_configs']}
				]
		'hostname': 'foo.bar.example.com',
		'policy: 'RedHat'
		
	'collect':
                'cluster': 'pacemaker',
		'hosts': [
			{'hostname': 'foo.bar.example.com', 'archive': 'relative/path/in/tarball/sosreport.tar.gz'}
		]
}
```

I think this is for the most part very straight forward. One part that might not be is the `tags` parameter  in the `commands` and `files` element for each plugin. This is an idea coming from working with the RH Insights team - by the use of tags such as this, it is far easier for third party analysis tools to locate relevant data. For example, in the `apache` plugin, we can tag the collection of both `/etc/httpd/conf/httpd.conf` and `/etc/httpd/conf.d/*.conf` as, for example `httpd_confs`. Then, these other tools can simply parse the metadata file and look for all things tagged with `httpd_confs` rather than having to grok through file name patterns.

As I said this came from talks with our Insights team, but I see applicability to this for `sos examine` as well later down the road. This metadata collection would also allow the various support teams that use sos to get better analytics about the archives themselves - E.G. "how long did this command take to run and is that concerning?", "are users frequently disabling specific plugins?", "should we adjust XYZ default behavior?", etc...

This would, of course, lead us to the not-so-trivial tasks of retroactively tagging collections in nearly 300 plugins today. Not that we have to do it all at once, but it is something that'd we'd want to be mindful of.

**Comment by pmoravec** [comment]
Talking too in advance: we already collect most of the (`report` only) data in `sos_reports/sos.json`.

**Comment by TurboTurtle** [comment]
Right, this would be an expansion of that. The question is, is this just an expansion of it or a complete replacement?
