### ISSUE TITLE
[4.0] Add Snap and Flatpak support

### ISSUE THREAD

**Issue by TurboTurtle** [sosreport/sos#1992]
Adding flatpak and snaps packaging as requested in #1959. As noted, this would lower the barrier to `sos` shipping in additional distributions.

**Comment by slashdd** [comment]
Would be really nice to get that support feature in next release. Plus having sosreport support more than 1 package manager for the same host. (e.g. In Ubuntu DEB and snap co-exist within the same system)

**Comment by BryanQuigley** [comment]
FYI, I gave up on adding Flatpak support because I couldn't find a current sos plugin where it would actually be useful to be used.

**Comment by slashdd** [comment]
This issue is not fixed. The intent of this bug was to make sure sos support SNAP FlatPak in PackageManager() just like it does for RPM and DEB.

The PR suggested by @arif-ali is the configuration to build sos as a SNAP, which is a different thing.

**Comment by slashdd** [comment]
Main discussion: https://github.com/sosreport/sos/issues/2237

**Comment by BryanQuigley** [comment]
The big issue that stopped me from pursuing flatpak was the apps are not designed to be called without a GUI of some kind. So once you get the list, what would you use it for it?

If there are multiple apps with the same name it does seem wise to flag that in some way - there can also be user installed flatpaks - but I'm not sure if there is a good way to pick up on them.

**Comment by arif-ali** [comment]
Now that we have both snap and flatpack package managers, I presume we can close this one now?
