### ISSUE TITLE
Determine if Ubuntu/Debian should default to /var/tmp or back to /tmp

### ISSUE THREAD

**Issue by BryanQuigley** [sosreport/sos#1997]
/var/tmp per systemd defaults gets cleaned every 30 days.  That makes it less impactful disk wise to default to /var/tmp.
On Ubuntu and Debian that was disabled per https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=773313

Also see: https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1870585

We may end up making the change anyway to be consistent, but at the very least we should test for full disk situations (if we don't already).  I'm also considering if we should have a sos specific cleanup...

**Comment by slashdd** [comment]
Just as an FYI to show the actual configuration based on Ubuntu 20.04/LTS to support the above comment.
```
lsb_release -cs
focal
```
```
cat /usr/lib/tmpfiles.d/tmp.conf

#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

# See tmpfiles.d(5) for details

# Clear tmp directories separately, to make them easier to override
D /tmp 1777 root root -
#q /var/tmp 1777 root root 30d
```

**Comment by BryanQuigley** [comment]
Ubuntu defaulted back to /tmp.. by specifying in /etc/sos/sos.conf so closing this.
