### ISSUE TITLE
Order of commands and files should be predicable

### ISSUE THREAD

**Issue by BryanQuigley** [sosreport/sos#1998]
Use  --build -o grub2 as the sample case

Sometimes:
-  files copied:
  * /etc/default/grub
  * /boot/grub/grub.cfg
  * /etc/grub.d/41_custom
  * /etc/grub.d/10_linux
  * /etc/grub.d/05_debian_theme
  * /etc/grub.d/20_memtest86+
  * /etc/grub.d/README
  * /etc/grub.d/10_linux_zfs
  * /etc/grub.d/30_os-prober
  * /etc/grub.d/00_header
  * /etc/grub.d/30_uefi-firmware
  * /etc/grub.d/40_custom
  * /etc/grub.d/20_linux_xen
  * /boot/efi/EFI/ubuntu/grub.cfg

Sometimes:
-  files copied:
  * /etc/grub.d/41_custom
  * /etc/grub.d/10_linux
  * /etc/grub.d/05_debian_theme
  * /etc/grub.d/20_memtest86+
  * /etc/grub.d/README
  * /etc/grub.d/10_linux_zfs
  * /etc/grub.d/30_os-prober
  * /etc/grub.d/00_header
  * /etc/grub.d/30_uefi-firmware
  * /etc/grub.d/40_custom
  * /etc/grub.d/20_linux_xen
  * /etc/default/grub
  * /boot/grub/grub.cfg
  * /boot/efi/EFI/ubuntu/grub.cfg

**Comment by BryanQuigley** [comment]
This is primarily helpful for validating that sos changes don't change to much.   I reviewed the full sos.txt diff (and I separately did a full directory diff) of what was collected for #1933 - and well this adds a lot of noise that is meh to filter out.  I don't want to run sort on sos.txt because it loses a lot of context.

This certainly could be solved by the proposed diff option for 4.0.

**Comment by pmoravec** [comment]
So your concern is not ordering of commands/files *captured*, but *reported* in `sos_reports/sos.*` ? That makes sense to sort it before generating the reports.

**Comment by bmr-cymru** [comment]
No, I think @BryanQuigley is talking about the order in which entries appear in the log, right?

In that case, if we wanted to change this, the solution is to sort the list returned by `os.listdir` - since the underlying `readdir`/`getdents` do not impose any ordering it's on us to do that. Similarly if we wanted to provie ordering on command lists (although that's complicated by immediate collection).

**Comment by BryanQuigley** [comment]
Sorry - yea I was talking about sos_reports/sos.* -  specifically I was comparing sos_report/sos.txt between two sosreports.  This is definitely wishlist :).

Aside: I've also been previously investigating replacing the use of listdir with walk which *might* get us this as an extra..  (also see - https://www.python.org/dev/peps/pep-0471/)
