### ISSUE TITLE
[Plugin] rabbitmq plugin refactoring

### ISSUE THREAD

**Issue by casual-lemon** [sosreport/sos#2001]
I'd like to add a few improvements to the rabbitmq plugin specifically geared towards updating the section with docker. For example if we run this command `docker ps -a --format='{{ .Names }}'` we can see the name of the docker container could be something like stupefied_goldwasser or practical_brown. This makes the assumption that the container image is named properly. On line 33: `if line.startswith("rabbitmq"):` We're doing a check and seeing if the name matches **rabbitmq** (it does not). So I'd like to change that to check the image name `docker ps --format='{{ .Image}}'` instead which prints something like this: `rabbitmq:3.8.3-management
rabbitmq:latest`. Then our code that does the compare does work and we can execute the docker commands. I'd also recommend adding these two commands `rabbitmqctl list_queues` and `rabbitmqctl list_unresponsive_queues` it could help debugging if you have a queue thats backed up and would like to know which one it is since `rabbitmqctl report` does not tell you this.

**Comment by casual-lemon** [comment]
@kajinamit I saw your PR this morning with regards to the rabbitmq plugin, I thought I'd give you a heads up on this refactoring

**Comment by casual-lemon** [comment]
I think you should not make the assumption that the name of the container is rabbitmq unless you control the naming of the container.  

I planned on targeting the 3.9.x branch for this work so I don't believe using `ContainerRuntime` would affect my work since it's going into the 4.0 release branch. 

But I would like the code to be generic enough so irregardless of container type(lxc,docker) or state(running, stopped, active) you wouldn't be missing any use cases.  

You could also implement an OR instead such as Names or Image.

I'd like to hear some other's opinions as well so I can make the decision to close this or continue on.

**Comment by kajinamit** [comment]
@casual-lemon Thank you for your heads up!

From TripleO perspective, it's correct to use container name instead of container image name to look up rabbitmq container, because in TripleO we expect pre-defined container names are assigned while container image names can be changed based on user's input in deployment templates.

So I think the point we should discuss here is whether we expect the use case where operators want to collect information from containerized rabbitmq, which is deployed not by TripleO but by some other tools.

**Comment by casual-lemon** [comment]
@kajinamit Thank you for your comment :) 

If you're environment is always TripleO then that makes sense, but if it's not and is deployed by another tool then the code should be flexible enough to account for that, just my thoughts.

You could still have the option of doing Names OR Images as well.

Would a change like this be effecting all plugins who use docker, not just rabbitmq?

I personally deploy RabbitMQ a lot from DockerHub https://hub.docker.com/_/rabbitmq

**Comment by kajinamit** [comment]
> If you're environment is always TripleO then that makes sense, but if it's not and is deployed by another tool then the code should be flexible enough to account for that, just my thoughts.

I agree about this point.

> Would a change like this be effecting all plugins who use docker, not just rabbitmq?

Theoretically, yes.
However as far as I see all the other plugins performing docker commands are related to openstack, like openstack_nova, openstack_heat etc, so we might define another policy about them (like saying we expect TripleO as the only deployment tool for OpenStack)

**Comment by casual-lemon** [comment]
Dropping this refactor as it's too much to work for an initial first commit as well as differences in implementation details.
