### ISSUE TITLE
Procedure for "just legacy" or "both upstream and legacy" PRs

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#2008]
Since we are in a new situation with two active branches, we should agree on procedure and rules how to propose a PR to the `legacy-3.9` branch. Some points to concern:

- we should clarify what changes are acceptable to `legacy-3.9`: I assume no new plugins, no new features until they are required for some other fix, no stylistic changes or similar

- filing a PR against `legacy-3.9` *only*: should it contain some dedicated string to clarify the diff is against this branch and not master? (just to prevent confusion of reviewers)

- filing a PR against both `legacy-3.9` and upstream: shall be 2 PRs failed? Or only when `legacy-3.9` "backport" is (substantially? anyhow?) different than the upstream patch? (imho PR against upstream followed by "please backport to `legacy-3.9`" request; if the backport isnt obvious, then a new PR is / will be requested by reviewers)
  - technically, no upstream PR is *directly* backportable due to the change in directory structure - but till `git format-patch | sed 's!/sos/report/!/sos/!g'` on master followed by `patch -p1` on `legacy` works (or is trivial to modify), imho no extra PR is needed

Your thoughts?

**Comment by TurboTurtle** [comment]
I would agree with most of this:

* no new plugins (that's up to downstreams), no new features, etc..
* PR must be opened against the `legacy-3.9` branch.

I was originally thinking that we should enforce a separate PR for each branch, however it would make it easier on contributors for the maintainers to do that on our end, if possible. We shouldn't generally have non-trivial changes to make on the legacy branch, so if we are unable to cleanly do a fixup on our end for merging we can make one-off requests for separate PRs.

**Comment by BryanQuigley** [comment]
I agree in principle - if it's trivial it's nicer to just do it to both branches... But that means the branch without a PR doesn't get the automated testing, right?

I'd prefer we require a PR against master first to be committed, and then once it's been accepted a new PR go against legacy-3.9.  We can choose to do that second PR on behalf of a contributor (and even say +1s count from the previous one).  

Aside from bugs that don't impact master for some reason, I don't think there is any other reason I want to see PRs directly to the legacy branch.

**Comment by pmoravec** [comment]
> I agree in principle - if it's trivial it's nicer to just do it to both branches... But that means the branch without a PR doesn't get the automated testing, right?
> 
> I'd prefer we require a PR against master first to be committed, and then once it's been accepted a new PR go against legacy-3.9. We can choose to do that second PR on behalf of a contributor (and even say +1s count from the previous one).
> 
> Aside from bugs that don't impact master for some reason, I don't think there is any other reason I want to see PRs directly to the legacy branch.

This sounds to me as the best approach.

**Comment by BryanQuigley** [comment]
It's always better with examples - I was recently asked about #2022 getting back to 3.9.   Given the policy written above I would say no it should wait for 4.0. 

It could also be viewed as a bug that ipmitool isn't the right one for Ubuntu - and if it had been a small addition to an existing ipmi plugin it would be acceptable to include.  

I'm personally happy either way but would ideally like this to match what either RH/C would actually bring back for the next 6 months (@slashdd thoughts?).   IMU 4.0 isn't that far away and we would plan to bring that to all supported Ubuntu releases.

**Comment by TurboTurtle** [comment]
@BryanQuigley sorry, don't know how I forgot about this one for so long.

My approach in merging to `legacy-3.9` thus far has been "does the plugin exist already?" and if yes "does at least one downstream consider this a _bug_ as opposed to an RFE?". For this I'm assuming bug to mean "this is causing an incorrect or broken collection, or causing issues on the system (such as loading kmods)". There's definitely flexibility in what an "incorrect" collection is - missing data pertinent to the version of the plugin's component shipping on that distro, partial collection, collection that shouldn't be happening, etc...

I'm happy to document this in the wiki if the above sounds reasonable to all parties, and then close this out.

**Comment by BryanQuigley** [comment]
What you wrote makes sense. 

I think it's likely a moot point for Ubuntu as the only release (16.04)  with 3.9 is going to be end of standard support this month.

**Comment by TurboTurtle** [comment]
Documented in https://github.com/sosreport/sos/wiki/Policy-on-changes-to-legacy-3.9
