### ISSUE TITLE
More python linting...

### ISSUE THREAD

**Issue by BryanQuigley** [sosreport/sos#2010]
Was looking at incorporating pylint.. or python coverage.

but there are so many - https://realpython.com/python-code-quality/#linters

Also two meta-tools are either flake8 (shows a bit of unused bits)  or pylama (more output, but not sure how useful).

Anyone have any preferences?

**Comment by TurboTurtle** [comment]
Taking a quick look at flake8, I like it  at first grok- though I haven't dug too deep into it.

pylama seems interesting in that it wraps more projects, but one of the default linters has some rather cryptic errors:

```
sos/report/plugins/__init__.py:885:1: C901 'Plugin._do_copy_path' is too complex (12) [mccabe]
sos/report/plugins/__init__.py:1021:1: C901 'Plugin.add_copy_spec' is too complex (28) [mccabe]
sos/report/plugins/__init__.py:1170:1: C901 'Plugin._add_device_cmd' is too complex (13) [mccabe]
sos/report/plugins/__init__.py:1321:1: C901 'Plugin._collect_cmd_output' is too complex (11) [mccabe]
sos/report/plugins/__init__.py:1596:1: C901 'Plugin.add_journal' is too complex (14) [mccabe]
sos/report/plugins/__init__.py:1738:1: C901 'Plugin.check_enabled' is too complex (11) [mccabe]
```

And looking at [the definition of c901](https://www.flake8rules.com/rules/C901.html), I'm not terribly convinced. Yes, smaller functions == good, but it seems rather arbitrary.

**Comment by TurboTurtle** [comment]
Closing this as we are now using flake8 as part of #2196
