### ISSUE TITLE
[systemd] systemd trigger

### ISSUE THREAD

**Issue by slashdd** [sosreport/sos#2013]
The `systemd.py` plugin should rely on the existence of `/run/systemd/system` directory which would be, IMHO, a more reliable trigger/verification to enable the plugin and that will also ensure a common standard regardless of the distribution flavor. (excluding the usual `Packages` verification already in place which lgtm)

My rationale behind `/run/systemd/system` usage:
https://www.freedesktop.org/software/systemd/man/sd_booted.html
https://github.com/systemd/systemd/blob/master/src/libsystemd/sd-daemon/sd-daemon.c#L598-L604

**Comment by ddstreet** [comment]
Agreed, the /lib/systemd/system vs. /usr/lib/systemd/system dirs vary between different distros; while the /run/systemd/system directory is created by systemd and should guarantee that systemd actually is managing the system.

**Comment by BryanQuigley** [comment]
Agreed, we actually have another check in the policy code that was changed to use it .. See 285873a (which did cause a regression, but that wouldn't impact this use case).

**Comment by slashdd** [comment]
@casual-lemon could you please submit a PR about it ?

**Comment by TurboTurtle** [comment]
Closed via e8b3804. Timing of the push with a GH outage prevented the auto close triggers from firing.
