### ISSUE TITLE
Collect loop device info

### ISSUE THREAD

**Issue by pierg75** [sosreport/sos#2014]
I've recently noticed that we don't collect almost any info about the loop devices, in particular the backing file.
I can provide a little patch to add this (I guess in the block plugin), either using directly losetup output or collecting the file /sys/block/loopX/loop/backing_file.

**Comment by TurboTurtle** [comment]
Checking in on this, we should be capturing loop device info for any command(s) that leverage the `add_blockdev_cmd()` call, unless those calls are restricted to specific device types not including `loop`.

From the `block` plugin we should be getting:

```
$ find . -name '*loop*'
./sos_commands/block/fdisk_-l_.dev.loop0
./sos_commands/block/parted_-s_.dev.loop0_unit_s_print
./sos_commands/block/udevadm_info_-a_.dev.loop0
./sos_commands/block/udevadm_info_.dev.loop0
./sys/block/loop0
./sys/devices/virtual/block/loop0
./sys/devices/virtual/block/loop0/loop
```


Additionally the backing file should be reported by `losetup -a` that the `block` plugin also collects:

```
$ cat losetup_-a 
/dev/loop0: [64770]:25415 (/home/jake/loopbackfile.img)
```


Is there anything else that needs collecting for this?

**Comment by TurboTurtle** [comment]
Closing this out, assuming the above collections are sufficient. If this is not the case please feel free to re-open this issue.
