### ISSUE TITLE
[process] collect iotop

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#2024]
How useful do you see collecting `iotop` in `process` plugin, e.g. `iotop -n 1 -b -o` ? I think it can help understanding inefficiency of processes, when they wait on I/O.

Does it make sense to collect it?

**Comment by TurboTurtle** [comment]
I like it, however I think we'd want to run with more than just one iteration since otherwise it seems we'd need to get lucky with IO actually happening the moment we run the command.

**Comment by pmoravec** [comment]
Hm right; how many snapshots over what timespan to collect? `iotop -b -o -n 10 -d 0.1`, i.e. 10 snapshots taken within 1 second? (decimal values in `-d` work at least on my Fedora)

**Comment by BryanQuigley** [comment]
Should this plugin run by itself?  I'd somewhat worry about sosreport being the top result - but testing would prove that out.

**Comment by TurboTurtle** [comment]
I was more referring to running for longer than 1 second. We should reach out to groups that are most likely to use this output and get a sense for how long a duration, and how many intervals in that duration, would be best suited for real world use cases.

@BryanQuigley We'd probably see child processes from sos no matter where/when it runs (since we run plugins in parallel, it'd be really hard to isolate this particular collection), but it's definitely something to keep an eye out for in testing.

**Comment by bu3ny** [comment]
I think SOS report usually takes between 1-3 minutes(sometimes longer) based on the collection process. Starting iotop and keep it running for around 1 minute with 5 seconds interval should reveal some info that may help.

**Comment by pmoravec** [comment]
> I think SOS report usually takes between 1-3 minutes(sometimes longer) based on the collection process. Starting iotop and keep it running for around 1 minute with 5 seconds interval should reveal some info that may help.

You should not compare running time of whole `sos report` with one command execution :) Recall that `sos report` (if we ignore some init and finalize phases) runs at most 4 (by default) plugins concurrently "only", and each plugin - independently on others - executes its commands sequentially. So adding say one minute long command to `process` plugin means overall time execution would grow by 30 seconds (on average, if my probabilistic math is correct).

Having commands lasting such longer time can be valuable, sometimes, but I think it is not the case of `iotop` where we should target its running time to seconds, I think.

**Comment by bu3ny** [comment]
It's true that the execution time will take much time. Perhaps we should make iotop to run as a plugin or on-demand(when the user explicitly add an option to sos command execution or we can define a condition to collect iotop data if the storage is loaded with more than X value). This will save a lot of time doing remote sessions with customers.

**Comment by TurboTurtle** [comment]
@pmoravec I think if we captured 10 snapshots at 1-second intervals, that would probably give us a decent dataset without causing unnecessarily long plugin runtime.

**Comment by jcastill** [comment]
From the storage point of view, having this will be very useful. Even a small capture can offer very good insight if there's an issue there already, that we'll have to investigate further.

I've been doing some tests in a server I use for storage performance debug/reproducers, and I've found that adding 20 samples, with 0.2 seconds delay captures a lot of information without causing the sosreport take a long time. The results in my tests show an average of 4 seconds, which doesn't put it in the longest running plugin (this being consistently 'lsinitrd' in my tests, with more than 5 seconds each time, and sometimes 'dnf' coming second place). I've been running the tests with -t, so we can have timestamps, and match it with the logs without problems. 
The more interesting part will be if we could instruct sos to actually gather more samples or change the delay, i.e. something like:

sos report -o process --samples 50 --delay 1

So you can capture 50 samples with 1 second each, if the default is not enough.

**Comment by jcastill** [comment]
10 samples with 1 second between each sample (iotop -b -o -n 10 -d 1 ) doesn't affect the time it takes the creation of the sosreport at all in my tests, so this may be a good match. 
20 samples with 0.5 seconds between each sample (iotop -b -o -n 20 -d 0.5) takes the same time but captures more data, so perhaps may be more useful?
