### ISSUE TITLE
Consistant way to handle exceptions

### ISSUE THREAD

**Issue by BryanQuigley** [sosreport/sos#2026]
Most of the flake issues, are around exceptions. This includes sos-collector PR.

$ flake8 sos
sos/options.py:176:13: F841 local variable 'e' is assigned to but never used
sos/options.py:220:49: F821 undefined name 'opts'
sos/policies/__init__.py:738:13: F841 local variable 'e' is assigned to but never used
sos/policies/__init__.py:940:32: F821 undefined name '_arg_names'
sos/collector/sosnode.py:22:1: F403 'from sos.collector.exceptions import *' used; unable to detect undefined names
sos/collector/sosnode.py:313:15: F405 'UnsupportedHostException' may be undefined, or defined from star imports: sos.collector.exceptions
sos/collector/sosnode.py:351:27: F405 'ControlSocketMissingException' may be undefined, or defined from star imports: sos.collector.exceptions
sos/collector/sosnode.py:388:19: F405 'CommandTimeoutException' may be undefined, or defined from star imports: sos.collector.exceptions
sos/collector/sosnode.py:472:27: F405 'InvalidPasswordException' may be undefined, or defined from star imports: sos.collector.exceptions
sos/collector/sosnode.py:474:27: F405 'TimeoutPasswordAuthException' may be undefined, or defined from star imports: sos.collector.exceptions
sos/collector/sosnode.py:476:23: F405 'PasswordRequestException' may be undefined, or defined from star imports: sos.collector.exceptions
sos/collector/sosnode.py:478:19: F405 'AuthPermissionDeniedException' may be undefined, or defined from star imports: sos.collector.exceptions
sos/collector/sosnode.py:480:19: F405 'ConnectionException' may be undefined, or defined from star imports: sos.collector.exceptions
sos/collector/sosnode.py:482:19: F405 'ConnectionException' may be undefined, or defined from star imports: sos.collector.exceptions
sos/collector/sosnode.py:484:19: F405 'ConnectionTimeoutException' may be undefined, or defined from star imports: sos.collector.exceptions
sos/collector/sosnode.py:728:16: F405 'CommandTimeoutException' may be undefined, or defined from star imports: sos.collector.exceptions
sos/report/__init__.py:30:1: F401 'sos.archive.TarFileArchive' imported but unused
sos/report/__init__.py:316:9: F841 local variable 'err' is assigned to but never used
sos/report/__init__.py:774:13: F841 local variable 'e' is assigned to but never used
sos/report/plugins/__init__.py:1850:9: F841 local variable 'e' is assigned to but never used
sos/report/plugins/__init__.py:1866:13: F841 local variable 'e' is assigned to but never used
sos/report/plugins/__init__.py:1919:9: F841 local variable 'e' is assigned to but never used

**Comment by TurboTurtle** [comment]
There's really only 2 choices here for the exceptions:

1. Explicitly import each exception in `sosnode.py` (and anywhere else we use non built-in exceptions in the future) - I believe `SoSNode` makes use of every exception defined in `exceptions.py`, so we aren't carrying unused imports.

2. Ignore F403 and F405 from flake8.

Option one is, for the moment, a one-time fix and a slightly-ugly bit at the top of `sosnode.py`. Option two may mask future legitimate concerns if we aren't careful about `*` imports in general. I think that makes our decision quite easy.

Unless there are better arguments for going with option 2, I can make a fixup commit to the collector PR before it gets properly merged.

**Comment by TurboTurtle** [comment]
I guess there is a third way - do away with the collector exceptions entirely, and just raise the base `Exception` with the error message.

**Comment by BryanQuigley** [comment]
Sure the third way is a possibility too.  I prefer the 1st (and then 3rd) - but I'm not worried about it in the short term.  Medium term we should have one way of doing for all of sos - for example, CommandTimeoutException might be useful in sos report too.

**Comment by BryanQuigley** [comment]
We are now running flake8 and no more issues, so this is fixed (or at least we've customized each exception given what we think it should do).
