### ISSUE TITLE
Travis builds fail on "18.04 native ppc64le" job due to disk quota

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#2048]
See e.g.:

https://travis-ci.org/github/sosreport/sos/jobs/683800130#L938
https://travis-ci.org/github/sosreport/sos/jobs/683806980#L735
https://travis-ci.org/github/sosreport/sos/jobs/683769195#L932

IMHO not(?) our fault, we clean our data properly in the test (confirmation needed). But simply these false alarms are confusing..

**Comment by TurboTurtle** [comment]
Yeah, from some searching around it seems this is an ongoing issue specifically on PPC for travis jobs.

https://travis-ci.community/t/disk-quota-exceeded-on-ppc64le/8006

We can either just ignore those failures, or disable the ppc builds for now until things stabilize on Travis' end.

**Comment by BryanQuigley** [comment]
I was hoping my recent PR would fix/mitigate that, but I guess not (maybe it helped? - all restarted and completed fine).  Wasn't able to figure out how to do optional - so if needed we could just drop it.

I also did want to ask, do we think we need both gzip2 and bz2 support?  (Is xz and one of those enough?)  bzip2 seems the worst - it also causes more failures on CI.

 failures false 	 time 27 	 Size 10.72MiB 	 --batch -z xz --log-size 1 
 failures false 	 time 27 	 Size 16.32MiB 	 --batch -z gzip --log-size 1 
 failures false 	 time 40 	 Size 14.17MiB 	 --batch -z bzip2 --log-size 1 
 failures false 	 time 43 	 Size 105.21MiB 	 --batch -z xz --all-logs 
 failures false 	 time 64 	 Size 187.38MiB 	 --batch -z gzip --all-logs 
 failures false 	 time 135   Size 182.86MiB 	 --batch -z bzip2 --all-logs

**Comment by pmoravec** [comment]
For me, just one alternative to the very common `xz` is sufficient, and afaik `gzip` is more widespread / used than `bz2`.

**Comment by TurboTurtle** [comment]
> I was hoping my recent PR would fix/mitigate that, but I guess not (maybe it helped? - all restarted and completed fine). Wasn't able to figure out how to do optional - so if needed we could just drop it.
> 
It did help, I just think the ppc builds on Travis are that unstable. Let's keep an eye on it for a little while longer and see if the situation changes. If it doesn't (call it 2 weeks?), I agree let's drop it.

> I also did want to ask, do we think we need both gzip2 and bz2 support? (Is xz and one of those enough?) bzip2 seems the worst - it also causes more failures on CI.
> 

I'd be ok with dropping bz2 support. `gzip` is as close to ubiquitous as you're ever going to get among compression utilities, so we should keep that imo.

**Comment by BryanQuigley** [comment]
Anyone feel we need to get ppc64le back or is testing arm/s390 good enough?
