### ISSUE TITLE
[conntrackd] Support Debian/Ubuntu and capture conntrack info

### ISSUE THREAD

**Issue by hillpd** [sosreport/sos#2049]
The plug-in checks for "conntrack-tools" but doesn't capture any debug information from the `conntrack` utility. On Debian/Ubuntu the tools package is simply named "conntrack" which should be included.

Recommend adding the following command output:
`conntrack -L -o extended`
`conntrack -S`

**Comment by ddstreet** [comment]
@slashdd @BryanQuigley

**Comment by jay-vosburgh** [comment]
"conntrack" is a separate package (on Ubuntu), so perhaps the cleanest way forward is to add a plugin for conntrack itself, and capture -L, -S, etc, via the separate plugin.

**Comment by BryanQuigley** [comment]
@TurboTurtle I'm thinking just add to current plugin makes sense.  It could also be separated as two plugins `conntract`  and `contractd` (On ubuntu conntract is supported, while conntractd is not).

**Comment by TurboTurtle** [comment]
Wow, this excerpt from [the manual](http://conntrack-tools.netfilter.org/manual.html) really hits the nail on the head

```
Although the name of both tools is very similar - and you can blame me for that, I'm not a marketing guy - they are used for very different tasks.
```

At any rate, since both utilities are at least logically coupled together I'd be in favor of adding this to the current plugin, rather than splitting out a new one.

**Comment by slashdd** [comment]
sosreport is fault tolerant (if cmd doesn't exist, it will continue) so I personally would simply add the `conntrack` command in the current plugin with the 'conntrack' package name as one of the possible triggers. And maybe rename the plugin from `conntrackd.py `to `conntrack.py` to make it more connection tracking specifics ?

**Comment by pmoravec** [comment]
+1 to have just one plugin, and rename it to `contrack`.
