### ISSUE TITLE
[sos] Standardize exit codes?

### ISSUE THREAD

**Issue by TurboTurtle** [sosreport/sos#2081]
Basically, should we?

Right now a lot of our exit patterns return an exit code of `1`, which works for programmatic checking of a successful run or not, but doesn't give us much more insight. Beyond the `130` code used for keyboard interrupts, should we standardize a set of exit codes for sos or are we fine with just having the "hey, something went wrong at some point" coverage of an exit code of `1`?

**Comment by bmr-cymru** [comment]
tl;dw there's not a lot you can do that isn't going to conflict with Someone Else's Standard. The only really widely recongised values these days are:

```
    1: Catchall for general errors
    2: Misuse of shell builtins (according to Bash documentation)
    126: Command invoked cannot execute
    127: "command not found"
    128: Invalid argument to exit
    128+n: Fatal error signal "n"
    255: Exit status out of range (exit takes only integer args in the range 0 - 255)
```

Personally I think good, diagnosable logging is of more value than precise exit status meanings.

**Comment by TurboTurtle** [comment]
Good points, let's scrap this one.
