### ISSUE TITLE
[container_log] /var/log/containers fragments collected in other plugins

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#2088]
Since adding `container_log` plugin, we do collect:

- whole `/var/log/containers` (up to some limit etc.) in `container_log` plugin
- some subdirs in two other plugins (https://github.com/sosreport/sos/blob/master/sos/report/plugins/openstack_placement.py#L43-L44 and https://github.com/sosreport/sos/blob/master/sos/report/plugins/openstack_placement.py#L49-L50 and https://github.com/sosreport/sos/blob/master/sos/report/plugins/collectd.py#L30)

This could raise the well known problem like #1596 .

Two approaches possible:
- fix the current parallelism in collecting same file by two plugins
- fix the `add_copy_spec` code to get over such error as a preventive resolution of future equivalent issues (this is 3rd instance of the same problem I am aware)

**Comment by jcastill** [comment]
Unless I'm looking in the wrong place, I think the number of plugins gathering stuff from /var/log/containers has grown in the last four years:

`sos/report/plugins/collectd.py

sos/report/plugins/container_log.py

sos/report/plugins/libvirt.py

sos/report/plugins/openstack_aodh.py

sos/report/plugins/openstack_ceilometer.py

sos/report/plugins/openstack_designate.py

sos/report/plugins/openstack_ironic.py

sos/report/plugins/openstack_manila.py

sos/report/plugins/openstack_nova.py

sos/report/plugins/openstack_placement.py

sos/report/plugins/ovn_host.py

sos/report/plugins/rabbitmq.py

`
@pmoravec any further thoughts on how to deal with this?
A third idea may be to add a new option for add_copy_spec(..., preferred_plugin=myplugin) where we specify that if there's a list of things to capture, and myplugin is specified there and it's active, the file will not be captured in any other plugin. 
Does it make sense, or is it over-complicated?

**Comment by pmoravec** [comment]
Indeed, the scope of the theoretical problem is bigger, since `container_log` is enabled whenever the `/var/log/containers/` directory exists, and it collects all `*log` files from its subdirectories - so really all those plugins collect same logfiles alongside with `container_log` one.

On the other side, if nobody has complained about the #1596 issue for this plugin in past 4 years (because the collected logs are probably small enough not to cause the logsize truncation?),it is rather theoretical than a real problem.

We shall somehow resolve the generic "two plugins collect same file" problem, but imho no extra need for this containers stuff if nobody complans.
