### ISSUE TITLE
sosreport without --batch overwrites lines with plugins execution on stdout

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#2097]
When running `sos report --batch`:

     Setting up archive ...
     Setting up plugins ...
     Running plugins. Please wait ...
    
      Starting 1/85  abrt            [Running: abrt]
      Starting 3/85  anaconda        [Running: abrt anaconda]
    ..
      Starting 85/85 yum             [Running: insights subscription_manager xfs yum]
      Finishing plugins              [Running: insights subscription_manager yum]
      Finishing plugins              [Running: insights subscription_manager]
      Finishing plugins              [Running: subscription_manager]
    
      Finished running plugins

When running `sos report` without `--batch`:

    Press ENTER to continue, or CTRL-C to quit.
    
    Please enter the case id that you are generating this report for []: 
    
     Setting up archive ...
     Setting up plugins ...
     Running plugins. Please wait ...
    
      Finishing plugins              [Running: subscription_manager]                          ger]
      Finished running plugins                                                               

See the lines overwriting each other.

**Comment by bmr-cymru** [comment]
I always understood this to be intentional:

```python
    def ui_progress(self, status_line):
        if self.opts.verbosity == 0 and not self.opts.batch:
            status_line = "\r%s" % status_line.ljust(90)
        else:
            status_line = "%s\n" % status_line
        if not self.opts.quiet:
            sys.stdout.write(status_line)
            sys.stdout.flush()
```

The `\r` is a carriage return character: i.e. return to the start of the current line and continue output (not to be confused with CRLF, the sequence of a carriage return and line feed character used as the newline encoding in DOS files).

We've been using this to re-write status lines for many years (at leas back to 2.x when the progress bar was removed).

**Comment by pmoravec** [comment]
Hm OK then, I thought it is a bug and not a feature - I was used to use `--batch` almost all the time, so I took the different behaviour during an independent testing without `--batch` as a surprise for me.

Closing this as intentional behaviour.
