### ISSUE TITLE
[RFE] Provide a drbd plugin

### ISSUE THREAD

**Issue by nniehoff** [sosreport/sos#2102]
First, I'm not a drbd expert so I don't feel qualified to write such a plugin.  However, when troubleshooting issues related to drbd it would be handy if there was a plugin in sosreport.  I'm just throwing this out there to track the request if anyone would like to write one.

**Comment by pmoravec** [comment]
I can assist with writing such a plugin / I can write it when having answers to below questions:


- when the plugin should be enabled by default? Is there a package or a service or a kernel module or a file, whose presence can be used for deterministic identification that the system has drbd ?
- what files (configs and/or logs) to collect?
- what command outputs to collect?
- is there some potential sensitive information (passwords, keyphrases, SSL private certs,..) in the collected data, that we should obfuscate?
- what distros can have drbd installed / on what distros should we collect that info? Is there some difference among those distros (like e.g. different package present on Red Hat distros than on Canonical distros, or different path to logfiles etc.)?

**Comment by nniehoff** [comment]
@pmoravec thanks for the assistance.  Let me see if I can answer some of these:

> when the plugin should be enabled by default? Is there a package or a service or a kernel module or a file, whose presence can be used for deterministic identification that the system has drbd ?

On Ubuntu the package is named drbd-utils but it might be safer we check for the kernel module drbd.

> what files (configs and/or logs) to collect?

This is where I'm not an expert, but some that I think would be useful:

/etc/drbd.conf
/etc/drbd.d/*
/proc/drbd

> what command outputs to collect?

Again, not an expert but some that I know about.
drbd-overview
drbdadm dump-xml
drbdsetup status
drbdsetup show

> is there some potential sensitive information (passwords, keyphrases, SSL private certs,..) in the collected data, that we should obfuscate?

Possibly, I'm not familiar with all use cases

> what distros can have drbd installed / on what distros should we collect that info? Is there some difference among those distros (like e.g. different package present on Red Hat distros than on Canonical distros, or different path to logfiles etc.)?

I have seen drbd on RH and Debian based systems but never gotten too much into the config so there are probably differences as well.

**Comment by nniehoff** [comment]
@jcastill I would grab anything in /etc/drbd.d/*.conf

**Comment by jcastill** [comment]
Perfect. Now, from when I used to support DRBD, we don't have any passwords that we need to mask in the config files. That's still the case, right?
Another question - do you think we should get drdbmeta output as well?

**Comment by jcastill** [comment]
First version created, all comments welcome. I've tested it quickly but I'm going to do more in depth testing in a bit. @nniehoff do you have any environment where you can test as well?

**Comment by nniehoff** [comment]
I recently built a test environment but I am on vacation until Tuesday so I’ll have to test then.

**Comment by nniehoff** [comment]
@jcastill It looks like the regex on line 18 doesn't work.  I changed it to match my installed package 'drbd-utils' and the plugin executed fine.
