### ISSUE TITLE
[sos4.0] Refactor configuration files/directories

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#2125]
As we refactored the `sosreport` into `sos [report|collect|clean]` in the tool's behaviour, we should do the same with configuration. Current status:

- `/etc/sos.conf` being used by `sos report`
- `/etc/sos.extras.d/` can be used by `sos_extras` plugin
- `/etc/sos/cleaner/default_mapping` that stores `cleaner`'s obfuscation mapping from previous runs
- I think nothing else..?

That "hierarchy"  is not logical, though it can serve our current purposes well. But as we will release a major version of the tool, it makes sense to refactor this. Some questions that answering can help us to decide:

- Is it worth having an extra directory for each component, to easily *add* (without an interference) config relevant to it? Or is e.g. `/etc/sos.d/` enough (and sections in the configs define the component)? Or is such a dir required at all?
- is an extra (mandatory? optional?) config file (for each component? or just whole `sos`?) required?
- is the current "default config dominance to `report`" useful? Should the default config file refer to `report` or to `sos`, rather?
- should we support reading `sos` Global options from a config file? (if not, then the global config file is less interesting) Or just from the config file of selected component? (I mean: running `sos report` should read `/etc/sos.conf` with global options first, and then `/etc/sos/report.conf` for `report`'s options?)

My proposal:
- `/etc/sos.conf` just being a symlink to `/etc/sos/report.conf` for legacy reasons; `report` should read from the later file
- `/etc/sos/[report|collect|clean].conf` the basic config file for the components; IMHO neither is mandatory (do we even really *need* current `/etc/sos.conf` to be present?)
- `/etc/sos/[report|collect|clean]` as optional directories: files with `*.conf` mask will be traversed in *undefined* ordering after the `/etc/sos/[report|collect|clean].conf` is read, files with different filemask serve specific needs for the component (like `default_mapping`)

But isn't that too complex?

**Comment by TurboTurtle** [comment]
Initially, my reaction is to say we should have a `.conf` file for each component. When that component is loaded, we read exclusively from that file for configuration updates.

For global options though, that can become a pain - but at the same time it seems silly to have _both_ a `sos.conf` and a `$component.conf` where the former only has global definitions.

I'm personally not a fan of the option `.conf` files - one place for each component should be granular enough imho.

I guess my proposal would be:

* Drop `/etc/sos.conf` entirely
* Introduce `/etc/sos/` config directory, with `report.conf`, `cleaner.conf`, `collect.conf`, etc.. inside there.
* Make an `/etc/sos/extras.d/` directory specifically for that plugin (where multiple files *does* make sense)
* Have default subdirs for components like `/etc/sos/collect/` where we can store host groups. Similarly for `report` we could save presets under `/etc/sos/report/`
    * Given `collect` is most likely to be run by non-root, should we allow non-root access to whole `/etc/sos` or just `/etc/sos/collect` or not at all, and continue to use an alternative location for host groups (e.g. `/var/lib/`)?
   * Again, no arbitrary `*.conf` files here. I don't think sos is a big enough beast to warrant it.

**Comment by pmoravec** [comment]
+1 to @TurboTurtle proposal. In case there is a need to implement multiple `*.conf` files, we could add it later.

**Comment by TurboTurtle** [comment]
Hmm. The more I look at this, the more I'm thinking perhaps a single unified config file is the way to go, with each component having a separate section.

E.G.

* Move `/etc/sos.conf` to `/etc/sos/sos.conf` (or whatever)
* Make `/etc/sos/extras.d/` for the extras plugin
* Make `/etc/sos/presets.d/` for report presets
* Make `/etc/sos/groups.d/` for root-created collect host groups (moving non-root groups to user's homedirs instead of `/var/lib`?)

The odd one out for me here, would be the `default_mapping` file for `sos clean`. Should it just go to `/etc/sos/default_mapping`? Some subdir where only that one file lives?

Within `/etc/sos/sos.conf` the structure would be something like:
```
[global]
threads = 4
verbose = 0

[report]
skip_plugins = some, list
log_size = 30

[collect]
jobs =4
skip_plugins = some, other, list  # repeat the key here since this would affect remote sos runs

[cleaner]
map_file = /etc/sos/default_mapping
```

**Comment by TurboTurtle** [comment]
Also, the above approach would make it easier to allow for per-user config overrides by mimicing the directory structure under `~/.config/sos` or similar, which would then make a fairly clean and concise place for per-user groups and cleaner mappings.
