### ISSUE TITLE
[logs] Review duplicit journal logs

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#2132]
Two issues spot when reviewing journal logs being collected in https://github.com/sosreport/sos/blob/master/sos/report/plugins/logs.py#L64-L66 :

            self.add_journal(since=since)
            self.add_journal(boot="this", catalog=True)
            self.add_journal(boot="last", catalog=True)

- `--since` option is not applied to `catalog=true` journals ; IMHO we should limit the 2 last lines with `since=since` option. If one wants to limit logs by a date, we shouldn't provide them older logs.

- much of the collected journal logs with and without `catalog` is duplicated. Which makes the "non-catalog" journal collection redundant. So it can be a legitimate question to drop the first line, esp. when journal logs collection takes some time and space. Anyway, we do collect duplicate commands outputs (ps, sar,..) as well for the sake of different usage of the outputs - and I feel the same rationale applies here as well. "catalog" is more verbose, while "noncatalog" easier to follow and/or parse.

- `journalctl` output collected together with raw `/[var|run]/log/journal` - is it reasonable to duplicate collecting that data in raw and cmdoutput-based format? Both is valuable in some situation(s): `journalctl` for human readable output, raw data for dealing with `journalctl` fatal issues (how often that could happen? isn't it worth to collect that conditionally only?)

**Comment by pmoravec** [comment]
The `--since` point is currently covered in #2130.

**Comment by BryanQuigley** [comment]
Catalog was kept for boot boot debugging in #1822, but that still doesn't make sense to me.  AFAIK all it adds is separating boots to files and catalog messages which you should be able to lookup elsewhere - https://freedesktop.org/wiki/Software/systemd/catalog/. I'd strongly prefer dropping the catalog variants out of those 3.  Can we dive deeper into the usefulness of the catalog with a specific example?

The most flexibility is to just capture the raw /[var|run]/log/journal - which you can then can put journalctl -D <at> to use all the journalctl commands as you would normally.  (this would trivially handle the last/this boot with catalog case IMU)

Another option would be to capture every boot to it's own file - which would be neat.  (Again, this is trivially handled by capturing the raw /[var|run]/log/journal and using the journalctl -b <thebootyouwant> command to parse.)

(I did previously mention a way to capture all previous boots except the last 2, but I don't think that actually worked).

**Comment by TurboTurtle** [comment]
Cycling around on this - I think I'm in favor of dropping `catalog=True` here, but unsure of dropping the `this` and `last` collections entirely. The matter of the "full" journal collection vs "this" and "last" boot-centric journals comes down to size limiting in my mind. With a size limit, we have no way to tell if the "full" journal is in fact full, or if it covers the entire current boot or the "last" boot.

I don't think we can outright always copy `/[var|run]/log/journal`, as this is binary data which means we can't only collect a snippet of it. It's all or nothing, and even on moderate usage this can generally lead to a couple GB of data. As a small data point, on my daily driver `/var/log/journal` sits around 2GB most of the time - without this collection an archive is ~3MB running _just_ the `logs` plugin. Enabling this collection expands the archive to ~57MB, and also significantly increases the compression time.

**Comment by pmoravec** [comment]
Re the `/[var|run]/log/journal` to collect or not to collect: Building upon these facts:

- we must either collect it whole or nothing
- collecting (even) decent amount of data significantly increases the size of the archive and runtime

I feel, we should have a plugin option "if the directory contains at most X GB, collect it whole (or nothing)" - with reasonable small default X (something from range 1-4 GB?).

**Comment by BryanQuigley** [comment]
I'm guessing this would be easier done by using the from systemd import journal in python, but journalctl --list-boots does give us the information about when boots happened:
  -1 7b8232722cc245b6a900417a7d57b230 Fri 2022-07-01 08:31:07 PDT—Fri 2022-07-01 14:00:06 PDT
   0 04ed625cb2684ec29a04773e9a42c05b Fri 2022-07-01 17:48:11 PDT—Sat 2022-07-02 13:59:16 PDT

and then journalctl --header can let us know which journal files have what time range:
File path: ~cd444213.journal
Head realtime timestamp: Thu 2022-06-23 09:18:19 PDT (5e21fcd444213)
Tail realtime timestamp: Fri 2022-07-01 14:00:05 PDT (5e2c4abb492e0)
Disk usage: 87.2M

Having said all that, just disabling Catalog and leaving everything else the same might be a good initial change.
