### ISSUE TITLE
Remove 'podman pod ps -a' command from podman plugin

### ISSUE THREAD

**Issue by control-d** [sosreport/sos#2146]
https://github.com/sosreport/sos/blob/6818b5481475e582900a8ed2a776bd7b3c77c28d/sos/report/plugins/podman.py#L41

The `-a` flag doesn't exist for `podman pod ps` in any current versions.  It can be removed from the list of collected commands.

**Comment by pmoravec** [comment]
As the option really seems superfluous for a long time (if it ever worked), ACK to remove the command as not needed even from legacy reasons.

**Comment by control-d** [comment]
Looks like I was just a little too slow getting my PR ready.  Thanks for putting this together.

**Comment by pmoravec** [comment]
Sorry for stepping on your toes :)
