### ISSUE TITLE
[foreman] foreman-initial-admin-password is being collected

### ISSUE THREAD

**Issue by mikelolasagasti** [sosreport/sos#2156]
$ grep foreman-initial-admin-password *
    satellite.4.log:[ INFO 2020-04-08T18:40:26 main] Running installer with args [["--scenario", "satellite", "--foreman-initial-organization", "ACME", "--foreman-initial-location", "Mars", "--foreman-initial-admin-username", "admin", "--foreman-initial-admin-password", "verys3cr3t", "--reset"]]
    satellite.6.log:[ INFO 2020-04-08T17:42:44 main] Running installer with args [["--scenario", "satellite", "--foreman-initial-organization", "ACME", "--foreman-initial-location", "Mars", "--foreman-initial-admin-username", "admin", "--foreman-initial-admin-password", "verys3cr3t", "--reset"]]
    satellite.9.log:[ INFO 2020-04-08T16:46:13 main] Running installer with args [["--scenario", "satellite", "--foreman-initial-organization", "ACME", "--foreman-initial-location", "Mars", "--foreman-initial-admin-username", "admin", "--foreman-initial-admin-password", "verys3cr3t"]]
    $ grep sos installed-rpms 
    sos-3.8-8.el7_8.noarch                                      Mon Jun  8 12:30:04 2020

**Comment by TurboTurtle** [comment]
Let's get this handled before we close 4.0, and I assume backport to 3.9.

**Comment by pmoravec** [comment]
I am preparing a patch already (that will hide some other "password=.." in puppet diff of candlepin.conf, as printed to the installer logfile).
