### ISSUE TITLE
sosreport shouldn't run as non-root, or at least, ask user confirmation when run as non root.

### ISSUE THREAD

**Issue by valleedelisle** [sosreport/sos#2159]
People often forget to run sosreport as root and this is a waste of time for everyone. I never got a use-case to run sosreport as non-root, but if there's any use-case, we should probably have a warning "Are you sure you want to run sosreport as a non-root user? The data collected by non-root is pretty limited"

**Comment by TurboTurtle** [comment]
Current `master` already does prevent non-root runs for report. The `sos` binary can be run as non-root for `clean` and `collect`, but `report` will abort if run as non-root.

~~~
[jake@terra sos]$ ./bin/sos report --batch
Could not initialize 'report': Component must be run with root privileges
~~~

**Comment by valleedelisle** [comment]
Nice job, my apologies for this issue. Closing.
