### ISSUE TITLE
[plugins] Too relaxed behaviour when hitting sizelimit

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#2175]
Assume 30+ `/var/log/messages*` each having exactly 1M size. Then `sosreport` with default 25M `log-size` will collect 27M of `/var/log/messages*` , not 25. And if the 27th file is huge, then up to 50MB.

The reason is twofold:
- if we are *exactly* on the sizelimit, we still *continue* in data collection, see https://github.com/sosreport/sos/blob/master/sos/report/plugins/__init__.py#L1118 and "`current_size > sizelimit`" (there should imho be "`>='")
- if we tail a file, we add whole `sizelimit` (see https://github.com/sosreport/sos/blob/master/sos/report/plugins/__init__.py#L1130) - so theoretically, if the "being tailed" file will be huge, we would copy `sizelimit` size of it and in fact *double* of `/var/log/messages` or what the `copyspec` is - here we should imho replace:

     tail(_file, sizelimit)

by:

    tail(_file, sizelimit - current_size)

Either of these suggested changes are imho technically correct as they ensure we collect exactly `sizelimit` of data. Since the changes might break anticipated "too relaxed" behaviour of `sizelimit` and `tailit`, I am opening an issue rather than PR directly.

Are both or either changes sound?

**Comment by TurboTurtle** [comment]
Ack, to both with a minor change to the second one. Wouldn't it need to be

```python
tail(_file, abs(sizelimit - current_size))
```

To take into consideration the times when `current_size > sizelimit`?

**Comment by pmoravec** [comment]
Neither that would be precise. Assume `sizelimit = 10`, `filesize = 5`, we already collected `8 MB` so `current_size` was increased from 8 to 13 before the test. We should add 2MB (from 8MB to 10MB) in this case.

In general: adding whole file means collecting `current_size` but we should collect `sizelimit` (`<=current_size) only. So we must add just

    (sizelimit - previous_current_size)

i.e.

    sizelimit - (current_size - filestat[stat.ST_SIZE]) =
     = sizelimit + filestat[stat.ST_SIZE] - current_size

**Comment by pmoravec** [comment]
And also the first suggestion is changed: in case collecting the latest file just reaches the limit, we can't tail it (as my original suggestion was, via the `current_size >= sizelimit`), but we must collect it as a whole file and *just* mark we are done by `limit_reached = True`.
