### ISSUE TITLE
[plugins] get_container_by_name() function doesn't return all containers with specific pattern

### ISSUE THREAD

**Issue by Meiyan89** [sosreport/sos#2176]
Hi, 

Calling `get_container_by_name()` function in **Class Plugin**  as below will only get one container with below pattern, 
I'm expecting to get a list of containers with specific pattern: 

    self._container_osd_name = self.get_container_by_name('ceph-osd-*')

I'm running this in RHEL8.1.  In containerized CEPH osd node, there could be several ceph-osd containers running on it. 
Is it possible to add a function to get all containers with specific name pattern? 

Best Regards,
Meiyan

**Comment by TurboTurtle** [comment]
Shouldn't be an issue to add a method for that. In the interim, you could potentially use `Plugin.get_containers()` which will return a list of all containers as 2-tuples of `(id, name)`. So you could do something like this:

```python
self._container_osd_name = [c[1] for c in self.get_containers() if re.match(c[1], 'ceph-osd-.*')]
```

**Comment by Meiyan89** [comment]
Hi Jake,

Thank you for your quick response and really appreciate for your suggestion! 
I can get all containers with specific name pattern now. 

Best Regards,
Meiyan
