### ISSUE TITLE
[npm] "npm cache ls" removed but used in sos report

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#2177]
See https://github.com/sosreport/sos/blob/master/sos/report/plugins/npm.py#L60 - while `npm cache ls` returns:

    npm ERR! Usage: npm cache add <tarball file>
    npm ERR! npm cache add <folder>
    npm ERR! npm cache add <tarball url>
    npm ERR! npm cache add <git url>
    npm ERR! npm cache add <name>@<version>
    npm ERR! npm cache clean
    npm ERR! npm cache verify

(which corresponds to `npm` manpages).

Any idea, how to rewrite the method https://github.com/sosreport/sos/blob/master/sos/report/plugins/npm.py#L39 , @TomasTomecek or @jpopelka ?

**Comment by TomasTomecek** [comment]
I'll be honest that I'm no longer working on the project which utilizes this functionality. 

Based on this issue it seems that `npm` changed their CLI in a backwards incompatible manner. Is it even able to list local modules with the change?

Given all of this, I won't be able to help here and wouldn't personally mind removing the module from sos, not sure how much it is being used by your users.

**Comment by TurboTurtle** [comment]
I dug into this a bit, and the long and short of it is that you can no longer look into the npm cache via npm anymore. Seems rather silly, but that's where we're at. We'd need to use the `cacache` node.js library which obviously isn't happening in sos.

We'll need to strip this stuff out of the `npm` plugin.
