### ISSUE TITLE
sos now enforces /var/tmp as tmpdir unless --tmp-dir option is used

### ISSUE THREAD

**Issue by slashdd** [sosreport/sos#2178]
Debian/Ubuntu systemd's implementation doesn't cleanup `/var/tmp` which makes it risky to archive sosreport at that specific location. We use /tmp for quite some time.

Testing the sosreport master (AKA [4.0]) it seems like `/var/tmp `is enforced -> https://github.com/sosreport/sos/blob/master/sos/component.py#L142

Unless tmp-dir option is used in command-line or in sos.conf
Adding the specification inside the ubuntu/debian policy doesn't seem to be taken into account.

**Comment by slashdd** [comment]
```
$ dpkg -S /usr/lib/tmpfiles.d/tmp.conf
systemd: /usr/lib/tmpfiles.d/tmp.conf
```
```
$ cat /usr/lib/tmpfiles.d/tmp.conf
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

# See tmpfiles.d(5) for details

# Clear tmp directories separately, to make them easier to override
D /tmp 1777 root root -
#q /var/tmp 1777 root root 30d

```

**Comment by slashdd** [comment]
A workaround would be to enforce is inside sos.conf at the packaging level

```
[global]
# Set global options here that are not component specific
# If you would like one global default value to be specifically overridden for
# just one component, but not others, you may override that value in the
# component specific section below
#verbose = 3
#verify = yes
#batch = yes
#log-size = 15
tmp-dir = /tmp
```

**Comment by slashdd** [comment]
@BryanQuigley fyi

**Comment by TurboTurtle** [comment]
Yes, this change was made in the initial 4.0 redesign to allow for multiple subcommands, and was highlighted and discussed in #1993.

#1997 is still open and tracking this already.

**Comment by slashdd** [comment]
@TurboTurtle I can add it into the debian/ubuntu package itselves, but would it be worth having a` tmpfiles.d/sosreport.conf `maintained upstream ? If sosreport comes with its tmpfiles.d directive, I'll be more comfortable to do the switch from "/tmp/" to "/var/tmp" once 4.0 version is released.

**Comment by TurboTurtle** [comment]
Yeah, I'm not opposed to carrying a `tmpfiles.d` conf in upstream.

Let's see if we need to do different vendor configs, what were you thinking for a time frame?

@pmoravec any preference on this for RHEL?

**Comment by slashdd** [comment]
Most of our user' sosreport archives are usually uploaded to our FTP the same day that it has been created, so in theory it is not data that one would need to keep very long, unless one has strict data internal policies.

I'm not aware of any particular case where one would intentionally retention or backup sosreport archive internally, but assuming there is, maybe we should find a time frame that give a reasonable amount of time for one to do their copy/backup/... (if needed).

What about a cleanup every 15-20 days range ?

**Comment by pmoravec** [comment]
Not much preference from RHEL side (as far as I can instantly check). But is it worth having such temp files retention policy (i.e. sort of customisation) present in multiple-distors upstream..? Can't package maintainers take care of it per distro, rather?

**Comment by slashdd** [comment]
I would say that if we agree on a something common, I would be +1 on keeping it upstream ?

What about something like this ?
`e /var/tmp/sosreport-* - root root 30d`

**Comment by TurboTurtle** [comment]
After discussing this a bit more internally, for the RH family distros we'd need a lot more runway to implement this kind of change, most notably to discuss it with support personnel and such.

That being said, I'm still open to carrying a `tmpfiles.d/sos.conf` here in upstream as an example of one to use, especially if it makes things easier on your end for the deb packaging. We can just leave it out for rpm builds.

**Comment by slashdd** [comment]
Ok will test a few scenarios and will submit a PR in the next few days. Thanks.

**Comment by slashdd** [comment]
For now, I've been testing with the following:
`e /var/tmp/sosreport* - - - 0`

https://www.freedesktop.org/software/systemd/man/tmpfiles.d.html:
`If the age argument is "0", contents will be unconditionally deleted every time systemd-tmpfiles --clean is run.`

It works but it doesn't fully do what I am trying to accomplish here. It only cleans un-archived sosreport folder contents, and does not clean anything that is a sosreport file at` /var/tmp` root nor delete the un-archived folder itself.

Before the clean:
```
# ls -altr sosreport*
-rw-------  1 root root 9229260 Aug 11 17:11 sosreport-<HOSTNAME>-2020-08-11-cbmtxfh.tar.xz

sosreport-<HOSTNAME>-2020-08-11-cbmtxfh:
total 68
drwxr-xr-x   4 root root  4096 Apr 23 07:34 usr
drwxr-xr-x   6 root root  4096 Jun 16 12:01 var
lrwxrwxrwx   1 root root     7 Aug  6 04:10 lib -> usr/lib
drwxr-xr-x   3 root root  4096 Aug  6 04:13 boot
drwxr-xr-x  62 root root  4096 Aug  7 17:28 etc
dr-xr-xr-x 495 root root 12288 Aug  8 16:54 proc
dr-xr-xr-x  10 root root  4096 Aug  8 16:54 sys
lrwxrwxrwx   1 root root    22 Aug 11 17:11 date -> sos_commands/date/date
lrwxrwxrwx   1 root root    25 Aug 11 17:11 installed-debs -> sos_commands/dpkg/dpkg_-l
lrwxrwxrwx   1 root root    29 Aug 11 17:11 mount -> sos_commands/filesys/mount_-l
lrwxrwxrwx   1 root root    37 Aug 11 17:11 df -> sos_commands/filesys/df_-al_-x_autofs
lrwxrwxrwx   1 root root    31 Aug 11 17:11 dmidecode -> sos_commands/hardware/dmidecode
lrwxrwxrwx   1 root root    26 Aug 11 17:11 hostname -> sos_commands/host/hostname
lrwxrwxrwx   1 root root    24 Aug 11 17:11 uptime -> sos_commands/host/uptime
lrwxrwxrwx   1 root root    28 Aug 11 17:11 uname -> sos_commands/kernel/uname_-a
lrwxrwxrwx   1 root root    25 Aug 11 17:11 lsmod -> sos_commands/kernel/lsmod
lrwxrwxrwx   1 root root    23 Aug 11 17:11 last -> sos_commands/login/last
lrwxrwxrwx   1 root root    39 Aug 11 17:11 lsof -> sos_commands/filesys/lsof_-b_M_-n_-l_-P
lrwxrwxrwx   1 root root    83 Aug 11 17:11 vgdisplay -> sos_commands/lvm2/vgdisplay_-vv_--config_global_locking_type_0_metadata_read_only_1
lrwxrwxrwx   1 root root    24 Aug 11 17:11 free -> sos_commands/memory/free
lrwxrwxrwx   1 root root    34 Aug 11 17:11 ip_addr -> sos_commands/networking/ip_-o_addr
lrwxrwxrwx   1 root root    32 Aug 11 17:11 route -> sos_commands/networking/route_-n
lrwxrwxrwx   1 root root    41 Aug 11 17:11 netstat -> sos_commands/networking/netstat_-W_-neopa
lrwxrwxrwx   1 root root    28 Aug 11 17:11 lspci -> sos_commands/pci/lspci_-nnvv
lrwxrwxrwx   1 root root    30 Aug 11 17:11 ps -> sos_commands/process/ps_auxwww
lrwxrwxrwx   1 root root    31 Aug 11 17:11 pstree -> sos_commands/process/pstree_-lp
lrwxrwxrwx   1 root root    32 Aug 11 17:11 lsb-release -> sos_commands/release/lsb_release
drwxr-xr-x   6 root root  4096 Aug 11 17:11 run
drwxr-xr-x  62 root root  4096 Aug 11 17:11 sos_commands
-rw-r--r--   1 root root   124 Aug 11 17:11 environment
drwxr-xr-x   2 root root  4096 Aug 11 17:11 sos_reports
-rw-r--r--   1 root root  1449 Aug 11 17:11 version.txt
drwxr-xr-x   2 root root  4096 Aug 11 17:11 sos_logs
drwx------  12 root root  4096 Aug 11 17:11 .
drwxrwxrwt  20 root root  4096 Aug 11 17:12 ..
```

After the clean:
```
# ls -altr sosreport*
-rw------- 1 root root 9229260 Aug 11 17:11 sosreport-<HOSTNAME>-2020-08-11-cbmtxfh.tar.xz
-rw------- 1 root root 9229260 Aug 11 17:11 sosreport-<HOSTNAME>-2020-08-11-cbmtxfh.tar.xz.md5

sosreport-<HOSTNAME>-2020-08-11-cbmtxfh:
total 8
drwx------  2 root root 4096 Aug 11 17:11 .
drwxrwxrwt 20 root root 4096 Aug 11 17:12 ..
```
So for now the current proposal would only do a partial cleanup.

I'll continue to investigate, but it seems tmpfiles.d does clean at directory level, so to clean everything properly, /var/tmp would need to be enabled as well on Debian side (systemd), and that will unlikely happen. See for reference: [debbug#966621](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=966621 )
