### ISSUE TITLE
[archive:TarFileArchive] Unable to add few empty files on some systems

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#2190]
On various systems (probably RHEL7 only), `sos report` prints errors:

    [archive:TarFileArchive] Unable to add '/var/tmp/sos.cecx8zog/sosreport-rhel7-iscsisrv-2020-08-09-amfndyz/proc/sys/vm/compact_memory' to archive: [Errno 13] Permission denied: '/var/tmp/sos.cecx8zog/sosreport-rhel7-iscsisrv-2020-08-09-amfndyz/proc/sys/vm/compact_memory'
    [archive:TarFileArchive] Unable to add '/var/tmp/sos.cecx8zog/sosreport-rhel7-iscsisrv-2020-08-09-amfndyz/sys/kernel/config/target/core/iblock_1/test/control' to archive: [Errno 13] Permission denied: '/var/tmp/sos.cecx8zog/sosreport-rhel7-iscsisrv-2020-08-09-amfndyz/sys/kernel/config/target/core/iblock_1/test/control'
    [archive:TarFileArchive] Unable to add '/var/tmp/sos.cecx8zog/sosreport-rhel7-iscsisrv-2020-08-09-amfndyz/sys/kernel/config/target/core/iblock_0/test2/control' to archive: [Errno 13] Permission denied: '/var/tmp/sos.cecx8zog/sosreport-rhel7-iscsisrv-2020-08-09-amfndyz/sys/kernel/config/target/core/iblock_0/test2/control'

The files on the disk are empty, generated tarball does collect them. Not reproducible on Fedora or RHEL8 or Ubuntu, just on RHEL7. Probably rather a matter of error message?

**Comment by bmr-cymru** [comment]
Those are `/sys` and `/proc` command interfaces - they are write-only. We could blacklist them since there's no use in trying to collect data from them.

**Comment by jcastill** [comment]
@pmoravec I don't think we ever followed up on this, blacklisting /sys and /proc, right? Also, you mentioned RHEL7 - did this ever happen in RHEL8 and later?
