### ISSUE TITLE
[global] have an option to exclude specific files

### ISSUE THREAD

**Issue by arif-ali** [sosreport/sos#2203]
There may be situations where a specific file is too big, and want to exclude this file. If it is not excluded the filesystem would be full and the `sos report` will fail to collect. Excluding the plugin is not feasible, as we want to collect the information that the plugin is collecting

maybe have an option called `--exclude-files` as a command line option?

**Comment by pmoravec** [comment]
`sos report` applies a size limit (by default 25MB) for a file / group of files. So until it is e.g. https://github.com/sosreport/sos/blob/master/sos/report/plugins/foreman.py#L79 case where we surpress the limit by `sizelimit=0`, just a limited amount of data should be collected. And that is configurable via `--log-size` option.

Or is the "too big file" one of those with unlimited sizelimit? Then two enhancements are possible:

- option `--exclude-files` as suggested
- enhance `sos_extras` plugin (https://github.com/sosreport/sos/blob/master/sos/report/plugins/sos_extras.py) that currently can collect *new* files and cmdoutputs - it should be easy to enhance it to blocklist some file patterns. BUT doing so would break plugin independence (no plugin shall affect any other one, we rely on this premise) - such an implementation shall work well, just the paradigm will be restricted.

**Comment by al3jandrosg** [comment]
An example "too big" file we found to be collected is `lastlog`, we've seen it causing free disk space issues. I guess that `--exclude-files` would be a better approach in such case as it is a plugin independent file

**Comment by bmr-cymru** [comment]
The `lastlog` file often *appears* huge since it is sparsely allocated on-disk and the maximum record (which determines the file size) depends on the highest numbered UID and GID in use on the system - **BUT** we have never collected the file in `sosreport`, so I am not sure what you are seeing that is causing it to be picked up?

Could you add the version of `sos` that you are running, and the set of plugins (including any 3rd party plugins not sourced from the upstream repository)?

There was a bug in an external component (the `ipsec barf` command provided by the OpenSwan package) that caused long runtimes when running a `grep` command on this file, however we fixed `sos` to not run this by default a number of years ago in sos-3.1:

```
commit 4858ce293a77cc9b973ab7552f3e0b041360b20e
Author: Bryn M. Reeves <bmr@redhat.com>
Date:   Tue Aug 13 15:31:37 2013 +0100

    Make 'ipsec barf' collection non-default in openswan plug-in
    
    The 'ipsec barf' debugging command has a nasty bug where it runs
    grep on /var/log/lastlog. Since this can be a multi-gigabyte
    sparse file this doesn't work very well and consumes huge amounts
    of memory. This can lead to timeouts and aborts when running sos
    since the openswan plug-in calls this command by default.
    
    The barf information is seldom useful anyway - turn it off by
    default to avoid this problem.
    
    Signed-off-by: Bryn M. Reeves <bmr@redhat.com>
```

**Comment by al3jandrosg** [comment]
Sosreport version: 3.6-1ubuntu0.16.04.3 

The following plugins are currently enabled:

 acpid,anacron    ,apache      ,apparmor    ,apport   ,apt  ,ata  ,block      ,boot,ceph,cgroups,conntrackd,corosync   ,cron ,crypto,date   ,dbus    ,devicemapper ,devices      ,dlm  ,dpkg,filesys    ,haproxy     ,hardware  ,host ,i18n ,iscsi,java      ,kernel     ,kvm  ,last,ldap,libraries  ,libvirt     ,logrotate  ,logs ,lvm2 ,md   ,memcached   ,memory      ,multipath   ,mysql,networking ,ntp ,numa ,openssl    ,openstack_ceilometer,openstack_cinder ,openstack_glance   ,openstack_heat     ,openstack_horizon ,openstack_keystone ,openstack_manila   ,openstack_neutron  ,openstack_nova     ,openstack_sahara   ,openstack_swift    ,openvswitch ,pacemaker   ,pam ,pci  ,perl ,postfix     ,procenv     ,process     ,processor   ,puppet     ,python      ,rabbitmq    ,release     ,scsi ,services    ,snmp ,soundcard   ,ssh  ,sssd ,system      ,systemd    ,sysvipc     ,ubuntu      ,udev ,upstart     ,usb  ,wireless   ,x11  ,xfs ,xinetd             

The following plugin options are available:

 apache.log                off             gathers all apache logs
 boot.all-images           off             collect lsinitrd for all images
 dlm.lockdump              off             capture lock dumps for DLM
 filesys.lsof              off             gathers information on all open files
 filesys.dumpe2fs          off             dump filesystem information
 filesys.frag              off             filesystem fragmentation status
 kernel.with-timer         off             gather /proc/timer* statistics
 libraries.ldconfigv       off             collect verbose ldconfig output
 lvm2.lvmdump              off             collect an lvmdump tarball
 lvm2.lvmdump-am           off             attempt to collect an lvmdump with advanced options and raw metadata collection
 mysql.dbuser              mysql           username for database dumps
 mysql.dbpass              off             password for database dumps (password visible in process listings)
 mysql.dbdump              off             collect a database dump
 networking.traceroute     off             collect a traceroute to www.example.com
 openstack_keystone.nopw   on              dont gathers keystone passwords
 pacemaker.crm_from        off             specify the start time for crm_report
 pacemaker.crm_scrub       on              enable password scrubbing for crm_report
 process.lsof-threads      off             gathers threads' open file info if supported
 services.servicestatus    off             get a status of all running services

 Profiles: boot, cluster, container, debug, desktop, hardware, identity, 
           java, kernel, mail, memory, network, openshift, openstack, 
           openstack_compute, openstack_controller, packagemanager, 
           performance, perl, security, services, storage, sysmgmt, 
           system, virt, webserver

 26 profiles, 87 plugins

**Comment by al3jandrosg** [comment]
Additional details: 

sosreport 3.6-1ubuntu0.16.04.3 , tried to collect lastlog
sosreport 3.9-1ubuntu0.16.04.2  , did not try to collect lastlog

I haven't found why yet. Any ideas?

**Comment by bmr-cymru** [comment]
Odd - I'd have to pull the .debs and take a look what's in there (plus any possible extra plugin packages) - unless any of our Ubuntu contributors can chime in?

**Comment by al3jandrosg** [comment]
I think the issue may be in the `logs` plugin. Namely, the `else` below (sosreport 3.6-1ubuntu0.16.04.3):

`def setup(self):
        super(DebianLogs, self).setup()
        if not self.get_option("all_logs"):
            self.add_copy_spec([
                "/var/log/syslog",
                "/var/log/syslog.1",
                "/var/log/kern.log",
                "/var/log/kern.log.1",
                "/var/log/udev",
                "/var/log/dist-upgrade",
                "/var/log/installer",
                "/var/log/unattended-upgrades"
            ])
            self.add_cmd_output('ls -alRh /var/log/')
        else:
            self.add_copy_spec("/var/log/")`

When the `all_logs` option is not set then the whole content of `/var/log` will be collected. Is that right?

**Comment by bmr-cymru** [comment]
> When the all_logs option is set then the whole content of /var/log is collected. Is that right?

Yes - although that has been tightened up a bit in sos-4.0:

```python
        else:  # If not using journal
            if not self.get_option("all_logs"):
                self.add_copy_spec([
                    "/var/log/syslog",
                    "/var/log/syslog.1",
                    "/var/log/syslog.2*",
                    "/var/log/kern.log",
                    "/var/log/kern.log.1",
                    "/var/log/kern.log.2*",
                    "/var/log/auth.log",
                    "/var/log/auth.log.1",
                    "/var/log/auth.log.2*",
                ])
            else:
                self.add_copy_spec([
                    "/var/log/syslog*",
                    "/var/log/kern.log*",
                    "/var/log/auth.log*",
                ])
```

I'd forgotten that historically the Debian/Ubuntu version of the Logs plugin tries to collect *everything* in the `--all-logs` case.

**Comment by al3jandrosg** [comment]
Indeed, version sosreport 3.9-1ubuntu0.16.04.2 already does it the way you mentioned

**Comment by al3jandrosg** [comment]
We got sidetracked here because of the issue that motivated the request. 

But resuming the start of the discussion, it may be still worth considering adding a `--exclude-files` option to prevent `sosreport` from collecting arbitrary files.
