### ISSUE TITLE
Redundant setting predicate in add_cmd_output ?

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#2204]
Reviewing a code, I think that

https://github.com/sosreport/sos/blob/master/sos/report/plugins/__init__.py#L1656-L1657

is redundant, due to

https://github.com/sosreport/sos/blob/master/sos/report/plugins/__init__.py#L1577

assuming `pred` can be `None`. And indeed, https://github.com/sosreport/sos/blob/master/sos/report/plugins/__init__.py#L1570-L1573 calls `self._add_cmd_output` without `pred` set, and it works well. But looking down to https://github.com/sosreport/sos/blob/master/sos/report/plugins/__init__.py#L768 , I start to feel `None` will be returned after the two lines removal, hence all cmds with no predicate would fail..?

(but still in that case, I would feel the setting dummy predicate on L1656-L1657 as redundant - test None predicate should pass, not fail, no?)

**Comment by jcastill** [comment]
@pmoravec is this issue still relevant?

**Comment by pmoravec** [comment]
Code references are not further valid :( The issue was rather theoretical and could bring a subtle speedup and nothing else - let close it for now.
