### ISSUE TITLE
Scope Discussion: new info|help component

### ISSUE THREAD

**Issue by TurboTurtle** [sosreport/sos#2205]
Now that 4.0 has closed, I'd like to prioritize one of the components that slipped from the release.

First is there a preference for either `sos info` or `sos help`? Or should we alias one to the other like we do with `clean|mask`?

Second, let's nail down the desired output. What I'm imagining for the use case here is an end use wants details on a specific plugin - such as expected collections, details on plugin options, etc... A rough template could be like:

```
Kernel Plugin Info - <short_desc>

<some longer description here - perhaps use docstrings?>

The following plugin options are available:
    with-timer            <short desc from option tuple>        <default value>
            <longer detailed description>
    [...other plugin options...]

This plugin is expected to collect the following output:

    commands:
        <list of add_cmd_output() calls>

    files:
       <list of add_copy_spec() specs>

```

This raises a few questions to me:

1. Should we use docstrings for the long description, or another class attr?
2. How should we handle longer plugin option descriptions? Extend the tuple, or perhaps make plugin options a distinct class for easier/better manipulation?
3. Do we just grok the plugin for a_c_o and a_c_s calls, or do we run the plugin in dry run mode to account for iterative collections over interfaces? On that note, do we actually want to list all individual files being collected by a_c_s, or just the high level specs that may include globs or dirs? Do we even _want_ this output?
4. Would it be beneficial to add a method ala `help_output()` to `Plugin` that allows plugin authors to manually control output formatting and content?

For reference, my initial thoughts are:

1. Docstrings
2. Make it a class
3. grok both, but have an option to dry run commands to get all iterations across interfaces
4. I think such a method should _extend_ the help output, not override, if we add one. I say this, but then I think of how bloated the `openshift` plugin will be using defaults like the above, in which case an override would be better.

Third, what kind of command invocation should be used here. Do we interpret bare strings, or make some kind of template? E.G. `sos info|help kernel` vs. `sos info|help plugins.kernel` vs `sos info|help --plugin kernel`. 

With the first, we may run into conflicts, e.g. `sos info|help ubuntu` - does this refer to the plugin or the policy? Do we even want to provide help output for policies? Does `sos info|help ovirt` refer to the plugin or the cluster profile for `collect`?

I'm just trying to brainstorm here before we dive wholesale into development of this component, so please provide any and all comments or concerns.

**Comment by pmoravec** [comment]
> For reference, my initial thoughts are:
> 
>     1. Docstrings
> 
>     2. Make it a class
> 
>     3. grok both, but have an option to dry run commands to get all iterations across interfaces
> 
>     4. I think such a method should _extend_ the help output, not override, if we add one. I say this, but then I think of how bloated the `openshift` plugin will be using defaults like the above, in which case an override would be better.

ACK to all, no preference to plugopts (point 2.).

> Third, what kind of command invocation should be used here. Do we interpret bare strings, or make some kind of template? E.G. `sos info|help kernel` vs. `sos info|help plugins.kernel` vs `sos info|help --plugin kernel`.

If we wanted to cover `info|help` also for something else than `sos-report` plugins, the generic classes must be very .. well, generic. Since neither policy or `collect` knows plugopts or a_c_o or a_c_s .

**Comment by BryanQuigley** [comment]
We already have multiple ways to specify I want to focus on plugins, -o, -n, etc.  I also know some customers have wanted to know a list of everything collected from all the enabled plugins. 

Instead of a base component, thoughts on making it an extra paramater to list?  ala: sos report -o kernel -l --verbose? This tracks with what --verbose on an actual run does as well, but is certainly less discoverable than it's own component.

1) Docstrings
2) Do we need longer plugin option descriptions? I feel most don't require that much today. Any examples?
3) I wouldn't try to do a dry-run. Some plugins depend on other commands running, so it's more accurate to just show what commands or collections can occur.
4) I'd like to pursue the ability to show more than 1 plugin in the output, which I think wouldn't work with this.

**Comment by TurboTurtle** [comment]
> We already have multiple ways to specify I want to focus on plugins, -o, -n, etc. I also know some customers have wanted to know a list of everything collected from all the enabled plugins.
>
> Instead of a base component, thoughts on making it an extra paramater to list? ala: sos report -o kernel -l --verbose? This tracks with what --verbose on an actual run does as well, but is certainly less discoverable than it's own component.
> 
I don't think that'll fit in well with the rest of the project. What if a user wants info on a policy (like the default upload location)? Or a `collect` profile (what plugin options does this profile use)? A `clean|mask` parser? Some other component we add in some future release?

Having it as a separate component allows for far easier extension.

There's also integration points to consider. We could change `collect` over from parsing `-l` output on the remote nodes to getting something like `sos info --enabled-plugins --output=json` and loading that directly (or at least, moreso) rather than having to grok the entirety of `-l`. For that matter, we also wouldn't be instantiating all the bits that go with `report` that don't necessarily need to be present to get that information.

> 1. Docstrings
> 2. Do we need longer plugin option descriptions? I feel most don't require that much today. Any examples?
My thought here is that the longer descriptions would also have context hints, so perhaps 'description' was the wrong word here. Plugin option help parameters?

An example from the OpenShift plugin:

`        ('add-namespaces', ('colon-delimited list of namespaces to add to the '
         'default collections'), 'fast', '')`

A longer bit would be something like

```
Use this option to provide an additional set of namespaces/projects that exist within the OCP cluster that you want to collect information for (see below for resources collected from each namespace).

This may be a single value, or a colon delimited list of values. Values must be strings and may be python-style regexes to specify multiple namespaces at once.

The OpenShift plugin collects significant output from each namespace, so expect noticeably longer runtimes for the plugin if specifying more than a few additional namespaces here.

Note that the default collection is all openshift-* named resources.
```

> 3. I wouldn't try to do a dry-run. Some plugins depend on other commands running, so it's more accurate to just show what commands or collections can occur.
> 4. I'd like to pursue the ability to show more than 1 plugin in the output, which I think wouldn't work with this.

I don't see why not? Any `help_output()` or similar method would simply be called at the end of generating help output on a per-plugin basis. This should definitely be something that can be iterated over multiple specified plugins.

**Comment by BryanQuigley** [comment]
> What if a user wants info on a policy (like the default upload location)?

Right now (correct me if I'm wrong) those kinds of defaults could just be provided in bin/sos --help.  There is no reason to query other policies at this time.

> Or a collect profile (what plugin options does this profile use)?
This would just be: sos report -p identity  -l --verbose

>Having it as a separate component allows for far easier extension.
I agree with this, and I may be thinking to report specific.

2)  Understood, +1 to your proposal on this.
3) We can just saw commands will invoke starting with these options or similar. 
4) Oh, I guess what I'm thinking is a combined list of commands/files if you select multiple plugins.
