### ISSUE TITLE
Could not initialize 'report': dictionary keys changed during iteration

### ISSUE THREAD

**Issue by slashdd** [sosreport/sos#2206]
In the attempt to package sos in Debian/Ubuntu, I keep facing this situation.
Could it be a py3.8 incompatibility or something ?
 
```
sos report -a --debug
Could not initialize 'report': dictionary keys changed during iteration
```

```
Traceback (most recent call last):
  File "/usr/bin/sos", line 21, in <module>
    sos = SoS(sys.argv[1:])
  File "/usr/lib/python3/dist-packages/sos/__init__.py", line 121, in __init__
    self._init_component()
  File "/usr/lib/python3/dist-packages/sos/__init__.py", line 181, in _init_component
    raise err
  File "/usr/lib/python3/dist-packages/sos/__init__.py", line 176, in _init_component
    self._component = _to_load(self.parser, self.args, self.cmdline)
  File "/usr/lib/python3/dist-packages/sos/report/__init__.py", line 120, in __init__
    super(SoSReport, self).__init__(parser, args, cmdline)
  File "/usr/lib/python3/dist-packages/sos/component.py", line 86, in __init__
    self.opts = self.load_options()
  File "/usr/lib/python3/dist-packages/sos/component.py", line 208, in load_options
    opts.update_from_conf(self.args.config_file, self.args.component)
  File "/usr/lib/python3/dist-packages/sos/options.py", line 222, in update_from_conf
    _update_from_section("global", config)
  File "/usr/lib/python3/dist-packages/sos/options.py", line 189, in _update_from_section
    for key in odict.keys():
RuntimeError: dictionary keys changed during iteration
```

**Comment by slashdd** [comment]
It seems to do the trick here:

`/usr/lib/python3/dist-packages/sos/options.py`
```
                - for key in odict.keys():
                + for key in list(odict):
```

**Comment by TurboTurtle** [comment]
Interesting. I get this behavior on F32 (python-3.8) but not on F31 (python-3.7) - so it's definitely a change there, but what I don't understand is how this went undetected when we've been testing on 3.8 via travis for a while now.

Easy enough of a fix, though this does raise some confidence concerns for me with our current Travis tests.

**Comment by slashdd** [comment]
Would it be better to  `import collections` then

`/usr/lib/python3/dist-packages/sos/options.py:185`
```
-                odict = collections.OrderedDict(config.items(section))
+                odict = dict(config.items(section))
```

?

**Comment by TurboTurtle** [comment]
I think `list(odict)` would be best here - `OrderedDict.keys()` also returns a view, like `dict.keys()` does. The difference being:

```python
>>> o = OrderedDict()
>>> o['foo'] = 'bar'
>>> o.keys()
odict_keys(['foo'])


>>> d = {'foo': 'bar'}
>>> d.keys()
dict_keys(['foo'])
```

Though I have no basis for this aside from paranoia stemming from the `dict_keys()` view change, there's nothing to suggest the `odict_keys()` view won't change as well.

`list(dict)` is effectively just shorthand for `list(dict.keys())` anyways, so let's go with that.

**Comment by slashdd** [comment]
doing it now.

**Comment by slashdd** [comment]
@TurboTurtle would it be worth a releasing a maintenance release including this fix since this could be a major blocker for those who want to run sos 4.0.
