### ISSUE TITLE
"password" field collected from NetworkManager system-connection file

### ISSUE THREAD

**Issue by arossbell** [sosreport/sos#2220]
Received sosreport from customer with a file under `/etc/NetworkManager/system-connections/`having a "password" value collected. Block with identifiable information omitted:
```
...
[802-1x]
altsubject-matches=
eap=peap;
identity=<username omitted from issue report>
password=<cleartext password omitted from issue report>
phase2-altsubject-matches=
phase2-auth=mschapv2
...
```
It appears that [there is filtering for "psk,"](https://github.com/sosreport/sos/blob/88dc5f9d0af635a95fcda366299d3e40d00a0680/sos/report/plugins/networkmanager.py#L112) but not for the "password" value in a block like above.

**Comment by TurboTurtle** [comment]
Thanks for the report. At first glance it should be easy to extend the existing postproc. I'll make a note to look into this this coming Monday.
