### ISSUE TITLE
Collect or integrate dbinfo.sh for s390x support

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#2228]
Debugging IBM z systems relies on a tool similar to `sos report`: [dbginfo.sh](https://github.com/ibm-s390-tools/s390-tools/blob/master/scripts/dbginfo.sh). For at least Red Hat support, it would be beneficial to have the tool somehow integrated into `sos report`, such that collecting debugging information from a z system requires to run just one tool.

My current proposal is to create a new plugin enabled by presence of `s390-tools` package, that will call `dbginfo.sh` script and collect the generated tarball. That will allow support engineers to call just `sos report` and get all data in one tarball, though with some data duplicated.

From a longer term perspective, or as a step 2, it would make sense to implement `dbginfo.sh` into `sosreport` natively, likewise we did so with [foreman-debug](https://github.com/sosreport/sos/pull/1525). This requires an agreement with the tool's upstream community.

Cc @hoeppnerj and @julianwiedmann from `s390-tools`.

**Comment by TurboTurtle** [comment]
Looking over the script, there is a _lot_ of overlap of information that sos already collects. I know we've previously carried calling an external script while porting it to sos, but in this case I'd suggest we go straight to step 2; find out what the script collects today that sos doesn't, and put those bits only into plugin(s).

But +1 for integrating another collection script.

**Comment by julianwiedmann** [comment]
cc @sa-liu

**Comment by TurboTurtle** [comment]
I've been looking at this again, and the non-z/VM changes are actually quite small in size. I have a draft commit available that adds those commands to existing plugins, and then adds a `zvm` plugin for those commands. However, the `zvm` plugin is entirely structured around my understanding of the dbginfo script, which may not be fully accurate.

I have not yet found a test s390 system for testing the z/VM plugin. I'm going to continue to dig on that, but in the meantime if such a system is available to any other contributor, please take a look at this draft plugin, try to run it, and let me know if changes  need to be made.


https://github.com/sosreport/sos/compare/master...TurboTurtle:integrate-s390x-dbginfo

**Comment by julianwiedmann** [comment]
> I have not yet found a test s390 system for testing the z/VM plugin. I'm going to continue to dig on that, but in the meantime if such a system is available to any other contributor, please take a look at this draft plugin, try to run it, and let me know if changes need to be made.
> 

Sorry, missed this. Note that https://developer.ibm.com/gettingstarted/ibm-linuxone/ offers free access to Linux VMs running on z/VM.
