### ISSUE TITLE
Quoting for container commands seems to be broken for `docker` runtime

### ISSUE THREAD

**Issue by nicolasbock** [sosreport/sos#2231]
The call to [`fmt_container_cmd`](https://github.com/sosreport/sos/blob/master/sos/report/plugins/rabbitmq.py#L37) quotes the command including the whitespace between `rabbitmqctl` and `report` which breaks the `docker exec` command. The quoted command is:
```
docker exec  rabbitmq-container 'rabbitmqctl report'
```

Running this command from the commandline results in the following:
```
$ docker exec  rabbitmq-container 'rabbitmqctl report'
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"rabbitmqctl report\": executable file not found in $PATH": unknown
```

According to upstream docker docs quotes are not supported for the `exec` command [[1]](https://docs.docker.com/engine/reference/commandline/exec/#extended-description).

**Comment by TurboTurtle** [comment]
Looking into this on the podman side, it looks to be similar. However, on older versions I do see quoting working (oddly, intermittently).

I think the best way to address this would be to make the default to not quote but have an option to enable quoting - if for no other reason than being ready in the event of new container runtimes that use or even want quoting.

**Comment by nicolasbock** [comment]
Thanks. I'll see if I can change it.

**Comment by nicolasbock** [comment]
Please have a look at #2232 @TurboTurtle . I hope I caught all of the places where the extra `quote` parameter are needed.

Thanks for the hint!
