### ISSUE TITLE
[clean] hostname doesn't get fully obfuscate inside a clean tarball.

### ISSUE THREAD

**Issue by slashdd** [sosreport/sos#2236]
- lvmdump file and content still reveal the "real" hostname.
- process plugins command line still reveal the "real" hostname

**Focal/20.04LTS with upstream code**
**lvmdump**
```
# cat sosreport-host0-2020-09-16-pijduqq/sos_commands/lvm2/lvmdump_-d_.tmp.sos.4q7xacpx.sosreport-nuc7-2020-09-16-pijduqq.sos_commands.lvm2.lvmdump
Creating dump directory: /tmp/sos.4q7xacpx/sosreport-nuc7-2020-09-16-pijduqq/sos_commands/lvm2/lvmdump
 
Gathering LVM & device-mapper version info...
Gathering dmsetup info...
Gathering process info...
Gathering console messages...
Gathering /etc/lvm info...
Gathering /dev listing...
Gathering /sys/block listing...
```

```
sos_commands/process/ps_axo_flags_state_uid_pid_ppid_pgid_sid_cls_pri_addr_sz_wchan_20_lstart_tty_time_cmd:
4 S   122     830       1     830     830  TS  19    -  2182 poll_schedule_timeou Fri Sep 11 16:21:36 2020 ?        00:00:15 avahi-daemon: running [nuc7.local]
sos_commands/process/ps_axo_flags_state_uid_pid_ppid_pgid_sid_cls_pri_addr_sz_wchan_20_lstart_tty_time_cmd:
0 S     0  859271  850144  859271  850144  TS  19    - 36470 futex_wait_queue_me  Wed Sep 16 21:55:16 2020 pts/0    00:02:49 /usr/bin/python3 /usr/bin/sos clean /tmp/sosreport-nuc7-2020-09-16-pijduqq.tar.xz
```

**Comment by TurboTurtle** [comment]
For the first two, `lvmdump` and the first result from `ps axo`, it looks like we're skipping the file for some reason. If I ramp up the verbosity, I can see the log message for obfuscating everything in the `lvmdump` _directory_, but not the file containing the output of the command. Similarly, I don't see an obfuscation message for that specific `ps` command output, but everything else is read normally. I'm not immediately sure why this is.

As for the last one, I must be missing something. Did you collect an sosreport while that `sos clean` command was running? How did the `ps` output file get in the archive that includes an invocation of `sos clean`, which wouldn't have written any new ps data to the archive?

**Comment by slashdd** [comment]
The `sos clean `output in ps is because my machine was running another instance of `sos clean `simultaneously while running `sos report`.

Please ignore the following:
```
sos_commands/process/ps_axo_flags_state_uid_pid_ppid_pgid_sid_cls_pri_addr_sz_wchan_20_lstart_tty_time_cmd:
0 S     0  859271  850144  859271  850144  TS  19    - 36470 futex_wait_queue_me  Wed Sep 16 21:55:16 2020 pts/0    00:02:49 /usr/bin/python3 /usr/bin/sos clean /tmp/sosreport-nuc7-2020-09-16-pijduqq.tar.xz
```

Sorry for the confusion.

**Comment by slashdd** [comment]
Nevertheless, it should have caught the occurrence of the "real" hostname in the output.

**Comment by TurboTurtle** [comment]
Right, definitely the same issue - the file is being skipped for some reason. I just was a bit confused on the context of how it got there.

**Comment by TurboTurtle** [comment]
Found the issue, at least for the `lvmdump` command. It is getting skipped due to the fact that the tarball name appears _twice_ in the filepath, and we are currently splitting on the tarball name to get the filepath within the archive.

The `ps axo` files being skipped is....well, I can't help but laugh. It's getting skipped because it is hitting our don't-match-tarballs regex is ever so slightly too vague on the matching of the `tar` bit.

Easy enough fixes. I'll have something up tomorrow for this.

**Comment by slashdd** [comment]
@TurboTurtle thanks
