### ISSUE TITLE
[snappy] proposal to rename the plugin from 'snappy' to 'snap'

### ISSUE THREAD

**Issue by slashdd** [sosreport/sos#2243]
'snappy' is not a term that is often use (in our day-to-day support and by Canonical customer).
IMHO, it would be more appropriate to rename the plugin to 'snap'.

@BryanQuigley, @mvo5 thought ?

**Comment by slashdd** [comment]
@arif-ali thought ?

**Comment by arif-ali** [comment]
I'd agree, everything else within the plugin is `snap` or `snapd`. Also it is more generally recognised as `snap` in the wider community.
