### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by BryanQuigley** [sosreport/sos#2250]
I totally forgot about the website at http://sosreport.github.io/sos/
It's built from the gh-pages branch.  (Btw, can we clean up older branches?)

I have two thoughts on this: 
* Just Kill it.  We've go the wiki and readthedocs. (Likely could make it a redirect, etc)
* Update it, enable HTTPS and look at moving readthedocs content there.

**Comment by pmoravec** [comment]
I am in small fovour of killing it completely (do we have some stats about the visits of the page?). If we would decide to remain it, +1 for some automatic uploads of some doc content there.

**Comment by TurboTurtle** [comment]
I'd be in favor of killing it off as well.

**Comment by BryanQuigley** [comment]
Traffic stats are available from the main github repo pages (https://github.com/sosreport/sos/graphs/traffic)

Referring sites
Site 	Views 	Unique visitors
Google 	127 	97
bugzilla.redhat.com bugzilla.redhat.com 	66 	19
github.com 	49 	30
man.linuxde.net man.linuxde.net 	23 	1
people.canonical.com people.canonical.com 	15 	2
bugs.launchpad.net bugs.launchpad.net 	13 	1
sos.readthedocs.io sos.readthedocs.io 	7 	6
mail.google.com mail.google.com 	7 	2
m.facebook.com m.facebook.com 	7 	1
jira.astralinux.ru jira.astralinux.ru 	3 	3


I am unsure if http://sosreport.github.io/sos/ counts as internal Github links or not, but have made 3 more unique views since this morning.  I'll plan to work on making it a simple redirect at first and then fully kill it some time later.

**Comment by BryanQuigley** [comment]
And sosreport.github.io now has 4 hits indicating I believe nobody usually goes there (or at least finds the actual github site from it).

**Comment by BryanQuigley** [comment]
Since we don't see any activity from it I've gone ahead and killed the branch - which is apparently the easiest way to disable Github pages.
