### ISSUE TITLE
[oVirt] Collect ovirt-imageio configuration

### ISSUE THREAD

**Issue by jorti** [sosreport/sos#2260]
The oVirt imageio proxy configuration is not collected. It's located in `/etc/ovirt-imageio` in recent versions. Previously it was in `/etc/ovirt-imageio-proxy`

**Comment by pmoravec** [comment]
Asking rather for a sanity check as a ovirt noob: Can't be there some secret (i.e. password or similar) or some SSL keys or some potentially huge file (that would be truncated, either way, but..) in either dir?

**Comment by jorti** [comment]
No, It only has what certificate files the service uses. As it needs a plain-text certificate key, there's no passwords stored here.

**Comment by TurboTurtle** [comment]
We do have `Plugin.do_file_private_sub()` to scrub certificate contents. It'll end up leaving something like this in place:

```
-----SCRUBBED RSA PRIVATE KEY-----
```

**Comment by pmoravec** [comment]
> No, It only has what certificate files the service uses. As it needs a plain-text certificate key, there's no passwords stored here.

So does it contain some certificate worth to be obfuscated (e.g. by the method Jake suggested)? Or just a list of certs is printed there?

As you filed a PR: will you propose a PR or shall/can I ? Either works for me, just want to ensure one PR will be prepared.

**Comment by jorti** [comment]
There's no sensitive data, it just has the list of certificate files that the service uses.

I've closed the previous PR as it was not correct. I'll submit a new one
