### ISSUE TITLE
[pulp] Get dynaconf list into pulp plugin debug

### ISSUE THREAD

**Issue by sjha4** [sosreport/sos#2266]
We need to add the below command to pulp debug output.
**sudo -u pulp PULP_SETTINGS='/etc/pulp/settings.py' DJANGO_SETTINGS_MODULE='pulpcore.app.settings' dynaconf list**

**Comment by ekohl** [comment]
Note that this is really Pulp 3. I don't know if there will be a distinction between Pulp 2 and Pulp 3 in sosreport.

For understanding: the name pulpcore was chosen so Pulp 4 can be released on the same codebase. Pulp 3 plugins are named pulp-$myplugin (pulp-rpm, pulp-deb, etc).

Pulp 2 and Pulp 3 can live in parallel on the same system.

The settings can contain a `SECRET_KEY` and also a database password.

**Comment by pmoravec** [comment]
I think it is safe to collect it on pulp-2 (where I think `dynaconf` isnt even installed, hence the output will be empty and wont appear in sosreport, even).

Currently, `pulp` plugin in `sos` is enabled by presence of either `pulp-server` or `pulp-katello` package (https://github.com/sosreport/sos/blob/master/sos/report/plugins/pulp.py#L21). I guess pulp 3 does contain either such package, thus `pulp` plugin will be enabled on a `pulp 3` server by default?

Re obfuscation of sensitive data: could you please provide example output including a `SECRET_KEY` and also a database password, so we can build a r.e. to scrub it? Just the two pieces of data to obfuscate?

**Comment by ekohl** [comment]
> I guess pulp 3 does contain either such package, thus `pulp` plugin will be enabled on a `pulp 3` server by default?

I think `python3-pulpcore` is currently the closest. I know their Ansible based installer can also install using pip rather than RPMs but I don't touch that. From a Foreman perspective we always deal with packages.

**Comment by pmoravec** [comment]
OK, that will need to be added to `packages` list.

Reviewing code of `pulp` plugin, a lot of stuff is `pulp-2`-only related, I think - I will need to review this. But still it makes sense to keep one plugin for `pulp-2` and `pulp-3`.

Pls. provide the examples of data to obfuscate, such that I can prepare a PR for this.

**Comment by ekohl** [comment]
@sjha4 could you take a look at the data and what to obfuscate?

**Comment by sjha4** [comment]
@ekohl , @pmoravec 
So the secret key and Database password live in the /etc/pulp/settings.py file which looks like this:
https://gist.github.com/sjha4/a2630d5c43d150bebb69cfb1780fdb44

**Comment by ekohl** [comment]
How is that content different than `/etc/pulp/settings.py` (`PULP_SETTINGS`)?

**Comment by sjha4** [comment]
@ekohl : It's the same file..

**Comment by sjha4** [comment]
The dynfloa list o/p looks like this:
https://gist.github.com/sjha4/1fc64d6a8ce5f338d6d3dcf8ac37a01b 

It has the same secret_key and db password fields in the o/p

**Comment by pmoravec** [comment]
Thanks for the feedback. Since there is still big overlap in pulp-2 and pulp-3 wrt. what sosreport collects, it makes sense to enhance `pulp` plugin accordingly. So the plugin will newly:

- be automatically enabled by presence of `python3-pulpcore` package (`pulp-3` is `python3`-only based? no further `python2`? I will doublecheck..)
- collect `sudo -u pulp PULP_SETTINGS='/etc/pulp/settings.py' DJANGO_SETTINGS_MODULE='pulpcore.app.settings' dynaconf list`
- the cmdoutput will be stored in `sos_commands/pulp/dynaconf_list` (more human readable name than `sudo_-u_pulp_..` one)
- in the output, below stuff will be obfuscated:

    SECRET_KEY = *******
    'PASSWORD': *******

- let me know if `/etc/pulp/settings.py` (a python script?) should be also collected (not in my plans, atm) and if the format to obfuscate there differs

**Comment by ekohl** [comment]
If the migration plugin is installed, there can also be a `"password": "..."` secret as well:
https://github.com/theforeman/puppet-pulpcore/blob/66591673a988e2b9c12a8b2c7ae06416eb1422d6/templates/migration-settings.py.erb#L8

**Comment by pmoravec** [comment]
Thanks, PR updated to reflect both lower and uppercase.
