### ISSUE TITLE
Stratis - Include new output for key-description, engine report, and cli version

### ISSUE THREAD

**Issue by drckeefe** [sosreport/sos#2273]
In the plugin stratis.py (sos/report/plugins/stratis.py.)
Stratis (https://github.com/stratis-storage/), version 2.1.0 has a new pool encryption feature and report of the engine state, which should be added to sos.    
The new additions to the stratis.py file should be:

"stratis key list"  - collect a list of key descriptions 
"stratis report engine_state_report" - collect the current state of Stratis' engine

Also, the version of the cli should be added.

"stratis --version"  - collect the version of stratis-cli

**Comment by drckeefe** [comment]
Opened BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1888012

**Comment by TurboTurtle** [comment]
Can definitely add these. One question, for `stratis key list` is there any iteration we should be doing to get detailed information for each key listed?

**Comment by drckeefe** [comment]
@TurboTurtle not at this time.  We only need stratis key list output.
