### ISSUE TITLE
better formatting of cmdline option error

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#2285]
Two issues spotted in scenario:

    # python3 bin/sos report --all-logs=on
    usage: sos report [options]
    sos <component> [options]
    
    Available components:
    	report, rep                   Collect files and command output in an archive
    	clean, cleaner, mask          Obfuscate sensitive networking information in a report
    	collect, collector            Collect an sos report from multiple nodes simultaneously report: error: argument --all-logs: ignored explicit argument 'on'

- the formatting lacks newlines before "`report: error: ..`" (or ideally print just the `report error` but not the usage? as clearly we used proper component?)
- I think we should support "`on/off/yes/no`" to enable/disable cmdline options, likewise we do in config file

**Comment by TurboTurtle** [comment]
Hmm. This is strange since the loop that builds the "Available components" bit has a trailing newline:

```python
        for com in self._components:
            aliases = self._components[com][1]
            aliases.insert(0, com)
            _com = ', '.join(aliases)
            desc = self._components[com][0].desc
            _com_string += (
                "\t{com:<30}{desc}\n".format(com=_com, desc=desc)
            )
        usage_string = ("%(prog)s <component> [options]\n\n"
                        "Available components:\n")
        usage_string = usage_string + _com_string
```

Add a quick test of adding more newlines shows no difference in the error output. Perhaps this is a bug in `argparse` directly? Would need to dig some more.

As for on/off/no/yes, absolutely +1 from me.

**Comment by TurboTurtle** [comment]
I've not been able to make any headway on this, so I'm going to be opening an upstream python bug report.

**Comment by pmoravec** [comment]
The #2301 fixes the formatting issue. To allow "--all-logs=on", my understanding of `argparse` let me found:

    --- a/sos/report/__init__.py
    +++ b/sos/report/__init__.py
    @@ -177,6 +177,9 @@ class SoSReport(SoSComponent):
     
         @classmethod
         def add_parser_options(cls, parser):
    +        def valueToBool(val):
    +            return (val in ("on", "yes"))
    +
             report_grp = parser.add_argument_group(
                 'Report Options',
                 'These options control how report collects data'
    @@ -184,8 +187,8 @@ class SoSReport(SoSComponent):
             report_grp.add_argument("-a", "--alloptions", action="store_true",
                                     dest="alloptions", default=False,
                                     help="enable all options for loaded plugins")
    -        report_grp.add_argument("--all-logs", action="store_true",
    -                                dest="all_logs", default=False,
    +        report_grp.add_argument("--all-logs", type=valueToBool, nargs='?',
    +                                const=True, dest="all_logs", default=False,
                                     help="collect all available logs regardless "
                                          "of size")
             report_grp.add_argument("--since", action="store",

This works well for use cases: 
- (no `--all-logs` option)
- `--all-logs`
- `--all-logs=yes`
- `--all-logs=qux`  # or anything else as `yes`/`on` will disable the option - not ideal, I think..

Is it sufficient good enhancement? Worth adding to (all?) other options like `-a`, `--batch` etc. (that have `action="store_true"`)?

**Comment by TurboTurtle** [comment]
I think a cleaner approach would be to do what we do with list options [1], by registering it as a new action in the parser [2] (and subparsers) so that any boolean option like this going forward just needs to use `action=foo`.

[1] https://github.com/sosreport/sos/blob/master/sos/options.py#L311-L319
[2] https://github.com/sosreport/sos/blob/61096436ad9e5ff4c36b6a3a0626038e95e5269f/sos/__init__.py#L99
