### ISSUE TITLE
[report] drop bzip2 from suggested compression_methods

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#2286]
Reviewing a code, and being aware of `bzip2` compression method dropped in #2053, I found we still can suggest using this method in an error log:

https://github.com/sosreport/sos/blob/master/sos/report/__init__.py#L815

Anyway, what is the reason for the whole test https://github.com/sosreport/sos/blob/master/sos/report/__init__.py#L817 , if `self.opts.compression_type` can have a value from https://github.com/sosreport/sos/blob/master/sos/__init__.py#L154 , only?

Am I right the whole `if` block is now redundant?

**Comment by TurboTurtle** [comment]
Yeah, the entire block is effectively dead-code now. Let's drop it.
