### ISSUE TITLE
[rhui] prevent calling of hardcoded binary `python`

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#2287]
As some distributions dont have `python` binary but `python2`/`python3` and similar only, running `rhui-debug` from `rhui` plugin will fail:

https://github.com/sosreport/sos/blob/master/sos/report/plugins/rhui.py#L36

Currently, as far as I know, there are no solid plans to migrate RHUI to python3, which makes this plugin currently obsolete for `sos report`.

I suggest dropping this plugin now, and in case / once RHUI become working on platforms that `sos` supports, we can add the plugin back (while I expect quite different content, ideally natively implemented debug tool).

**Comment by TurboTurtle** [comment]
I'd agree with dropping the plugin if it won't be brought forward for py3 compatibility. Like you said, we can always bring it back new-and-improved if things change.
