### ISSUE TITLE
"effective options now" to log valid variants of cmdline options

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#2288]
effective options now: --batch --build --log-size 100 --only-plugins host --plugopts apache.log=on -vvv

But:

    sosreport --batch --build --log-size 100 --only-plugins host --plugopts apache.log=on -vvv
    ..
    sosreport: error: unrecognized arguments: --plugopts apache.log=on

Not sure if some other option is affected the same.

**Comment by bmr-cymru** [comment]
Awkward. __Most__ of our long option names map directly to the `dest` value used in `add_argument()` calls, but this is one that doesn't. The bug has existed for quite a long time. We can either bring the `dest` values into sync with the long options or introduce another mapping layer in `to_args()` to fix up the mismatches.

**Comment by TurboTurtle** [comment]
Any opposition to instead add `--plugopts` as a valid long form name, perhaps eventually deprecating the existing `--plugin-option` for it?

**Comment by pmoravec** [comment]
ACK to either/both.

**Comment by bmr-cymru** [comment]
No preference for which way it's resolved, but the intent of logging the message in `--command-line --notation` was that it should be possible to copy & paste from the logs to a new command line - so long as they are consistent and that works I am fine with whichever option names are chosen.

**Comment by pmoravec** [comment]
Same issue is `--no-report` that is printed as `effective options now: --noreport`. Here, `s/noreport/no-report/g` in `./sos/report/__init__.py` does the fix.

Since we print cmdline options based on ther `dest` where we replace `_` by `-` (https://github.com/sosreport/sos/blob/master/sos/options.py#L298), I spot few other options affected the same - listing all of them with my suggestions:

- `--plugin-option` / `plugopts` (no preference)
- `--no-report` / `noreport` (`dest=no_report`)
- `--profile` / `profiles` (`--profiles`, as it can be a list)
- `--skip-commands` / `skip_cmds` (`dest=skip_commands`)
- `--map` / `map_file` (`--map-file` to be more specific in option name)
