### ISSUE TITLE
wiki is a little outdated

### ISSUE THREAD

**Issue by april4** [sosreport/sos#2290]
such as "https://github.com/sosreport/sos/wiki/How-to-Write-a-Plugin"
by look "https://github.com/sosreport/sos/blob/master/tests/plugin_tests.py", found that
`from sos.plugins import ...` has already become `from sos.report.plugins import ...`

**Comment by TurboTurtle** [comment]
Yeah, this has been on the to-do list for a while now. I'll try and get it updated (along with a few other articles on the wiki) this month.

**Comment by BryanQuigley** [comment]
first pass at updating done.. still needs work though...

**Comment by TurboTurtle** [comment]
I have further updated the wiki article for writing plugins. @april4 please let us know if there are further questions, concerns, or any additional clarity needed.

**Comment by TurboTurtle** [comment]
I've cleaned up a bit more, the last item on my list is to clean up the `How to write a Policy` page. After that, the wiki should be sufficiently up to date.

**Comment by TurboTurtle** [comment]
I've updated the Policy wiki page now as well given the recent changes to tree layout for policies. With that, I believe this is now satisfied and the wiki is sufficiently current.
