### ISSUE TITLE
report skips hidden files

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#2296]
User story: `ovirt` plugin collects `/etc/pki/ovirt-engine/` directory via https://github.com/sosreport/sos/blob/master/sos/report/plugins/ovirt.py#L145, but does not collect `/etc/pki/ovirt-engine/.truststore`. The cause is that sos report skips all hidden files (until explicitly mentioned), as `glob.glob()` skips them in:

https://github.com/sosreport/sos/blob/master/sos/report/plugins/__init__.py#L2423

This is intentional behaviour of `glob` method, per the bottom example at https://docs.python.org/3/library/glob.html .

The question is: should sosreport collect *all* hidden files? Doing so, can't we start collecting too many potential secrets? Or should we collect hidden files only when explicitly mentioned, like now (and enhance `ovirt` plugin accordingly)?

**Comment by pmoravec** [comment]
When re-thinking on the topic, I think the default behaviour here should be *not* collecting hidden files by default / until explicitly requested via e.g. `add_copy_spec`. The hidden files are intended to be .. well.. hidden :) with more natural way to contain very random confidential data we should not collect by default.

**Comment by TurboTurtle** [comment]
Yeah, the behavior as-is is preferable to me. If we absolutely need hidden files, we should explicitly list them.
