### ISSUE TITLE
[packit] Packit failing RPM builds

### ISSUE THREAD

**Issue by TurboTurtle** [sosreport/sos#2318]
I saw that packit was set for the wrong repo in the sosreport org, and moved it over earlier today. First PR to trigger it however resulted in a failed build [1].

It looks like the issue is that copr is generating a bunch of locale files, though at first glance I'm not entirely sure why that is [2]. Doing manual builds via `rpmbuild -bs sos.spec` and `rpmbuild -bb sos.spec` doesn't generate those files.

@dhodovsk or @sandrobonazzola  any suggestions? I only see one real difference in our specfile and the Fedora specfile, which I don't think would be significant here

```
%files -f %{name}.lang
vs
%files
```

[1] https://copr.fedorainfracloud.org/coprs/packit/sosreport-sos-2317/build/1779472/
[2] https://download.copr.fedorainfracloud.org/results/packit/sosreport-sos-2317/fedora-rawhide-x86_64/01779472-sos/builder-live.log.gz

**Comment by pmoravec** [comment]
I did to the same conclusion and mimicking the commands from the failing `copr` build, I was able to reproduce locally. Adding the lang files to `%files` does prevent the `/usr/lib/rpm/check-files` error.

Raising PR for this change.
