### ISSUE TITLE
[RFC] Threading Plugin.collect()?

### ISSUE THREAD

**Issue by TurboTurtle** [sosreport/sos#2327]
We've had threading in the form of "run several plugins concurrently" for some time now. I'm curious what the thoughts are to extending this to `Plugin.collect()`? The historical design of plugins already lends itself to this very well - `setup()` populates lists of files and commands to collect, which would be trivial to feed into `ThreadPoolExecutor`s.

Obviously this would only be a tangible benefit to the largest of plugins - `networking`, `openshift`, `logs`, several `openstack_*`, etc... so I imagine this would be an opt-in feature for individual plugins.

The main benefit would be reducing our total runtime on large systems, and in so doing sidestepping potential timeout issues. The drawback though could be fairly large - CPU and memory requirements could likely spike. For the `logs` plugin for example, imagine running 4 `journalctl` commands concurrently that each require size limiting. We go from one thread taking up to 100MB of memory (200MB briefly when `AsyncReader.get_contents()` is called) to E.G. four threads taking up a combined 400 MB (800MB in `get_contents()`), plus the CPU overhead.

The work would be easy, the questions are - is it safe? Is it worth while even if it is safe?

**Comment by pmoravec** [comment]
What we could gain by multi-threading `collect` method of a plugin, if that is a part of multi-threaded `collect_plugin` method? If there are spare CPUs, isnt it easier to run `sos report --threads 20`?

**Comment by TurboTurtle** [comment]
Each plugin run by `collect_plugin()` is still single-threaded in its own right. This would make the change such that each plugin (that opts-in to this design) is itself multi-threaded, in addition to sos running multiple plugins concurrently. `sos report --threads 20` would just increase the number of plugins run concurrently, not how fast each of those plugins is collected.

For example, in the `networking` plugin let's say we have 100 commands queued from `setup()`. Today, we run each of those serially, one after the other. With this proposal we'd run up to `--threads` commands concurrently, while we're _also_ running X number of other plugins as well. This would significantly speed up collection times for the `networking` plugin. It also has the added benefit that a single long-running command would no longer cause the entire rest of the plugin to be skipped if a timeout is hit during that long-running command.

**Comment by BryanQuigley** [comment]
As a first pass, we could just look at seeing if we can find the bottlenecks in the plugins that cause timeouts more - many of them we could seriously consider splitting up.  

On my desktop system at timeout 2 seconds: apt, logs, systemd all timeout.
At 1 second cgroups, date (just the once..), kernel, networking, processor are added to the above.

It would be good to get some idea from a bigger machine as well - and what specific commands are taking the longest.

**Comment by TurboTurtle** [comment]
> As a first pass, we could just look at seeing if we can find the bottlenecks in the plugins that cause timeouts more - many of them we could seriously consider splitting up.
> 

I don't think splitting up the plugins would be the answer here, at least not for the use case I'm talking about. For example, the `networking` and `openshift` plugins' runtime doesn't come from a few individual long running commands - it comes from having potentially _hundreds_ of iterations of several commands otherwise quick-to-collect commands. Splitting up `networking` for say, namespace-specific collection loops, seems like it'd create a lot of extra maintenance overhead.

> On my desktop system at timeout 2 seconds: apt, logs, systemd all timeout.
> At 1 second cgroups, date (just the once..), kernel, networking, processor are added to the above.
> 
> It would be good to get some idea from a bigger machine as well - and what specific commands are taking the longest.

These kind plugin runtimes sound more aligned to #1585 than threading `collect` in my mind.

**Comment by BryanQuigley** [comment]
I have not looked closely at the openshift plugin before now. Assuming I understand correctly - I wonder if it would make more sense as part of the "collect" component?  That would allow it to prompt for the login information - and it really is a getting all info for a cluster.

For networking it certainly can still create a lot of items that can be looped over, but for networking the most obvious one to separate out IMHO is iptables/firewall bits.

**Comment by TurboTurtle** [comment]
> I have not looked closely at the openshift plugin before now. Assuming I understand correctly - I wonder if it would make more sense as part of the "collect" component? That would allow it to prompt for the login information - and it really is a getting all info for a cluster.
> 

The cluster information is coming from the Openshift API, which is shared among the master nodes. `sos collect` is focused on collecting sosreports from multiple nodes, and isn't (currently) designed for collecting API information like that. The `collect` integration here would be to extend the existing cluster profile to OCP4 and then ensuring the API data is only retrieved from one node. That way we get host information from each system, and API data from the master.

> For networking it certainly can still create a lot of items that can be looped over, but for networking the most obvious one to separate out IMHO is iptables/firewall bits.

The following was actually what I was thinking of when I thought about hundreds of commands being queued during `setup()` for certain environments:

```python
        for namespace in self.get_network_namespaces(
                            self.get_option("namespace_pattern"),
                            self.get_option("namespaces")):
            ns_cmd_prefix = cmd_prefix + namespace + " "
            self.add_cmd_output([
                ns_cmd_prefix + "ip address show",
                ns_cmd_prefix + "ip route show table all",
                ns_cmd_prefix + "ip -s -s neigh show",
                ns_cmd_prefix + "ip rule list",
                ns_cmd_prefix + "iptables-save",
                ns_cmd_prefix + "ip6tables-save",
                ns_cmd_prefix + "netstat %s -neopa" % self.ns_wide,
                ns_cmd_prefix + "netstat -s",
                ns_cmd_prefix + "netstat %s -agn" % self.ns_wide,
            ])
```
...and then add the `ethtool` collections on a per-namespace basis. Right now that adds up to 15 extra commands per namespace. For environments that make decent use of networking namespaces (OpenStack for example) that can add up rather quickly.

It wouldn't really make sense to split this out (splitting out firewall collection is interesting though and warrants another discussion). Granted, the environments where this becomes a concern are not a majority of where sos is used.

**Comment by TurboTurtle** [comment]
Closing this for now, if more plugins start building huge lists of commands to execute in the future we can revisit this possibility.
