### ISSUE TITLE
subscription-manager plugin inserts ******** into rhsm.conf on new line if password unset

### ISSUE THREAD

**Issue by dmd** [sosreport/sos#2328]
https://github.com/sosreport/sos/blob/3fddddf8ea14436afdffadfb679411e03bf1ec61/sos/report/plugins/subscription_manager.py#L48

Suppose your rhsm.conf proxy_password looks like this (including context):

```
# user name for authenticating to an http proxy, if needed
proxy_user =

# password for basic http proxy auth, if needed
proxy_password =

# host/domain suffix blacklist for proxy, if needed
no_proxy =
```

Then in the saved output, it will look like this:

```
# user name for authenticating to an http proxy, if needed
proxy_user =

# password for basic http proxy auth, if needed
proxy_password =

 ********
no_proxy =
```

Note it also removed the comment line before `no_proxy = `.

**Comment by pmoravec** [comment]
Good catch, PR proposed.
