### ISSUE TITLE
"sos collect --help" to warn it is unavailable when pyexpect package missing

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#2336]
When `python3-pexpect` is not installed, `sos collect --help` does not warn the subcommand is unavailable. We should provide that info and be consistent with e.g.:

    # python3 bin/sos --help
    usage: sos <component> [options]
    
    Available components:
	    report, rep                   Collect files and command output in an archive
    	    clean, cleaner, mask          Obfuscate sensitive networking information in a report
	    collect                       (unavailable) Collect an sos report from multiple nodes

**Comment by TurboTurtle** [comment]
Should be easy enough to add/override `parser.epilog` for this.
