### ISSUE TITLE
RFE: collect TigerVNC configuration files

### ISSUE THREAD

**Issue by yuokada126** [sosreport/sos#2347]
Recent `tigervnc-server` package contains 3 configuration files under `/etc/tigervnc`, which are not contained before.

- Fedora 33
```
$ rpm -q tigervnc-server
tigervnc-server-1.11.0-8.fc33.x86_64
$ rpm -ql tigervnc-server | grep /etc/tigervnc
/etc/tigervnc/vncserver-config-defaults
/etc/tigervnc/vncserver-config-mandatory
/etc/tigervnc/vncserver.users
```
- RHEL 8.3
```
$ rpm -q tigervnc-server
tigervnc-server-1.10.1-7.el8.x86_64
$ rpm -ql tigervnc-server | grep /etc/tigervnc
/etc/tigervnc/vncserver-config-defaults
/etc/tigervnc/vncserver-config-mandatory
/etc/tigervnc/vncserver.users
```

It would be helpful if sosreport gathers these files.

**Comment by yuokada126** [comment]
Currently, there seems to be no vnc plugin. If I want to add the feature, should I add a new vnc plugin which only gathers 3 configuration files? (I'm new to sos community, and just reading through the Contribution-Guidelines and How-to-Write-a-Plugin pages.)

**Comment by pmoravec** [comment]
I would vote for `tigervnc` plugin, as there can be different `VNC` servers with different commands/files to collect. I recommend taking some small plugin like e.g. https://github.com/sosreport/sos/blob/master/sos/report/plugins/frr.py, copy&modify it for your use (and for a PR :) ).
