### ISSUE TITLE
Add a plugin to collect bcache perf stats

### ISSUE THREAD

**Issue by pponnuvel** [sosreport/sos#2378]
Collecting perf stats on bcache [0] [1] is useful to identify performance problems if they're deployed as a caching layer.
Useful stats are:

- `/sys/block/bcache*/bcache/{cache_mode,dirty_data,io_errors,sequential_cutoff,state,writeback_percent,stats_hour/{bypassed,cache_{hit_ratio,hits,misses}},cache/internal/copy_gc_enabled}`

- `/sys/fs/bcache/*/{block_size,bucket_size,cache_available_percent,congested_*_threshold_us}`

- `/sys/fs/bcache/*/{*,stats_*/*,internal/*,bdev*/*,bdev*/stat_*/*}`

I plan to work on adding a new plugin to collect these.

[0] https://wiki.archlinux.org/index.php/bcache
[1] https://bcache.evilpiepirate.org/

**Comment by hillpd** [comment]
This data would definitely be useful. 

Be mindful of lp#1840043 [0]. It is an older issue where stat collection can severely impact system performance. The plug-in may need to check and prevent stat collection for exposed kernels.

[0] https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1840043

**Comment by bmr-cymru** [comment]
Executing the stat collection can be gated by a predicate - we just need the right criteria for when to exclude the collection. The `SoSPredicate` supports various checks that are used to determine whether or not a command should run.

**Comment by pponnuvel** [comment]
@hillpd Thanks, Dan, for the note. `priority_stats` isn't in the list of the stats I planned to collect on bcache (which degrades performance when queried). So we're OK.

**Comment by pponnuvel** [comment]
@bmr-cymru It'd be useful if bcache are deployed as a caching device. I am thinking of `IndependentPlugin` with `files` set one of the sysfs entry something like as: 

https://github.com/sosreport/sos/commit/b6a7a8158111ee55ad6f471d5cd577a39b256e45

(I haven't tested it yet - will make a PR after test).
