### ISSUE TITLE
sosreport error in cockpit -- No module named 'sos.presets'

### ISSUE THREAD

**Issue by fluxcap1** [sosreport/sos#2390]
I can't get sos to work with cockpit-199 - 

````
Please note the 'sosreport' command has been deprecated in favor of the new 'sos' command, E.G. 'sos report'.
Redirecting to 'sos report --batch'
Traceback (most recent call last):
  File "/usr/bin/sosreport", line 32, in <module>
    sos = SoS(args)
  File "/usr/lib/python3.6/site-packages/sos/__init__.py", line 60, in __init__
    import sos.report
  File "/usr/lib/python3.6/site-packages/sos/report/__init__.py", line 30, in <module>
    import sos.policies
  File "/usr/lib/python3.6/site-packages/sos/policies/__init__.py", line 10, in <module>
    from sos.presets import (NO_PRESET, GENERIC_PRESETS, PRESETS_PATH,
ModuleNotFoundError: No module named 'sos.presets'
````
Please help.

**Comment by bmr-cymru** [comment]
Cockpit will need to be updated to work with the new module layout and interfaces in sos-4.0. In the meantime you can use an older version or the legacy-3.9 branch from upstream.

**Comment by fluxcap1** [comment]
> Cockpit will need to be updated to work with the new module layout and interfaces in sos-4.0. In the meantime you can use an older version or the legacy-3.9 branch from upstream.

Okay, I will get 3.9 and report. Thank you.

**Comment by TurboTurtle** [comment]
Actually, I believe this may be due to another issue - the presets packages aren't referenced in `setup.py`, so if one uses that for generating a source tarball for packaging, presets won't be included. I have something in the works for this momentarily.

**Comment by fluxcap1** [comment]
Thanks, TurboTurtle. I upgraded glibc & systemd on Leap and compiled cockpit-232, it works somewhat. SUSE_Leap_15.3 will have glibc-2.31 and systemd-246, please make a dedicated sosreport branch for SUSE.

**Comment by TurboTurtle** [comment]
@fluxcap1 we don't have distro-specific branches for sos. If what you need is SUSE to ship an updated rpm for sos, you'd need to open a bug with them for that. While several of the downstream packagers for sos are in fact contributors and/or maintainers for the upstream repo, the project doesn't have any direct involvement there. I'm not sure who does the packaging for SUSE for sos, or if they're just rebuilding RHEL srpms like Oracle does.

**Comment by fluxcap1** [comment]
> @fluxcap1 we don't have distro-specific branches for sos. If what you need is SUSE to ship an updated rpm for sos, you'd need to open a bug with them for that. While several of the downstream packagers for sos are in fact contributors and/or maintainers for the upstream repo, the project doesn't have any direct involvement there. I'm not sure who does the packaging for SUSE for sos, or if they're just rebuilding RHEL srpms like Oracle does.

They are rebuilding RHEL srpms. Leap 15.3 has an updated systemd and glibc. I will build it today and report back.
