### ISSUE TITLE
[report] pulp and apache plugins both collect /var/log/httpd/pulp* logfiles

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#2413]
See https://github.com/sosreport/sos/blob/master/sos/report/plugins/pulp.py#L70-L75 and https://github.com/sosreport/sos/blob/master/sos/report/plugins/apache.py#L82-L84 (which can be enabled by `satellite` preset that contains `-k apache.log=on`).

A straightforward patch would be to extend `forbidden_path` on https://github.com/sosreport/sos/blob/master/sos/report/plugins/apache.py#L34 also to `pulp*`. More solid options could be:

- reconsider if `-k apache.log=on` in `satellite` preset is required (I would say so, to ensure various changing-in-time logfiles are collected without a need to update e.g. `foreman` package too regularly)
- allow feature "multiple plugins can copy the same file independently" (with respect to different sizelimits etc., not simple request)

I lean to the first straighforward option, but if there is a different opinion, let me know.

**Comment by pmoravec** [comment]
Usually, the current state *just* means we copy the `/var/log/httpd/pulp*` files once but sometimes twice:

    sos_strings/apache/var.log.httpd.pulp-https_access_ssl.log.tailed
    sos_strings/pulp/var.log.httpd.pulp-https_access_ssl.log.tailed

and in a very specific use case when the file size exceeds sizelimit exactly between `apache` and `pulp` plugins collect it, we get the "Path .. exists and is not a regular file" like in #1596.

**Comment by TurboTurtle** [comment]
I agree, let's extend the forbidden_path in `apache` to include pulp logs.

I think any potential change for multiple plugins specifying the same file warrants a very thorough discussion and would be a change we need to make very carefully. So for now, we can use the forbidden_path approach and later if we decide to add this feature it's a simple update.
