### ISSUE TITLE
ovn_central timeout on non-leader host

### ISSUE THREAD

**Issue by dosaboy** [sosreport/sos#2418]
When running the ovn_central plugin on a non-leader host the sbctl command hangs indefinitely until the sosreport 300s timeout kicks in. We can fix this by doing e.g. "ovn-sbctl -t 5 show".

**Comment by TurboTurtle** [comment]
Is there a straight forward way of identifying a host as a leader or non-leader? If so, we can instead just gate the leader-only commands in the plugin.

**Comment by dosaboy** [comment]
Im not sure yet, both leader and non-leader have ovsdb-server listening on /var/run/ovn/ovnsb_db.sock which is what the command reads and hangs on because the db doesn't respond. I think there might be a better way though, checking now.

**Comment by dosaboy** [comment]
Ok found it:

# ovs-appctl -t /var/run/ovn/ovnsb_db.ctl cluster/status OVN_Southbound| grep "Leader: self"
Leader: self

If you don't get that you are not the leader.

**Comment by dosaboy** [comment]
@TurboTurtle do you have an example of how you would normally gate a plugin in sosreport?

**Comment by dosaboy** [comment]
ah I guess you use SoSPredicate()

**Comment by pmoravec** [comment]
Yes, `SoSPredicate`, like e.g. https://github.com/sosreport/sos/blob/master/sos/report/plugins/grub2.py#L38-L42

**Comment by dosaboy** [comment]
@pmoravec thanks!
