### ISSUE TITLE
[foreman] separate foreman-proxy to a new plugin

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#2423]
Split foreman plugin into `foreman` and `foreman-proxy`.

While every `foreman` instance is deployed with its integrated `foreman-proxy`, there are external proxies (smart proxy / Capsule) where executing most of `foreman` plugin content is redundant (i.e. most of postgres stuff). Possible negative outcome apart of the redundant commands to be executed on an external proxy: see #2421. Therefore we should split the plugin into two.

I plan to prepare the PR in next weeks.

**Comment by pmoravec** [comment]
I hit an ambiguity problem:

- files should be collected by exactly one plugin
- SmartProxy has various `/var/log/foreman-installer/` or `/var/log/httpd/*` or `/etc/foreman-installer/*` files, i.e. `foreman-proxy` plugin must collect these
- hence `foreman` plugin itself shouldn't collect them
- BUT `foreman` itself does log to the same files and use the same installer configs that we can very hardly separate between the plugins

We can move all of these logs and configs to `foreman-proxy` plugin only, but we risk a user running `sos report -o foreman` woudl lack those important stuff.

Is that an acceptable cons of the split?

**Comment by pmoravec** [comment]
OK, a draft PR proposed, with the notice above applicable.

Some review from @ekohl or @jjansky1 is welcomed.

**Comment by ekohl** [comment]
Does it make sense to introduce a foreman-installer plugin as well to deal with that ambiguity? Within the platform team we've been talking about a standalone scenario for the external PostgreSQL server. Then there is neither Foreman nor Foreman Proxy but understanding the installation when it fails can be useful.
