### ISSUE TITLE
[foreman] smart_proxies should exclude non-primary interface ip

### ISSUE THREAD

**Issue by matt8754** [sosreport/sos#2424]
select sp.name, sp.url,  sp.download_policy,n.ip from smart_proxies as sp left join hosts as h on h.name=sp.name left join nics as n on n.host_id=h.id;
                 name                 |                        url                        | download_policy |       ip
--------------------------------------+---------------------------------------------------+-----------------+-----------------
satellite.example.com      | https://satellite.anzlab.bne.redhat.com:9090      | on_demand       | 192.168.254.248
 satellite.example.com      | https://satellite.anzlab.bne.redhat.com:9090      | on_demand       | 10.1.2.3

Here we have two records for this Satellite server. People might think there are duplicate smart proxies entries and cause further confusion..

**Comment by matt8754** [comment]
The related code:

https://github.com/sosreport/sos/blob/master/sos/report/plugins/foreman.py#L228

**Comment by pmoravec** [comment]
So adding ` where n.primary = true` to the query will be a resolution?

Are we sure each and every smart proxy must have primary NIC? (otherwise we might skip some smart proxies)

**Comment by matt8754** [comment]
> So adding ` where n.primary = true` to the query will be a resolution?
> 
> Are we sure each and every smart proxy must have primary NIC? (otherwise we might skip some smart proxies)

In most cases, it should. Unless people modify the interfaces later on. However, I never see this happen in a real life, :-)

**Comment by matt8754** [comment]
Not sure why we need to collect capsule's ip here  since it does not really tell which ip is the real one. If we really need to do that, it might be better to just ping each capsule? I can see we already do that for the satellite server. For example,

[mjia@supportshell foreman]
cat ping_-c1_-W1_capsule.examle.com
PING clspcoykhsc-v-cv (10.136.246.1) 56(84) bytes of data.

**Comment by pmoravec** [comment]
Good point, just knowledge of smart proxy IP addresses sounds useless. Not sure if "ping proxy" is valuable for some debugging - if something, then

    curl --key /etc/foreman/client_key.pem --cert /etc/foreman/client_cert.pem --connect-timeout=5 --max-time=20 https://smart-proxy007.example.com:9090/v2/features

rather? This will test rather application level of the proxy than just TCP/IP connectivity. Some timeouts with rule-of-thumb values suggested, timeout of `add_cmd_output` can be used as well. Pros: testing connectivity&liveness of each proxy and list of features that can matter (i.e. for REX/DNS/provisioning issues), negs: it adds extra nontrivial time to `foreman` plugin (there are instances with 20+ smart proxies, a `curl` usually takes 0.2s or more).

My preference is either to skip the IP, or optionally get list of features of all smart proxies.

The original request came from https://github.com/sosreport/sos/issues/1972, cc @waldirio for opinion.

**Comment by matt8754** [comment]
Thanks Pavel. I would +1 for skipping IP and introducing a new IP for collection features if required.
