### ISSUE TITLE
[openshift] sosreport replaces /usr from current container with the one from the initial debug container

### ISSUE THREAD

**Issue by travier** [sosreport/sos#2436]
This issue was initially reported in https://bugzilla.redhat.com/show_bug.cgi?id=1915537. Feel free to take over that BZ or assign it to the correct team.

This is my current understanding of the issue and may not be exactly what's happening.

# Current behavior

sosreport, when run from a toolbox container spawned from a oc debug node/xyz -> chroot /host container, will over mount `/usr` from the initial debug container in the current container, thus altering the toolbox container.

# Expected behavior

sosreport reads information from /host from current container or performs mount point changes in a sub mount namespace to avoid altering the current container filesystem mounts.

# Impacted version

Non exhaustive list of versions where this is happening: 3.8 and 3.9.1

**Comment by TurboTurtle** [comment]
sos does not do any mounting on its own. The behavior of chrooting to `/host` comes from reading env variables set in the container, and is based on the `support-tools` image. I am not sure if this is the same image used by `oc debug`, however as I am also the maintainer of the `support-tools` image I can tell you that that container image also does not do any mounting of `/usr`. That container only mounts `/run` from the host into the container, and the host's `/` to `/host`, which we then use to chroot all collections to.

As an aside, when using the `support-tools` image, there is no need to manually chroot into `/host` - sos is designed to detect it is in a container and act accordingly to get diagnostic output from the host.


If `/usr` is being mounted over-top, then that is coming either from `oc`, the image being launched for `oc debug` if it is not `support-tools`, or elsewhere - but nothing in sos directly does any kind of changes to mount locations.

**Comment by travier** [comment]
In our case this is a little bit weirder. The setup is:
`oc debug node/...` -> spawns an `openshift/tools` container that does not include `sosreport`-> `chroot /host` (no `sosreport` here either) -> `toolbox` -> spawns an `registry.redhat.io/rhel8/support-tools` container via podman that includes `sosreport`.

And after doing all that, I realized that this is most likely not an sosreport issue at all as I can reproduce without running sosreport 😅 .

Sorry for the noise and thanks for the help!
