### ISSUE TITLE
[clean][mask] User obfuscation for ubuntu user

### ISSUE THREAD

**Issue by slashdd** [sosreport/sos#2454]
I found a corner case for when run inside container (lxd). The default UID for the ubuntu user is 1000 in our images.

obsfucation is based on` sos_commands/login/lastlog_-u_1000-60000
`
mapping file:
```
    "keyword_map": {},
    "username_map": {
        "ubuntu": "obfuscateduser0"
    }

```
This is creating a mapping as shown above ^ and generate unwanted obfuscation all across the sosreport collection.

**Comment by slashdd** [comment]
while we want to catch 1000 in certain situation. Maybe we could generate a ignore_list ?

**Comment by TurboTurtle** [comment]
Nice catch - yeah we can add it to the `skip_list` here - https://github.com/sosreport/sos/blob/master/sos/cleaner/parsers/username_parser.py#L30
