### ISSUE TITLE
Is sos4.1 tested for ARM64 and POWERPC architecture ?

### ISSUE THREAD

**Issue by slashdd** [sosreport/sos#2456]
Is 4.1 tested against arm64 and PowerPC ? 

In Ubuntu simple.sh reveals the following for both arches:

```
### end stdout
### start extraction
### stop extraction
######### DONE WITH --mask #########
!!! TEST FAILED: IP address not obfuscated in all places !!!
grep: /tmp/sosreport/_test/*: No such file or directory


Summary
 
 failures false 	 time 2 	 Size 0.00MiB 	 List plugins 
 failures false 	 time 3 	 Size 0.00MiB 	 List presets 
 failures false 	 time 3 	 Size 0.00MiB 	 List profiles 
 failures false 	 time 7 	 Size 0.00MiB 	 --build -t1 -o host,kernel,filesys,hardware,date,logs 
 failures false 	 time 26 	 Size 2.40MiB 	 -vvv 
 failures false 	 time 23 	 Size 2.41MiB 	 -e opencl -v -k kernel.with-timer,libraries.ldconfigv --no-postproc 
 failures false 	 time 4 	 Size 5.63KiB 	 --no-report --label TEST -o hardware 
 failures false 	 time 21 	 Size 2.87MiB 	 --log-size 0 --no-env-vars -z gzip 
 failures true 	 time 63 	 Size 2.26MiB 	 --mask

Tests Failed: 1
Failures within each test:

 	 test_mask: 		 IP address not obfuscated in all places
autopkgtest [18:05:57]: test simple.sh: -----------------------]
autopkgtest [18:05:59]: test simple.sh:  - - - - - - - - - - results - - - - - - - - - -
simple.sh            FAIL non-zero exit status 1
autopkgtest [18:05:59]: @@@@@@@@@@@@@@@@@@@@ summary
simple.sh            FAIL non-zero exit status 1
Exit request sent.
```

Full output:
https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-hirsute/hirsute/ppc64el/s/sosreport/20210322_180613_b5ca9@/log.gz

https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-hirsute/hirsute/arm64/s/sosreport/20210322_180956_ceb1e@/log.gz

I don't easily have access to such HW to test by myself.

It works fine for under s390 and amd64

**Comment by TurboTurtle** [comment]
Not since moving to GCE, that was the trade-off we made - we now have direct control over the test VMs, their config, etc.. but we're limited to x86 until GCE offers other arches.

As for those test failures, I'm not sure what would be causing that. The test is failing because the `grep` command hits an error, rather than an IP address being discovered - but the path it seems to be looking for doesn't make sense. `simple.sh` forces the use of `/var/tmp` for the temp directory, whereas that `grep` command is looking where a "normal" sos run on Ubuntu would result in a tarball. But further then that, it's looking inside a `_test` subdir, which `simple.sh` doesn't specify (we extract to `/var/tmp/sosreport_test`, not `/var/tmp/sosreport/_test`.

**Comment by arif-ali** [comment]
I've just tested sos 4.1 in hirsute, where @slashdd is having issues.

I have installed hirsute daily in an LXD container on an arm64 device, and I have not got this issue on arm64. I will test again tomorrow on a native arm64 installation on my arm device, and will report back

**Comment by slashdd** [comment]
> Not since moving to GCE, that was the trade-off we made - we now have direct control over the test VMs, their config, etc.. but we're limited to x86 until GCE offers other arches.
> 
> As for those test failures, I'm not sure what would be causing that. The test is failing because the `grep` command hits an error, rather than an IP address being discovered - but the path it seems to be looking for doesn't make sense. `simple.sh` forces the use of `/var/tmp` for the temp directory, whereas that `grep` command is looking where a "normal" sos run on Ubuntu would result in a tarball. But further then that, it's looking inside a `_test` subdir, which `simple.sh` doesn't specify (we extract to `/var/tmp/sosreport_test`, not `/var/tmp/sosreport/_test`.

I have modify simple.sh to use /tmp in the autopkgtest of Ubuntu to avoid confusion between /tmp and /var/tmp, since our systemd implementation doesn't have tmpfiles.d cleaning under /var/tmp.

**Comment by slashdd** [comment]
> I've just tested sos 4.1 in hirsute, where @slashdd is having issues.
> 
> I have installed hirsute daily in an LXD container on an arm64 device, and I have not got this issue on arm64. I will test again tomorrow on a native arm64 installation on my arm device, and will report back

Thanks keep me posted, please.

**Comment by slashdd** [comment]
The `sosreport_test` vs `_test` is just a typo in the echo command inside the if statement. Look like a red herring to me
https://github.com/sosreport/sos/blob/master/tests/simple.sh#L174

Let's see @arif-ali 's testing outcome.

**Comment by slashdd** [comment]
I retried the test several time and it finally work on ppc64el. Maybe it was the autopkgtest infra. I'll re-run arm64 a couple more time and see.

`autopkgtest for sosreport/4.1-1ubuntu1: amd64: Pass, arm64: Regression ♻ , armhf: No test results, ppc64el: Pass, s390x: Pass
`

**Comment by slashdd** [comment]
Closing issue since @TurboTurtle answered my questions.
