### ISSUE TITLE
ibmkvm policies effectiveness?

### ISSUE THREAD

**Issue by BryanQuigley** [sosreport/sos#2470]
Aside from showing an IBM specific support link (but it's been broken for a while), I'm not sure what purpose the ibmkvm distro policies actually do today - namely after the changes to IndependentPlugin.  If it's properly marked as based on RHEL it should do the *right thing* based on the existing distro policies.

**Comment by BryanQuigley** [comment]
@kamalesh-babulal  thoughts?

**Comment by TurboTurtle** [comment]
Yeah I don't know if it's been useful for a while now that you bring it up. No objections to drop it from me (potentially ZKVM as well?), but I'll try and reach out to some IBM folks to get more feedback on it.

**Comment by hegdevasant** [comment]
We created `ibmkvm` policy when we created initial PowerKVM project (few year ago). Now that all support is integrated into  distro , it may be OK to drop this support.

I will poke around internally and get back to you,

zKVM : I don't know the story around zKVM. I will try to check.

-Vasant

**Comment by kamalesh-babulal** [comment]
@BryanQuigley Sorry for the delayed response, I was out of office for a week. I will let @hegdevasant to get back with response. Vasant Thank you.

**Comment by hegdevasant** [comment]
@BryanQuigley I had contacted various folks in Power and Z side. Based on our internal discussion we think its safe to remove ibmkvm policies.

-Vasant

**Comment by TurboTurtle** [comment]
@hegdevasant one more consideration - I'm working on porting `dbginfo.sh` for #2228. Most of what it collects is already in sos, with the exception of the z/VM commands, which are easily added in a new plugin. If we port dbginfo.sh, does that change anything?

If no, ack to removing.

**Comment by hegdevasant** [comment]
@TurboTurtle 

> @hegdevasant one more consideration - I'm working on porting `dbginfo.sh` for #2228. Most of what it collects is already in sos, with the exception of the z/VM commands, which are easily added in a new plugin. If we port dbginfo.sh, does that change anything?

Sorry. I don't know about z/VM side. I have forwarded this request to system z folks . Will let you know once I get response from them.

-Vasant

**Comment by mihajlov** [comment]
The KVM for IBM z product was discontinued, so there's no impact to current or future sos activities.
