### ISSUE TITLE
[ubuntu][upload] --upload doesn't work on 4.1

### ISSUE THREAD

**Issue by slashdd** [sosreport/sos#2472]
Leaving this here as a reminder for future analysis, when my time will permit.
Meanwhile, any comment are welcome.

```
root@hsosh:~# sos report -o ubuntu --upload

sosreport (version 4.1)

This command will collect system configuration and diagnostic
information from this Ubuntu system.

For more information on Canonical visit:

        Community Website  : https://www.ubuntu.com/
        Commercial Support : https://www.canonical.com

The generated archive may contain data considered sensitive and its
content should be reviewed by the originating organization before being
passed to any third party.

No changes will be made to system configuration.


Press ENTER to continue, or CTRL-C to quit.

Please enter the case id that you are generating this report for []: 
Traceback (most recent call last):
  File "/usr/bin/sos", line 22, in <module>
    sos.execute()
  File "/usr/lib/python3/dist-packages/sos/__init__.py", line 186, in execute
    self._component.execute()
  File "/usr/lib/python3/dist-packages/sos/report/__init__.py", line 1372, in execute
    self.prework()
  File "/usr/lib/python3/dist-packages/sos/report/__init__.py", line 857, in prework
    self.policy.pre_work()
  File "/usr/lib/python3/dist-packages/sos/policies/distros/__init__.py", line 163, in pre_work
    if cmdline_opts.upload and self.get_upload_url():
  File "/usr/lib/python3/dist-packages/sos/policies/distros/ubuntu.py", line 77, in get_upload_url
    fname = os.path.basename(self.upload_archive)
  File "/usr/lib/python3.9/posixpath.py", line 142, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not method
```

**Comment by TurboTurtle** [comment]
Taking a quick look it seems we're clobbering `upload_archive` (ironically _in_ the `Policy.upload_archive()` method).

This gets hit on Ubuntu because `get_upload_url()` for that policy is trying to leverage the name of the archive-to-be-uploaded, which only gets set when `Policy.upload_archive()` is called, and `get_upload_url()` is called before that as a sanity check to make sure we even _can_ upload for a given policy.

The root issue here is that `get_upload_url()` is called in `Policy.pre_work()` so that we can properly prompt users for upload credentials. Ubuntu's `get_upload_url()` is relying on the archive name being available, but the name is only set at the beginning of `Policy.upload_archive()` by way of `Report.final_work()` which is where the archive name is generated/finalized. 

The following would fix the clobbering issue at least, but wouldn't address the chicken-and-egg problem for needing the archive name in `get_upload_url()`:

```
diff --git a/sos/policies/distros/__init__.py b/sos/policies/distros/__init__.py
index 022ba7f4..53c36bd3 100644
--- a/sos/policies/distros/__init__.py
+++ b/sos/policies/distros/__init__.py
@@ -237,7 +237,7 @@ class LinuxPolicy(Policy):
         `get_upload_url_string()`
             Print a more human-friendly string than vendor URLs
         """
-        self.upload_archive = archive
+        self.upload_archive_name = archive
         if not self.upload_url:
             self.upload_url = self.get_upload_url()
         if not self.upload_url:
@@ -384,7 +384,7 @@ class LinuxPolicy(Policy):
             raise Exception("Unable to upload due to missing python requests "
                             "library")
 
-        with open(self.upload_archive, 'rb') as arc:
+        with open(self.upload_archive_name, 'rb') as arc:
             if not self._use_https_streaming:
                 r = self._upload_https_no_stream(arc)
             else:
@@ -467,9 +467,9 @@ class LinuxPolicy(Policy):
                             % str(err))
 
         try:
-            with open(self.upload_archive, 'rb') as _arcfile:
+            with open(self.upload_archive_name, 'rb') as _arcfile:
                 session.storbinary(
-                    "STOR %s" % self.upload_archive.split('/')[-1],
+                    "STOR %s" % self.upload_archive_name.split('/')[-1],
                     _arcfile
                 )
             session.quit()
diff --git a/sos/policies/distros/ubuntu.py b/sos/policies/distros/ubuntu.py
index 94a4a241..a81fe806 100644
--- a/sos/policies/distros/ubuntu.py
+++ b/sos/policies/distros/ubuntu.py
@@ -74,7 +74,7 @@ class UbuntuPolicy(DebianPolicy):
 
     def get_upload_url(self):
         if not self.upload_url or self.upload_url.startswith(self._upload_url):
-            fname = os.path.basename(self.upload_archive)
+            fname = os.path.basename(self.upload_archive_name)
             return self._upload_url + fname
         super(UbuntuPolicy, self).get_upload_url()
```

**Comment by TurboTurtle** [comment]
@slashdd Just a thought, since we call `get_upload_url()` again when performing the actual upload, I think we could resolve this by:

1. Initializing `self.upload_archive_name()` to a blank string in `Policy.pre_work()` (assuming the change from above to no longer clobber `upload_archive`
2. Adding this to `Ubuntu.get_upload_url()`:

```python
diff --git a/sos/policies/distros/ubuntu.py b/sos/policies/distros/ubuntu.py
index 94a4a241..308c1e35 100644
--- a/sos/policies/distros/ubuntu.py
+++ b/sos/policies/distros/ubuntu.py
@@ -74,7 +74,9 @@ class UbuntuPolicy(DebianPolicy):
 
     def get_upload_url(self):
         if not self.upload_url or self.upload_url.startswith(self._upload_url):
-            fname = os.path.basename(self.upload_archive)
+            if not self.upload_archive_name:
+                return self._upload_url
+            fname = os.path.basename(self.upload_archive_name)
             return self._upload_url + fname
         super(UbuntuPolicy, self).get_upload_url()

```

But I haven't tested this at all. I think this should avoid the traceback though, since the initial call in `pre_work()` would validate that we do in fact have an upload target (the policy default), but we won't try to finalize that upload target with the archive name until that name is set.

**Comment by slashdd** [comment]
> Taking a quick look it seems we're clobbering `upload_archive` (ironically _in_ the `Policy.upload_archive()` method).
> 
> This gets hit on Ubuntu because `get_upload_url()` for that policy is trying to leverage the name of the archive-to-be-uploaded, which only gets set when `Policy.upload_archive()` is called, and `get_upload_url()` is called before that as a sanity check to make sure we even _can_ upload for a given policy.
> 
> The root issue here is that `get_upload_url()` is called in `Policy.pre_work()` so that we can properly prompt users for upload credentials. Ubuntu's `get_upload_url()` is relying on the archive name being available, but the name is only set at the beginning of `Policy.upload_archive()` by way of `Report.final_work()` which is where the archive name is generated/finalized.
> 
> The following would fix the clobbering issue at least, but wouldn't address the chicken-and-egg problem for needing the archive name in `get_upload_url()`:
> 
> ```
> diff --git a/sos/policies/distros/__init__.py b/sos/policies/distros/__init__.py
> index 022ba7f4..53c36bd3 100644
> --- a/sos/policies/distros/__init__.py
> +++ b/sos/policies/distros/__init__.py
> @@ -237,7 +237,7 @@ class LinuxPolicy(Policy):
>          `get_upload_url_string()`
>              Print a more human-friendly string than vendor URLs
>          """
> -        self.upload_archive = archive
> +        self.upload_archive_name = archive
>          if not self.upload_url:
>              self.upload_url = self.get_upload_url()
>          if not self.upload_url:
> @@ -384,7 +384,7 @@ class LinuxPolicy(Policy):
>              raise Exception("Unable to upload due to missing python requests "
>                              "library")
>  
> -        with open(self.upload_archive, 'rb') as arc:
> +        with open(self.upload_archive_name, 'rb') as arc:
>              if not self._use_https_streaming:
>                  r = self._upload_https_no_stream(arc)
>              else:
> @@ -467,9 +467,9 @@ class LinuxPolicy(Policy):
>                              % str(err))
>  
>          try:
> -            with open(self.upload_archive, 'rb') as _arcfile:
> +            with open(self.upload_archive_name, 'rb') as _arcfile:
>                  session.storbinary(
> -                    "STOR %s" % self.upload_archive.split('/')[-1],
> +                    "STOR %s" % self.upload_archive_name.split('/')[-1],
>                      _arcfile
>                  )
>              session.quit()
> diff --git a/sos/policies/distros/ubuntu.py b/sos/policies/distros/ubuntu.py
> index 94a4a241..a81fe806 100644
> --- a/sos/policies/distros/ubuntu.py
> +++ b/sos/policies/distros/ubuntu.py
> @@ -74,7 +74,7 @@ class UbuntuPolicy(DebianPolicy):
>  
>      def get_upload_url(self):
>          if not self.upload_url or self.upload_url.startswith(self._upload_url):
> -            fname = os.path.basename(self.upload_archive)
> +            fname = os.path.basename(self.upload_archive_name)
>              return self._upload_url + fname
>          super(UbuntuPolicy, self).get_upload_url()
> ```

```
python3 ./bin/sos report -o ubuntu --upload

Traceback (most recent call last):
  File "./bin/sos", line 22, in <module>
    sos.execute()
  File "/tmp/sos/sos/sos/__init__.py", line 186, in execute
    self._component.execute()
  File "/tmp/sos/sos/sos/report/__init__.py", line 1375, in execute
    self.prework()
  File "/tmp/sos/sos/sos/report/__init__.py", line 860, in prework
    self.policy.pre_work()
  File "/tmp/sos/sos/sos/policies/distros/__init__.py", line 163, in pre_work
    if cmdline_opts.upload and self.get_upload_url():
  File "/tmp/sos/sos/sos/policies/distros/ubuntu.py", line 77, in get_upload_url
    fname = os.path.basename(self.upload_archive_name)
AttributeError: 'UbuntuPolicy' object has no attribute 'upload_archive_name'

```

**Comment by TurboTurtle** [comment]
Right, we'd need to initialize `upload_archive_name` in `Policy.pre_work()`, e.g.:

```
diff --git a/sos/policies/distros/__init__.py b/sos/policies/distros/__init__.py
index 022ba7f4..87a0f4e3 100644
--- a/sos/policies/distros/__init__.py
+++ b/sos/policies/distros/__init__.py
@@ -149,6 +149,7 @@ class LinuxPolicy(Policy):
         self.upload_user = cmdline_opts.upload_user
         self.upload_directory = cmdline_opts.upload_directory
         self.upload_password = cmdline_opts.upload_pass
+        self.upload_archive_name = ''
 
         if not cmdline_opts.batch and not \
                 cmdline_opts.quiet:

```

**Comment by slashdd** [comment]
The following works as expected:

Thanks.

```
diff --git a/sos/policies/distros/__init__.py b/sos/policies/distros/__init__.py
index 022ba7f4..a24a0e5b 100644
--- a/sos/policies/distros/__init__.py
+++ b/sos/policies/distros/__init__.py
@@ -149,6 +149,7 @@ class LinuxPolicy(Policy):
         self.upload_user = cmdline_opts.upload_user
         self.upload_directory = cmdline_opts.upload_directory
         self.upload_password = cmdline_opts.upload_pass
+        self.upload_archive_name = ''
 
         if not cmdline_opts.batch and not \
                 cmdline_opts.quiet:
@@ -237,7 +238,7 @@ class LinuxPolicy(Policy):
         `get_upload_url_string()`
             Print a more human-friendly string than vendor URLs
         """
-        self.upload_archive = archive
+        self.upload_archive_name = archive
         if not self.upload_url:
             self.upload_url = self.get_upload_url()
         if not self.upload_url:
@@ -384,7 +385,7 @@ class LinuxPolicy(Policy):
             raise Exception("Unable to upload due to missing python requests "
                             "library")
 
-        with open(self.upload_archive, 'rb') as arc:
+        with open(self.upload_archive_name, 'rb') as arc:
             if not self._use_https_streaming:
                 r = self._upload_https_no_stream(arc)
             else:
@@ -467,9 +468,9 @@ class LinuxPolicy(Policy):
                             % str(err))
 
         try:
-            with open(self.upload_archive, 'rb') as _arcfile:
+            with open(self.upload_archive_name, 'rb') as _arcfile:
                 session.storbinary(
-                    "STOR %s" % self.upload_archive.split('/')[-1],
+                    "STOR %s" % self.upload_archive_name.split('/')[-1],
                     _arcfile
                 )
             session.quit()
diff --git a/sos/policies/distros/ubuntu.py b/sos/policies/distros/ubuntu.py
index 94a4a241..308c1e35 100644
--- a/sos/policies/distros/ubuntu.py
+++ b/sos/policies/distros/ubuntu.py
@@ -74,7 +74,9 @@ class UbuntuPolicy(DebianPolicy):
 
     def get_upload_url(self):
         if not self.upload_url or self.upload_url.startswith(self._upload_url):
-            fname = os.path.basename(self.upload_archive)
+            if not self.upload_archive_name:
+                return self._upload_url
+            fname = os.path.basename(self.upload_archive_name)
             return self._upload_url + fname
         super(UbuntuPolicy, self).get_upload_url()
 
```

**Comment by slashdd** [comment]
If you don't mind, I'll let one of you two do the PR, for both of you to get the credit.
