### ISSUE TITLE
[foreman] collect PostgreSQL logs for Satellite 6.8+

### ISSUE THREAD

**Issue by matt8754** [sosreport/sos#2483]
Starting from 6.8+, the postgresql data directory is moved to /var/opt/rh/rh-postgresql12/lib/pgsql. Sosreport should collect this instead.

**Comment by pmoravec** [comment]
This should have been properly implemented in upstream in https://github.com/sosreport/sos/commit/b3fccdd6cf82024820d1caaba81b1aecfa8e5b19 , as well as in legacy-3.9 branch (https://github.com/sosreport/sos/commit/612ccc67233f14447f0a20a19916780f3def673f) for python2 deployments (roughly speaking). If you miss it in a sos report in downstream RHEL (or other distro?), let talk to the downstream maintainers (but I see the most relevant https://bugzilla.redhat.com/show_bug.cgi?id=1897903 as fixed already..?)

**Comment by matt8754** [comment]
> https://bugzilla.redhat.com/show_bug.cgi?id=1897903

Thanks for your quick reply. I'll close this.
