### ISSUE TITLE
 [sos41][sos-collect] "unsupported operand type(s)" error during report generation 

### ISSUE THREAD

**Issue by Gleland** [sosreport/sos#2488]
When trying out the new version (4.1), I get an error during report generation.

Both the remote and local machines are using the latest version of soreport:
```
$ apt-cache policy sosreport
sosreport:
  Installed: 4.1-1ubuntu0.20.04.1
  Candidate: 4.1-1ubuntu0.20.04.1
  Version table:
 *** 4.1-1ubuntu0.20.04.1 500
        500 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     3.9-1ubuntu2 500
        500 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages
```
Both the remote and local machines are using 20.04.2 (from `cat /etc/os-release`)

Here's the full output (node and user have been redacted), including the debug flag:
```
$ sos collect --batch -a --all-logs --clean --nodes $node --ssh-user $user --debug

sos-collector (version 4.1)

This utility is used to collect sosreports from multiple nodes simultaneously.
It uses OpenSSH's ControlPersist feature to connect to nodes and run commands
remotely. If your system installation of OpenSSH is older than 5.6, please
upgrade.

An archive of sosreport tarballs collected from the nodes will be generated in
/tmp/sos.fie0k2xs and may be provided to an appropriate support representative.

The generated archive may contain data considered sensitive and its content
should be reviewed by the originating organization before being passed to any
third party.

No configuration changes will be made to the system running this utility or
remote systems that it connects to.

sos-collector ASSUMES that SSH keys are installed on all nodes unless the
--password option is provided.

Local sos report generation forcibly skipped due to lack of root privileges.
Either use --nopasswd-sudo, run as root, or do not use --batch so that you will be prompted for a password

Cluster type set to Pacemaker High Availability Cluster Manager
Cluster status could not be determined. Is the cluster running on this node?

The following is a list of nodes to collect from:
        $node

Connecting to nodes...

Beginning collection of sosreports from 1 nodes, collecting a maximum of 4 concurrently

$node : Generating sosreport...
[$node:execute_sos_command] Error running sosreport: unsupported operand type(s) for +: 'bool' and 'str'
Error running sosreport: unsupported operand type(s) for +: 'NoneType' and 'str'
No sosreports were collected, nothing to archive...```

**Comment by TurboTurtle** [comment]
Thanks for the report!

Please note, `--debug` is used for enabling an interactive debugger, not for including debug logging.

For debug logs, use `-vvv`. If you could provide those logs, that might get us further.

**Comment by Gleland** [comment]
sure thing! here's [verbose_output.txt](https://github.com/sosreport/sos/files/6305874/verbose_output.txt)

**Comment by TurboTurtle** [comment]
Hrm. Well, I was hoping there'd be more in there but it's a bit sparse. We do at least see that we're at the point where we should be actually spawning the command, but the exception is odd. I don't see a place where we're doing string concatenation in that flow.

Based on the other issue you opened, I'm curious if the sudo prompt is getting caught somewhere. If you run with `--nopasswd-sudo` (assuming there's no sudo password set) does it change anything?

**Comment by Gleland** [comment]
Ah, I think that's part of it. Now I only get one occurrence of the error for the local report generation (and I bet it's because i ran it without `sudo`). The remote report generation runs without issue. For the local sos report, here's the relevant snippet:

```
 78 [$localhost:execute_sos_command] Timeout exceeded
 79 Error running sosreport: unsupported operand type(s) for +: 'NoneType' and 'str'
```

[with_nopasswd_flag.txt](https://github.com/sosreport/sos/files/6306341/with_nopasswd_flag.txt)

**Comment by TurboTurtle** [comment]
That helps! The exception actually seems to be propagating from `cleanup()`, where we're assuming we have an archive path set. 

The local report generation takes care of wrapping sudo locally just like it does for remote collections. My money is on `--all-logs` causing the timeout. The timeout in turn is why we don't have an archive path (because there isn't an archive generated). We can fix this by improving the path checking logic in `cleanup()`, and I should be able to get something posted tomorrow for it.

**Comment by TurboTurtle** [comment]
I've opened #2494 for this, if you'd like to see if that properly handles the exceptions (provided `--nopasswd-sudo` is used).

**Comment by TurboTurtle** [comment]
@Gleland can you confirm if the current master branch resolves this issue for you?

**Comment by TurboTurtle** [comment]
Closing this out, assuming the above PR fixed this. If this is an ongoing issue please feel free to reopen this issue and include output/logs from a failed run.
