### ISSUE TITLE
when using `--clean` the local hostname should be obfuscated as well

### ISSUE THREAD

**Issue by Gleland** [sosreport/sos#2490]
On the newest sos version, (4.1), when creating a report with the `--clean` flag [1], remote host names will be obfuscated in various places (`sos_logs/`, `manifest.json`, etc.). However, the local machine where the `sos` command is being run does not receive the same treatment. 

For security and obscurity, can this also be obfuscated as `localhost` or some other opaque name to be consistent? For example, AWS hostnames by default include their private IP address [0], which should not be exposed unless decided by the user.

[0] https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-hostname.html
[1] example command that shows this behavior: ` $ sos collect --batch -a --all-logs --clean --nodes $node --ssh-user $user -vvv --nopasswd-sudo ` (see resulting `manifest.json` for transparent hostname)

**Comment by TurboTurtle** [comment]
Can you elaborate a bit on this? It sounds similar to an issue RH QE found, but I'm not sure if it's the same.

What I'm currently aware of is an issue where entire archives might not be obfuscated properly in a `collect` run. For example, for a `collect` run for `localhost`, `node1`, and `node2`, the final tarball would include an obfuscated archive for `localhost` and `node2`, but `node1` while having it's file name properly obfuscated, the actual contents (e.g. a journal inside the `node1` archive) not be obfuscated. What I'm currently investigating is how reproducible this is, as so far what I've not seen consistency in is _which_ archive is effectively skipped over.

Is that your same issue, or is it something different? For the record, we specifically exclude the string `localhost` from obfuscation (same with `127.0.0.1`, any APIPA address, and `8.8.8.8` for the IP address side of things).

**Comment by Gleland** [comment]
Thanks for the quick response! This issue is for obfuscating the references to the local server.

Say I'm running the command on a local server (`server1`), but I'm wanting to get a report for a second server (`server2`) that I can only reach by ssh. In this case, the command I provided (when being run on `server1`) would also generate a report for `server1`, but the report generated would not obfuscate references to `server1` itself.

**Comment by TurboTurtle** [comment]
Ok, I _think_ that is the same issue I'm looking into currently. What I believe is the issue is the order in which we load the maps with prep data from specific files in each archive. Currently we do it after archive extraction, but I believe we need to do it before we begin that loop. I'm testing some changes today in that vein and hope to have a PR opened for review later this week.
