### ISSUE TITLE
[python] the plugin for ubuntu/Debian is deprecated as all releases are now on py3

### ISSUE THREAD

**Issue by slashdd** [sosreport/sos#2502]
The plugin for Ubuntu/Debian is deprecated and need to be updated as all releases are now on py3.

**Comment by TurboTurtle** [comment]
Is this still the case since https://github.com/sosreport/sos/commit/5211c0248c50190c40d7fe604dfac507a53d8963 ?

**Comment by slashdd** [comment]
@TurboTurtle yes, it is still the case, and the plugin needs some polishing still.

There is no such thing as python (unless one install the package that create a symlink from python3 to python) in all stable releases now.

Python2 is still available but in universe (community driven) not Canonical supported, so it's fine to drop py2 in sosreport at Ubuntu/Debian's perspective.

**Comment by slashdd** [comment]
```
$lsb_release -cs
focal
```

```
$ python

Command 'python' not found, did you mean:

  command 'python3' from deb python3
  command 'python' from deb python-is-python3
```
