### ISSUE TITLE
[insights] insights plugin performs undesirable system changes

### ISSUE THREAD

**Issue by superjamie** [sosreport/sos#2508]
As discussed in https://github.com/sosreport/sos/issues/1435 having sos perform system changes such as loading kernel modules is undesirable. The `--allow-system-changes` flag was implemented for this purpose.

Since https://github.com/sosreport/sos/commit/0766cc739d424932e18c250c88f0227da06ecaed the insights plugin runs `insights-client --offline` which then runs a large amount of commands (many of which are redundantly already included in other sos plugins).

These commands include `ss_-tupna` which loads the networking diag modules, and `brctl show` which loads the bridge module. I have not audited all commands to determine if others perform system changes which sos promises it does not perform.

The insights plugin requires at least a `SoSPredicate()` around `insights-client --offline` similar to https://github.com/pmoravec/sos/commit/f3b1977d2e4ca4522c4777ba97655cc9a3ddb400 but also adding the `bridge` module. However, that just solves the immediate problem.

The wider issue is that the command `insights-client --offline` is not part of sos, so could theoretically do anything, and sos is not protected from future system changes which such a large-scope command may run.

It's currently running the equivalent of a second "mini-sosreport" inside an existing sosreport. It seems counter to a sos plugin's purpose to run a command which then re-does much of the same things which other sos plugins are already doing in the first place.

My impression of the sos plugin infrastructure is that each plugin should collect data specifically useful to that plugin domain, and not large system-wide commands or commands which are the scope of other plugin domains, as is currently being done here.

I'm not sure the best way to address this. Argubaly `insights-client --offline` should be removed from this plugin altogether, and replaced with specific commands which are useful to the Insights software only?

**Comment by superjamie** [comment]
Discussed with Insights developer Paul Wayper, resolved by https://github.com/sosreport/sos/pull/2509

**Comment by pmoravec** [comment]
Agreed. If some specific command/config for debugging the insights software is required (i.e. test connection to insights server/proxy), let us know and we can add it to the plugin.
