### ISSUE TITLE
Foreman's production.log isn't collected on EL8

### ISSUE THREAD

**Issue by ekohl** [sosreport/sos#2511]
In the sosreports we see, there isn't a `production.log`. I didn't check other files, but I wonder if that's because it's a subclass of `SCLPlugin`:

https://github.com/sosreport/sos/blob/652d11827fd26fd276b78ba0e77b6fcd9581d5b6/sos/report/plugins/foreman.py#L334-L341

**Comment by TurboTurtle** [comment]
Can you confirm the foreman plugin does actually run on your EL8 hosts? The `SCLPlugin` subclass shouldn't affect the main `Foreman.setup()` collection, unless it is for some reason interfering with plugin enablement.

Is there a particular sos version where you're seeing the log isn't captured?

**Comment by pmoravec** [comment]
`sos report -l | grep foreman` shows "inactive" (plugin disabled by default) or not? `sos report -o foreman` will collect the logfile?

**Comment by ekohl** [comment]
From the same CI run [CentOS 7](https://ci.theforeman.org/job/foreman-nightly-rpm-pipeline/1029//artifact/artifacts/foreman-pipeline-foreman-nightly-centos7-install/sosreport-pipe-foreman-server-nightly-centos7-2021-04-27-viemwyw.tar.xz) and [CentOS 8](https://ci.theforeman.org/job/foreman-nightly-rpm-pipeline/1029//artifact/artifacts/foreman-pipeline-foreman-nightly-centos8-install/sosreport-pipe-foreman-server-nightly-centos8-2021-04-27-inzmchq.tar.xz).

In the c7 I see `sos_commands/foreman` which I don't see in c8. That makes me think the whole plugin doesn't run.

```console
# sosreport -l | grep foreman
WARNING: unable to set option for disabled or non-existing plugin (boot)

 foreman              excluded       Foreman/Satellite 6 systems management
```

I don't know the code well enough or what that means. On the same machine I see that if I install redis that it's also still marked as `excluded`. The same goes for postgresql.

**Comment by ekohl** [comment]
```console
# sosreport -o foreman

sosreport (version 3.9)

WARNING: unable to set option for disabled or non-existing plugin (boot)
WARNING: unable to set option for disabled or non-existing plugin (boot)


This command will collect diagnostic and configuration information from
this CentOS system and installed applications.

An archive containing the collected information will be generated in
/var/tmp/sos.ef7wjoof and may be provided to a CentOS support
representative.

Any information provided to CentOS will be treated in accordance with
the published support policies at:

  https://www.centos.org/

The generated archive may contain data considered sensitive and its
content should be reviewed by the originating organization before being
passed to any third party.

No changes will be made to system configuration.

Press ENTER to continue, or CTRL-C to quit.

Please enter the case id that you are generating this report for []: 

 Setting up archive ...
 Setting up plugins ...
[plugin:foreman] Failed to find prefix for SCL tfm, using /opt/rh
[plugin:foreman] Failed to find prefix for SCL tfm, using /opt/rh
[plugin:networking] skipped command 'ip -s macsec show': required kmods missing: macsec.  Use '--allow-system-changes' to enable collection.
[plugin:networking] skipped command 'ss -peaonmi': required kmods missing: af_packet_diag, inet_diag, unix_diag, udp_diag, netlink_diag, tcp_diag.  Use '--allow-system-changes' to enable collection.
 Running plugins. Please wait ...

  Finishing plugins              [Running: rpm]                                           
  Finished running plugins                                                               
Creating compressed archive...

Your sosreport has been generated and saved in:
  /var/tmp/sosreport-dac4316d6f6a-2021-04-28-fpswhww.tar.xz

 Size	5.45MiB
 Owner	root
 md5	4cda244393b67e766fd7e3d9c29d0d39

Please send this file to your support representative.
```

Then it does run the command and collects `production.log`.

**Comment by TurboTurtle** [comment]
> 
> sosreport (version 3.9)


I think this is the issue. 3.9 had an issue with SCL enablement that was only fixed in 4.1 - 93842c4. I know that 4.0 is still in the pipeline for the next minor version. @pmoravec this might need an async/backport.

However, that being said I wouldn't expect the plugin to be listed as `excluded`. That should only be seen when a profile is requested and the plugin isn't in that profile. The default `satellite` preset doesn't use a profile either.

@ekohl would you be able to try the latest master branch on your C8 hosts? If this isn't resolved by the commit above I'd want to get on this asap.

**Comment by evgeni** [comment]
I think this is a dupe of https://github.com/sosreport/sos/issues/2407 and should be fixed in master

**Comment by evgeni** [comment]
and the "excluded" is probably because @ekohl has run this in a container, which excludes quite some plugins.

**Comment by ekohl** [comment]
That explains why I couldn't explain it while reading the code. So this issue is mostly about getting the fix into RHEL 8. A Github issue is probably not the best way for that. I'd be ok with closing this.

**Comment by evgeni** [comment]
There is a BZ that has the original issue I filed linked, and it's scheduled for an later EL Update.

**Comment by ekohl** [comment]
Closing since https://bugzilla.redhat.com/show_bug.cgi?id=1927231 should track inclusion.
