### ISSUE TITLE
OpenShift 4 disconnected environments - add an option to specify registry and image for  sos-collector-tmp container

### ISSUE THREAD

**Issue by andreaskaris** [sosreport/sos#2539]
Hi,

This is for OpenShift 4 disconnected environments.

Please add an option to specify registry and image for  sos-collector-tmp container in disconnected environments with a private registry.

Thanks,

Andreas

**Comment by TurboTurtle** [comment]
This option already exists, via the `--image` option. Just specify the registry with the image, e.g. `--image registry.example.com/foo/barimage`
