### ISSUE TITLE
RFE to add shortcut for timedatectl

### ISSUE THREAD

**Issue by thebyrdman-git** [sosreport/sos#2559]
Hello all,

I think it would be great to have a shortcut added to the parent directory for the timedatectl output.

We could have something like the following examples:

$ cat tz
OR
$ cat time

**Comment by TurboTurtle** [comment]
We already have a `date` root symlink, so this feels a little redundant.

Would it be better to just change what that symlink is pointing to?

**Comment by thebyrdman-git** [comment]
Yes, I think that would work well. My thought is that a symlink for the timezone in the long format would be nice because I like to copy/paste it when analyzing packet captures, i.e., TZ="America/New_York"

**Comment by TurboTurtle** [comment]
@pmoravec @BryanQuigley @bmr-cymru thoughts on switching the `date` symlink target?

**Comment by BryanQuigley** [comment]
I personally prefer it, but it does make us more systemd centric.. which I'm OK with, but should be considered as such..

**Comment by TurboTurtle** [comment]
Yeah, that is one hesitation, albeit minor. At the moment it's basically a non-issue since all of our supported downstreams use systemd.

**Comment by BryanQuigley** [comment]
Agreed - I'm guessing there are other improvements we could make if we decide systemd is required.

As a relevant (although low impact) example: We could replace running hwclock and date command entirely with timedatectl in the date plugin (and move timedatectl from the systemd plugin).

**Comment by pmoravec** [comment]
The change makes sense. Some timezone acronyms are not unique - afaik CST is a very good example of ambigous one.
