### ISSUE TITLE
There is no output with Command "systemctl show *service --all" 

### ISSUE THREAD

**Issue by huali027** [sosreport/sos#2567]
I found there is no output for "systemctl show *service --all", we can only get output by  "systemctl show *.service --all".
Currently the file sos_commands/systemd/systemctl_show_.service_--all is empty.

**Comment by TurboTurtle** [comment]
Thanks for reporting this!

Looks like we may need to add `--no-pager` to this command.

**Comment by huali027** [comment]
@TurboTurtle  I test it on Red Hat Enterprise Linux Server release 7.9 (Maipo) and the sos version is sos-3.9-5.el7_9.4.noarch.
I think it doesn't relate with the sos package, when I run the command on REHL directly, it has no output. But I found it works on RHEL 8.3.

**Comment by TurboTurtle** [comment]
Right, this seems more of a systemd issue to me. '*service' and '*.service' should be considered the same by all globbing behaviors that I'm aware of.

@jjansky1 thoughts on if this would be valid for a backport fix on 7.9 if we did a `legacy-3.9`-only bugfix?

**Comment by TurboTurtle** [comment]
Closing as this is not an sos bug.

**Comment by huali027** [comment]
@TurboTurtle, since it won't be fixed, this command will be always empty in sosreport on RHEL7, right?
