### ISSUE TITLE
Add VMware related log to sosreport if guest run on VMware ESXi

### ISSUE THREAD

**Issue by dulili** [sosreport/sos#2580]
when rhel run on VMware ESXi, there are some logs under /var/log/ should collect to sosreport,
vmware-network.log
vmware-vgauthsvc.log.0
vmware-vmsvc-root.log
vmware-vmtoolsd-root.log
vmware-vmusr-root.log
These logs are useful for debug issue.

**Comment by TurboTurtle** [comment]
We can definitely add those for collection. Are they only present when vmware-tools is installed or is some other client package required?

**Comment by dulili** [comment]
Hi TurboTurtle,
yes, these log onlu present when vmware-tools or open-vm-tools installed.
