### ISSUE TITLE
sos.conf honors just one variant for each command line option

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#2605]
Having either of:

    name=myname
    plugin-option=qpid.port=12345
    profile=sysmgmt

in `[report]` section of `/etc/sos/sos.conf`, the options are ignored, like:

    Unknown option 'plugin-option' in section 'report'

The reason is we allow multiple variants of long cmdline options (i.e. both `--plugin-option` and `-plugopts` (alongside to `-k` that we disallow to use in config file)), but we store & deal with just one such variant (`plugopts` in this case).

We probably need to update `update_from_conf` method for the explicit (currently) three variants of long cmdoptions by replacing `name` to `label` etc., similarly like we do a renaming in https://github.com/sosreport/sos/blob/master/sos/options.py#L188-L191 .

Or is there a better place for that change?

**Comment by TurboTurtle** [comment]
I believe this is fully resolved with 24a79ae. Feel free to re-open if that is incorrect.
