### ISSUE TITLE
[ceph] Retrieve the running config of OSDs

### ISSUE THREAD

**Issue by pponnuvel** [sosreport/sos#2613]
Ceph OSDs have a number of options whose the defaults may differ across different ceph versions. The defaults options (along with any modified options) control specific behaviour of OSDs.

It'd be nice to capture the running config of OSDs.

This can be done by running `ceph osd ls` and then iterating over the list with `ceph config show-with-defaults osd.X`.

(Untested code)
```
osds_output = self.collect_cmd_output('ceph osd ls')
        if osds_output['status'] == 0:
            osds = [osd.split()[0] for osd in osds_output['output'].splitlines()[1:]]
            self.add_cmd_output([
                "ceph config show-with-defaults osd.%s" % osd for osd in osds
            ], subdir='ceph')
```

**Comment by TurboTurtle** [comment]
We can certainly add this type of collection, and the code snippet looks good at first glance. The only thing I might change is `subdir='ceph'`. This would add the `ceph config` command outputs under `sos_commands/ceph/ceph`.

I'd suggest either dropping `subdir` there and letting these be collected in the standard plugin directory, or use something like `osd_configs` for the subdir name.

**Comment by pponnuvel** [comment]
This is already captured by recent improvements to ceph plugins.
