### ISSUE TITLE
[collector] unable to pass --plugin-option to cluster nodes

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#2641]
Reproducer:

    python3 bin/sos collect --batch -vvv --node sos-node1 -o services -k services.servicestatus=on | grep "Final sos command set to"
    [pmoravec-rhel8:finalize_sos_cmd] Final sos command set to /usr/sbin/sos report --batch -c auto --only-plugins=services

And no notion (or configuring) `-k ..` option.

The same for `--plugin-option` instead of `-k`.

So far I was able to check that https://github.com/sosreport/sos/blob/master/sos/collector/__init__.py#L484 already gets `self.opts` with `only_plugins=services` (correct) but `plugin_options=None` (already lost).

**Comment by TurboTurtle** [comment]
This is due to the use of `--only-plugins` - https://github.com/sosreport/sos/blob/8793ff269d6acc0bf2f12ea98a72dc60a8b5ab77/sos/collector/sosnode.py#L769

We should probably move the plugin option block on line 795 up before the `--only-plugins` check.

**Comment by pmoravec** [comment]
Hm.. that is the *second* place that needs fixing, indeed.

The problem is that `self.plugin_options` is empty there (per my debugs), so the line 795 will be no-op. Some passing options has to drop plugopts (while keeping all/most other opts).
