### ISSUE TITLE
[ssh] Can ssh plugin check the permissions set for /home/*/.ssh files?

### ISSUE THREAD

**Issue by m-strzelczyk** [sosreport/sos#2658]
Hello!

When users set wrong permissions to files in their ~/.ssh/ folder, i.e. they set write permission for `~/.ssh/authenticated_keys` for `other`, the SSH server will refuse to accept connections for this user.

I think it would be nice for the [ssh] plugin to check, if the permissions set for files in the `.ssh` folders of system users are correct, or if they are corrupted in some way. 

A very simple solution for that would be to just run `ls -l .ssh/` in every home directory. Would it be OK to extend the ssh plugin to do this? Would it be better to have a separate plugin do this?

Let me know what you think, and I'll give it a try if that's ok :)

**Comment by pmoravec** [comment]
Collecting permissions on that file belongs to sos report duty, so in general, I am in favour. And I think `ssh` plugin is a good destination for that. Just several concerns:

- should we  collect just "`ls -lZ .ssh/authenticated_keys`" for all users? Can't listing *whole* directory reveal some sensitive info (I dont know `ssh` and its config enough, to be sure here)?
- how to enumerate all users (or rather their home dirs)? Via `cat /etc/passwd | cut -d: -f6` ?
- should we collect all that info every time, or only when enabled by a plugin option? I *think* these kind of problems are rare, which suggests not collecting it by default. On the other side, collecting that will be fast, so..

**Comment by m-strzelczyk** [comment]
As for listing the whole `.ssh` folder or just `.ssh/authenticated_keys`, I'd say we'd want the whole `.ssh` folder. As per this [SO thread](https://superuser.com/questions/215504/permissions-on-private-key-in-ssh-folder) there is more to it than just the `authenticated_keys` file.

Getting list of all users may not be as simple as checking `/etc/passwd`. There is for example `getent passwd` described [here](https://linuxize.com/post/how-to-list-users-in-linux/). I think I'd try to use `getent passwd` and if that fails fall back to `cat /etc/passwd`.

Checking file permissions seems like something we could do every time. I'd be surprised if someone had sensitive information stored in the names of files stored in their `~/.ssh/` directory.
