### ISSUE TITLE
Allow plugins to discard stderr?

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#267]
The nova plugin does a whole lot of:

```
    self.add_cmd_output("cmd 2>/dev/null")
```

Currently we capture stdout and stderr merged in a single file. A long time ago stderr was discarded but since then we've taken the approach that if something writes to stderr it may be useful information so it's captured in-situ with the rest of the output.

The redirection use in the nova plugin needs to go now that we're not running commands via a shell (commit 6b487ac) but this raises the question whether there should be a way to request this behavior via the plugin API?

**Comment by TurboTurtle** [comment]
This should have been closed via 7b28857.
