### ISSUE TITLE
Allow plugins to sort command ouptut?

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#268]
The Nova plugin does:

``` python
    self.add_cmd_output("cmd | sort")
```

This will fail since commit 46b6c3d.. Should we provide an interface for sorting command output?

There's a similar use with a more complex pipeline in the RPM plugin that's currently hacked around by running 'sh -c "..."'.

**Comment by TurboTurtle** [comment]
Closing this out at this point. Between 2014 and now, plugin structure has changed quite a lot. I think `rpm` is the only plugin doing any sorting, and afaik all other output groking is line iteration that sorting isn't likely to help.

If there is further interest or need for this kind of funtionality, as always feel free to re-open this or open a new issue.
