### ISSUE TITLE
Add "smallreport" preset?

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#2686]
I have heard several complains that `sos report` takes a long time, which delays overall problem investigation. Our generic answer is "collect few plugins with small logsize etc. first". Is it worth proposing particular values for that suggestion?

From the options available, these four do affect the report collection speed and they are generic enough (`--only-plugins` is product/deployment specific):

- `--threads`
- `--log-size`
- `--plugin-timeout`
- `--cmd-timeout`

I did some evaluation of impact of the options to report time and also tarball size (less important for us), by running full matrix of all combinations of pre-defined values of these options and make an average of each `--option=value`:

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>
<body>

default | seconds | size (kB)
-- | -- | --
--threads=4 --log-size=25 --plugin-timeout=300 --command-timeout=300 | 109,787 | 17240
  |   |  
threads | seconds | size (kB)
4 | 98,32 | 15 413,69
8 | 92,55 | 15 583,19
16 | 87,18 | 14 712,19
  |   |  
logsize | seconds | size (kB)
1 | 88,33 | 13 215,00
5 | 90,46 | 14 434,42
10 | 93,12 | 16 492,83
25 | 98,82 | 16 803,17
  |   |  
plugtimeout | seconds | size (kB)
10 | 71,33 | 13 915,17
30 | 96,12 | 15 578,00
60 | 101,49 | 15 724,33
300 | 101,79 | 15 727,92
  |   |  
cmdtimeout | seconds | size (kB)
5 | 87,55 | 14 915,17
10 | 93,59 | 15 299,25
60 | 94,75 | 15 325,50
300 | 94,85 | 15 405,50

</body>
</html>

The test was run on a moderate-used RHEL8 system with no layered product on top of it. Hence I expect for layered products or much utilised components (where some commands will take more time and there will be more bigger logs), the differences in above table would be bigger.

So my proposal is to have a `smallreport` preset, that will set:
- `threads=$nproc` (changing number of threads can have an impact primarily till there are spare CPUs)
- `logsize=5` (1 sounds too small to me and the diff isnt big)
- `plugin-timeout=30` (10 is too small and no drastic time improvement)
- `command-timeout=30` as this option does not show to have much effect to overall time, in my case; limiting it to `plugin-timeout`

Some thoughts?

**Comment by TurboTurtle** [comment]
The "Size (**M**B)" column is a typo, right? If not, what's causing 14-18GB sos reports here?

I'd like to source more data on what end users consider "takes too long" to be. We may want to review possible superfluous collections and/or perhaps gate some long-running collections behind plugin options if there are consistent themes we see from these reports.

I wouldn't mind including a "quick but potentially not helpful" preset in theory, but since all of our options revolve around reducing the amount of collected data we need to be careful that we're not chasing performance goals that actually hinder end users by way of requiring additional executions of `sos report`.

**Comment by pmoravec** [comment]
> The "Size (**M**B)" column is a typo, right? If not, what's causing 14-18GB sos reports here?

Yes, that was a typo, it is output of "du -k" so in kB. Fixing it now..

> I'd like to source more data on what end users consider "takes too long" to be. We may want to review possible superfluous collections and/or perhaps gate some long-running collections behind plugin options if there are consistent themes we see from these reports.

Yeah, I agree. I heard the complains here and there but never got a particular sosreport tarball to investigate. I will poke around for some more particular data.
