### ISSUE TITLE
[runc] redundant collection of container details from an error output

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#2689]
(just spot it in a sosreport, clarifying the circumstances)

When `runc list -q` returns:

    0026e6c31bfd6c055312771d6e9c003bcf745191abc9b11b5035ba158b42f123: json: cannot unmarshal string into Go struct field State.init_process_start of type uint64

we should either split the container name from it (and not take the whole line as the container name / argument for `'runc ps %s' % con`), or ignore the stderr (if the output is printed there).

**Comment by TurboTurtle** [comment]
Follow up talks with principal level support folks indicate that all of the `runc` collections are likely redundant with other plugins. Unless other distros want to enable the plugin, as it is currently only a Red Hat plugin, we can likely drop it altogether.
