### ISSUE TITLE
[debian] debian policy knows only about wheezy and jessie.

### ISSUE THREAD

**Issue by slashdd** [sosreport/sos#2691]
```
The next release of Debian is codenamed bookworm — testing — no release date has been set
Debian 11 (bullseye) — current stable release
Debian 10 (buster) — current oldstable release
Debian 9 (stretch) — oldoldstable release, under LTS support
Debian 8 (jessie) — archived release, under extended LTS support
Debian 7 (wheezy) — obsolete stable release
Debian 6.0 (squeeze) — obsolete stable release
```

**Comment by TurboTurtle** [comment]
Is this for `Policy.dist_version()`?

Right now only one place in the entire project uses this - the `python` plugin (and specifically only the `RedHatPython` plugin at that).

Should we look at better utilizing distro versioning or perhaps removing it?

**Comment by slashdd** [comment]
> Is this for `Policy.dist_version()`?
Yes
> Right now only one place in the entire project uses this - the `python` plugin (and specifically only the `RedHatPython` plugin at that).
> 
> Should we look at better utilizing distro versioning or perhaps removing it?
Maybe removing it would work I guess, if unused, depending on much Red Hat depends on it.

**Comment by TurboTurtle** [comment]
In the `python` plugin, RH is using it to call `platform-python -V` in place of `python -V` for RHEL 8. There are certainly other ways to make that switch if we elect to drop `dist_version()`.

 I've come up with a few possible additional use cases, but I'm not sure if they're actually useful:

1. Adding dist_version to manifest.json. There's an effort starting on the RH side to do some analysis based on the manifest (e.g. average runtimes, frequency of option use, etc...), and this could be potentially useful information. On the other hand, the same analysis could just as easily read `/etc/redhat-release` within the archive that holds the manifest.
2. Perhaps some control for host types with `sos collect`. E.G. different ways of launching a container to run sos in based on version, or some logic surrounding the called binary and/or options. I don't know if this is actually applicable or useful off the top of my head though.
3. Should we do a plugin review to see if there are areas that could benefit from calling `dist_version()` like `python` does? One of the original intents I believe was to allow specifying plugin behavior differently across different versions. For example, differently named files or commands. However, long standing plugin design has been more in-line with "throw all possible variations in one plugin and let our missing file/invalid command/etc... handling do its job"

**Comment by slashdd** [comment]
We could definitely do a plugin review (and see if other plugins could benefit it). If it turned out to be only use/"needed" by the python plugin in the RedHat context, and it can easily be sorted it out without it. I'm in favor to drop it with the rationale that anyway most plugins are mostly backward compatible with no longer existing feature/cmd/tools/...

**Comment by TurboTurtle** [comment]
Cycling around on this. On the RH side we've actually done a little tinkering with `dist_version()` recently, and there are 2 plugins, `foreman` and `python`, that do use it. I can envision a handful of further use cases springing up in the not so distant future, so for that side of the house we need to keep it.

I think idea 1 above does have some merit for data analysis so I'll open something up shortly to add it to the manifest.

@slashdd if you could provide a PR to add the missing Debian releases, that'd be great.
