### ISSUE TITLE
Collect running ovn schemas using ovsdb-client

### ISSUE THREAD

**Issue by pmannidi** [sosreport/sos#2697]
Collect OVN NB DB and SB DB schemas using ovsdb-client command along with files.

If we don't migrate the DB to new schema, DB would be running with old schema. It'd be better to collect running schema rather than the schema file on the file system.

**Comment by pmoravec** [comment]
Is https://bugzilla.redhat.com/show_bug.cgi?id=1975414 talking about the same, please? There seems to be some consensus to leave this as is (for now) - see e.g. https://bugzilla.redhat.com/show_bug.cgi?id=1975414#c17.

**Comment by pmannidi** [comment]
I meant `ovsdb-client get-schema <OVN DB CONN URI>`. the bug you are talking about is collecting the DBs using ovsdb-client. The reason being for non-containerized deployments (very rare or non-existent), this would get the schema directly from OVN DBs servers instead of relying on schema files which might not be used after initial deployment. same goes for containerized.

**Comment by pmannidi** [comment]
closing the issue, as we're collecting OVN DBs files, collecting schema will not help us anyway.

More details are discussed in https://github.com/sosreport/sos/pull/2698
