### ISSUE TITLE
collect /etc/pulp/settings.py

### ISSUE THREAD

**Issue by matt8754** [sosreport/sos#2709]
It would be helpful to collect  /etc/pulp/settings.py in order to troubleshoot automation hub with pulp3 related issues.

**Comment by TurboTurtle** [comment]
That file is already collected by the `pulpcore` plugin. The `pulpcore` plugin is for pulp3, whereas the 'plain' `pulp` plugin is for pulp2.

https://github.com/sosreport/sos/blob/main/sos/report/plugins/pulpcore.py#L88

**Comment by matt8754** [comment]
Great, is pulpcore pulgin enabled by default? which sos version has it? 
Thanks

**Comment by TurboTurtle** [comment]
`pulpcore` was added in sos-4.2, our most recent release. `pulpcore`'s enabled is actually determined by if that file is present or not.

**Comment by matt8754** [comment]
Cool, thanks. I'll wait for 4.2 release.
