### ISSUE TITLE
Wiki: plugin options - outdated

### ISSUE THREAD

**Issue by m-strzelczyk** [sosreport/sos#2714]
Hi!

Is there a way I could make a Pull Request with an update to this [wiki page](https://github.com/sosreport/sos/wiki/How-to-Write-a-Plugin#add-plugin-options)? It's outdated, but the changes are not that big, so I could quickly prepare a new draft.

If there's no way for a PR, I'll just write something here so one of the maintainers can just copy-paste.

**Comment by TurboTurtle** [comment]
PRs can't affect the GH Wiki. I have this on my list to update this week, but if you'd like to contribute an update then certainly feel free to post something here.

**Comment by TurboTurtle** [comment]
Ack, updated.
