### ISSUE TITLE
[testing] nose is unmaintained and not functional with python-3.10

### ISSUE THREAD

**Issue by TurboTurtle** [sosreport/sos#2716]
Starting today, we've seen our nosetest check for PRs fail. This is due to the use of python-3.10 in the `latest` python container image. `nose` itself is now unmaintained, so this will not be corrected within that package.

We have 4 options it seems:

- Fallback to python-3.9 and continue to use `nose`.
- Switch to `nose2`, though at first glance there will need to be some work done to update the unittests, as simply replacing `nose` with `nose2` results in chaining import errors.
- Switch to `pytest` - this should be seamless and local tests show it is a drop-in replacement.
- Look into re-writing the unittests for `avocado`, thus matching our integration test suite.

Options 2 and 4 will definitely take some time, so perhaps we could go with option 1 or 3 to start with while we work out the kinks for either 2 or 4 going forward.

**Comment by TurboTurtle** [comment]
Looking in option 4 a bit more, it seems the main changes needed are relative paths for test files within the `tests/unittests/` directory.

These should be simple to clean up, however I see one potential issue - avocado does not print the actual error message for a failed or error'd test:

```
$  avocado run tests/unittests/archive_tests.py 
JOB ID     : bc07891812d234c36279987aed235fc1e33ebf56
JOB LOG    : /home/jake/avocado/job-results/job-2021-10-06T12.44-bc07891/job.log
 (01/10) archive_tests.TarFileArchiveTest.test_create: PASS (0.12 s)
 (02/10) archive_tests.TarFileArchiveTest.test_add_file: PASS (0.12 s)
 (03/10) archive_tests.TarFileArchiveTest.test_add_node_dev_null: PASS (0.11 s)
 (04/10) archive_tests.TarFileArchiveTest.test_add_string_from_file: PASS (0.11 s)
 (05/10) archive_tests.TarFileArchiveTest.test_add_renamed: ERROR: Unittest reported error(s) (0.14 s)
 (06/10) archive_tests.TarFileArchiveTest.test_add_string: PASS (0.12 s)
 (07/10) archive_tests.TarFileArchiveTest.test_get_file: PASS (0.11 s)
 (08/10) archive_tests.TarFileArchiveTest.test_rewrite_file: PASS (0.11 s)
 (09/10) archive_tests.TarFileArchiveTest.test_make_link: PASS (0.12 s)
 (10/10) archive_tests.TarFileArchiveTest.test_compress: PASS (0.11 s)

```

@clebergnu can we adjust this behavior and have avocado print the failure message or the exception raised? If we set a test to fail with either raising an exception or calling `self.fail()` with some message, I see this from avocado:

```

ERROR: test_add_renamed (archive_tests.TarFileArchiveTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jake/projects/sos/tests/unittests/archive_tests.py", line 74, in test_add_renamed
    self.check_for_file('test/tests/unittests/ziptest_renamed')
  File "/home/jake/projects/sos/tests/unittests/archive_tests.py", line 31, in check_for_file
    rtf.getmember(filename)
  File "/usr/lib64/python3.9/tarfile.py", line 1790, in getmember
    raise KeyError("filename %r not found" % name)
KeyError: "filename 'test/tests/unittests/ziptest_renamed' not found"

avocado.utils.process.CmdError: Command '/usr/bin/python3 -m unittest -q -c archive_tests.TarFileArchiveTest.test_add_renamed' failed.
stdout: b''
stderr: b'======================================================================\nERROR: test_add_renamed (archive_tests.TarFileArchiveTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/jake/projects/sos/tests/unittests/archive_tests.py", line 74, in test_add_renamed\n    self.check_for_file(\'test/tests/unittests/ziptest_renamed\')\n  File "/home/jake/projects/sos/tests/unittests/archive_tests.py", line 31, in check_for_file\n    rtf.getmember(filename)\n  File "/usr/lib64/python3.9/tarfile.py", line 1790, in getmember\n    raise KeyError("filename %r not found" % name)\nKeyError: "filename \'test/tests/unittests/ziptest_renamed\' not found"\n\n----------------------------------------------------------------------\nRan 1 test in 0.009s\n\nFAILED (errors=1)\n'
additional_info: None


Traceback (most recent call last):
  File "/home/jake/.local/lib/python3.9/site-packages/avocado/core/test.py", line 1299, in test
    super(PythonUnittest, self).test()
  File "/home/jake/.local/lib/python3.9/site-packages/avocado/core/test.py", line 1264, in test
    self._execute_cmd()
  File "/home/jake/.local/lib/python3.9/site-packages/avocado/core/test.py", line 1173, in _execute_cmd
    raise exceptions.TestFail(test_failure)
avocado.core.exceptions.TestFail: Exited with status: '1', stdout: '', stderr: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jake/.local/lib/python3.9/site-packages/avocado/core/test.py", line 1303, in test
    self.error("Unittest reported error(s)")
  File "/home/jake/.local/lib/python3.9/site-packages/avocado/core/test.py", line 995, in error
    raise exceptions.TestError(message)
avocado.core.exceptions.TestError: Unittest reported error(s)


```

**Comment by clebergnu** [comment]
> Looking in option 4 a bit more, it seems the main changes needed are relative paths for test files within the `tests/unittests/` directory.
> 
> These should be simple to clean up, however I see one potential issue - avocado does not print the actual error message for a failed or error'd test:
> 
> ```
> $  avocado run tests/unittests/archive_tests.py 
> JOB ID     : bc07891812d234c36279987aed235fc1e33ebf56
> JOB LOG    : /home/jake/avocado/job-results/job-2021-10-06T12.44-bc07891/job.log
>  (01/10) archive_tests.TarFileArchiveTest.test_create: PASS (0.12 s)
>  (02/10) archive_tests.TarFileArchiveTest.test_add_file: PASS (0.12 s)
>  (03/10) archive_tests.TarFileArchiveTest.test_add_node_dev_null: PASS (0.11 s)
>  (04/10) archive_tests.TarFileArchiveTest.test_add_string_from_file: PASS (0.11 s)
>  (05/10) archive_tests.TarFileArchiveTest.test_add_renamed: ERROR: Unittest reported error(s) (0.14 s)
>  (06/10) archive_tests.TarFileArchiveTest.test_add_string: PASS (0.12 s)
>  (07/10) archive_tests.TarFileArchiveTest.test_get_file: PASS (0.11 s)
>  (08/10) archive_tests.TarFileArchiveTest.test_rewrite_file: PASS (0.11 s)
>  (09/10) archive_tests.TarFileArchiveTest.test_make_link: PASS (0.12 s)
>  (10/10) archive_tests.TarFileArchiveTest.test_compress: PASS (0.11 s)
> ```
> 
> @clebergnu can we adjust this behavior and have avocado print the failure message or the exception raised? If we set a test to fail with either raising an exception or calling `self.fail()` with some message, I see this from avocado:
> 
> ```
> 
> ERROR: test_add_renamed (archive_tests.TarFileArchiveTest)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/jake/projects/sos/tests/unittests/archive_tests.py", line 74, in test_add_renamed
>     self.check_for_file('test/tests/unittests/ziptest_renamed')
>   File "/home/jake/projects/sos/tests/unittests/archive_tests.py", line 31, in check_for_file
>     rtf.getmember(filename)
>   File "/usr/lib64/python3.9/tarfile.py", line 1790, in getmember
>     raise KeyError("filename %r not found" % name)
> KeyError: "filename 'test/tests/unittests/ziptest_renamed' not found"
> 
> avocado.utils.process.CmdError: Command '/usr/bin/python3 -m unittest -q -c archive_tests.TarFileArchiveTest.test_add_renamed' failed.
> stdout: b''
> stderr: b'======================================================================\nERROR: test_add_renamed (archive_tests.TarFileArchiveTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/jake/projects/sos/tests/unittests/archive_tests.py", line 74, in test_add_renamed\n    self.check_for_file(\'test/tests/unittests/ziptest_renamed\')\n  File "/home/jake/projects/sos/tests/unittests/archive_tests.py", line 31, in check_for_file\n    rtf.getmember(filename)\n  File "/usr/lib64/python3.9/tarfile.py", line 1790, in getmember\n    raise KeyError("filename %r not found" % name)\nKeyError: "filename \'test/tests/unittests/ziptest_renamed\' not found"\n\n----------------------------------------------------------------------\nRan 1 test in 0.009s\n\nFAILED (errors=1)\n'
> additional_info: None
> 
> 
> Traceback (most recent call last):
>   File "/home/jake/.local/lib/python3.9/site-packages/avocado/core/test.py", line 1299, in test
>     super(PythonUnittest, self).test()
>   File "/home/jake/.local/lib/python3.9/site-packages/avocado/core/test.py", line 1264, in test
>     self._execute_cmd()
>   File "/home/jake/.local/lib/python3.9/site-packages/avocado/core/test.py", line 1173, in _execute_cmd
>     raise exceptions.TestFail(test_failure)
> avocado.core.exceptions.TestFail: Exited with status: '1', stdout: '', stderr: ''
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/jake/.local/lib/python3.9/site-packages/avocado/core/test.py", line 1303, in test
>     self.error("Unittest reported error(s)")
>   File "/home/jake/.local/lib/python3.9/site-packages/avocado/core/test.py", line 995, in error
>     raise exceptions.TestError(message)
> avocado.core.exceptions.TestError: Unittest reported error(s)
> ```

Hi @TurboTurtle,

That's a worthy feature indeed... and I wonder why we haven't implemented it yet.  Anyway, I'm giving it a go, and locally, it seems to be working. I'll send a PR to Avocado and ask for you to test it with SOS.

Cheers.

**Comment by clebergnu** [comment]
> Starting today, we've seen our nosetest check for PRs fail. This is due to the use of python-3.10 in the `latest` python container image. `nose` itself is now unmaintained, so this will not be corrected within that package.
> 
> We have 4 options it seems:
> 
> * Fallback to python-3.9 and continue to use `nose`.
> * Switch to `nose2`, though at first glance there will need to be some work done to update the unittests, as simply replacing `nose` with `nose2` results in chaining import errors.
> * Switch to `pytest` - this should be seamless and local tests show it is a drop-in replacement.
> * Look into re-writing the unittests for `avocado`, thus matching our integration test suite.
> 

There shouldn't be any need to rewrite unittests (generally speaking) to have them run under Avocado.  With that being said:
* the `nrunner` based implementation of the Python unittest resolver/runners are more consistent with Avocado's own naming of tests (you'll find them to follow the `path/to/test.py:Class.test_method` pattern, rather than the "dotted name" unittest approach.  This allows you to copy & paste a test name and run it again.
* the `nrunner` based implementations have each test ran even more isolated than the "legacy" runner.
* the `nrunner` isolation has a cost -- but it can be offset by the fact that it will run tests in parallel by default
* small tweaks may be needed (generally speaking) 

> Options 2 and 4 will definitely take some time, so perhaps we could go with option 1 or 3 to start with while we work out the kinks for either 2 or 4 going forward.

**Comment by clebergnu** [comment]
@TurboTurtle FIY, the requested feature is implemented here: https://github.com/avocado-framework/avocado/pull/5013
