### ISSUE TITLE
can i install via pip and a git url?

### ISSUE THREAD

**Issue by ciq-mcarifio** [sosreport/sos#2737]
Will `python -m pip install --user --upgrade git+https://github.com/sosreport/sos@4.2` install the latest released version 4.2 correctly? By correctly here, I mean it will place the `sos` driver script in `$(python -m site --user-site)/bin` so I can run it.

This does seem to work, but it looks like some other things happen on the way to `dnf`. Please advise. Thanks.

**Comment by TurboTurtle** [comment]
We don't currently release to pypi, so any use of pip for installation is a "your mileage may vary" scenario. We recommend using downstream packaging, or directly from a cloned copy of the github repo.

**Comment by ciq-mcarifio** [comment]
"or directly from a cloned copy of the github repo." Could you clarify that? According to README..md I could do something like:
```git clone https://github.com/sosreport/sos; cd sos; git checkout 4.2; python setup.py install``` 
for a "manual" install(?). I'll have to confirm this, but that's basically the name as `python -m pip install --user --upgrade git+https://github.com/sosreport/sos@4.2`, in other words it clones and the runs setup.py.

"This is untested." is a valid response, of course. It's just pretty close to the documented manual method (I think). Ty..

**Comment by TurboTurtle** [comment]
> According to README.md I could do something like: `git clone https://github.com/sosreport/sos; cd sos; git checkout 4.2; python setup.py install` for a "manual" install(?).

Yup, that. Sorry, I should have been more specific.

> I'll have to confirm this, but that's basically similar to `python -m pip install --user --upgrade git+https://github.com/sosreport/sos@4.2`, in other words it clones and the runs setup.py.

If that's the process then it _should_ function as expected, but again we don't actively ensure that the `pip` approach is functional.
