### ISSUE TITLE
Remove 'speed' attribute from plugin options?

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#274]
The 'speed' attribute of plugin options has never been very well-defined or meaningful. I'm not sure whether to try to make it something useful (e.g. a weighting system with criteria plugin authors can use to determine the cost of data collection) or just remove it all together.

**Comment by TurboTurtle** [comment]
Let's bring this up again - does it actually help us with, for example, `sos info`? Do we want to have the plugin options trigger some preset text of "this option may extend plugin run time" or similar for `slow` options?

Or should we just drop `fast|slow` entirely and leave the text completely up to individual plugins when they are called via `sos info`?

**Comment by BryanQuigley** [comment]
I might be missing it, but does it actually do anything today?

I think if something is an option that is super slow it should be in the description.

I'd be for killing it.

**Comment by pmoravec** [comment]
+1, afaik the attribute is never used. At least grepping of `fast` or `slow` or `speed` found nothing.
