### ISSUE TITLE
plugins and the files they generate

### ISSUE THREAD

**Issue by ciq-mcarifio** [sosreport/sos#2742]
Looking at some random plugin like say [boom.py](https://github.com/sosreport/sos/blob/main/sos/report/plugins/boom.py), there seems to be a convention where:

- the plugin describes itself
- copies some config files to the sos directory
- issues some commands

Where in the directory do they go? Is there a mapping of plugin to "it's results"? Ty.

**Comment by TurboTurtle** [comment]
Check `sos_reports/manifest.json` within any sos report archive (from sos-4.0 onwards that is). You'll see a listing of all collected files and command outputs, with additional information including where in the archive the collection was saved to.

At a high level though - copied files are copied to the same path relative to the sos report archive. E.G. if a plugin copies `/etc/fstab` from the host, then it will be written to `$archive_root/etc/fstab`. Command output is written to `$archive_root/sos_commands/$plugin/`. Some plugins make use of subdirs for more friendly organization of large amounts of data (e.g. the `podman` or `openshift` plugins), but those subdirs will always be under the aforementioned plugin directory.

See https://github.com/sosreport/sos/wiki#can-i-see-what-it-is-collecting

**Comment by TurboTurtle** [comment]
Closing this as answered above. If you have further questions please feel free to re-open this.
