### ISSUE TITLE
-k plugin.timeout is applied to all plugins

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#2744]
reproducer:

    python3 bin/sos report -o kernel,selinux -k selinux.timeout=1 --batch --build

causes *both* kernel and selinux plugins to timeout (within one second). Moreover, this leads to segfault like https://github.com/sosreport/sos/issues/2722 due to an attempt to write to closed file (will be resolved in that issue).

**Comment by TurboTurtle** [comment]
Looks like this is because the default plugin options are built before the individual plugins are instantiated. I'm hammering out a fix for this on my end, and trying to make a test case for it going forward. I'll post a PR later today for it, as this is quite significant.
