### ISSUE TITLE
[networking] Enable ss command when diag modues are built into kernel

### ISSUE THREAD

**Issue by superjamie** [sosreport/sos#2753]
Issue https://github.com/sosreport/sos/issues/1435 described that running the `ss` command in the sos networking plugin loads diagnostic kernel modules which weren't previously loaded.

This resulted in the `--allow-system-changes` sos option and removal of the `ss` command from the default sos report.

As discussed on that issue, this has somewhat impaired our ability to proactively get detailed network connection information from a sosreport. It is not desirable from a support perspective.

RHEL9 changes to build these diagnostic modules into the kernel, as described in the RHEL 9 Beta Release Notes:

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9-beta/html-single/9.0_release_notes#enhancement_networking

> The `diag` modules are now included with the kernel image. With this update, the `diag` modules no longer need to be dynamically loaded when the `ss` command is used. This allows better debugging of networking issues regardless of the customer policy on kernel modules.

This is a feature request for sos to detect this and run `ss` by default when the system won't be changed by running it. The detection could be based off OS (all EL9) or the relevant kernel config `CONFIG_modulename_DIAG` in the boot directory.

**Comment by TurboTurtle** [comment]
These should be listed in `/usr/lib/modules/$(uname -r)/modules.builtin`, right? If so, we should already be set for this:

https://github.com/sosreport/sos/blob/main/sos/policies/distros/__init__.py#L159


Or have you already tried this on EL9 Beta and are saying this detection is not working? I have not yet looked into this myself on EL9.

**Comment by TurboTurtle** [comment]
Ah, ok. I spun up an EL9 beta VM and took a look. Currently, it is shipping sos-4.1, which does not have the changes to `init_kernel_modules()` linked above.

Those changes were introduced in sos-4.2, and I've confirmed that using sos-4.2 on EL9 does indeed collect the `ss` output by default.

**Comment by superjamie** [comment]
Confirmed sos-4.2 works. Thank you!
