### ISSUE TITLE
Collect MGR specific information in the ceph_mgr plugin

### ISSUE THREAD

**Issue by nkshirsagar** [sosreport/sos#2759]
#1945 split the ceph plugin into individual component plugins. One of the reasons this was done was so we could add component specific data collection for each individual ceph service.

This issue has been opened to enhance the ceph_mgr plugin to collect the ceph manager related detailed data. Data the ceph_mgr plugin will collect includes

ceph daemon mgr.id < ... >

config diff
config show
dump_cache
dump_mempools
dump_osd_network
mds_requests
mds_sessions
objecter_requests
get_command_descriptions
mds_requests
mds_sessions
perf dump
perf histogram dump
perf histogram schema
perf schema
status
version

If the mgr is colocated with the mon (as is the usual case) and the keyring is present on the machine, additionally we might also want to collect,

ceph mgr dump
ceph mgr metadata
ceph mgr module ls
ceph mgr services
ceph mgr versions

**Comment by TurboTurtle** [comment]
> This issue has been opened to enhance the ceph_mgr plugin to collect the ceph manager related detailed data. Data the ceph_mgr plugin will collect includes
> 
> ceph daemon mgr.id < ... >
> 

Is this literally `ceph daemon mgr.id` or is `id` variable, i.e. we'd actually be executing `ceph daemon mgr.1234` or somesuch?

> config diff config show dump_cache dump_mempools dump_osd_network mds_requests mds_sessions objecter_requests get_command_descriptions mds_requests mds_sessions perf dump perf histogram dump perf histogram schema perf schema status version
> 

Do any of these potentially contain sensitive info? Like passwords or private keys? Particularly interested in `config show`.

Are the `perf` commands particularly expensive to run? As in they have a long runtime or could cause a spike in memory usage? If they do, we'll want to gate them behind a plugin option likely.

> If the mgr is colocated with the mon (as is the usual case) and the keyring is present on the machine, additionally we might also want to collect,
> 

How do we detect this?

> ceph mgr dump ceph mgr metadata ceph mgr module ls ceph mgr services ceph mgr versions

**Comment by nkshirsagar** [comment]
Hi Jake, 

> > This issue has been opened to enhance the ceph_mgr plugin to collect the ceph manager related detailed data. Data the ceph_mgr plugin will collect includes
> > ceph daemon mgr.id < ... >
> 
> Is this literally `ceph daemon mgr.id` or is `id` variable, i.e. we'd actually be executing `ceph daemon mgr.1234` or somesuch?

The latter. The mgr id in fact seems a hostname in the env I have , unlike the ID's of the OSDs which are numeric.

root@juju-fed208-1-lxd-0:~# ceph daemon mgr.juju-fed208-1-lxd-0 status
{
    "metadata": {},
    "dentry_count": 0,
    "dentry_pinned_count": 0,
    "id": 0,
    "inst": {
        "name": {
            "type": "client",
            "num": 4104
        },
        "addr": {
            "nonce": 106605992,
            "addr": "10.230.61.253:0"
        }
    },
    "inst_str": "client.4104 10.230.61.253:0/106605992",
    "addr_str": "10.230.61.253:0/106605992",
    "inode_count": 0,
    "mds_epoch": 0,
    "osd_epoch": 11,
    "osd_epoch_barrier": 0,
    "blacklisted": false
}

I plan to use the same approach as https://github.com/sosreport/sos/pull/2736 where I had used the ps output to parse the IDs out. (with some checks to ensure I didn't pick out invalid lines from the ps output)

root@juju-fed208-1-lxd-0:~# ps -eaf | grep ceph
root      2875  2861  0 06:41 pts/0    00:00:00 grep --color=auto ceph
ceph     12496     1  0 Oct27 ?        01:05:27 /usr/bin/ceph-mon -f --cluster ceph --id juju-fed208-1-lxd-0 --setuser ceph --setgroup ceph
ceph     12741     1  0 Oct27 ?        01:32:24 /usr/bin/ceph-mgr -f --cluster ceph --id juju-fed208-1-lxd-0 --setuser ceph --setgroup ceph

> > config diff config show dump_cache dump_mempools dump_osd_network mds_requests mds_sessions objecter_requests get_command_descriptions mds_requests mds_sessions perf dump perf histogram dump perf histogram schema perf schema status version
> 
> Do any of these potentially contain sensitive info? Like passwords or private keys? Particularly interested in `config show`.

https://pastebin.com/S0NdiYqi has the output of config show (link expiry in 1 month). @hillpd @pponnuvel please can you help me understand if any of the ceph daemon mgr.id commands might have sensitive info we would rather not collect?

> Are the `perf` commands particularly expensive to run? As in they have a long runtime or could cause a spike in memory usage? If they do, we'll want to gate them behind a plugin option likely.

There is a related discussion about some ceph commands having the potential to take a long time in https://github.com/sosreport/sos/pull/2736#discussion_r739682957 . I will check with @hillpd and @pponnuvel  about which of these mgr related commands might have performance problems and we can then simply not collect them. 

> > If the mgr is colocated with the mon (as is the usual case) and the keyring is present on the machine, additionally we might also want to collect,
> 
> How do we detect this?

The ps output will also show us if a mon is running on the same node. In which case, it will have the keyring.

**Comment by pponnuvel** [comment]
@nkshirsagar @The list of commands look safe. They don't contain any sensitive info - `config show` won't show keyring itself) or can cause performance/memory impact - `perf dump` returns the counters, doesn't do any perf tests & such. Btw, the equivalent commands already exist in the Ceph OSD plugin.

Couple of questions:
1. do we need `get_command_descriptions`? I think we can get this info offline (e.g. from documentation)?

2.
> If the mgr is colocated with the mon (as is the usual case) and the keyring is present on the machine, additionally we might also want to collect [..]

If not, do we run these commands as part of mon plugin?

**Comment by nkshirsagar** [comment]
Hi Pon!
thanks for taking a look.

We do not run the ceph mgr commands as part of the mon plugin. If you think it makes sense, I could just add these in there,

ceph mgr dump
ceph mgr metadata
ceph mgr ls
ceph mgr services                                                                                              list service endpoints provided by mgr modules
ceph mgr versions                                                                                              check running versions of ceph-mgr daemons

 and not collect any ceph mgr ones in the ceph_mgr plugin everytime. 

I think it will be cleaner that way, otherwise we'd need one plugin to somehow know if they've been collected in the other.

Also, yes I will remove get_command_descriptions, that should not have been in the list.

**Comment by pponnuvel** [comment]
> Hi Pon! thanks for taking a look.
> 
> We do not run the ceph mgr commands as part of the mon plugin. If you think it makes sense, I could just add these in there,
> 
> ceph mgr dump ceph mgr metadata ceph mgr ls ceph mgr services ceph mgr versions
> 
> and not collect any "ceph mgr" ones in the ceph_mgr plugin everytime because they will fail if there's no keyring (i.e if mgr is not on the same node as the mon)
> 
> I think it will be cleaner that way, otherwise we'd need one plugin to somehow know if they've been collected in the other.
> 
> Also, yes I will remove get_command_descriptions, that should not have been in the list.

I am just concerned that we might end up not collect some of these commands if the node, where ceph-mgr plugin runs, happens to have no admin keyring. Currently, we do collect because every command is run everywhere (and some fail). 

Perhaps, as a compromise, we could collect these `ceph mgr ...` as part of ceph-mon *if* ceph-mon plugin can detect ceph-mgr doesn't run exist on the same node and can put these commands' output to `ceph_mgr` directory rather than its own `ceph_mon` directory. Just a thought.

**Comment by nkshirsagar** [comment]
That can be worked out, but I think its cleaner to simply collect them in ceph_mon which already collects things like "ceph osd metadata" and other "ceph osd, ceph df, ceph osd crush dump" kind of commands. I do get that most of the time mon and mgr will be co-located, so we could treat mgr as a special case and collect the "ceph mgr" commands in the ceph_mgr plugin , but that would end up as an exception to the rule that all the "ceph ..." commands would be in the ceph_mon and therefore to be found in the sos_commands/ceph_mon folder.  

So for sake of consistency, I think all the "ceph ..." commands should be collected by the mon, and the ceph daemon XXX and other commands (like ceph daemon ...) can be collected in individual plugins. 

Please let me know what you think.
