### ISSUE TITLE
insights.parsers.df.DiskFree_LI  and insights.parsers.df.DiskFree_ALP are missing from site-packages/insights/specs/sosarchive.py

### ISSUE THREAD

**Issue by rameshsahoo111** [sosreport/sos#2798]
Hello Team,

I am writing an insights rule that requires checking filesystem inode uses. I request to add respective file reference for insights.parsers.df.DiskFree_LI  and insights.parsers.df.DiskFree_ALP to the site-packages/insights/specs/sosarchive.py

I checked that in site-packages/insights/specs/sosarchive.py file, the commands df_li and df_alp are missing. After registering them manually, I can get the expected result. 

```
df__li = first_file(["sos_commands/filesys/df_-ali_-x_autofs"])
 
(gss-rules) ⌊gss-rules⌋»$ insights-inspect insights.parsers.df.DiskFree_LI /tmp/sosreport-test
IPython Console Usage Info:
Enter 'DiskFree_LI.' and tab to get a list of properties 
Example:
In [1]: DiskFree_LI.<property_name>
Out[1]: <property value>
To exit ipython enter 'exit' and hit enter or use 'CTL D'
Starting IPython Interpreter Now
In [1]: %config Completer.use_jedi = False
In [2]: DiskFree_LI.get_mount("/var/log")
Out[2]: Record(filesystem='/dev/mapper/vg00-lv_var_log', total='1448', used='468', available='980', capacity='33%', mounted_on='/var/log')
```

**Comment by TurboTurtle** [comment]
I'm a little confused as to what you're asking for exactly.

Are you wanting to add new insights specs? Or are you wanting sos to collect new command output for `df -li` and `df -alp`?

If the first one, this is the wrong github repo for that. You'd need to open this request in the insights repo.

If the latter - we already collect `df -ali` and `df -al` in the filesystem plugin. Do you need `-p` added to the second collection (or a new, separate collection with `-p`?)

**Comment by TurboTurtle** [comment]
Closing this assuming this was posted to the wrong repo. If not, please feel free to reopen and clarify from my comment above.

**Comment by rameshsahoo111** [comment]
I want to check inode uses from the sosreport which is available at sos_commands/filesys/df_-ali_-x_autofs file but soarchive.py file doesn't have any reference to that path.  Hence I want to add the following line to  site-packages/insights/specs/sosarchive.py file. 

  df__li = first_file(["sos_commands/filesys/df_-ali_-x_autofs"])

**Comment by TurboTurtle** [comment]
>  but soarchive.py file doesn't have any reference to that path. Hence I want to add the following line to site-packages/insights/specs/sosarchive.py file.
> 

This file is not maintained by the sos project/team. You need to engage with the Insights team to make this change.

**Comment by rameshsahoo111** [comment]
Hello this spec has to be added for the sosreport in the site-packages/insights/specs/sosarchive.py file but not to the shared_rules/specs/sos_archive.py. The file site-packages/insights/specs/sosarchive.py is maintained by the insights core team so I can't request for the same to the sos project/team.

**Comment by TurboTurtle** [comment]
> site-packages/insights/specs/sosarchive.py

This is not our file. We do not ship this. It is not provided by the sos package. Because of that, we cannot make any changes to that file here. You need to engage with the relevant insights team to make this change. The sos team/project cannot help you here.
