### ISSUE TITLE
Typo in help output for sos collect 

### ISSUE THREAD

**Issue by jc305697** [sosreport/sos#2802]
Hello, 
I just wanted to let you know that there is a typo in the following line obtained in the output for sos collect --help on RHEL 8:

--clean, --mask Obfuscate sensistive information

It should be sensitive instead of sensistive . 

I couldn't really find which file generates this specific output so I can't open a pull request for the moment. 

Cheers,
Jeremy

**Comment by TurboTurtle** [comment]
Good eye! For reference, this is in https://github.com/sosreport/sos/blob/main/sos/collector/__init__.py#L419 (and seems a copy-paste has it in https://github.com/sosreport/sos/blob/main/sos/report/__init__.py#L345 as well) if you want to submit a fix.

**Comment by jc305697** [comment]
I will try again to do a pull request tomorrow in the evening but this time I will do it the right way :) .
