### ISSUE TITLE
add_copy_spec_limit() is limited

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#281]
The add_copy_spec_limit() interface has always been a bit of a hack. Size limits are applied during setup() to the result of applying glob expansion to the copyspec argument. Paths that pass the test are subsequently passed to add_copy_spec() with no limit. Since the glob results can include directories this is obviously broken for any glob that would include a directory in its expansion.

This can definitely be improved:
- Stat files during setup() and get an estimate of the report size
  - can't easily estimate command output size
- Apply limits during collect()
- Separate global, plugin and file limits

It's not really clear how the limit should be applied to paths that include directories; if we're going to allow the limit interface to be used with directories we should define how it's applied. E.g. collect files in the order returned by sorting the  result of os.walk() for each item that matches a copyspec.

Having a global limit (and a default plugin limit) would fix the general concerns raised in Issue #150.

**Comment by TurboTurtle** [comment]
Closing this as `add_copy_spec_limit()` no longer exists, and we now implicitly set limits to each file pattern added via `add_copy_spec()`.
