### ISSUE TITLE
Allow filtering log files by timestamp

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#284]
Extend add_copy_spec() interface for time filtering:
- Try to filter log time stamps for specified time range
- On failure to match or other error fall back to inode mtime

**Comment by pmoravec** [comment]
I would like to review this improvement (and ideally implement it (by myself)):

- should there be just a new option to `add_copy_spec()` or is it worth splitting the method to "copy spec" (mainly configs that should be collected all) and "copy logs" (that shall be more filtered based on time/size)? I was inclined to the split but now I feel it won't get much benefit other than methodological.

- two options should be added?
  - "older than": collect only logs older than given number of (days?)
  - newer than": collect only logs newer than given number of (days?)
  - I think we should keep the specification of interval very simple, error-prone, and # days is a worth compromise here (maybe `pcp` or few others require hours?)
  - we will filter files against their `mtime`

- if both `sizelimit` and `[older|newer]_than` filters applied, *both* will be applied altogether (if one wants to collect logs from past week regardless of size, use `sizelimit=0`).

**Comment by pmoravec** [comment]
Closing in favour of https://github.com/sosreport/sos/pull/1747
