### ISSUE TITLE
[low prio] a_s_c should skip collecting (all) binary files instead of tailing them due to sizelimit

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#2851]
Reproducer on Red Hat distros:

    sos report -o rpm -k rpm.rpmdb=true

will attempt to collect `/var/lib/rpm/Packages` which is a binary file often >25MB big. So we get an unusable tail.

Currently, we skip collecting tail of *some* binary files, those matching https://github.com/sosreport/sos/blob/main/sos/report/plugins/__init__.py#L69. It is worth expanding the check to more evident binary files, BUT we should be careful here:

- there is no simple and/or reliable heuristic to detect a file is binary (cf. the discussion about `file_is_binary` in cleaner, though there the heuristic can be more strict)
- the heuristic "is_binary" in `report` should rather return false negative than *any* false positive result. We should skip tailing *just* files we are sure they are binary.

I dont see much reliable way how to improve current situation in `report` in this aspect. Until somebody gets an idea, I am also fine closing this as a known limitation.

**Comment by TurboTurtle** [comment]
It's crude, but would it be viable for us to call `file --mime-type $filename` in this case, and filter out anything that has an `application/*` mime-type?
