### ISSUE TITLE
[cleaner] broken symlinks due to parsers enhancing maps after a symlink is processed by cleaner

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#2852]
Generic reproducer:

- parsers load map files (cleaner executes whole `preload_all_archives_into_maps`)
- obfuscation of some files processes symlink like `foo.bar.example.com -> qux.bar.example.com`
- some parser (e.g. hostname one) detects `bar.example.com` as a new domain
- processing `qux.bar.example.com` renames the filename but symlink from `foo.bar` remains the broken one, keeping original (non-obfuscated) symlink destination

Theoretical fix: during obfuscation, keep the list of *already* processed symlinks. When adding any new item to a parser's mapping, traverse the list to optionally obfuscate the symlinks.

**Comment by TurboTurtle** [comment]
The other option we have is to skip all symlinks during our regular iteration, track them in some separate list, and then after everything else is processed iterate over the symlinks together.

**Comment by pmoravec** [comment]
I like the simplistic approach!
