### ISSUE TITLE
[4.3] sos.help is ignored at package build time

### ISSUE THREAD

**Issue by slashdd** [sosreport/sos#2860]
It's causing runtime issue once sos 4.3 is built (DEB package here) due to lack of `sos.help` module presence.

```
$ sos report 
Traceback (most recent call last):
  File "/usr/bin/sos", line 21, in <module>
    sos = SoS(sys.argv[1:])
  File "/usr/lib/python3/dist-packages/sos/__init__.py", line 62, in __init__
    import sos.help
ModuleNotFoundError: No module named 'sos.help'
```

Adding the following before the build process fixes the issue by including `sos.help` in the mix:

`setup.py`
```
     packages=[
-        'sos', 'sos.presets', 'sos.presets.redhat', 'sos.policies',
+        'sos', 'sos.help', 'sos.presets', 'sos.presets.redhat', 'sos.policies',
```

**Comment by pmoravec** [comment]
Good catch, https://github.com/sosreport/sos/pull/2861 should fix that (and also two other relevant bits).
