### ISSUE TITLE
[report] Not able to set timeout using "plugin_timeout" attribute. 

### ISSUE THREAD

**Issue by NikhilKakade-1** [sosreport/sos#2863]
@TurboTurtle @pmoravec 
Not able to set plugin timeout.
As per [document](https://sos.readthedocs.io/en/main/plugins.html), the timeout of an individual plugin can be set using `plugin_timeout`.

Explicitly added `sleep 10` and `plugin_timeout=1`

<img width="632" alt="Screenshot 2022-02-17 at 9 55 53 AM" src="https://user-images.githubusercontent.com/66179696/154406320-7a7e35b4-537f-4373-a03f-d9976baf6f22.png">

### RESULT
<img width="632" alt="Screenshot 2022-02-17 at 9 55 29 AM" src="https://user-images.githubusercontent.com/66179696/154406165-befdcd2f-5638-4f32-af55-4678582360f9.png">

**Comment by pmoravec** [comment]
Indeed, when I collect e.g. `foreman` plugin, I see in generated `sos_reports/manifest.json` :

            "plugins": {
                "foreman": {
                    ..
                    "timeout": 300,
