### ISSUE TITLE
[etcd] Support containerized etcd

### ISSUE THREAD

**Issue by vikas-goel** [sosreport/sos#2906]
This is etcd plugin enhancement request to add support for the service running in container form factor.

**Comment by vikas-goel** [comment]
- I see rabbitmq plugin has support for both running directly on OS and inside container. https://github.com/sosreport/sos/blob/main/sos/report/plugins/rabbitmq.py#L29. The assumption is that the container name starts with the service name which is good for me.
- Whatever is collected in the current plugin when etcd runs directly on the OS should be good enough
- Not that I can think of
- I am not sure what `master-exec` wrapper is. It doesn't exist in my deployment

**Comment by TurboTurtle** [comment]
Sorry for the silence on this, been wrapped up in other initiatives recently.

After some digging, it appears `master-exec` is no longer used, and it was only part of Origin.

We can update the plugin for current deployments, however I'd need some guidance on the current state of etcd.

- Are the current set of commands (`--version`, `member list`, `cluster-health`, `ls --recursive`) sufficient? Do we need to build that out at all?
- The etcd plugin currently tries to determine an etcd listening address and performs a `curl` against specific end points. Is this still relevant?

**Comment by vikas-goel** [comment]
> Sorry for the silence on this, been wrapped up in other initiatives recently.
> 
> After some digging, it appears `master-exec` is no longer used, and it was only part of Origin.
> 
> We can update the plugin for current deployments, however I'd need some guidance on the current state of etcd.
> 
> * Are the current set of commands (`--version`, `member list`, `cluster-health`, `ls --recursive`) sufficient? Do we need to build that out at all?
> * The etcd plugin currently tries to determine an etcd listening address and performs a `curl` against specific end points. Is this still relevant?

The commands look good. The curl from host won’t be allowed when running etcd inside container because of security policy. The curl inside the container should be fine, though.
