### ISSUE TITLE
Distro detection crashes in bare bones container

### ISSUE THREAD

**Issue by SuperSandro2000** [sosreport/sos#2928]
I am currently working on bare bones container which only contains sos and all strictly necessary dependencies without any shell.
Because of that ``/etc/lsb-release`` and similar files are also not existing.
When running sos it crashes with the following error:

```
root@7c51f4770da2:/# sosreport
Please note the 'sosreport' command has been deprecated in favor of the new 'sos' command, E.G. 'sos report'.
Redirecting to 'sos report '
WARNING: Unable to read configuration file /etc/sos/sos.conf : No such file or directory

sosreport (version 4.3)

plugin clear_containers does not install, skipping: 'GenericPolicy' object has no attribute 'init_system'
plugin cloud_init does not install, skipping: 'GenericPolicy' object has no attribute 'init_system'
plugin cockpit does not install, skipping: 'GenericPolicy' object has no attribute 'init_system'
plugin cups does not install, skipping: 'GenericPolicy' object has no attribute 'init_system'
plugin devicemapper does not install, skipping: 'GenericPolicy' object has no attribute 'kernel_mods'
plugin fwupd does not install, skipping: 'GenericPolicy' object has no attribute 'init_system'
plugin gdm does not install, skipping: 'GenericPolicy' object has no attribute 'init_system'
plugin lightdm does not install, skipping: 'GenericPolicy' object has no attribute 'init_system'
plugin opencontrail does not install, skipping: 'GenericPolicy' object has no attribute 'runtimes'
plugin powerpc does not install, skipping: 'GenericPolicy' object has no attribute 'get_arch'
plugin s390 does not install, skipping: 'GenericPolicy' object has no attribute 'get_arch'
plugin snap does not install, skipping: 'GenericPolicy' object has no attribute 'init_system'
Traceback (most recent call last):
  File "/nix/store/zf0k29fh2d4zlki0sg93gl1zp9iz4w7g-python3.9-sosreport-4.3/bin/.sosreport-wrapped", line 34, in <module>
    sos.execute()
  File "/nix/store/zf0k29fh2d4zlki0sg93gl1zp9iz4w7g-python3.9-sosreport-4.3/lib/python3.9/site-packages/sos/__init__.py", line 188, in execute
    self._component.execute()
  File "/nix/store/zf0k29fh2d4zlki0sg93gl1zp9iz4w7g-python3.9-sosreport-4.3/lib/python3.9/site-packages/sos/report/__init__.py", line 1587, in execute
    self.batch()
  File "/nix/store/zf0k29fh2d4zlki0sg93gl1zp9iz4w7g-python3.9-sosreport-4.3/lib/python3.9/site-packages/sos/report/__init__.py", line 1002, in batch
    msg = self.policy.get_msg()
  File "/nix/store/zf0k29fh2d4zlki0sg93gl1zp9iz4w7g-python3.9-sosreport-4.3/lib/python3.9/site-packages/sos/policies/__init__.py", line 608, in get_msg
    return self.msg % {'distro': self.system}
KeyError: 'vendor'
```

If I just touch ``/etc/lsb-release`` it no longer crashes.

**Comment by TurboTurtle** [comment]
Is `GenericPolicy` still loaded when you touch lsb-release? Or does another policy load? The `KeyError` seems unlikely to be _directly_ resolved just by file presence at first glance.

**Comment by SuperSandro2000** [comment]
I ran the sos command instead of sosreport when I verified the workaround and just creating the file is not enough.

Out of curiosity: Isn't it a bug that the GenericPolicy is missing vendor?

That is the output when I run it without the above mentioned not working workaround:

```
Please note the 'sosreport' command has been deprecated in favor of the new 'sos' command, E.G. 'sos report'.
Redirecting to 'sos report '
WARNING: Unable to read configuration file /etc/sos/sos.conf : No such file or directory

sosreport (version 4.3)

plugin clear_containers does not install, skipping: 'GenericPolicy' object has no attribute 'init_system'
plugin cloud_init does not install, skipping: 'GenericPolicy' object has no attribute 'init_system'
plugin cockpit does not install, skipping: 'GenericPolicy' object has no attribute 'init_system'
plugin cups does not install, skipping: 'GenericPolicy' object has no attribute 'init_system'
plugin devicemapper does not install, skipping: 'GenericPolicy' object has no attribute 'kernel_mods'
plugin fwupd does not install, skipping: 'GenericPolicy' object has no attribute 'init_system'
plugin gdm does not install, skipping: 'GenericPolicy' object has no attribute 'init_system'
plugin lightdm does not install, skipping: 'GenericPolicy' object has no attribute 'init_system'
plugin opencontrail does not install, skipping: 'GenericPolicy' object has no attribute 'runtimes'
plugin powerpc does not install, skipping: 'GenericPolicy' object has no attribute 'get_arch'
plugin s390 does not install, skipping: 'GenericPolicy' object has no attribute 'get_arch'
plugin snap does not install, skipping: 'GenericPolicy' object has no attribute 'init_system'
Traceback (most recent call last):
  File "/nix/store/zf0k29fh2d4zlki0sg93gl1zp9iz4w7g-python3.9-sosreport-4.3/bin/.sosreport-wrapped", line 34, in <module>
    sos.execute()
  File "/nix/store/zf0k29fh2d4zlki0sg93gl1zp9iz4w7g-python3.9-sosreport-4.3/lib/python3.9/site-packages/sos/__init__.py", line 188, in execute
    self._component.execute()
  File "/nix/store/zf0k29fh2d4zlki0sg93gl1zp9iz4w7g-python3.9-sosreport-4.3/lib/python3.9/site-packages/sos/report/__init__.py", line 1587, in execute
    self.batch()
  File "/nix/store/zf0k29fh2d4zlki0sg93gl1zp9iz4w7g-python3.9-sosreport-4.3/lib/python3.9/site-packages/sos/report/__init__.py", line 1002, in batch
    msg = self.policy.get_msg()
  File "/nix/store/zf0k29fh2d4zlki0sg93gl1zp9iz4w7g-python3.9-sosreport-4.3/lib/python3.9/site-packages/sos/policies/__init__.py", line 608, in get_msg
    return self.msg % {'distro': self.system}
KeyError: 'vendor'
```

**Comment by TurboTurtle** [comment]
> I ran the sos command instead of sosreport when I verified the workaround and just creating the file is not enough.
> 

Is it the same error?

> Out of curiosity: Isn't it a bug that the GenericPolicy is missing vendor?
> 
Yes, it is. I was just saying that touching `/etc/lsb-release` shouldn't resolve the key error, so we may have 2 things going on here.

That being said, we haven't really ever seen a use case for `GenericPolicy` in a real world application of sos. Moreso if this is from a container - container based executions of sos have historically been to capture from containerized _hosts_ - which would cause sos to look at the host's `/etc/(lsb|os)-release` file instead when the container is configured correctly.

We can absolutely fix `GenericPolicy`, of course, but I'm curious what the intent here is - are you trying to capture from the host via a container or from within the container sos is run from?

> That is the output when I run it without the above mentioned not working workaround:

Right, but what is the error with the workaround in place?

**Comment by SuperSandro2000** [comment]
> Is it the same error?

No, `sos` itself does not error, only ``sosreport``/``sos report``.

> Moreso if this is from a container - container based executions of sos have historically been to capture from containerized _hosts_ - which would cause sos to look at the host's `/etc/(lsb|os)-release` file instead when the container is configured correctly.

We tried that, too but we are using flatcar linux on the host from where ``sos report`` is executed which is not detected. I think the closest already supported distro is CoreOS.

```ShellSession
$ cat /etc/os-release
NAME="Flatcar Container Linux by Kinvolk"
ID=flatcar
ID_LIKE=coreos
VERSION=3185.1.0
VERSION_ID=3185.1.0
BUILD_ID=2022-04-05-1730
SYSEXT_LEVEL=1.0
PRETTY_NAME="Flatcar Container Linux by Kinvolk 3185.1.0 (Oklo)"
ANSI_COLOR="38;5;75"
HOME_URL="https://flatcar-linux.org/"
BUG_REPORT_URL="https://issues.flatcar-linux.org"
FLATCAR_BOARD="amd64-usr"
CPE_NAME="cpe:2.3:o:flatcar-linux:flatcar_linux:3185.1.0:*:*:*:*:*:*:*"
$ cat /etc/lsb-release
DISTRIB_ID="Flatcar Container Linux by Kinvolk"
DISTRIB_RELEASE=3185.1.0
DISTRIB_CODENAME="Oklo"
DISTRIB_DESCRIPTION="Flatcar Container Linux by Kinvolk 3185.1.0 (Oklo)"
```

> are you trying to capture from the host via a container or from within the container sos is run from?

From the host where the container is running on.



> Right, but what is the error with the workaround in place?

It didn't change anything. The error stayed the same with and without the error.

**Comment by TurboTurtle** [comment]
Ack. So we do have two issues to address here:

1. Fix `GenericPolicy` to load properly.
2. Create a new policy for `Flatcar Linux`

Item 1 I think we can directly fix quite easily, however writing a test case for it will be...interesting.

For item 2, we'll want to do this so that there is some measure of control for plugin enablement beyond those tagged as `IndependentPlugin`s. This also provides for policy control of PATHs, potential for upload targets, presets, etc...

I can do that, or if you'd prefer to create the policy that's fine too. Just let me know.

One thing I'd like to highlight though is for collecting-from-host-with-sos-in-a-container requires a couple things to function correctly:

- The host's `/` must be volume mounted to the container
- The `HOST` env var must be set to this location. E.G. the registry.redhat.io/rhel8/support-tools container mounts the hosts `/` to `/host` in the container and then sets the `HOST` env var to `/host`.
- You'll want to make it a privileged container, and use the host's namespaces. Look at the `RUN` label on the support-tools image mentioned above for a good example of how to set the container up for host collections.

**Comment by TurboTurtle** [comment]
@SuperSandro2000 just checking in - is there a desire for a Flatcar Linux policy?

**Comment by TurboTurtle** [comment]
@SuperSandro2000 is there still a desire for a Flatcar Linux policy?

**Comment by SuperSandro2000** [comment]
> Fix `GenericPolicy` to load properly.

I think that would be good enough for our use case for now. Thanks for fixing that already.
I will let you know if we need flatcar support in the future.

**Comment by TurboTurtle** [comment]
Ack, thanks for the confirmation. Closing this one out then. If you need a Flatcar policy in the future, just open a new issue for one.
