### ISSUE TITLE
[testing] Build and install for each stage?

### ISSUE THREAD

**Issue by TurboTurtle** [sosreport/sos#2933]
Our tests currently rely on running from the checkout that `cirrus` provides to each VM upon setup.

We also have distinct tests for an install via distutils, and building an RPM, but we don't link those in any way. Meaning, we don't use those artifacts for the later tests.

I'd like to discuss changing that, so that our pipeline becomes:

flake/lgtm checks -> distutils install works check -> build package artifacts -> stageone w/artifacts -> stagetwo -> etc...

Cirrus provides the ability to save artifacts and load them into later tasks, so this is entirely feasible from a technical standpoint.

The things we'd need to cover or change, in no particular order:

-  Do we change the avocado tests to **only** use a locally installed version? Or do we have some toggle to flip between locally installed and running from a checkout? On the surface, I think this would be trivial to implement.
- We'd need to build `.deb`s to provide testing coverage for Ubuntu/Debian.
    - I personally have no experience with these builds. @BryanQuigley @slashdd @ddstreet - what would need to be added to the repo to support local builds?
- For RPMs, is there a way to consume the packit builds within cirrus? Or should we just do this "internally" to cirrus and leave packit for manual testing?
- (Quick review) do we have any distros that would need packaging other than rpms/debs and should be added to the testing matrix?

**Comment by ddstreet** [comment]
> what would need to be added to the repo to support local builds?

assuming it's being built on debian/ubuntu, the only things needed would be 1) a 'debian/' subdirectory with the appropriate build config files (similar to an rpm 'spec' file), and 2) the build dependencies, which you can install (once the debian/ dir is in place) by running 'sudo apt build-dep .' from the top level of the source dir (where the debian/ dir is located). Then you can simply build with 'dpkg-buildpackage' and the resulting deb files will be in the parent dir.

**Comment by arif-ali** [comment]
we ought to add some testing of snaps as well, considering I had issues on bionic earlier today.

So, build snap, install built snap and then do a simple sos report on all supported platforms?

**Comment by TurboTurtle** [comment]
That's perfectly fine - I have this on my short list for sos-4.5, so I should be getting to work on it (for RPM distros anyways) sooner than later. If you're willing to contribute the bits needed to handle snap builds, then we can fold that into the Cirrus runs for the applicable distros.

**Comment by TurboTurtle** [comment]
The snap builds are done and in use, though there is a question about which python is in use in #3044.

The only potential outstanding item is building a .deb. @arif-ali or @ddstreet is that desired at this point, or is testing with the snap packaging sufficient?

**Comment by arif-ali** [comment]
We are currently discussing this between ourselves on the best way forward for the deb.

Wrt the snap issue, I will try and work this out and see what I can find. I will update the team once I've worked it out, and the best way forward on testing using the snap

**Comment by TurboTurtle** [comment]
Closing this out as it seems snap testing is sufficient. If this changes, feel free to open a PR with the changes needed to build a `.deb`.
