### ISSUE TITLE
Change default locale of command from C to C.UTF-8?

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#2946]
There have been a few cases where `sos report` failed to collect some commands output on a localised environments (French, Czech, Japanese,.. locales) due to default `LC_ALL=C` environment set (https://github.com/sosreport/sos/blob/caabbe5cfd28cedb34e92f4cee7dfaad5fdff3e9/sos/utilities.py#L162) that can't cope with non-ASCII characters in commands outputs. A possible solution would be changing the locale to `C.UTF-8`.

We can do so on per-command basis as the individual issues are reported, or we can change the default. Which might have unexpected potential corner issues.

Any thoughts on this?

**Comment by TurboTurtle** [comment]
@bmr-cymru thanks for that PEP!

After reading through it a bit, I'm more in favor on changing to doing this broadly as our new default. We'll want to spend some extra time testing this on different envs, of course.

**Comment by bmr-cymru** [comment]
This is pretty much a reliable fix-all for any affected Python program - my only worry is that there might be other (non-Python) programs out there that do the wrong thing when they see C.UTF-8 - it's quite possible I'm being paranoid, and I have no examples, but it might be worth a few tests on systems with funny character sets and where we get a lot of plugin/command coverage.
