### ISSUE TITLE
sosreport does not capture contents of /dev 

### ISSUE THREAD

**Issue by mamatha4** [sosreport/sos#2966]
sosreport does not capture contents of /dev directory. This can sometime result in additional request for data capture. One such recent example is [comment 25] RH2017121 

$ cd sosreport-2022-06-29-dphxrdh/
$ ls
boot         free            lsmod    ps            sos_logs     var
date         hostname        lsof     pstree        sos_reports  version.txt
dev          installed-rpms  mount    root          sys          vgdisplay
df           ip_addr         netstat  route         uname
environment  last            pmstat   run           uptime
etc          lib             proc     sos_commands  usr

$ cd dev
$ ls
nvram

$ ls -l
total 0
crw-------. 1 root root 10, 144 Jun 29 03:13 nvram

$ uname -r
5.14.0-119.el9.ppc64le
 

/dev contains lot of files on the actual system.
$ cd /dev
$ ls
autofs           hvc7               sda3    tty20  tty42  tty7     vcsa3
block            hwrng              sg0     tty21  tty43  tty8     vcsa4
bsg              initctl            shm     tty22  tty44  tty9     vcsa5
char             input              snd     tty23  tty45  ttyS0    vcsa6
console          kmsg               SRC     tty24  tty46  ttyS1    vcsa7
core             log                stderr  tty25  tty47  ttyS2    vcsa8
cpu_dma_latency  loop-control       stdin   tty26  tty48  ttyS3    vcsu
crypto           mapper             stdout  tty27  tty49  uhid     vcsu1
disk             mem                tpm0    tty28  tty5   uinput   vcsu2
dm-0             mqueue             tpmrm0  tty29  tty50  urandom  vcsu3
dm-1             net                tty     tty3   tty51  usbmon0  vcsu4
dm-2             null               tty0    tty30  tty52  vas      vcsu5
dma_heap         nvram              tty1    tty31  tty53  vcs      vcsu6
fd               ppp                tty10   tty32  tty54  vcs1     vcsu7
full             ptmx               tty11   tty33  tty55  vcs2     vcsu8
fuse             pts                tty12   tty34  tty56  vcs3     vfio
hugepages        random             tty13   tty35  tty57  vcs4     vga_arbiter
hvc0             rfkill             tty14   tty36  tty58  vcs5     vhci
hvc1             rhel_ltcden14-lp7  tty15   tty37  tty59  vcs6     vhost-net
hvc2             rtc                tty16   tty38  tty6   vcs7     vhost-vsock
hvc3             rtc0               tty17   tty39  tty60  vcs8     zero
hvc4             sda                tty18   tty4   tty61  vcsa
hvc5             sda1               tty19   tty40  tty62  vcsa1
hvc6             sda2               tty2    tty41  tty63  vcsa2

**Comment by pmoravec** [comment]
`sos report` does not collect everything (as a reaction on wrong deduction in the RHBZ that triggered some confusion, that "I dont see /dev/SOMETHING in sosreport, so it was missing in the system..?").

Could you please elaborate what in particular is requested to collect from `/dev` and why? E.g. `/dev/[sv]d*` or `/dev/tty*` or `/dev/zero` are quite surely not requested to be collected, right? ;-)

**Comment by mamatha4** [comment]
As per RHBZ I think developer was looking for block data..
Can we add following data in sosreport
1) /dev/block
2) /dev/char
3) /dev/hugepages/

**Comment by TurboTurtle** [comment]
We could add directory listing collections, however the problem with collecting from those locations is that they are symlinks to actual devices.

E.G. `add_copy_spec('/dev/block/*')` would end up trying to copy the _whole device_ backing the symlinks.

**Comment by mamatha4** [comment]
you are right...what I observed is all symlinks are pointing to /sys/devices/ as below

# ls -al /sys/block/
total 0
drwxr-xr-x.  2 root root 0 Jun 21 03:15 .
dr-xr-xr-x. 12 root root 0 Jun 21 03:15 ..
lrwxrwxrwx.  1 root root 0 Jun 21 03:15 dm-0 -> ../devices/virtual/block/dm-0
lrwxrwxrwx.  1 root root 0 Jun 21 03:15 dm-1 -> ../devices/virtual/block/dm-1
lrwxrwxrwx.  1 root root 0 Jun 21 03:15 dm-2 -> ../devices/virtual/block/dm-2
lrwxrwxrwx.  1 root root 0 Jun 21 03:15 sda -> ../devices/vio/30000068/host0/target0:0:1/0:0:1:0/block/sda
lrwxrwxrwx.  1 root root 0 Jun 21 03:15 sdb -> ../devices/vio/30000068/host0/target0:0:2/0:0:2:0/block/sdb

and again we are not collecting all dir under /sys/devices any reason for that?
sosreport is collecting only following dir data

# ls sosreport-2022-06-29-wemtohy/sys/devices/
system  vio  virtual

On system I am seeing following dir's under /sys/devices

# ls  /sys/devices/
breakpoint  cpu  hv_24x7  hv_gpci  kprobe  platform  software  system  tracepoint  uprobe  vio  virtual
 
Would like to know, on what basis we are collecting data of /sys in sosreport

**Comment by TurboTurtle** [comment]
> and again we are not collecting all dir under /sys/devices any reason for that?

Using latest sos, we do in fact collect the /sys/block symlinks:

```
[jake@terra sosreport-terra-2022-06-29-diovaow]$ pwd
/home/jake/sostmp/sosreport-terra-2022-06-29-diovaow
[jake@terra sosreport-terra-2022-06-29-diovaow]$ ls sys/block/
dm-0  dm-1  dm-2  nvme0n1  sda  sdb  sr0  zram0
[jake@terra sosreport-terra-2022-06-29-diovaow]$ ll sys/block/
total 0
lrwxrwxrwx. 1 jake jake 29 Jun 25 15:19 dm-0 -> ../devices/virtual/block/dm-0
lrwxrwxrwx. 1 jake jake 29 Jun 25 15:19 dm-1 -> ../devices/virtual/block/dm-1
lrwxrwxrwx. 1 jake jake 29 Jun 25 15:19 dm-2 -> ../devices/virtual/block/dm-2
lrwxrwxrwx. 1 jake jake 66 Jun 25 15:19 nvme0n1 -> ../devices/pci0000:00/0000:00:01.1/0000:01:00.0/nvme/nvme0/nvme0n1
lrwxrwxrwx. 1 jake jake 88 Jun 25 15:19 sda -> ../devices/pci0000:00/0000:00:01.3/0000:02:00.1/ata1/host0/target0:0:0/0:0:0:0/block/sda
lrwxrwxrwx. 1 jake jake 88 Jun 25 15:19 sdb -> ../devices/pci0000:00/0000:00:01.3/0000:02:00.1/ata2/host1/target1:0:0/1:0:0:0/block/sdb
lrwxrwxrwx. 1 jake jake 88 Jun 25 15:19 sr0 -> ../devices/pci0000:00/0000:00:01.3/0000:02:00.1/ata5/host4/target4:0:0/4:0:0:0/block/sr0
lrwxrwxrwx. 1 jake jake 30 Jun 25 15:19 zram0 -> ../devices/virtual/block/zram0

```

As Pavel mentioned above, we don't just arbitrarily grab the entire structure of `/sys` or other parts of the filesystem. 


> Would like to know, on what basis we are collecting data of /sys in sosreport 

The basis is that there is some rationale to collect what is gathered into an archive. If we don't collect something it is likely because no one has ever asked that it be collected. What is the use case for these collections? What kind of troubleshooting is hampered by these not being present in an archive?

**Comment by mamatha4** [comment]
Thanks for the detailed info... will check and list what are the required data we are looking in /sys and /dev

**Comment by TurboTurtle** [comment]
Closing this out at this time. If there are further specific requests for collections from `/sys` or `/dev`, please feel free to re-open or directly open a PR with the changes.
