### ISSUE TITLE
[archive] review IO exception handling to ensure non-root cases are handled properly

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#298]
Make sure exception handling during `SoSReport.collect()` does the right thing for the non-root case. For files that cannot be read by the user running sos log the fact and do not include an empty file in the archive.

**Comment by TurboTurtle** [comment]
Tagging this for `4.0` to discuss alongside the decision of if we want to support non-root runs at all going forward.

**Comment by TurboTurtle** [comment]
As we no longer support non-root runs of `sos report`, I'm closing this out.
