### ISSUE TITLE
collect mysqlrouter files (logs + sanitized config)

### ISSUE THREAD

**Issue by rodrigogansobarbieri** [sosreport/sos#2987]
Currently mysqlrouter files located at /var/lib/mysql/<mysql-router-folder>/ such as mysqlrouter.conf and log files at ./log are not collected.

It would be useful to collect sanitized config files and logs related to mysqlrouter to diagnose issues.

**Comment by TurboTurtle** [comment]
We can definitely add collections, however I'd like to clarify some points here first.

1. [Upstream documentation](https://dev.mysql.com/doc/mysql-router/8.0/en/mysql-router-configuration-file-locations.html) doesn't list `/var/lib/mysql/` as a default location. Only `/etc/mysqlrouter/` and `$HOME/.mysqlrouter.conf`. Is there a distribution where `/var/lib` is the default location? I actually only found a single mention of mysqlrouter in all of RH docs, so I'm assuming this component doesn't see much use there.

2. Can you please clarify the log file location?

3. Again taking a quick look at the upstream docs, there doesn't seem to be any particularly sensitive keys. Are there certain keys you think we'll need to obfuscate for collections?

**Comment by rodrigogansobarbieri** [comment]
Hi

Actually I just realized that the config file location is defined by who bootstraps the router, so it could be anywhere, would be up to them to put it in a standard location.

Yea the config file doesn't have sensitive data, the sensitive data is the cert files in the folder, but as long they are not collected it is fine.
