### ISSUE TITLE
Multus network-attach-def ipv6 is not obfuscated

### ISSUE THREAD

**Issue by ansvu** [sosreport/sos#3008]
Does sos clean 4.4 support ipv6 yet? 
I ran the test using sos clean 4.4, but it seems not cleaned those ipv6.
 Add: mvnr-du:du-ddc7f8cb6-qqw8p:3a88000e-bfe3-436e-b810-b2bd290fb66a:mvnr-du/du-f1c-conf(sriov):f1c {"cniVersion":"0.4.0","interfaces":[{"name":"f1c","sandbox":"/var/run/netns/4239d766-68e8-4c74-a983-6e4edf2583d3"}],"ips":[{"version":"6","interface":0,"address":"2607:c540:8c00:3318::34/64","gateway":"2607:c540:8c00:3318::1"}],"routes":[{"dst":"::/0"}],"dns":{}}

Thanks.

**Comment by TurboTurtle** [comment]
No, `clean` does not yet have support for ipv6 network address. There is support for ipv6 mac addrs, but that's it.

**Comment by ansvu** [comment]
Thank you, TT. Just wonder if you have this ipv6 feature support in the future?

**Comment by TurboTurtle** [comment]
It's definitely on the list. The actual matching of addresses is not really an issue - the stance we have on consistent network topology after obfuscation is however.

By this I mean, with ipv4 we maintain network topology and relationships with addresses. If we find an address from a new subnet, we create a new obfuscation subnet and assign addresses from there - it's not complete random assignment or even scrubbing an address to simply "--obfuscated_addr_0001--". This was a conscious decision made at the request of RH support teams (as a quick example, having topology consistent addressing can highlight a routing issue whereas scrubbing all addresses to "addr_XYZ" would hinder if not outright prevent that).

So, for ipv6 we would want to maintain that consistency. Given how much more complex ipv6 addressing is, and how the address format is malleable, this becomes fairly difficult to do within sos.

If there is another python module that has the ability to spit out addresses (e.g. "create an ipv6subnet object, and from it be able to generate addresses within that subnet on the fly") then that would make this implementation pretty straightforward actually.

**Comment by TurboTurtle** [comment]
@ansvu - I've just opened https://github.com/sosreport/sos/pull/3060 that I hope resolves this. If you are able, please try pulling either that branch or one of the generated RPMs and test it out and let us know if it works for you.
