### ISSUE TITLE
yum plugin merge stops collecting two optional commands

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#3024]
`Yum` plugin *optionally* collected `yum list` and/or `yum-debug-dump` commands output (in the latter case, content of the denerated dump file). Either command was triggered by a plugin option which was disabled by default.

Merging `yum` plugin into `dnf`, we loose collecting any equivalent data (available via `s/yum/dnf/g` in the commands)

Is there a desire to collect them again? On one side, an optional cmd output (and quite long) might not be worth to keep collecting. On the other side - we can still collect them optionally only.

**Comment by TurboTurtle** [comment]
When I did the plugin merge I got some ad-hoc feedback on those collections. From what I gathered they aren't really used, but admittedly that was from a small sample size.

I don't have a problem adding option-gated collections back in, but let's make sure they actually have a not-too-rare use case.

**Comment by pmoravec** [comment]
I had asked internally some broader audience, got no feedback, so I suppose there is no evident interest in either optional plugopt.
