### ISSUE TITLE
sos report -o krb5 not working

### ISSUE THREAD

**Issue by mschmitt** [sosreport/sos#3041]
Collection of Kerberos information fails as follows:

```
$ sudo bin/sos report --batch --only-plugins krb5

sosreport (version 4.4)

a non-existing plugin (krb5) was specified in the command line.
```

After this minor edit to **sos/report/plugins/krb5.py**, the report succeeds as expected:

```
$ git diff 
diff --git a/sos/report/plugins/krb5.py b/sos/report/plugins/krb5.py
index 0b7cabf8..c56368a3 100644
--- a/sos/report/plugins/krb5.py
+++ b/sos/report/plugins/krb5.py
@@ -8,10 +8,10 @@
 #
 # See the LICENSE file in the source distribution for further information.
 
-from sos.report.plugins import Plugin, RedHatPlugin
+from sos.report.plugins import Plugin, RedHatPlugin, IndependentPlugin
 
 
-class Krb5(Plugin):
+class Krb5(Plugin, IndependentPlugin):
 
     short_desc = 'Kerberos authentication'
     plugin_name = 'krb5'
```

The error can be reproduced without having to install any Kerberos related packages. With the additional class name in **krb5.py**, the report works on a Kerberos client as expected, and produces an empty report (also expected) if no Kerberos configuration is present.

**Comment by TurboTurtle** [comment]
What distribution are you wanting to collect this on?

The `krb5` plugin currently only has support for Red Hat distros (and has been that way for years it seems). The construction of the plugin is a bit odd, as we usually use that design pattern (base class with `Plugin` and nothing else), when we have multiple distros to support but they have different collection needs (i.e. further classes subclass `krb5` *and* a tagging class).

**Comment by mschmitt** [comment]
I discovered this on Ubuntu 22.04 (sosreport 4.3), but it also fails on Debian Testing (sosreport 4.0), with the difference that Debian requires "DebianPlugin" instead of "IndependentPlugin" in that place.

**Comment by TurboTurtle** [comment]
Ack.

Thanks for the report. It seems the Ubuntu/Debian support got inadvertently dropped as far back as sos-3.7. I'll whip something up for this that fits current plugin design patterns.

**Comment by mschmitt** [comment]
Sounds great, thanks for the super quick feedback. :+1:

**Comment by mschmitt** [comment]
Regarding the list of packages in the plugin, maybe note that Debian/Ubuntu don't have krb5-libs and krb5-server.

[apt-krb5.txt](https://github.com/sosreport/sos/files/9736177/apt-krb5.txt)
