### ISSUE TITLE
[buildsys] py3 builds for RPM distros

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#307]
Fedora is planning to switch to [py3 as default in Fedora 22](http://fedoraproject.org/wiki/Changes/Python_3_as_Default). Thanks to @battlemidget we have support for native py3 builds today but this isn't hooked up to the RPM spec file.

We don't need to make any changes to the RPM packaging for 3.2 as F21 will stay with py2 as default (so we've got another 6mo or so to throw the switch).

I started hacking around with this on branch [bmr-fedora-py3](https://github.com/sosreport/sos/branches/bmr-fedora-py3) but it needs more work to get it into a mergeable shape.

**Comment by TurboTurtle** [comment]
The Fedora spec has the py3 bits, but currently the master sos.spec still is using py2. Should we sync with the spec used in Fedora?

Also, noticed that the changelog is missing both the 3.6 and 3.7 releases.
