### ISSUE TITLE
[dnf] password/proxy_password directives in dnf.conf are not hidden by sosreport

### ISSUE THREAD

**Issue by miztake** [sosreport/sos#3072]
The dnf plugin tries to hide the password/proxy_password directive with ********.

https://github.com/sosreport/sos/blob/2556e64b36a1f312e331589dc77146e35c6941e8/sos/report/plugins/dnf.py#L127-L131

However, the /etc/dnf/dnf.conf where password/proxy_password would be written is out of scope.
We need to add /etc/dnf/dnf.conf as a file that hides password/proxy_password.

**Comment by brozs** [comment]
Working on a patch.
