### ISSUE TITLE
Allow sos collect to specify how sos report should be executed

### ISSUE THREAD

**Issue by facundofc** [sosreport/sos#3127]
This issue aims at solving #1844. The reasons for not fixing that are clear and understandable, but it remains a problem when using sos collect to gather sosreports from several nodes. sos collect doesn't provide any way of changing the how the sosreport process is executed.

Adding a flag to sos collect, allowing to specify a command to prepend to the sosreport command execution, would go a long way towards making this easier.

This could be done:

```
sos collect --nodes IP1,IP2,IP3 --exec 'ionice -c3' --batch
```
and that'd cause
```
ionice -c3 sos report --batch -c auto
```
to be executed on the remote hosts.

**Comment by pmoravec** [comment]
What a dilema (or trilema):

- either add to `sos` yet another optional/weak dependency, esp. here on AppStream. Which, despite it is optional, leads to installation yet another package by default, whenever available (at least in `dnf`, not sure about `apt-get` behaviour). Not ideal, but probably least unpleasant
- or we would implement the functionality from `python3-psutil` on our own, but why to reinvent the wheel?
- or we abandon to implement this feature

I lean to the first option, to add another dependency. BUT if the request is *just* "allow calling `sos` under `ionice -cX`", can't we add `--ionice-class` option that - only when set - will call `sos` under `ionice -cX` ?

**Comment by TurboTurtle** [comment]
> I lean to the first option, to add another dependency. BUT if the request is just "allow calling sos under ionice -cX", can't we add --ionice-class option that - only when set - will call sos under ionice -cX ?

That's also an option if we want to avoid the dependency. It'd be a simple implementation too - check that the binary exists and then simply shell out to our own pid.

I'll play around with this a little bit and see if there are any gotchas.
