### ISSUE TITLE
[acpid] review

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#313]
Collects logs with a glob:

```
[plugin:acpid] added copyspec '/var/log/acpid*'
[plugin:acpid] added copyspec '/etc/acpi/events/power.conf'
```

Plugin is potentially obsolete anyway.

**Comment by TurboTurtle** [comment]
Haven't heard any complaints about the plugin for years, and changes to globs and size limiting over the last few versions should prevent any unwanted behavior.
