### ISSUE TITLE
Order of the contents when building tar archives

### ISSUE THREAD

**Issue by juanmasg** [sosreport/sos#3139]
When writing tools that automate reading or extracting specific contents from a sosreport, I understand that it's expected that `version.txt` and the manifests under `sos_reports` are the parsed first, so such tools know what's available in the archive and can abort the task if a certain file is not there according to the manifest.
When accessing tar archives directly in memory without extracting them to the filesystem, the order of the files matter. In this case, if for example `version.txt` is the last file added to the archive, then the whole contents of the archive must be read only to know the sosreport version used.

My question is: does sosreport take care somehow of the order in which the contents are added to the tar archive?

If not, could we make sure in future versions that both `version.txt` and `sos_reports/` are the very first contents added to the tar file when building the archive?

This little change would bring a great performance improvement for such tools.

Thanks

**Comment by pmoravec** [comment]
Good idea! We use one `tar.add` call (https://github.com/sosreport/sos/blob/main/sos/archive.py#L702-L703) which adds whole sos working directory. I *think* `python` or the `tarfile` library orders the content alphabetically, hence `version.txt` is one of the latest.

It can be modified to something like (very draft):

    tar.add(self._archive_root + '/version.txt', arcname=self._name + '/version.txt')
    tar.add(self._archive_root + '/sos_reports', arcname=self._name + '/sos_reports')
    tar.add(self._archive_root, arcname=self._name,
            filter=self.copy_permissions_filter)

.. where the `self.copy_permissions_filter` is enhanced to return `None` for `version.txt` and `sos_reports` stuff (to prevent adding these twice).

Until somebody opposes, I can write a PR for it.

**Comment by juanmasg** [comment]
Thanks for checking @pmoravec !

I ran a couple of tests, it seems that when adding a full directory, the order of creation (inode number?) is followed, the same as the  command line version of `tar` does:

```
tmp% mkdir test                                                             
tmp% touch test/b.txt                                                       
tmp% touch test/z.txt                                                       
tmp% touch z.txt                                                            
tmp% touch test/a.txt                                                       
                                                                            
In [2]: import tarfile                                                      
In [3]: t = tarfile.open("test.tar.xz", "x:xz")                             
In [4]: t.add("test/")                                                      
In [5]: t.add("z.txt")                                                      
In [6]: t.close()                                                           
                                                                            
% tar tvfJ test.tar.xz                                                      
drwxrwxr-x root/root 0 2023-02-19 17:38 test/                               
-rw-rw-r-- root/root 0 2023-02-19 17:37 test/b.txt                          
-rw-rw-r-- root/root 0 2023-02-19 17:38 test/z.txt                          
-rw-rw-r-- root/root 0 2023-02-19 17:38 test/a.txt                          
-rw-rw-r-- root/root 0 2023-02-19 17:38 z.txt                               
                                                                            
In [7]: t2 = tarfile.open("test2.tar.xz", "x:xz")                           
In [8]: t2.add("test/z.txt")                                                
In [9]: t2.add("z.txt")                                                     
In [10]: t2.add("test/")                                                    
In [11]: t2.close()                                                         
                                                                            
% tar tvfJ test2.tar.xz                                                     
-rw-rw-r-- root/root 0 2023-02-19 17:38 test/z.txt                          
-rw-rw-r-- root/root 0 2023-02-19 17:38 z.txt                               
drwxrwxr-x root/root 0 2023-02-19 17:38 test/                               
-rw-rw-r-- root/root 0 2023-02-19 17:37 test/b.txt                          
-rw-rw-r-- root/root 0 2023-02-19 17:38 test/z.txt                          
-rw-rw-r-- root/root 0 2023-02-19 17:38 test/a.txt   
```

So looks like as you suggest, just calling `add()` for both `version.txt` and `sos_reports/` before adding the complete directory should do the trick. 

Good point about using `filter`, It's amazing that `tarfile` doesn't detect duplicate contents :D

Thanks!
