### ISSUE TITLE
[openshift] review directory collection

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#315]
Current openshift collects a couple of directories:

```
[plugin:openshift] added copyspec '/var/log/openshift/'
[plugin:openshift] added copyspec '/etc/openshift/'
```

These should be reviewed and replaced with globs or single files where possible.

**Comment by sferich888** [comment]
@bmr-cymru can this be closed or @codificat are more changed needed with the v2 sosreport plugin?

**Comment by bmr-cymru** [comment]
The `/etc/openshift` stuff is done but the `/var` directory grab is still there:

```python
        self.add_copy_spec([
            "/etc/openshift-enterprise-release",
            "/var/log/openshift",
            "/etc/openshift/*.conf",
            "/etc/openshift/upgrade",
        ])
```

If we really can't do any better than that then it warrants a comment explaining why but I'm sure there is some appropriate patterning to the files in this location.

**Comment by bmr-cymru** [comment]
Ideally this would be split out, given a glob, and switched to `add_copy_spec_limit()`.

**Comment by codificat** [comment]
@sferich888 can you help with narrowing down the various specific log files to collect from `/var/log/openshift` for nodes/masters? I'm a bit tight on time and working on the v3 and related plugins.

**Comment by sferich888** [comment]
**Broker:** 
/var/log/openshift/:
broker/  console/  upgrade.log

/var/log/openshift/broker:
development.log  httpd/  production.log  user_action.log

/var/log/openshift/broker/httpd:
access_log  error_log

/var/log/openshift/console:
httpd/

/var/log/openshift/console/httpd:
access_log  error_log

**Node:** 
/var/log/openshift/:
node/  upgrade.log

/var/log/openshift/node:
node-web-proxy/ platform-trace.log  watchman.log platform.log  ruby193-mcollective.log         

/var/log/openshift/node/node-web-proxy:
supervisor.log  

- Note: any archived or gziped logs are also stored in these locations, as well.

**Comment by bmr-cymru** [comment]
@sferich888 thanks, @codificat I guess we can check/incorporate these when you're back from PTO - we'll still have time for patches until early July.

**Comment by TurboTurtle** [comment]
@sferich888 @codificat Is this issue still relevant?

**Comment by codificat** [comment]
That's for the OpenShift 2.x plugin, and OpenShift 2.x EOL'd quite some time ago (and development stopped even longer ago) so I believe this issue isn't relevant anymore.

@sferich888  maybe you want to follow up with another issue/pr to remove the `openshift` plugin alltogether? Or maybe replace it (rewrite it) with the upcoming openshift 4.x needs, which I assume the `origin` (3.x) plugin might not cover.

But as for this issue in particular, I think it's ok to close.

**Comment by sferich888** [comment]
I agree with @codificat, however as I didn't file this issue the question should be directed at @bmr-cymru on what the end goal of this issue was. 

I vote for removing the plug-in.

**Comment by bmr-cymru** [comment]
> I vote for removing the plug-in.

I vote for burn it with fire.

**Comment by TurboTurtle** [comment]
Closing as the `openshift` plugin has been updated for OCP 4.x, with specific input from the RH OCP support team.
