### ISSUE TITLE
[tests] LogsSizeLimitTest.test_string_not_in_manifest false alarm when /var/log/messages are big

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#3154]
When `/var/log/messages` is beyond `--log-size` on a tested machine, then `LogsSizeLimitTest.test_string_not_in_manifest` fails - since:

    var/log/messages: symbolic link to ../../sos_strings/logs/var.log.messages.tailed

and `sos_reports/manifest.json` contains:

                        "strings": {
                            "var_log_messages_tailed": {
                                "path": "sos_strings/logs/var.log.messages.tailed",
                                "tags": []
                            }
                        },

**Comment by TurboTurtle** [comment]
I think the test's scope needs to be adjusted. The intent of this was no string entries for journals, and #3148 has an update to that effect. But the more I think about it, I think this test is simply outdated now and we can drop it. We don't mind having string collections for files, and nowadays (and more some time) we don't follow the same flow for command output.

So, all that to say - I think we can just drop this test instead?

**Comment by TurboTurtle** [comment]
Handled by #3148 - closing.
