### ISSUE TITLE
[tests] networking plugin test can fail if /sys/class/net/bonding_masters file exists

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#3176]
In https://github.com/sosreport/sos/blob/main/tests/report_tests/plugin_tests/networking.py#L35, we iterate over `/sys/class/net` to get list of networking devices to test if `networking` plugin collects `ethtool * <device>` commands outputs. This fails when the directory looks like:

    # ls -l /sys/class/net
    total 0
    -rw-r--r--. 1 root root 65536 Mar 29  2023 bonding_masters
    lrwxrwxrwx. 1 root root     0 Mar 29  2023 env2 -> ../../devices/vio/30000002/net/env2
    lrwxrwxrwx. 1 root root     0 Mar 29  2023 lo -> ../../devices/virtual/net/lo
    #

There is no `bonding_masters` device, so `sosreport` (which detects networking devices via `nmcli` tool by default) does not collect `ethtool * bonding_masters` output, so the test fails with:

    tests/report_tests/plugin_tests/networking.py:NetworkingPluginTest.test_netdevs_properly_iterated: FAIL: No files matching sos_commands/networking/ethtool_*_bonding_masters found (0.09 s)

Per [manpages](https://man7.org/linux/man-pages/man5/sysfs.5.html), there should be just symlinks there, which was technically violated by change in https://lwn.net/Articles/142330/ adding the `bonding_interface` file.

The test should either filter out the `bonding_interface` namely, or rather should consider just symlinks from the dir.

Th patch is easy, just dont know if there is some preference among the options?

**Comment by TurboTurtle** [comment]
I'd say let's just filter out `bonding_*` - easier to understand at a glance in the future when looking over the test suite.
