### ISSUE TITLE
URL for commercial support seems wrong

### ISSUE THREAD

**Issue by juanmasg** [sosreport/sos#3190]
Just noticed that the vendor URL for commercial support is not working. Looks like the leading `www.` should be removed:

https://github.com/sosreport/sos/blob/31b991ef2b51856264c911018eddea8dd55b5718/sos/policies/distros/redhat.py#L41

```
% curl https://www.access.redhat.com/
curl: (6) Could not resolve host: www.access.redhat.com

```

**Comment by pmoravec** [comment]
Good point.

Would you like to open a PR for it or shall I do so? (whatever works for me)

**Comment by juanmasg** [comment]
I'll open the PR, I wasn't sure if I was missing something :sweat_smile:
