### ISSUE TITLE
[juju] cluster collection doesn't work in 2 scenarios

### ISSUE THREAD

**Issue by arif-ali** [sosreport/sos#3213]
based on my testing, the following 2 scenarios will not work

1. if there is an application deployed, but no unit is consuming it, then should be ignored, and move on
2. subordinate charms will not have an allocated unit, so the `units` key will not exist

Proposing the following solution

```diff
diff --git a/sos/collector/clusters/juju.py b/sos/collector/clusters/juju.py
index d783bd76..3b596f4c 100644
--- a/sos/collector/clusters/juju.py
+++ b/sos/collector/clusters/juju.py
@@ -70,6 +70,10 @@ def _get_index(model_name):
                 subordinate_to = app_info.get("subordinate-to", [])
                 for parent in subordinate_to:
                     self.apps[app].extend(self.apps[parent])
+                    if not self.apps[parent]:
+                        continue
+                    if 'units' not in juju_status["applications"][parent]:
+                        continue
                     units = juju_status["applications"][parent]["units"]
                     for unit, unit_info in units.items():
                         node = f"{self.model_name}:{unit_info['machine']}"
```

\cc @jneo8

**Comment by TurboTurtle** [comment]
Code-wise the changes look fine. I defer to yourself and @jneo8 as to applicability and fitness for `juju`.

**Comment by jneo8** [comment]
Hi @arif-ali, the fix seems ok, can you provide the juju status json file so I can add unit-test to it?

**Comment by jneo8** [comment]
I think it's because the unit status is not health, it's a broken deployment case.
We can add some error handling to it.
