### ISSUE TITLE
[RFC] [docs, guidelines] require an example in comment for all regex substitutions 

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#323]
It's helpful to have an example of the data that's being redacted by regex substitutions. Putting this in a comment preceding the substitution call seems like the simplest solution.

**Comment by TurboTurtle** [comment]
+1 I like this idea, and a new release (4.1) would be a nice starting point to add this to the contributor guidelines.

@pmoravec @BryanQuigley ?

**Comment by BryanQuigley** [comment]
+1 from me!

**Comment by TurboTurtle** [comment]
Motion passed, wiki updated. From now on maintainers will just need to be cognizant of merges and make sure examples are present where needed. We can do updates to existing substitutions over time.
