### ISSUE TITLE
Issue with do_file_private_sub on the juju plugin

### ISSUE THREAD

**Issue by dnegreira** [sosreport/sos#3261]
I've discovered an issue with the juju plugin while testing an [Ubuntu proposed release with sosreport version 4.5.3](https://bugs.launchpad.net/ubuntu/+source/sosreport/+bug/2018270), log as follows:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sos/report/__init__.py", line 1459, in postproc
    plug.postproc()
  File "/usr/lib/python3/dist-packages/sos/report/plugins/juju.py", line 69, in postproc
    self.do_file_private_sub(agents_path)
  File "/usr/lib/python3/dist-packages/sos/report/plugins/__init__.py", line 1257, in do_file_private_sub
    self.do_file_sub(path, _certmatch, replace)
  File "/usr/lib/python3/dist-packages/sos/report/plugins/__init__.py", line 1287, in do_file_sub
    result, replacements = re.subn(regexp, subst, content,
  File "/usr/lib/python3.8/re.py", line 221, in subn
    return _compile(pattern, flags).subn(repl, string, count)
  File "/usr/lib/python3.8/re.py", line 299, in _compile
    raise ValueError(
ValueError: cannot process flags argument with a compiled pattern
```

It seems that the `flags=re.IGNORECASE` argument cannot be passed with a compiled pattern.

I've done a bit of digging and seems that the issue was introduced with [this change](https://github.com/sosreport/sos/commit/bb43ac3b0dddcecf9bf34e489490296e15a2addc).

I have done a quick test and removed the specific [line](https://github.com/sosreport/sos/blob/bb43ac3b0dddcecf9bf34e489490296e15a2addc/sos/report/plugins/__init__.py#L1288) and the plugin then works properly, and it doesn't error out, as well as the substitutions in this specific juju plugin are done.

**Comment by TurboTurtle** [comment]
We definitely want these to be case insensitive. Looks like we need to investigate `do_file_private_sub()` a bit more.

**Comment by TurboTurtle** [comment]
It most certainly does, however this was changed in 4.5.2, so there hasn't been a whole lot of use there since the container image is on 4.5.1 by default still (we don't rebuild the container image just for sos releases, so there is some delay).
