### ISSUE TITLE
cleaner does not obfuscate entire passwords that have spaces

### ISSUE THREAD

**Issue by slapcat** [sosreport/sos#3266]
Version: 4.4

Given a line such as this:
```
ldap_default_authtok = 50 Leagues Under the Sea
```

sosreport will insufficiently obfuscate it to this:
```
ldap_default_authtok = ******** Leagues Under the Sea
```

**Comment by TurboTurtle** [comment]
What file is this from?

**Comment by slapcat** [comment]
`/etc/sssd/sssd.conf`

**Comment by TurboTurtle** [comment]
Ok, looks like the current regex is too conservative - perhaps spaces were not always a valid option here?

Anyways, I'm opening a PR for it shortly. It seems to work in a mocked `sssd.conf`, but it'd be great if you could try the changes in the PR yourself and provide feedback on if it works for you.
