### ISSUE TITLE
Request to be a member of the project from Canonical/Ubuntu perspective

### ISSUE THREAD

**Issue by arif-ali** [sosreport/sos#3275]
Hi folks, 

As both Bryan and Eric have left Canonical, i know this has been discussed in the past.

Both myself and @nkshirsagar have made significant additions, fixes and help to maintain the snap and/or the deb package now from the Canonical perspective. In line with us potentially upstreaming the `debian` folder for testing and maintaining, I think this would be a great opportunity for more people to have approval/merge rights

I suspect from last time slashdd requested to be maintainer (2020), maybe more granular roles are now allowed in GH, which may be more suited. From another repo I own, there are Triage and Write membership if full maintainer is not feasible. I think, this could help with more Ubuntu specific features to be reviewed, labelling of issues and PRs, and could make the right assignments to issues/PRs.

You would agree that in the past year both myself and @nkshirsagar have made considerable contributions to this project, and we both are currently influencing and maintaining the project internally for testing, bugs and training; So, if this could be considered, then that would be great

**Comment by pmoravec** [comment]
+1 for such membership(*), no strong preferences of fine-tuning roles assignement; is there some rationale to review the current coarse maintainer membership model?

(*) at least for @arif-ali , I recall just a few PRs from Nikhil but no problem there either.

Also, speaking on the same topic, we would like to add PR review or maintainer role to @jcastill - if nothing else then to help reviewing PRs that sometimes are pending on me and I am on due with that.

(maybe we can utilize Discussions tab as a new(?) feature of GH, for such nontechnical communication?)

**Comment by arif-ali** [comment]
+1 on @jcastill :)

For us, it's all about redundancy, and we can unblock each other if needed same as yourself.

I've not seen the Discussions tab, that looks pretty cool. I think this would be quite good, especially for those people that are not on IRC or matrix

Nikhil has made some major rework and improvements to the ceph plugins, see below for his contributions. He is also our main person that uploads and maintains the deb package within Canonical/ubuntu, and will be moving forward. So, we can be expecting a lot more, once we start upstreaming the `debian` packaging, and any of the testing required for that

```
* 0db0afa0 [landscape] Add more logging
* ca8a8a7b [ceph_mon] collect mon status on octopus
* 0a9e5dfc [ceph_mds] Collect mds specific data in ceph_mds
* 2288f46b [ceph_mgr] Add more data collection to ceph_mgr
* 22754fd1 [ceph_osd] Add more data collection
* 13ce8115 [ceph] split the ceph plugin
```

**Comment by TurboTurtle** [comment]
A general review of team composition and roles has been in the back of my mind for a while now. Mixed with my recent departure from Red Hat (I'll still be maintaining this project, just personally and not for RH or my new employer) this seems like a good time to look over everything.

I'll try to jump back on Libera (I think there may still be a ghost matrix presence for me there? It's been a while) later today or tomorrow and we can start going over everyone.
