### ISSUE TITLE
Some MAAS config files missing from collection

### ISSUE THREAD

**Issue by al3jandrosg** [sosreport/sos#3280]
Currently we're only collecting `/var/lib/maas/dhcp`, meaning that we're missing other key config files that would help with troubleshooting MAAS issues, e.g.,  `/var/lib/maas/http`. I'd suggest to add the below paths to be collected:

* /var/lib/maas/http/*
* /var/lib/maas/*.conf

**Comment by jcastill** [comment]
Thank you for reporting this issue @al3jandrosg . Do you want to send a PR, or should I?
Do any of these new files to be collected have any password or secrets that must be obfuscated?

**Comment by al3jandrosg** [comment]
Hi @jcastill, thanks for the quick response! I'll try to submit a PR later today, but feel free to do it yourself if you like or I don't manage to do that by the end of the day. I'll check if any of the files need obfuscation and will take that into account accordingly.

**Comment by jcastill** [comment]
Ack @al3jandrosg . Let me know if you have any questions about the process.
