### ISSUE TITLE
[RFC][plugin] in-tree test plugins

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#334]
It's quite common during testing to whip up a quick 'fake' plugin to test some aspect of the plugin class behaviour (e.g. command timeouts, regex substitutions, enablement checks etc.).

To date we've not included any such plugins in the source tree although there are some good reasons why we could:
- avoids wheel reinvention every time a mock plugin is needed
- provides a base for new custom test code
- could begin to form the basis of an integration test suite for plugins

There are a few things we'd need to do to make this workable:
- need a way to label these (new TestPlugin tagging class + policy support?)
- Need to exclude from installs (Makefile + setup.py)
- Need to be default disabled - i.e. `-e plugname` or `-o plugname` to enable

Thoughts?

**Comment by TurboTurtle** [comment]
I'm closing this out, as I don't think the situation is the same as it was in 2014. Especially with the new test suite, "fake" plugins now have a specific place in the repo and are already excluded from builds, and any new Plugin-centric feature should have an accompanying test case with it, either using an existing fake plugin or adding one for future tests.
