### ISSUE TITLE
[RFC][global] docker docker docker testing framework

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#335]
[Docker](http://docker.io) is a container engine for Linux systems. It's one of the current heavily-hyped 'cloudy' technologies that's getting a lot of attention.

One of the interesting aspects of Docker is its layered approach to constructing container images. You can start with a 'base' image (say some distribution flavour) and then add additional layers to provide frameworks, application servers, and apps themselves.

It occurred to me that this might provide an interesting new way to test sos; today we have very little in the way of integration testing support (i.e. testing a whole run of sosreport under controlled conditions and verifying the output is as expected).

One of the difficulties in doing this type of testing with sos is the sheer size of our testing matrix: with over 150 plugins supporting commands, logs and configuration from somewhere around ~1000 packages across five distributions it takes a lot of time and manual effort to create an environment to test, say, the oVirt, cluster, directory server, or gluster plugins. The more support we add for deployments that span more than one system, or that have complex dependencies, the worse this problem becomes.

The idea to use Docker to help manage this comes down to the idea that after we've carried out one successful run we have an example of how the report should look for that one test case. By post-processing the generated report we can create 'fake' binaries (scripts) that regurgitated the captured content on demand. To give a specific example say we have:

```
# ls sos_commands/directoryserver/certutil_-L_-d_.etc.dirsrv.slapd-bmr-rhel7-vm1
sos_commands/directoryserver/certutil_-L_-d_.etc.dirsrv.slapd-bmr-rhel7-vm1
# cat sos_commands/directoryserver/certutil_-L_-d_.etc.dirsrv.slapd-bmr-rhel7-vm1

Certificate Nickname                                         Trust Attributes
                                                             SSL,S/MIME,JAR/XPI

#
```

We'd need to create a script in the Docker image at say `/usr/bin/certutil` that when called as `certutil -L -d /etc/dirsirv/slapd-bmr-rhel7-vm1` reproduces the previously captured output.

There are a few tricky aspects to making this work properly but I think they can all be overcome:
- Command-to-argument-set matching needs to be a little fuzzy; in particular some aspects of the transformation in `Plugin::mangle_command()` are non-reversible.
- File and command output collected during a 'golden' run must not be post-processed if we're going to be able to test regex substitutions (fixing Issue #286 would address this).
- 'golden' images will need to be periodically refreshed to account for changes in other components

Thoughts/comments/flames?

**Comment by TurboTurtle** [comment]
I'm going to close this out for a few reasons; the inactivity of this thread, the limited use of sos in containers in practice, and the high complexity this would entail when there are other options to have more coverage of our support matrix for plugins.
