### ISSUE TITLE
[discussion] What is the purpose of "Signed-off-by:" DCO requirement?

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#3385]
Our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines), [PR template](https://github.com/sosreport/sos/blob/main/.github/PULL_REQUEST_TEMPLATE.md?plain=1#L7) and namely DCO CI check (https://probot.github.io/apps/dco/) require each commit message to have "Signed-off-by:" statement. What the author signs off? What is the purpose of that requirement? E.g. git blame does not require it.

**Comment by TurboTurtle** [comment]
The DCO is the intent behind our requirement of the Signed-off-by line on the commit messages. This has been a requirements for, I believe, as long as the project has existed (@bmr-cymru could say more definitively on that end).

AFAIK, it originated as a requirement from RH.

**Comment by hroncok** [comment]
If that's the case, could you please document that in the project's [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)?

**Comment by bmr-cymru** [comment]
It was added around the time that we moved to git and GitHub from the previous subversion hosting. I forget exactly what prompted it but I think it was an internal discussion about the provenance of contributions coming from different sources (back then it was more common to receive patches via the mailing list or even private mail than what we have today). The intent is exactly the same as the kernel DCO, roughly "I am either the author of these changes or have the permission of the author and I am entitled to contribute these changes under the project license".

Today with virtually everything coming via GitHub it's maybe less relevant. I long ago formed a habbit of "git commit -s" for sos but at the time I was working in several projects that expected a signed-off-by so it was something of a reflex.

**Comment by bmr-cymru** [comment]
OK digging through the logs the first person to commit with a DCO was @adam-stokes, followed by Jesse Jaggars. I started adding them in early 2013. I don't remember if that was the result of a discussion at the time or if I was just following along. DCO was pretty widespread on the projects I worked on at the time so either is possible.

**Comment by TurboTurtle** [comment]
I have updated the wiki to explicitly call this out in the Contribution Guidelines.

**Comment by hroncok** [comment]
Thanks!
