### ISSUE TITLE
[flatpak] Missing flatpak versions break sos execution

### ISSUE THREAD

**Issue by TurboTurtle** [sosreport/sos#3404]
If `flatpak list` contains flatpaks without version numbers, e.g.:

```
$ sudo flatpak list --columns=name,version
Name                                                   Version
Spotify                                                1.1.55.498.gf9a83c60
Freedesktop Platform                                   19.08.8
Freedesktop Platform                                   20.08.13
default
Mesa                                                   21.1.1
ffmpeg-full
openh264
openh264                                               2.1.0
Fractal                                                4.4
GNOME Application Platform version 3.38
Adwaita theme
```

`sos` execution breaks when a policy tries to load the flatpak package manager abstraction:

```
  File "/home/jake/projects/sos/sos/policies/package_managers/__init__.py", line 67, in packages
    self._generate_pkg_list()
  File "/home/jake/projects/sos/sos/policies/package_managers/__init__.py", line 188, in _generate_pkg_list
    for pkg in self._parse_pkg_list(pkg_list):
  File "/home/jake/projects/sos/sos/policies/package_managers/flatpak.py", line 27, in _parse_pkg_list
    name, version = pkg[0], pkg[1]
                            ~~~^^^
IndexError: list index out of range
```

The `flatpak` manager does not have any current error handling associated with it:

```python
    def _parse_pkg_list(self, pkg_list):
        for line in pkg_list.splitlines():
            pkg = line.split()
            name, version = pkg[0], pkg[1]
            yield (name, version, None)

# vim: set et ts=4 sw=4 :
```

This is a straight forward fix from the python perspective - we need to wrap this in a try block, but the question becomes what do we do with version-less flatpaks?

If we don't include the flatpak in the package manager's package list, we could theoretically end up in a situation where a user expects some plugin to do something based on a flatpak being present and we don't do that $something. Alternatively, the package manager abstraction expects _some_ kind of version string here. Passing `None` will just break things further down the line. Should we set some bogus version like `0.0`? to ensure package checks pass, but in turn version checks will almost certainly fail?

Looking for feedback on this one. I'm personally of the mind that if there is no version associated with it, we should _not_ consider that flatpak to be present for our purposes, but I also am not familiar with flatpaks at all so I don't know how common this actually is.

**Comment by jcastill** [comment]
I had a fix for this one in the previous PR that I ended up not including - basically, there is the column version, which can be empty, and then branch, which is never empty. I'll push in a bit the PR I was working on this week. So it's completely acceptable to have an empty version from flatpak perspective, and at the same time we should consider version always with branch.
