### ISSUE TITLE
[slurm] Could not open conf file /etc/slurm/slurm.conf because the slurmd is running in `Configless` mode.

### ISSUE THREAD

**Issue by lonicerae** [sosreport/sos#3439]
Hello,

When the slurm is running under configless mode[1], the slurm.conf is will be placed elsewhere.
 - https://slurm.schedmd.com/configless_slurm.html

The plugin will complain:
~~~
[plugin:slurm] Could not open conf file /etc/slurm/slurm.conf: [Errno 2] No such file or directory: '/etc/slurm/slurm.conf'
~~~

Could we enhance the plugin to better handle this case? Thank you.

Best regards,
Flos

**Comment by arif-ali** [comment]
@lonicerae Thanks for reporting this issue.

I will look into this, and hopefully get an update out soon. Seems like, it generates the file with configless in  `/var/run/slurm/conf/slurm.conf`, and hence we need to collect this config file instead?

**Comment by torkilt** [comment]
> @lonicerae Thanks for reporting this issue.
> 
> I will look into this, and hopefully get an update out soon. Seems like, it generates the file with configless in `/var/run/slurm/conf/slurm.conf`, and hence we need to collect this config file instead?

RHEL 9.3, the file seems to be here:

/var/spool/slurm/d/conf-cache/slurm.conf

**Comment by arif-ali** [comment]
> RHEL 9.3, the file seems to actually be here: /var/spool/slurm/d/conf-cache/slurm.conf
> 
> ```
> [root@g112 slurm]# ls -lah /var/run/slurm/conf
> lrwxrwxrwx. 1 root root 29 Dec 11 14:53 /var/run/slurm/conf -> /var/spool/slurm/d/conf-cache
> ```
> 
> Not sure if it matters.

I've just had another look on Ubuntu as well, so seems like the links are in different places. So it makes sense to do it from `/var/run/slurm/conf`

```
root@slurm-comp01:~# ls -lha  /var/run/slurm/conf
lrwxrwxrwx 1 root root 28 Dec 11 14:33 /var/run/slurm/conf -> /var/spool/slurmd/conf-cache
```
