### ISSUE TITLE
Sos stores upload passwords in the sos.log and manifest.json files.

### ISSUE THREAD

**Issue by TrevorBenson** [sosreport/sos#3462]
When running `sos report` or `sos collect` and uploading the archive file using either `--upload-pass` or an `--upload-url` that contains the credentials in the format `https://user:password@URL`, the password is exposed in the `sos_log/sos.log` and `sos_reports/manifest.json` files. The report was requested without a `--clean` flag. 

I would not consider these values part of the details important for diagnosing issues. If they did not work the upload would fail anyway. If passwords are collected interactively sos uses  `getpass()` instead of `input()` to hide secrets from the console. It seem like secrets should also be obfuscated in these files  even when the cleaner is not requested.

**Comment by TurboTurtle** [comment]
Well that's not good!

I took a quick look, and I see it in `sos.log` as part of the options/command string logging and in `manifest.json` as part of the `cmdline` entry - are you seeing it anywhere else?

I've been out of pocket for a little bit due to schedules, but I think I can take a look at this this weekend or early next week - in any event, prior to sos-4.7.

**Comment by pmoravec** [comment]
I can also see the passwords and only in the two files, even when running `sos` in verbose mode.

I have some time now, will work on PR now.

**Comment by TrevorBenson** [comment]
@pmoravec @TurboTurtle I went back and ran another pass at this without limiting which plugins were enabled, as was set during my initial observation of the behavior. I can see the passwords/secrets are also leaked into plugins:
* **process**
  * `./sos_commands/process/ps_auxwwwm`
  * `./sos_commands/process/ps_alxwww`
  * `./sos_commands/process/ps_-elfL`
  * `./sos_commands/process/ps_axo_flags_state_uid_pid_ppid_pgid_sid_cls_pri_addr_sz_wchan_20_lstart_tty_time_cmd`
* **systemd**
  * `./sos_commands/systemd/systemctl_status_--all`
* **selinux**
  * `./sos_commands/selinux/ps_auxZww`

**Comment by pmoravec** [comment]
Hm.. we should keep a list of _globs_ (in case we change a `ps` option, no need to update this list) covering all such files and `SoSComponent` will apply the `do_file_sub` to all such files matching each glob.

Does it sound good to you?

**Comment by TurboTurtle** [comment]
> @pmoravec @TurboTurtle I went back and ran another pass at this without limiting which plugins were enabled, as was set during my initial observation of the behavior. I can see the passwords/secrets are also leaked into plugins:
> 
> * **process**
>   
>   * `./sos_commands/process/ps_auxwwwm`
>   * `./sos_commands/process/ps_alxwww`
>   * `./sos_commands/process/ps_-elfL`
>   * `./sos_commands/process/ps_axo_flags_state_uid_pid_ppid_pgid_sid_cls_pri_addr_sz_wchan_20_lstart_tty_time_cmd`
> * **systemd**
>   
>   * `./sos_commands/systemd/systemctl_status_--all`
> * **selinux**
>   
>   * `./sos_commands/selinux/ps_auxZww`


This is covered in the man pages:

        --upload-pass PASS
              Specify the password to use for authentication with the destination server.

              If this option is omitted and upload is requested, you will be prompted for one.

              If --batch is used, this prompt will not occur, so any uploads are likely to fail unless this option
              is used.

              Note that this will result in the plaintext string appearing in `ps` output that may be collected by
              sos  and be in the archive. If a password must be provided by you for uploading, it is strongly rec‐
              ommended to not use --batch and enter the password when prompted rather than using this option.

              You also have the option of providing this value via the SOSUPLOADPASSWORD environment variable.  If
              this  variable is set, then no password prompt will occur and --batch may be used provided all other
              required values (case number, upload user) are provided.


Unless, @pmoravec you're suggesting we apply the `do_file_sub()` addition to these files as well after everything else is said and done? I'm not opposed to that, either.

**Comment by pmoravec** [comment]
I *knew* we discussed the "ps commands can leak passwords" but I forget we added it to manpages :) .

As there is second thought from second person on some password leak, I am in favour of applying `do_file_sub()` to these files (and keep the manpages heads-up in case we miss something).

I will bump the PR most probably still today.

**Comment by TurboTurtle** [comment]
Ack, let's change that "will result" to "may result" at the same time. Basically, make a "best effort" attempt to obfuscate them, but still warn users that it's at least a possibility that it will end up somewhere and if they absolutely don't want that they should use the environment variable.

**Comment by pmoravec** [comment]
PR updated. Getting `glob` to work on _relative_ paths was bit tricky, but should work well.
