### ISSUE TITLE
sos [report|collect] can leak upload user password to stdout

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#3465]
A side-issue from #3462 that we should also ideally fix: `sos` can print upload user credentials with password in plaintext to standard output - esp. when the upload fails. Then the engineer can easily provide (as a help to diagnose the upload failure) also their password, like:

    # sos report --upload-url https://user:PASSWORD@URL --batch
    ..
    Attempting upload to https://user:PASSWORD@URL
    Upload attempt failed: ..

We should ideally obfuscate the `PASSWORD` there. Despite such password leak can happen only when engineer manually copies standard output, it is a weakness that can happen and we should prevent it.

This means `get_upload_url_string` method in `LinuxPolicy` needs to obfuscate a password if present, similarly like #3463 does, and `RHELPolicy` + `UbuntuPolicy` should call that method as a fallback (cf. https://github.com/sosreport/sos/blob/main/sos/policies/distros/redhat.py#L309 and https://github.com/sosreport/sos/blob/main/sos/policies/distros/ubuntu.py#L88).

**Comment by swarajpande5** [comment]
Hi @pmoravec, As this issue seems beginner-friendly, can this be assigned to me please ?
