### ISSUE TITLE
The sos-4.6.1.tar.gz seems to reference sos-4.6.0

### ISSUE THREAD

**Issue by aadhar-agarwal** [sosreport/sos#3493]
In the sos-4.6.1 [release](https://github.com/sosreport/sos/releases/tag/4.6.1), the source code (tar.gz) seems to be referencing 4.6.0 instead of 4.6.1. The [bump](https://github.com/sosreport/sos/commit/d338a232cd7c829ca8ca5e5febef51035d1f7da5) to 4.6.1 was made on Jan 10 but the source code (tar.gz) seems to have been generated on Jan 8.

Could someone help regenerate the source code (tar.gz)? :)

Found this while running `sos report` which showcased version 4.6.0
![image](https://github.com/sosreport/sos/assets/108542189/0ebe278d-a61f-4001-a49b-5113d1c27f3e)

**Comment by arif-ali** [comment]
Hi @aadhar-agarwal,

This is a known issue, and it just has a commit missing which had the version bump. So you should be able to use it as is for now

This is also being discussed in #3492

**Comment by aadhar-agarwal** [comment]
> Hi @aadhar-agarwal,
> 
> This is a known issue, and it just has a commit missing which had the version bump. So you should be able to use it as is for now
> 
> This is also being discussed in #3492

Thank you for pointing me to the discussion! @arif-ali

**Comment by pmoravec** [comment]
Hi @TurboTurtle , can we update the tarball? I am not aware of a way doing so.. I guess updating the tarball is safe, while moving the tag to the right commit means overwriting git history that is already over the line.

I really apologize for the mistake :( .

**Comment by TurboTurtle** [comment]
Not really a way to update it, no. We'd have to delete the release, then create a new one. At that point, since we've had commits since the 4.6.1 version bump we'd need to bump it again to 4.6.2.

Since we're about 3.5 weeks out from 4.7.0, I'm not sure doing so would be advantageous to our downstreams.

**Comment by arif-ali** [comment]
Going to close this issue, as there isn't much we can do, and Mariner based on the linked PR has already pushed a version bump as per Pavels commit.
