### ISSUE TITLE
plugin for Kubeflow

### ISSUE THREAD

**Issue by nishant-dash** [sosreport/sos#3494]
Would it be possible to define a plugin that an operator can run for a kubeflow environment?
For example, pulling in the all container logs from pods in the kubeflow namespace, pod definitions, pvc states, etc...

Or is this something than can/should be accomplished by the k8s plugin + some extra kubeflow specific rules and such?

**Comment by TurboTurtle** [comment]
If it is just a different namespace, it should be handled by the `kubernetes` plugin. There might be some more changes needed to the plugin, as when the `kuberenetes` and `openshift` plugins splits, more development for this kind of thing went into `openshift`, but there is still the basic framework in `kubernetes` for it.

**Comment by arif-ali** [comment]
Speaking to one of my kubeflow persons, we should be able to achieve this through the normal kubernetes plugin once the microk8s stuff is also integrated.

We could potentially create a `kubeflow` preset, which will ensure we collect all the things we need to debug it. As, we would ideally need logs via `kubectl` for the `kubeflow` namespace. This could easily be achieved by enabling the extra options that are available there in the plugin

**Comment by TurboTurtle** [comment]
The default behavior of the `kubernetes` plugin (as opposed to the `openshift` plugin) is to grab _all_ namespaces, so this should be happening today. If that's not working, we'll want to investigate the kube plugin a bit more deeply, as it has not had the same attention paid to it as the `openshift` plugin has.

**Comment by arif-ali** [comment]
yup, if you do a `-a --all-logs` then we have the following on by default with `-o kubernetes`

```
 kubernetes.all            on              collect all namespace output separately
 kubernetes.describe       on              collect describe output of all resources
 kubernetes.podlogs        on              capture stdout/stderr logs from pods
```

So, I think we should be cool, once #3501 is merged

**Comment by arif-ali** [comment]
@nishant-dash the above PR is now merged, and you should be able to get the relevant logs and information from the kubernetes plugin, whether you're using microk8s or any other kubernetes platform.

Let us know if this meets the requirements. If it doesn't, then it may be useful to give us the commands or items that we could be looking out for

**Comment by arif-ali** [comment]
@nishant-dash I am marking this as resolved as many things have been added and amended to get the relevant details from `microk8s` and normal `kubernetes`. This is based on some discussions internally as well from one contact who knows kubeflow
