### ISSUE TITLE
[ubuntu][microk8s] Extend kubernetes options to microk8s plugin

### ISSUE THREAD

**Issue by phvalguima** [sosreport/sos#3500]
Hi,

I am currently using microk8s with SOS report as part of my testing. However, I have no options to automatically capture logs at the same level of details as `kubernetes` plugin.

In particular, I am interested in capturing pod-level logs, like `kubernetes.podlogs=true`, and information about all namespaces.

I see two alternatives:
1) Turning `microk8s` a subclass of `UbuntuKubernetes`: in this case, all options in Kubernetes plugin would be automatically available
2) Adding `/var/snap/microk8s/current/credentials/client.config` to `UbuntuKubernetes` `files` tuple

I am more inclined to doing option (1), as I also want to have some microk8s-related information, besides containers only.

**Comment by phvalguima** [comment]
@dnegreira hi, I am tagging you in this issue as I see you've committed the first version of microk8s plugin

**Comment by dnegreira** [comment]
Hey @phvalguima - We should extend the kubernetes plugins to gather the log pods from microk8s if something is missing there. The intent of microk8s plugin is to gather all the micork8s bits like microk8s config, microk8s status.

LMK if you need help with this.
