### ISSUE TITLE
Drop any SCL related code?

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#3559]
sos report supports collecting data from Software Collections. That is roughly speaking RHEL7 specifics which we dont support in sos upstream for years. So we shall drop any `*scl` methods or `SCLPlugin` class completely, I think.

Since the SCL stuff is bundled into multiple plugins (foreman, postgres, redis, at least), we should review those plugins if we dont cause any regression by dropping the SCL methods / class(es).

**Comment by TurboTurtle** [comment]
That's what I couldn't remember, if there was any bleed over into RHEL 8 or not.

I'm 100% onboard with dropping SCL wholesale. I'll work on that this weekend/earlier this coming week.

**Comment by TurboTurtle** [comment]
Actually, this looks more straight forward than I was thinking...I'll have something posted shortly.
