### ISSUE TITLE
4.7.0: pytest fails because missing `sos_tests` module and deprecation waning

### ISSUE THREAD

**Issue by kloczek** [sosreport/sos#3571]
I'm packaging your module as an rpm package so I'm using the typical PEP517 based build, install and test cycle used on building packages from non-root account.
- `python3 -sBm build -w --no-isolation`
- because I'm calling `build` with `--no-isolation` I'm using during all processes only locally installed modules
- install .whl file in </install/prefix> using `installer` module
- run pytest with $PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>
- build is performed in env which is *`cut off from access to the public network`* (pytest is executed with `-m "not network"`)

<details>
<summary>Here is pytest output:</summary>

```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/sos-4.7.0-2.fc36.x86_64/usr/lib64/python3.9/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/sos-4.7.0-2.fc36.x86_64/usr/lib/python3.9/site-packages
+ /usr/bin/pytest -ra -m 'not network'
==================================================================================== test session starts ====================================================================================
platform linux -- Python 3.9.18, pytest-8.1.1, pluggy-1.4.0
benchmark: 4.0.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /home/tkloczko/rpmbuild/BUILD/sos-4.7.0
plugins: benchmark-4.0.0, aspectlib-2.0.0
collected 6 items / 1 error

========================================================================================== ERRORS ===========================================================================================
________________________________________________________________ ERROR collecting tests/cleaner_tests/ipv6_test/ipv6_test.py ________________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/sos-4.7.0/tests/cleaner_tests/ipv6_test/ipv6_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/cleaner_tests/ipv6_test/ipv6_test.py:9: in <module>
    from sos_tests import StageTwoReportTest
E   ModuleNotFoundError: No module named 'sos_tests'
===================================================================================== warnings summary ======================================================================================
../../../../../usr/lib/python3.9/site-packages/magic/__init__.py:468
  /usr/lib/python3.9/site-packages/magic/__init__.py:468: PendingDeprecationWarning: Using compatibility mode with libmagic's python binding. See https://github.com/ahupp/python-magic/blob/master/COMPAT.md for details.
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================================================================================== short test summary info ==================================================================================
ERROR tests/cleaner_tests/ipv6_test/ipv6_test.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================================================ 1 warning, 1 error in 0.31s ================================================================================
```
</details>

Please let me know if you need more details or want me to perform some diagnostics.

**Comment by TurboTurtle** [comment]
We do not use pytest as our test suite, we use avocado and develop our tests under that context. An example of how we build RPMs can be seen in our [cirrus CI configuration](https://github.com/sosreport/sos/blob/main/.cirrus.yml#L107), which follows the recommended build patterns for RPM-based distributions.

That said, it looks like pytest cannot find the correct top-level module on which our tests are built because you are overriding `PYTHONPATH` and I'd wager that that path does not include the `tests/` directory (or specifically, the `tests/sos_tests.py` file) in which these classes are defined.

**Comment by kloczek** [comment]
OK so that is current state. I understand.
Really try to play with pytest because it is already used in +98% OSS projects with python code (it is de facto standard)
Simple instead maintaining own testing framework it is easier to take something off-the-shelve 😋

**Comment by TurboTurtle** [comment]
> Really try to play with pytest because it is already used in +98% OSS projects

[citation needed]

> Simple instead maintaining own testing framework

We don't maintain avocado. [avocado](https://github.com/avocado-framework/avocado) maintains avocado.

> it is easier to take something off-the-shelve 😋

If pytest met our needs, perhaps. But it doesn't.
