### ISSUE TITLE
sos.conf options dont match cmdline options

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#3671]
Example:

    sos report --batch --build -o networking --clean --skip-cleaning-files="*"

should basically disable cleaner (artificial example). But having in `/etc/sos/sos.conf`:

    [clean]
    skip-cleaning-files=*

is ignored. The "right" option there equivalent to `--skip-cleaning-files="*"` is:

    [clean]
    skip-clean-files=*

Not sure if just this option is affected, or some others as well.

**Comment by TurboTurtle** [comment]
It's because of this:

```python
        clean_grp.add_argument('--skip-cleaning-files', '--skip-masking-files',
                               action='extend', default=[],
                               dest='skip_clean_files',  <====
                               help=('List of files to skip/ignore during '
                                     'cleaning. Globs are supported.'))
```

So we just need to update the internal variable name, I think. Will have something up shortly after some quick tests.

**Comment by jcastill** [comment]
And this as well, right?

 arg_defaults = {
        'archive_type': 'auto',
        'domains': [],
        'disable_parsers': [],
        'skip_clean_files': [], <-- 
        'jobs': 4,
        'keywords': [],
        'keyword_file': None,
        'map_file': '/etc/sos/cleaner/default_mapping',
        'no_update': False,
        'keep_binary_files': False,
        'target': '',
        'usernames': []
    }


In sos/cleaner/__init__.py .

**Comment by TurboTurtle** [comment]
Yes, it's in a number of places. Also, I've found a bug in handling skipping files where if we don't have _any_ parsing to do (e.g. the `*` value, or anything that would cause all parsers to skip the file) we still go through the process of creating a temp file and reading/scanning/writing stuff out. It's definitely an edge case primarily highlighted by this synthetic scenario but it's worth addressing.
