### ISSUE TITLE
[RFE] Set a UserAgent for --upload-protocol s3

### ISSUE THREAD

**Issue by TrevorBenson** [sosreport/sos#3688]
# Request
Set a custom UserAgent for S3 (boto3) so that sos report can be identified as the upload client for S3 buckets. This could be a string like `sos`, `sosreport`, or `sos-report` etc..

# Reason

Permits identifying sos report/collect as a specific UserAgent instead of generically reporting the same UseAgent any Python script using boto3 does. Custom policies can be defined on s3 buckets. One use of a policy could be a condition/requirement for the UserAgent string. Two potential use cases by using a custom UserAgent in a policy:
* Limit uploads even, when valid credentials are provided, to only work with the specified UserAgent.
* Allow a specific UserAgent to upload an archive to a bucket without requiring valid credentials (access/secret keypair).

**Comment by TrevorBenson** [comment]
@pmoravec @TurboTurtle Is `sosreport` acceptable as the UserAgent label for uploads from both `sos report` and `sos collect`? Did I miss any UserAgent which might be preferred instead?

TIA

**Comment by TurboTurtle** [comment]
Good question. A safe default may just be `sos`, to cover both use cases. Alternatively, we could just match it to the component e.g. `sos-report` and `sos-collect`, if it would for any reasonable be desirable to not glob everything together.
