### ISSUE TITLE
[RFE] add the output of “ps auxfwww” to the report

### ISSUE THREAD

**Issue by casantos** [sosreport/sos#3706]
The “forest” output helps debugging problems in GUI sessions and services launched via systemd.

**Comment by jcastill** [comment]
@casantos at the moment we capture:

            "ps alxwww"
            "ps -elfL"

Your RFE is to add a third capture, not to expand the first one, right?

**Comment by casantos** [comment]
Right. Add a third capture with "ps auxfwww".
