### ISSUE TITLE
Missing documentation related to node, extra, presets file formats/examples

### ISSUE THREAD

**Issue by cidrbl0ck** [sosreport/sos#3742]
Exploring the `sos collector/or` and there is mention of running it and specifying `--nodes` creating a group file in the users home/.config. However I have found this is not the case.. So I tried finding any information about how the group files should be formatted and came up empty.

Can we get at least an example of how a user can create these files?

**Comment by TurboTurtle** [comment]
`--save-group` is what you're looking for. That option causes `sos collect` to write out the node list based on what gets returned for the run you're executing.

For example:

```
$ sos collect --nodes foo.bar.example.com,barfoo.example.com --save-group example_group --cluster-type jbon --no-local
[...]
jake@terra:~/projects/sos$ ls ~/.config/sos/groups.d/
example_group  rhvtest
jake@terra:~/projects/sos$ cat ~/.config/sos/groups.d/example_group 
{"name": "example_group", "primary": "", "cluster_type": "jbon", "nodes": ["foo.bar.example.com", "barfoo.example.com"]}
```

Functionally, the file is just a json dump of the options passed to `sos collect`, note in this example `primary` being empty means "treat this localhost as the primary node in the cluster" and `cluster_type` of `jbon` is "just a bunch of nodes - don't try to source nodes from anywhere other than what the --nodes option provides".

**Comment by TurboTurtle** [comment]
You would then use the `--group $group_name` option to load those values, e.g. `sos collect --group example_group`.

**Comment by cidrbl0ck** [comment]
Ah this is super! I was only able to find a few other things by searching the entire repo but, did not think of the word 'save' lol.
This is very helpful, thanks!

**Comment by cidrbl0ck** [comment]
Good to close, thanks for the help!
