### ISSUE TITLE
Pull in Eucalyptus plugins

### ISSUE THREAD

**Issue by battlemidget** [sosreport/sos#375]
Currently working with the Eucalyptus team to get their plugins merged upstream:

https://github.com/eucalyptus/eucalyptus-sosreport-plugins/issues/68

I'll probably re-work the plugins to match our current codebase and guidelines. PR coming soon

**Comment by BryanQuigley** [comment]
I'm going to go ahead and close this as eucalyptus support seems to no longer be relevant 

Feel free to reopen if I'm wrong on this.
