### ISSUE TITLE
most plugins doesn't collect ALL_PROXY environment variable

### ISSUE THREAD

**Issue by pafernanr** [sosreport/sos#3788]
Multiple OS commands rely on `libcurl` hence in the environment variables `libcurl` understands. Most of the plugins are collecting `http_proxy` and similar env_vars. But `ALL_PROXY` is not being collected by the plugins which leads to miss important environment details.

Currently only `crio`, `docker` and `podman` are collecting this env_var.

It could also be great to include `[scheme]_proxy` into collected vars, but it would require rewrite `def collect_env_vars` to make some kind of `regex` evaluation.

- libcurl supported env_vars: https://curl.se/libcurl/c/libcurl-env.html

In addition to that, let me ask: (Probably this question was already answered, solved, or has security implications)
Is it better to `self.add_env_var(["ALL_PROXY"])` on all required plugins? Or worth to obtain "ALL" current shell environment variables in a dedicated plugin?

**Comment by pafernanr** [comment]
Another approach could be initialize `self.env_vars` with a commonly used env_vars `report/__init__.py` and let plugins define only the specific required ones. 
E.g:
~~~
self.env_vars = set(["ALL_PROXY", "NO_PROXY", "FTP_PROXY", "HTTP_PROXY", "HTTPS_PROXY"])
~~~

Does it makes sense?

**Comment by TurboTurtle** [comment]
Environment variables are handled a bit differently than most collections. The plugins aren't actually doing the collection themselves, but rather updating a global (well, report-level) list of environment variables to capture _after_ all plugins have finished their normal execution.

We can add these `*_PROXY` vars to a default set, though I believe we initially avoided doing so do to concerns around end users (read: customers of vendors) not wanting something like this collected by default. We can mitigate some related concerns around passing credentials in the variable, but the big item was "should this _always_ be collected?". At the time we said no, but that's by no means set in stone.

Similarly, when we initially added this there was the thought of "why don't we just collect every environment variable there is", and were met with a swift "not just no, but hell no" from various security folks.

**Comment by pafernanr** [comment]
Sure, I fully agree  with that from a security point of view.

My concern is because, currently, a connection can be "proxyfied/not proxyfied" depending on env_vars that are not being collected. Some plugins seems to have noted this and include related env_vars, but not all of them. 

To mitigate this, I think ["ALL_PROXY", "NO_PROXY"] could be added on all plugins that are currently including `*_PROXY` on their added `env_vars`.

**Comment by pmoravec** [comment]
Another idea (no preference what can be better): what about collecting env.variable *names*, but without their values? Information `os.env` does contain, say, `HTTP_PROXY` set, is a hopefully sufficient hint to support engineers to consider this aspect. On the other side, no(?) security implications from it, as no value is shared.

If even list of environment variable names might be a security issue, what about listing the names of few well known (like the `*_PROXY`)?

**Comment by pafernanr** [comment]
great idea @pmoravec. Should your approach be implemented on a new plugin? Do you think it is the way to go? It should just list the env_vars names without values; this, I guess, won't have any security implications.

On the other hand; IMHO we still must add the "missing" env_vars ["ALL_PROXY", "NO_PROXY"]  to those plugins that are currently using `*_PROXY` env_vars. (#3789 helpS here)
