### ISSUE TITLE
Feature Request: Include container image manifests and layers in sosreport

### ISSUE THREAD

**Issue by tawfiqfm** [sosreport/sos#3796]
Currently, sosreport does not capture detailed information about container images running on a node. This can make it difficult to troubleshoot issues with containerized applications. Requesting feature to dump all manifests and layers for images on a Node in sosreport.

**Comment by TurboTurtle** [comment]
Sounds reasonable - what environments/runtimes are you looking for?

`podman` I think this would be provided via `podman image inspect $image`, is that what you're looking for, or something else? `docker` would be the same I think? Would need to look into k8s or OCP if you're looking for those plugins as well or instead.

**Comment by SergeyKanzhelev** [comment]
We are interested in containerd. But other runtimes may be interested in it as well. Some hierarchy of layers and all the manifests would be great to have in the report.

cc: @samuelkarp to advice on the best way to collect this for containerd

**Comment by tawfiqfm** [comment]
Seems like this was closed by mistake. This hasn't been implemented by Containerd.

**Comment by TurboTurtle** [comment]
Yep, mistakenly closed. I had updated the tag to `Related`, so not sure why this got closed out.

**Comment by lutierigb** [comment]
I don't see an easy way to retrieve the manifest for an image with crictl(containerd). @samuelkarp any ideas?

Sergey and I agree that would be beneficial to be able to see all the layers for the images present on the node.
