### ISSUE TITLE
Feature request: collect cgroup information per process

### ISSUE THREAD

**Issue by samuelkarp** [sosreport/sos#3799]
`/proc/<pid>/cgroup` should expose the association between processes and cgroups.  It does not appear like this is [currently captured](https://github.com/sosreport/sos/blob/96e4d79231819b45ef62629206a7a3da31b3a1dd/sos/report/plugins/process.py#L52-L58).  The same information can be found through the cgroup hierarchy (`cgroup.procs` file for cgroup v2 and `tasks` file for v1), but that requires traversing the entire hierarchy to find.

**Comment by jcastill** [comment]
Nice catch. We have a cgroups plugin where we can collect this, so it may be better to place it there. 
I'll send a quick PR so we can discuss some possible implementations with the maintainers.

**Comment by TurboTurtle** [comment]
I believe this was satisfied by #3801. Feel free to reopen if not fully addressed.
