### ISSUE TITLE
Man page not correct directory location for presets

### ISSUE THREAD

**Issue by twoflowers** [sosreport/sos#3826]
When reviewing the man page for `--preset`, the user defined preset directory location is not accurately described.  In the page it states: 

` User defined presets are saved under /var/lib/sos/presets as JSON-formatted files.`

In Nobel (24.04.01) the directory actually shoudl be `/etc/sos/presets.d`.

**Comment by jcastill** [comment]
Same in RHEL and Fedora. Do you want to send a PR with the fix?

**Comment by twoflowers** [comment]
@jcastill yep, I will have a PR for this
