### ISSUE TITLE
[plugin] copy spec glob ordering is arbitrary

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#383]
Currently the order in which copy spec items are processed after glob expansion is somewhat arbitrary. E.g. in `add_copy_spec_limit()` we have:

``` python
410     def add_copy_spec_limit(self, copyspec, sizelimit=None, tailit=True):
415         if not (copyspec and len(copyspec)):
416             return False
417 
418         files = glob.glob(copyspec)
419         files.sort()
```

I.e. the spec is glob-expanded and then list sorted. Items are then processed in list order.

On the other hand add_copy_spec() performs no sorting:

``` python
452     def add_copy_spec(self, copyspec):
456         if not (copyspec and len(copyspec)):
457             self._log_warn("added null or empty copy spec")
458             return False
459         copy_paths = self.expand_copy_spec(copyspec)
460         self.copy_paths.update(copy_paths)
461         self._log_info("added copyspec '%s'" % copyspec)
[...]
594     def expand_copy_spec(self, copyspec):
595         return glob.glob(copyspec)
```

For `add_copy_spec()` the order is not really important; since all copy specs will be collected it has no effect on the report content. For `add_copy_spec_limit()` this is not the case; items that appear later in the copy spec ordering may not be collected as a result of size limiting.

The current sorting mode in `add_copy_spec_limit()` gives results like this:

``` python
>>> files = glob.glob("/tmp/messages*")
>>> files.sort()
>>> files
['/tmp/messages', '/tmp/messages.1', '/tmp/messages.2', '/tmp/messages.3', '/tmp/messages.4']
>>> files = glob.glob("/tmp/log*")
>>> files.sort()
>>> files
['/tmp/log', '/tmp/log-20140820', '/tmp/log-20140822', '/tmp/log-20140825', '/tmp/log-20140827']
```

This works well for the 'logfile.N' rotation style but falls apart for the 'logfile-DATE' style.

Unfortunately there is no lexical sort that will give the ideal result (current file first, then rotated copies in order of ascending age).

There are two options to address this: pick an arbitrary ordering and stick with it (so that at least it's documented and well understood) or switch to a better method of sorting paths for collection for e.g. using the inode mtime.

**Comment by TurboTurtle** [comment]
Closing this, as this was resolved via ae76de1 some time ago.
