### ISSUE TITLE
[clean] running sos collect w/ --clean hangs for around 15 minutes

### ISSUE THREAD

**Issue by TrevorBenson** [sosreport/sos#3846]
```
time sudo sos collect --debug --nopasswd-sudo --ssh-user artesca-os --nodes 172.31.100.80,172.31.100.95 --clean
Found 2 total reports to obfuscate, processing up to 4 concurrently

sosreport-ip-172-31-100-80-2024-11-20-ksxnqru :    Extracting...
sosreport-ip-172-31-100-95-2024-11-20-posedgg :    Extracting...
sosreport-ip-172-31-100-80-2024-11-20-ksxnqru :    Beginning obfuscation...
sosreport-ip-172-31-100-95-2024-11-20-posedgg :    Beginning obfuscation...
sosreport-ip-172-31-100-80-2024-11-20-ksxnqru :    Re-compressing...
sosreport-ip-172-31-100-80-2024-11-20-ksxnqru :    Obfuscation completed


sosreport-ip-172-31-100-95-2024-11-20-posedgg :    Re-compressing...
sosreport-ip-172-31-100-95-2024-11-20-posedgg :    Obfuscation completed
sos collect directory :                            Beginning obfuscation...
sos collect directory :                            Obfuscation completed

Successfully obfuscated 2 report(s)

A mapping of obfuscated elements is available at
	/var/tmp/sos-collector-2024-11-20-efhvj_private_map

The following archive has been created. Please provide it to your support team.
	/var/tmp/sos-collector-2024-11-20-efhvj-obfuscated.tar.xz


real	31m12.701s
user	0m0.004s
sys	0m0.013s

ls -l /var/tmp/sos-collector-2024-11-20-efhvj-obfuscated.tar.xz
-rw-------. 1 root root 28369652 Nov 20 01:04 /var/tmp/sos-collector-2024-11-20-efhvj-obfuscated.tar.xz
```

The Obfuscation completed message happened around 4:50  (00:50 UTC) or earlier, but it took until 01:04 to return.

**Comment by pmoravec** [comment]
> The Obfuscation completed message happened around 4:50 (00:50 UTC) or earlier, but it took until 01:04 to return.

The *second* `Obfuscation completed` message happened that time, right?

How much time was spent in compressing the archive? I would add some debugs to the code after the `Obfuscation completed` and e.g. the `A mapping of obfuscated ..` logs, to pinpoint where the delay origins from.

**Comment by TrevorBenson** [comment]
> > The Obfuscation completed message happened around 4:50 (00:50 UTC) or earlier, but it took until 01:04 to return.
> 
> The _second_ `Obfuscation completed` message happened that time, right?
> 
> How much time was spent in compressing the archive? I would add some debugs to the code after the `Obfuscation completed` and e.g. the `A mapping of obfuscated ..` logs, to pinpoint where the delay origins from.

I'm doing an asciinema recording an idle time of 1 second, using tmux with 1 pane doing a watch -n10 on `date` and the other pane doing the collection and cleaning. If I can confirm the reported timings I'll attach a link, if not I'll close this ticket out as noise.

**Comment by TrevorBenson** [comment]
The recording disproves the original reported timing. 

It took 3 minutes to collect, 1 minute for the first obfuscation to complete, 33 minutes for the second obfuscation, and the collection obfuscates in under a second.

Closing this out, apologies for the extra noise.
