### ISSUE TITLE
[collect] Saltstack transport fails to collect when from nodes without flatpak installed

### ISSUE THREAD

**Issue by TrevorBenson** [sosreport/sos#3860]
```
[sostest-2:run_command] Running command cat /etc/os-release
[sostest-1:run_command] Running command rpm -qa --queryformat "%{NAME}|%{VERSION}|%{RELEASE}\n"
[sostest-2:run_command] Running command rpm -qa --queryformat "%{NAME}|%{VERSION}|%{RELEASE}\n"
[sostest-1:run_command] Running command flatpak list --columns=name,version,branch
[sostest-2:run_command] Running command flatpak list --columns=name,version,branch
No nodes connected. Aborting...
Could not obtain installed package list
[root@sostest-1 ~]# flatpak list
-bash: flatpak: command not found
```
By installing flatpak on a single node, instead of `No nodes connected. Aborting...` 1 node ends up connected and the collection continues to execute.

Found while testing from packit copr repository in sos-4.8.1.

**Comment by jcastill** [comment]
Thanks for the heads up. I'll try to reproduce in the lab tonight

**Comment by TrevorBenson** [comment]
> Thanks for the heads up. I'll try to reproduce in the lab tonight

Did `oc` transport work fine while flatpak is missing? If so I'll dig deeper into saltstack as it being the only transport that seems to have the problem.

**Comment by jcastill** [comment]
So far I had no luck reproducing, but that could be more an issue on my lab than anything else.  Start digging deeper into saltstack and as soon as I manage to get it reproduced I'll let you know.

**Comment by TrevorBenson** [comment]
@jcastill So you ran `sos collect --cluster ocp --transport oc` and any node without flatpak installed still appeared in the sos-collection? If that is the case then I suspect it is specific to the saltstack transport.

**Comment by TrevorBenson** [comment]
@jcastill Found the root cause, opened #3886 to resolve the issue.
