### ISSUE TITLE
NetworkManager keyfiles are not being gathered from all locations

### ISSUE THREAD

**Issue by palonsoro** [sosreport/sos#3875]
Currently, the `networkmanager` sos plugin collects all the NetworkManager connection keyfiles from `/etc/NetworkManager/system-connections` as we can see [here](https://github.com/sosreport/sos/blob/add55ea9ef6c8a753b8646546c2da5ec07bb54cc/sos/report/plugins/networkmanager.py#L24).

However, that's not the only location for NetworkManager connection keyfiles. As we can see in `man 5 nm-settings-keyfile`, the apart from `/etc/NetworkManager/system-connections/`, we should be including `/usr/lib/NetworkManager/system-connections/` and `/run/NetworkManager/system-connections/`.

The latter is specially important in case that temporary in-memory connections are defined, like the default auto-generated ones.

**Comment by jcastill** [comment]
Thank you for opening the issue @palonsoro . I imagine that we have to mask passwords and secrets from these locations as well, since the file formats will be the same in all of them, right?

**Comment by palonsoro** [comment]
> Thank you for opening the issue @palonsoro . I imagine that we have to mask passwords and secrets from these locations as well, since the file formats will be the same in all of them, right?

Correct. Same data masking must be done on those files too. It is the same format (in case you are curious, it is documented in `man 5 nm-settings-keyfile` and `man 5 nm-settings`).
