### ISSUE TITLE
sosreport hang when any subset of commands in sosreport plugin hang

### ISSUE THREAD

**Issue by arunabal** [sosreport/sos#407]
We have a bug in sosreport that any subset of debug data collection commands in sosreport plugin having hang issue, the overall sosreport hangs (has to be killed).This results in complete loss of debug data, which results in unsatisfied customers.
Sosreport should be fixed to collect debug information on a system even if it is in hang state (e.g. io hang or disk error).
We need a fix that when sosreport finds certain commands are having hangs/errors it can be able to ignore them with proper tracing and execution of the remaining part of sosreport resuting in as much as possible available debug data when sosreports ends.

**Comment by bmr-cymru** [comment]
I'm closing this issue as we have had command timeout protection in place for years now, and this is the only claim of it "not working" in a 3.x release.

If you are still having problems please re-open and include the exact sos version, as well as the steps you are taking to reproduce.
