### ISSUE TITLE
"date" output should (also) be in UTC?

### ISSUE THREAD

**Issue by portante** [sosreport/sos#408]
Seems like the default "date" command output will (much of the time) include an abbreviated timezone string, but that string is a bit ambiguous for some time zones (see http://stackoverflow.com/questions/1703546/parsing-date-time-string-with-timezone-abbreviated-name-in-python/4766400#4766400).

If we added `date --utc` output as well, consumers of reports could more easily reason about the time a sosreport was collected compared to other timestamps.

For example, what timezone does "IST" represent? While we have /etc/localtime information for some systems, it not be always be available.

**Comment by TurboTurtle** [comment]
Closing per 971b958
