### ISSUE TITLE
[kernel] dmesg in containers may fail

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#410]
Like this:

```
$ cat sosreport-atomicdockercontainer-20140925070217/sos_commands/kernel/dmesg 
dmesg: read kernel buffer failed: Permission denied
```

**Comment by jcastill** [comment]
So far I've managed to reproduce this, with a RHEL 7 container and sos 3.5-9.el7_5. Next step, I'll test it with latest upstream one. 

One interesting thing I've found is that I get a SELinux alert in the host:

> SELinux is preventing dmesg from syslog_read access on the system Unknown.
> 
> *****  Plugin catchall (100. confidence) suggests   **************************
> 
> If you believe that dmesg should be allowed syslog_read access on the Unknown system by default.
> Then you should report this as a bug.
> You can generate a local policy module to allow this access.
> Do
> allow this access for now by executing:
> # ausearch -c 'dmesg' --raw | audit2allow -M my-dmesg
> # semodule -X 300 -i my-dmesg.pp
> 
> Additional Information:
> Source Context                system_u:system_r:container_t:s0:c227,c505
> Target Context                system_u:system_r:kernel_t:s0
> Target Objects                Unknown [ system ]
> Source                        dmesg
> Source Path                   dmesg
> Port                          <Unknown>
> Host                          hogwarts
> Source RPM Packages           
> Target RPM Packages           
> Policy RPM                    selinux-policy-3.14.1-40.fc28.noarch
> Selinux Enabled               True
> Policy Type                   targeted
> Enforcing Mode                Permissive
> Host Name                     hogwarts
> Platform                      Linux hogwarts 4.17.19-200.fc28.x86_64 #1 SMP Fri
>                               Aug 24 15:47:41 UTC 2018 x86_64 x86_64
> Alert Count                   6
> First Seen                    2018-09-12 12:01:38 BST
> Last Seen                     2018-09-12 12:09:34 BST
> Local ID                      672ca2b3-e58f-430e-83ba-98f78174eb4d
> 
> Raw Audit Messages
> type=AVC msg=audit(1536750574.749:853): avc:  denied  { syslog_read } for  pid=18734 comm="dmesg" scontext=system_u:system_r:container_t:s0:c227,c505 tcontext=system_u:system_r:kernel_t:s0 tclass=system permissive=1


If I disable SELinux in the host, I can run 'dmesg' without problems in the container.

**Comment by jcastill** [comment]
This comment in bz seems to explain this:

https://bugzilla.redhat.com/show_bug.cgi?id=1167826#c2

TBH I'm not familiar with containers so I'll keep investigating.

**Comment by bmr-cymru** [comment]
I thought the "super privileged" support containers that `sos` is supposed to run in were meant to have all the SELInux labels, permissions and capabilities needed for all these commands?

**Comment by TurboTurtle** [comment]
@bmr-cymru Correct - running in an SPC (`--privileged`) is what allows this to work properly. If sos is run in a non-SPC container, then these errors should be expected.

**Comment by TurboTurtle** [comment]
Closing this as when `sosreport` is run in a properly configured SPC container (according to the distro policy in use), this is not an issue.

This is an expected failure if `sosreport` is run in a "regular" container that is not configured according to policy.
