### ISSUE TITLE
[global] produce release tarballs and host them somewhere sane

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#414]
GitHub's release tarballs are made of pain and fail when it comes to packaging. See e.g. the (Fedora packaging guidelines)[https://fedoraproject.org/wiki/Packaging:SourceURL?rd=Packaging/SourceURL#Github].

We can make life easier for our downstreams (which is us half the time :-) by producing a stable release tarball and hosting it somewhere else.

**Comment by TurboTurtle** [comment]
I'm thinking this can be closed. Afaik the github tarballs are used for RHEL, Fedora, and Ubuntu, so this probably isn't the same problem is was in 2014.

@slashdd @sandrobonazzola - can you confirm if you do/don't use the GH release tarballs for the downstream package builds?

**Comment by slashdd** [comment]
@TurboTurtle I do use the GH release tarball for Debian and Ubuntu.

**Comment by sandrobonazzola** [comment]
@TurboTurtle within Fedora spec file I have:
```
Source0: https://github.com/sosreport/sos/archive/%{version}.tar.gz
```
and works fine for me. I'm fine closing.

**Comment by bmr-cymru** [comment]
Yeah, this dates back from when GitHub's releases were more difficult to work with, and before we changed the tagging format to give the expected tarball structure. Ack to closing.
