### ISSUE TITLE
[openstack_neutron] with latest sos-3.2-4.el7.noarch neutron configuration and logs files are not captured.

### ISSUE THREAD

**Issue by poornimakshirsagar** [sosreport/sos#420]
Environment:
RHEL 7 + RHOS5
sos package:sos-3.0-23.el7.noarch

Issue:
When running profile or only neutron plugin with commands "sosreport -p openstack" or "sosreport -o openstack_neutron" 
openstack_neutron plugin does not collect /var/log/neutron logs and /etc/neutron files.

**Comment by mkerrin** [comment]
Hi we have also hit this problem which is fixed by 234f0104a887c267c0826fdb85c3752534636be8. This patch is currently on the bmr-openstack_neutron-pkgcheck branch. Is it planned to be moved onto master and into a future release?

**Comment by bmr-cymru** [comment]
Ugh sorry - this should've been merged months ago. Fixed - the new commit ID is 3f8c4b658c5d702bde59bdd98cb114ea0064eae9 after rebasing to today's master.

**Comment by mkerrin** [comment]
no problems. thanks for the quick response

**Comment by poornimakshirsagar** [comment]
Thanks Bryn, Happy to see changes merged in master .
