### ISSUE TITLE
maas dumpdata error: argument COMMAND: invalid choice

### ISSUE THREAD

**Issue by chrisjohnston** [sosreport/sos#423]
usage: /usr/lib/python2.7/dist-packages/maascli/__main__.py [-h] COMMAND ...
/usr/lib/python2.7/dist-packages/maascli/__main__.py: error: argument COMMAND: invalid choice: u'dumpdata' (choose from u'list', u'login', u'logout', u'refresh', u'maas')

**Comment by battlemidget** [comment]
This was fixed already
