### ISSUE TITLE
[puppet] add new plugin

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#450]
Puppet is a popular configuration management system. Add a plugin to collect configuration and logs:

```
/etc/puppet/*.conf
/etc/puppet/rack/*
/etc/puppet/manifests/*
/var/log/puppet/*.log
```

The configuration also needs checking for the presence of secrets.

**Comment by sbradley7777** [comment]
Created a new branch that contains a new plugin for puppet  "sbradley-puppet-new_plugin":
- https://github.com/sosreport/sos/compare/sbradley-puppet-new_plugin

The diff against upstream:
- https://github.com/sosreport/sos/commit/79984402303b01c81eb5a6825350d030e4022edd

**Comment by battlemidget** [comment]
@sbradley7777 can you file a pull request? making sure to follow https://github.com/sosreport/sos/wiki/Contribution-Guidelines

**Comment by sbradley7777** [comment]
No problem. I will do that.
