### ISSUE TITLE
[cgroups] doe anything still use /etc/sysconfig/cgconfig?

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#453]
This file was removed from Red Hat distros to accommodate systemd management of cgroups. If there are no remaining users we should drop it from the plugin.

**Comment by pmoravec** [comment]
After filing the PR, I realized the file is still relevant for older RHEL versions, so it should be still collected :-/

**Comment by bmr-cymru** [comment]
Right: I still see this on my EL6 boxes. I'll close the issue & associated PR as we'll need to support pre-systemd setups for some time.
