### ISSUE TITLE
[pci] lspci collection is frustrating

### ISSUE THREAD

**Issue by jbainbri** [sosreport/sos#458]
Currently sos collects:

~~~python
        self.add_cmd_output("lspci", root_symlink="lspci")
        self.add_cmd_output([
            "lspci -nvv",
            "lspci -tv"
        ])
~~~

Just `lspci` on its own is relatively useless, it contains no extended info or PCI IDs.

It's frustrating to look through `lspci -nvv` because it only contains bus locations, not device names, so you constantly have to check back between one and the other. This used to collect into the one `lspci` file (in EL6) but as of EL7 it's in two files, which is worse.

The tree `lspci -tv` is okay, though it would be better with PCI IDs next to the names.

The most useful output is `lspci -vvnn` which gives PCI IDs and extended info and device names.

I propose to only collect this useful command, and to add PCI IDs to the tree command:

~~~python
        self.add_cmd_output("lspci -vvnn", root_symlink="lspci")
        self.add_cmd_output([
            "lspci -tvnn"
        ])
~~~

Sound good?

**Comment by bmr-cymru** [comment]
Gets my vote.
