### ISSUE TITLE
[sosreport] tarball names make my eyes bleed

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#469]
```
sosreport-bmr-rhel7-vm1-20150120185311.tar.xz
sosreport-bmr-rhel7-vm1-20150120185466.tar.xz
sosreport-bmr-rhel7-vm1-20150120190021.tar.xz
```

I'd meant to file this for review for 3.2 but it missed the boat. We've changed the tar/directory name format a few times over the years but I still find the long numbers awkward and clumsy to deal with (esp. at the terminal when working with several reports from the same host at slightly different times).

One improvement would be to just add dashes for the date components:

```
sosreport-bmr-rhel7-vm1-2015-01-20-185466.tar.xz
```

But I think we can do better; either way, if we're going to make another change it should be something we're going to stick with for a reasonable length of time.

**Comment by battlemidget** [comment]
Maybe break it up under a directory labeled like 'sos-2015-01-20/sosreport-bmr-rhel7.tar.xz' -- just throwing out an idea, not really sure the best way to handle this

**Comment by TurboTurtle** [comment]
I'm not alone with the bleeding eyes it seems!

I was thinking that reducing the timestamp and adding a short 3-character random string would do well. It would still allow for organizing/tab-completing by date for the most part, and would make referencing a specific sosreport easier between multiple parties - even without referencing the timestamp.

For example `sosreport-jhunsake.1234567-2017-01-24-iia.tar.xz` could be referenced simply as "sosreport iia" or somesuch between parties as the chance for string collisions is extremely low. 

I have something whipped up for this but held back on the PR for now.

https://github.com/TurboTurtle/sos/commit/5b7ccc2f27df939105e9e31927987830d7c87151

**Comment by bmr-cymru** [comment]
I'd be inclined to go for 7 chars for the hash/uniquifier - 3 chars doesn't give a whole lot of space for environments using large-scale automation.

More generally though (and the reason I didn't push too hard on this, and kinda parked it..) is that it needs coordination with a whole bunch of stakeholders at Red Hat, Canonical and elsewhere.

If you're happy to work on this, and help come up with a plan for when we are going to introduce this - or (I literally just thought of this) - a policy/config file tunable to switch between "legacy naming" and "nice naming" (or whatever.. :) ), that would be really awesome!

**Comment by TurboTurtle** [comment]
I like the idea of a policy/tunable, and sure I can run with this.

My reason for the 3 character example is that, at least for me, there is little difference between seeing `185466` in a file name (separated by dashes or not) and `abcdef`. 3 may well be short, but if my memory of high school math isn't utter garbage (not saying it isn't) going to 4 would still put us below a 0.01% chance of collision unless you're generating an obscene number of sosreports. 

I'll see what I can come up with though.

**Comment by bmr-cymru** [comment]
I only suggested 7 as it's a generally accepted length that you can truncate a hash to, and still have a good chance of it being unique - e.g. git commit IDs.

I like breaking up the date and making it more human-readable and if we're already changing the format then we could try to include the short file hash (md5/sha256 depending on FIPS settings) in the name itself.

That's where I was going with the earlier comment (which re-reading it did not make that very clear :-)

**Comment by TurboTurtle** [comment]
Worked on this a bit today. Still holding off on the PR for now but I think this could work.

Basically, policies now have a configurable `name_scheme` that can be either `legacy` which uses the current naming scheme (and everything defaults to), `friendly` which does the above - shorten the date and adds a randomly generated string of a length set by the policy, or `custom` which allows a policy to set it's own naming scheme using substitution.

So, for example, using `name_scheme = ('friendly', 5)` in a policy  would give you this:

    sosreport-jhunsake-123456-2017-01-25-xhoqq.tar.xz
