### ISSUE TITLE
[plugins] ExperimentalPlugin tag?

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#470]
In the puppet plugin discussion it occurred to me that it may be useful to have plugins in the tree that are not enabled by default (e.g. because they haven't been tested on a particular distribution) but that can be turned on by a command line option, say `--experimental` or whatever.

I'd imagine this being used something like this:

```python
class QuxPlugin(Plugin, RedHatPlugin):
    """ Qux data collection
    """

    def setup(self):
        self.add_copy_spec("/some/file/to/collect")
        self.add_cmd_output("some-cmd-to-run")

class DebianQuxPlugin(QuxPlugin, DebianPlugin, ExperimentalPlugin):
    """ Qux data collection (experimental)
    """
    pass

```

This way we can get things in & allow users to test without adding untested code to the default plugin set.

**Comment by battlemidget** [comment]
I actually have a use case for this now :smile_cat:

**Comment by bmr-cymru** [comment]
See if that work for it :)
