### ISSUE TITLE
[plugins] add 'mail' profile

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#474]
A suggestion came up in a discussion with Red Hat QE about adding the `ssmtp` plugin to the `network` profile. Imho `network` should be for the network itself primarily (rather than services that run on it) and I suggested creating a `mail` profile instead, e.g.:

```
  dovecot
  postfix
  sendmail
  ssmtp
```

Thoughts?

**Comment by bmr-cymru** [comment]
See also #475

**Comment by karibou** [comment]
Hi,

Le 23/01/2015 13:01, Bryn M. Reeves a écrit :
> A suggestion came up in a discussion with Red Hat QE about adding the `ssmtp` plugin to the `network` profile. Imho `network` should be for the network itself primarily (rather than services that run on it) and I suggested creating a `mail` profile instead, e.g.:
> 
> ```
>   dovecot
>   postfix
>   sendmail
>   ssmtp
> ```
> 
> Thoughts?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/sosreport/sos/issues/474
> 

Sounds good to me and I agree that network profile is not the place for that.


Kind regards,

...Louis

-- 
Louis Bouchard
Software engineer, Cloud & Sustaining eng.
Canonical Ltd
Ubuntu developer                       Debian Maintainer
GPG : 429D 7A3B DD05 B6F8 AF63  B9C4 8B3D 867C 823E 7A61
