### ISSUE TITLE
[plugins] add 'exim' and 'qmail' MTA plugins?

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#475]
The [exim](http://www.exim.org/) mailer is a popular MTA shipped in several supported distributions.

[qmail](http://www.qmail.org/top.html) seems to be falling off in popularity but there are still several distributions supporting it.

Filing this to collate file and command requirements for these two packages.

**Comment by j47997** [comment]
"exim -bV" dumps a few lines about the installed configuration.  But Debian call the binary "exim4"...


The last line in the output from the above, starting at the 3rd word, is the location of the toplevel config file.   Debian, in some configs, autobuild this from several fragment source files; I don't know if
it's worth caring about them.

"exiwhat" is a command to give a view on current exim processes, including what processing stage they are at.

"mailq" is a command to dump the current spool (3 lines per item).

**Comment by TurboTurtle** [comment]
I've asked the RH support teams at least twice about these, and neither are needed on our end.

Given the amount of time this issue has been open and the lack of requests to fulfill it, I'm closing this out.
