### ISSUE TITLE
[x11]  Collect OpenGL and xrandr info

### ISSUE THREAD

**Issue by BryanQuigley** [sosreport/sos#482]
The following commands output could be useful.  I'm thinking in the X11 plugin, but not sure if we just should make a new one.

**/usr/lib/nux/unity_support_test -p**
Unity specific test to see if Unity can run at full graphics.

Example output:
OpenGL vendor string:   NVIDIA Corporation
OpenGL renderer string: GeForce GTX 750 Ti/PCIe/SSE2
OpenGL version string:  4.5.0 NVIDIA 346.35

Not software rendered:    yes
Not blacklisted:          yes
GLX fbconfig:             yes
GLX texture from pixmap:  yes
GL npot or rect textures: yes
GL vertex program:        yes
GL fragment program:      yes
GL vertex buffer object:  yes
GL framebuffer object:    yes
GL version is 1.4+:       yes

Unity 3D supported:       yes

Mesa's **glxinfo**
Small excerpt:
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GTX 750 Ti/PCIe/SSE2
OpenGL core profile version string: 4.4.0 NVIDIA 346.35
OpenGL core profile shading language version string: 4.40 NVIDIA via Cg compiler
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.5.0 NVIDIA 346.35
OpenGL shading language version string: 4.50 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.1 NVIDIA 346.35
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
OpenGL ES profile extensions:

**xrandr --verbose**
Shows state of the different screens/available video outputs.

Small excerpt:
Screen 0: minimum 8 x 8, current 1440 x 900, maximum 16384 x 16384
DVI-I-0 disconnected (normal left inverted right x axis y axis)
	Identifier: 0x1be
	Timestamp:  7701
	Subpixel:   unknown
	Clones:    
	CRTCs:      0 1 2 3
	Transform:  1.000000 0.000000 0.000000
	            0.000000 1.000000 0.000000
	            0.000000 0.000000 1.000000
	           filter: 
	BorderDimensions: 4 
		supported: 4
	Border: 0 0 0 0 
		range: (0, 65535)
	SignalFormat: VGA 
		supported: VGA
	ConnectorType: DVI-I 
	ConnectorNumber: 0 
	_ConnectorLocation: 0

**Comment by battlemidget** [comment]
Maybe xrandr in the X11 plugin and unity as a separate one?

**Comment by BryanQuigley** [comment]
That makes sense.
