### ISSUE TITLE
[plugin] last output

### ISSUE THREAD

**Issue by alexandrujuncu** [sosreport/sos#514]
Hello!

Any reason why there isn't a plugin available for the output of last (last reboot, last shutdown)?

It would be useful to correlate with information from /var/log/messages in order to see if was a graceful shutdown or crash.

Thanks!

**Comment by bmr-cymru** [comment]
No particular reason - nobody's requested it to date. One concern would be that this includes names defined by the local system (inc. possibly network identity services).

**Comment by alexandrujuncu** [comment]
RFC: https://github.com/alexandrujuncu/sos/compare/sosreport:master...master ?

What is the policy/recommendation on dealing with user info?
If adding all information from last would be too much of an issue, how about only 'last shutdown' and 'last reboot' ?

Thank you!

**Comment by bmr-cymru** [comment]
Thanks for working on this - there isn't really a strict policy except that we do consider collecting /obviously/ private data (password values, private keys, etc.) a bug. That's not the case here though - the patch is fine technically.

When it comes to other data it's more debatable; user names appear throughout the system logs for e.g. but we have had requests to add the ability to strip them in the past so it's something that comes up when there's a new addition including them. Similar story for IP addresses (and even MAC addresses recently for reasons that make slightly more sense).

My only real hesitation here is whether this wants to be in a plugin of its own or whether we can combine it with other related commands or file content (e.g. `who`, `loginctl show-sessions`).

**Comment by alexandrujuncu** [comment]
Hi!

I would speak for myself and the reason why I am asking for this: the need came from trying to see if the system crashed (and no logs were available) or the system was gracefully shutdown. So I wouldn't be interested in the logins and sessions, but the tracking of admin actions like reboot and shutdown.
An important keyword would be 'crash' in possible output of last.

**Comment by TurboTurtle** [comment]
Handled in #572 - closing.
