### ISSUE TITLE
[rsyslog] add postprocessing for passwords

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#525]
The rsyslog wiki [sayeth](http://wiki.rsyslog.com/index.php/Security):

```
Passwords currently need to be stored as plain-text in rsyslog.conf. It would not
make much sense to encrypt them with a well-known open symmetric key, as
anybody would quite simply be able to obtain the password value. So it is advised
to use as restricted accounts as possible within rsyslog.conf. 
```

Although this seems rare in practice we should ensure we are postprocessing these (esp. since commit b5f77b66bc216e0a21ee440e104fe2fd41a064e5 adds support for collecting `/etc/rsyslog.d` which the above docs suggest as a better place for secrets).

**Comment by battlemidget** [comment]
@BryanQuigley maybe you want to tackle this?

**Comment by BryanQuigley** [comment]
Sure thing

**Comment by bmr-cymru** [comment]
So one class is mysql database write selector lines, e.g.:

```
*.*       :ommysql:database-server,database-name,database-userid,database-password
```

Although that's apparently "legacy" (syslog selector-style) notation. The cool kids are doing:

```
$ModLoad ommysql
*.* 	action(type="ommysql" server="mysqlserver.example.com" serverport="1234"
	       db="syslog_db" uid="user" pwd="pwd")
```

There's also [$ActionlibdbiPassword](http://ftp.ics.uci.edu/pub/centos0/ics-custom-build/BUILD/rsyslog-3.19.7/doc/omlibdbi.html) and possibly others.

**Comment by BryanQuigley** [comment]
I wasn't sure of the best regex to handle the legacy class.  Pull request for the others here: https://github.com/sosreport/sos/pull/529
