### ISSUE TITLE
Can we have an option for --disable-plugin to not kill the command when non-existent or already disabled?

### ISSUE THREAD

**Issue by portante** [sosreport/sos#537]
Lately have been working on RPMs which use sosreport across multiple versions of RHEL and Fedora, with multiple versions of sosreport.

It would really help to start now relaxing the behavior of killing the sosreport command when --disable-plugin specifies a non-existent plugin, or one that is already disabled.

**Comment by bmr-cymru** [comment]
Let me think about this some; I know some users have used error returns as a "plugin detection" mechanism so my main concern would be that we aren't breaking any downstream use cases.

Otherwise it seems a reasonable request.

**Comment by sandrobonazzola** [comment]
I think that relaxing the check will make a bit harder to see that sos changed from a caller program point of view. You'll never see that your super-useful-plugin changed name in extremely-useful-plugin unless you actually check the report content or inspect carefully the execution output. I would prefer to keep existing behavior.

**Comment by bmr-cymru** [comment]
@sandrobonazzola that's exactly my concern - that downstream users could be relying on the "fail if unknown" behaviour.

Personally I would much rather see this tackled by providing an API for programmatic execution of sos than by changing very long standing command line behaviour.

That said if we cannot find any examples of that reliance I would consider making this change to ease transitions for users who do need to interrogate the plugin set.

**Comment by bmr-cymru** [comment]
A possible compromise would be to add a new command line option, say `--mask-plugins`, that accepts a list of plugins (just like `-n` does now), to be "masked off" - but with the difference that masking a non-existent plugin is explicitly not treated as error.

This may also then tie into another feature I've been thinking of for a while - a mechanism to allow administrators to persistently mask certain plugins (Solaris' explorer script has had this for some time).

**Comment by bmr-cymru** [comment]
Obviously this didn't make 3.5, but I'm going to re-flag it for 3.5 as I think it's worth considering.

**Comment by bmr-cymru** [comment]
Still no progress here & getting a bit close to 3.5... I think the final proposal for a `-m/--mask-plugins` is worth considering (a list of plugin names to mask out whether or not they actually exist).

**Comment by bmr-cymru** [comment]
Unfortunately out of time for 3.5 but this will be reconsidered for 3.6 (next April).
