### ISSUE TITLE
[process] Collect the basics per-process from /proc/$PID/

### ISSUE THREAD

**Issue by BryanQuigley** [sosreport/sos#542]
We should collect more of the per-process basics.   Old pull request:https://github.com/sosreport/sos/pull/436.  Collecting all of them causes run time to increase a lot.

Possible options forward:
1.  Collect the first 1000
2.  Write a bit of code to go through things that might be empty or the same (oom_, limits) and only record it once, and then say these PIDs also have that.
3.  Be more process specific.  For instance, I know I wanted to collect the limits from nova-compute,kvm, libvirt.   Just collect it from the first one of those.

**Comment by battlemidget** [comment]
option 2 may not be a bad idea, I'm not sure how'd we implement option 3 as there are so many of them. I was thinking maybe a process_mapping dictionary that the plugins could append to and have collecting process information that way. Still need to think more on this

**Comment by BryanQuigley** [comment]
fyi, I used a m1.large image with:
for i in `seq 1 30000`;
do
	sleep 10000 &
done
for previous testing.

**Comment by iranzo** [comment]
This will be interesting also for the OSP plugins related with qpid and rabbitmq as some issues are related with the number of maximum files and we need the value from /proc/pid/ for this.

Should this be covered under this issue or should a new one be filled for qpid and rabbitmq plugins?

**Comment by pmoravec** [comment]
Re @iranzo: Does not lsof command provide that information?

**Comment by iranzo** [comment]
Hi @pmoravec  with lsof we get the number of files currently open, but not the maximum of files that a process can hold, check for example <https://access.redhat.com/solutions/1395923>
