### ISSUE TITLE
[virsh] gather virt-manager logs and some domains info

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#544]
It is requested to gather below command outputs:

ls -l /var/lib/libvirt/qemu/*
virsh list --all
for all domains in virsh list, gather virsh dumpxml $DOM

And virt-manager logs:
/root/.virt-manager/*

**Comment by bmr-cymru** [comment]
imho this should go into a new virsh plugin - that stuff is part of the libvirt-client package on Fedora & related RH distros (which may be installed separately from libvirt itself).

**Comment by pmoravec** [comment]
New stuff moved to libvirt_client plugin, comments from the PR incorporated.

**Comment by bmr-cymru** [comment]
Considering virsh is the primary libvirt-client shipped in the package I think that would make a better name for the plugin:

```
$ rpm -ql libvirt-client | grep bin
/usr/bin/virsh
/usr/bin/virt-host-validate
/usr/bin/virt-pki-validate
/usr/bin/virt-xml-validate
```
