### ISSUE TITLE
sosreport needs enhanced functional testing

### ISSUE THREAD

**Issue by karibou** [sosreport/sos#555]
Due to specific Ubuntu requirements, the current release process for sosreport cannot propose a version that is recent once it has reached Stable Release on Ubuntu.

To alleviate this situation, Ubuntu needs to be able to have a better regression coverage and testing prior to release. We propose to use the autopkgtest test mechanism, standard to Ubuntu and Debian, to test for regressions and functionalities prior to release.  Autopkgtest is run at each package build and each time a package depending on sosreport is rebuilt (currently no such package exists).

Autopkgtest tests reside in ./debian/tests so they will remain confined to the Ubuntu and Debian distributions and will not affect other distributions using sosreport.

**Comment by bmr-cymru** [comment]
> Due to specific Ubuntu requirements, the current release process
> for sosreport cannot propose a version that is recent once it has
> reached Stable Release on Ubuntu.

What are they? This statement is confusing and I think we should understand the problem so that we can see how other distributions may be affected.

> better regression coverage and testing prior to release

Better regression testing & coverage is always welcome (although the other supported distros have seemed OK with doing this downstream so far).

> Autopkgtest tests reside in ./debian/tests so they will remain confined to the Ubuntu and Debian 
> distributions and will not affect other distributions using sosreport.

My main concern here is that we not implement things in `debian/tests` that could in fact be useful for other distributions and downstream users: I don't want to see one distro's test suite growing at the expense of the others.

**Comment by karibou** [comment]
Stable Release Update rules for Ubuntu do not allow backport of new functionalities into Stable Releases. The only way around this is to request for a Micro-Release Exception (MRE) which require blessing of the Ubuntu Technical Board (TB). Here is recent discussion regarding sosreport during the latest TB meeting :

http://irclogs.ubuntu.com/2015/04/14/%23ubuntu-meeting-2.html

The TB is mostly concerned about regressions so those tests are meant to make sure that (hopefully) no regression of existing functionalities and output will be introduced by an MRE.

I totally agree with your concerns : what can be beneficial to Ubuntu/Debian can also be useful to others. So I would be more than happy to make those tests distro-agnostic as far as much as I can. As a matter of fact, my first intention was to expand on the unittest mechanism, maybe even require unit tests for plugins, etc.  I just wanted to avoid polluting other distributions with Ubuntu specific requirements.

While the autopkgtest mechanism that I expect to use is specific to Ubuntu/Debian, there is no reason to share the tests and/or call them from the ./tests unit test directory if needs be. This way, anyone can make use of the tests that Ubuntu will be using while building the package.

How does that sound ? Any better ?

**Comment by battlemidget** [comment]
I'd like to see some sort of integration testing using something like BDD where we can outline some of those regressions/quality tests easily.

I think as far as unittests go we do a really good job, but, maybe we can do more outside of that test scope to validate that regressions aren't creeping back in before release.

A MRE is beneficial to Ubuntu whereas we can cut past some of the red tape in order to keep sosreport up to the latest bits quickly.

**Comment by BryanQuigley** [comment]
FMU the tests don't necessarily have to be integrated into the package building process itself.  Obviously the more you can get there the better.

**Comment by battlemidget** [comment]
Good point, for this to be accepted it would have to cover all distributions we support. I think keeping it out of the package build process is the way to go.

**Comment by karibou** [comment]
Just so everybody knows, tests presents in ./tests (i.e. unit tests) do get run at debian package building time as well, so either solution would be fine with the MRE requirement

**Comment by bmr-cymru** [comment]
It needn't support all distros if it's specific to any one of them but if there are useful general integration tests I'd rather see them added in a distro-neutral way.

**Comment by battlemidget** [comment]
:+1:

**Comment by BryanQuigley** [comment]
I'm happy to iterate on https://github.com/sosreport/sos/pull/946/commits/4b1dea03fdad10e3ac3b58ad67b68f478c9aeedd  and starting creating some very simple runtime tests that are designed for the Travis environment.  

Do we have a preference on integrated runtime tests (say a framework to use)?

**Comment by battlemidget** [comment]
Would something like http://pythonhosted.org/behave/ be useful?

**Comment by karibou** [comment]
Debian/Ubuntu are using DEP8 (aka autopkgtest)[1] tests which I'm planning to submit upstream soon. They are still very basic but do : 
- verification of non-root execution behavior
- Verify that a basic tarball is created
- Verify if runtime errors (*errors.txt present in sos_logs)
- Verify the validity of the md5 checksum

I might be able to propose a PR soon.

[1] http://packaging.ubuntu.com/fr/html/auto-pkg-test.html

**Comment by BryanQuigley** [comment]
@karibou That sounds perfect!

**Comment by bmr-cymru** [comment]
I've had a few conversations with Red Hat QE folks on both the type of functional testing being discussed here and also the possibility of bringing some of their test cases to upstream.

Whatever we do on this I'd like to have as much coordination between downstreams as possible - that way we ensure that we're testing things that are useful, and that the results apply to as many of our users as possible.

Would it be useful to get on a call / video conference / IRC chat to discuss this further? I could probably pull a list of names from my side together in the next week or so.

**Comment by bmr-cymru** [comment]
Regarding the MRE issue for Ubuntu, RHEL has similar restrictions (they only apply to asynchronous errata though - the regular updates like 7.2, 7.3, ... do allow rebases and backports adding new functionality).

One way we can help address this is by maintaining stable branches and issuing featureless point releases that only include bug and security fixes on top of the base release.

The main need here is obviously someone to do the additional work of maintaining that branch and carrying out point releases as needed. I know @battlemidget has issued these in the past (I think for Ubuntu updates), but I don't want to just dump this on anyone unwilling :-)

**Comment by karibou** [comment]
Hello,

I would be more than happy to participate to such a meetup, whatever the media may be.

Regarding the MRE, this rule has changed and, with the help of the DEP8/autopkgtest, I was able to get 3.4 into all Ubuntu stable releases last week \o/ 

Now no longer being in the house will mean that it will be up to them to keep Ubuntu stable releases in sync, but I will do my best to keep Debian as close to trunk as possible.

**Comment by BryanQuigley** [comment]
I'm also in for a meetup and can gather people from Canonical.

**Comment by slashdd** [comment]
I'd like to be part of the meetup as well as a Canonical employee who contribute in sosreport, and more or less maintains it at the Ubuntu side.

**Comment by battlemidget** [comment]
Same, I'd like to attend as well

**Comment by BryanQuigley** [comment]
We now have functional regression testing in https://github.com/sosreport/sos/blob/master/tests/simple.sh for a while now.
