### ISSUE TITLE
Openstack scrubbing cleans the key which contains the password

### ISSUE THREAD

**Issue by iranzo** [sosreport/sos#574]
For example, in nova.conf:

qpid_password=guest

Gets scrubed to:
~~~
*********
~~~

Where it should be qpid_password=*********

**Comment by iranzo** [comment]
BTW, this was on sos-3.2-15.el7_1.1.noarch

**Comment by lyarwood** [comment]
@iranzo can you explain why this is an issue? This is obviously on purpose to avoid collecting sensitive information.

**Comment by iranzo** [comment]
The issue is removing the "qpid_password=" it just leaves the "***" with IMHO should be replaced to leave the "qpid_password=*****"

**Comment by lyarwood** [comment]
@iranzo ack apologies, I'll take a look at this one.

**Comment by bmr-cymru** [comment]
Yeah; what Iranzo said. This bug appears to have been c'n'ped across several OS plugins :-1:

**Comment by lyarwood** [comment]
@iranzo I can't reproduce this with 3.2-15 or upstream master, can you provide an example nova.conf that reproduces this?

@bmr-cymru yup, any objections to moving these 3 lines into an __init__.py method?

**Comment by iranzo** [comment]
Hi @lyarwood, I got already scrubbled from a sosreport, sorry, but don't have the original :/

**Comment by bmr-cymru** [comment]
We've talked about it a few times; it shouldn't be hard. Without thinking too much a method like:

```python
    def do_nvp_keys_sub(keys, files):
        regexp = r"((?m)^\s*#*(%s)\s*=\s*)(.*)" % "|".join(keys)
        for f in files:
            self.do_file_sub(f, regexp, r"\1********")
```

Then plugins just need to define their key and file lists and call the method.

**Comment by bmr-cymru** [comment]
Although `values_sub` may be more nit-pickingly correct...

**Comment by lyarwood** [comment]
Finally worked this one out, the regex is matching the commented out key then being greedy and applying a substitution to the next line when we have the following defined in a config file :

```
#key=
key=secret
```
Leaving the following :
```
#key=
**********
```
IMHO we don't need to subsitute commented out secrets (typically defaults) and so we just need to use the following regex here :

```python
regexp = r"((?m)^\s*(%s)\s*=\s*)(.*)" % "|".join(keys)
```

**Comment by bmr-cymru** [comment]
:+1:

Thanks Lee!
