### ISSUE TITLE
[juju] needs to support file size limits 

### ISSUE THREAD

**Issue by BryanQuigley** [sosreport/sos#579]
We've had customer's individual logs get over 1 GB and overflow the LXC container trying to capture them.

**Comment by BryanQuigley** [comment]
odd, I can't assign myself... I am planning on working on this.

**Comment by battlemidget** [comment]
@BryanQuigley i think you need to be part of the team to assign yourself

**Comment by BryanQuigley** [comment]
@battlemidget nope still doesn't work

**Comment by battlemidget** [comment]
@BryanQuigley har
