### ISSUE TITLE
[cluster] split the cluster.py plugin into a couple different plugins: pacemaker, dlm, gfs2, cluster

### ISSUE THREAD

**Issue by sbradley7777** [sosreport/sos#587]
The cluster plugin has gotten long in the tooth. The cluster plugin should be split into a couple different plugins: pacemaker.py, dlm.py, gfs2.py, cluster.py.

The cluster.py will be for clusters that are entirely "cman" based clusters and will still use the other plugins described above if they are "cman+{pacemaker, dlm, gfs2}".

For example: The `pacemaker.py` plugin already exist in upstream and we would move any pacemaker type data `cluster.py` gathers into `pacemaker.py`. The `dlm.py` and `gfs2.py` plugins do not exist and would have to be created.

**Comment by sbradley7777** [comment]
Currently building a version of sos with cluster.py split into different plugins. I will open branch once testing is complete.

**Comment by bmr-cymru** [comment]
If we're going to make `cluster` specific to CMAN clusters why not call the resulting plugin `cman`? I think we're making enough of a break from the past here that we can justify this and it's potentially less confusing for new users who might think `cluster` is some kind of generic clustering plugin.

**Comment by sbradley7777** [comment]
Looking over the cluster plugin, I think it would be safe to do that. We can change cluster plugin to cman.py, which will include commands/files to gather for cman based clusters which would include fencing, qdisk, and  rgmanager. Qdisk and rgmanager are a cman only thing, and fencing is done differently in pacemaker. 

I would say we can do this and will do on next update. Here is branch i created:
- https://github.com/sosreport/sos/tree/sbradley-cluster_plugin_split
