### ISSUE TITLE
[ovirt] obfuscate paswords in aaa profiles

### ISSUE THREAD

**Issue by timspeetjens** [sosreport/sos#588]
Properties files defining aaa profiles inside /etc/ovirt-engine/aaa contain passwords in clear text
Reported in https://bugzilla.redhat.com/1227019 - ovirt sosreport plugin doesn't obfuscate password used in aaa extensions

> Description of problem:
> oVirt plugin for sosreport includes /etc/ovirt-engine/aaa directory, which commonly includes bind-dn and password
>
> Version-Release number of selected component (if applicable):
> RHEV 3.5.0 and onwards
> 
> How reproducible:
> 100%
>
> Steps to Reproduce:
> 1. Specify a password in /etc/ovirt-engine/aaa/<anyprofile>.properties (vars.password)
> 2. Run a sosreport
>
> Actual results:
> The properties file for the profile contains the password, used for binding to the directory
>
> Expected results:
> Passwords should be replaced by ******

**Comment by bmr-cymru** [comment]
Please include enough information that a GitHub user can tell what you are reporting without having to visit a 3rd party site - just paste what your wrote into the bugzilla in a block-quoted section.

**Comment by sandrobonazzola** [comment]
@bmr-cymru anything else needed for getting @timspeetjens patch in?

**Comment by bmr-cymru** [comment]
Nope - had just fallen off my radar because the corresponding RH bugzilla is not against RHEL.
