### ISSUE TITLE
Review SELinux commands in enforcing/permissive/disabled modes.

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#605]
We had a bug report against RHEL recently where a user noticed setfiles messages leaking through from fixfiles when run with SELinux disabled:

```
# sosreport -vvv --batch --alloptions &> /tmp/sosreport.$(date +%Y%m%d-%H%M%S).log
usage:  /sbin/setfiles [-dnpqvW] [-o filename] [-r alt_root_path ] spec_file pathname...
usage:  /sbin/setfiles -c policyfile spec_file
usage:  /sbin/setfiles -s [-dnpqvW] [-o filename ] spec_file
```

Although this case appears to be a fixfiles bug we have never audited the commands issued by the SELinux module to ensure they behave correctly / predictably in different SELinux modes.

Only enabling the plugin on systems where SELinux is currently enabled is not an option since that causes a loss of diagnostics on hosts where SELinux has been temporarily disabled.

If there are commands that /must/ only run when SELinux is on it's trivial to gate these on the state of SELinux via the Python SELinux bindings or via /sys.

**Comment by TurboTurtle** [comment]
Closing per f72aaa6
