### ISSUE TITLE
[docker] collect docker logs (journald)

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#609]
Something like:

```
journalctl -r -u docker
```

Same idea as Kubernetes etc.

**Comment by jameswmills** [comment]
I'd really like to see this feature added.  Any chance we can move it forward, maybe without the "-r"?

**Comment by bmr-cymru** [comment]
There's nothing really blocking it except a need to get some feedback from the current related plugins (kubernetes principally) - we should either use or not use -r consistently (it's a trivial tac to reverse it analysis side anyway).

Right now and as I haven't heard anything from the kube guys I am inclined to just revert all `journalctl -r` use and merge this to the docker plugin. I'll ping again but I suspect I won't hear back.
