### ISSUE TITLE
[openshift] current plugin does not cover latest versions of OpenShift

### ISSUE THREAD

**Issue by codificat** [sosreport/sos#612]
The existing openshift plugin in sos covers version 2.x of OpenShift Enterprise (OSE) / upstream OpenShift Origin M4.

However, OSE 3 (origin M5) is a very different product and the existing plugin does not collect any relevant information about it.

The product is so different than I'm wondering if it's best to create a separate plugin for it rather than try to adapt the current one to handle both versions. Thoughts?

The docker plugin covers some of the information to collect for the new version - that should be included in the openshift profile. 

Latest OpenShift also bundles Kubernetes, but the kubernetes plugin as it is right now does not work for an openshift environment because the components, commands, config files etc have different names. I'm also wondering if the kubernetes plugin should be made aware of this or not.

**Comment by bmr-cymru** [comment]
> wondering if the kubernetes plugin should be made aware of this or not.

If we are going to collect kubernetes data in OSE3 then yes; we are not doing any special `openshift_kubernetes` (or any other "special" OSE/OSP plugin versions).

**Comment by pmoravec** [comment]
> However, OSE 3 (origin M5) is a very different product and the existing plugin does not collect any relevant information about it.

> The product is so different than I'm wondering if it's best to create a separate plugin for it rather than try to adapt the current one to handle both versions. Thoughts?

What packages would trigger the new plugin? What configs/logs/cmd output it should collect? Just to know the diff from current openshift plugin..

**Comment by jeremyeder** [comment]
See:  https://bugzilla.redhat.com/show_bug.cgi?id=1246423#c3

**Comment by codificat** [comment]
About information to collect: for openshift-sdn take a look at https://raw.githubusercontent.com/openshift/openshift-sdn/master/hack/debug.sh

**Comment by pmoravec** [comment]
. @codificat thanks - would you be so kind to identify from the script what commands etc. current sosreport does not collect? As e.g. the debug script collects

    nmcli --nocheck -f all con show

while sosreport calls:

    nmcli con show --active

i.e. without some fields/details. Are these details important for Openshift troubleshooting?

Similarly other commands I dont know if their similar variant in sos is satisfactory or not.

**Comment by sferich888** [comment]
Adding Ideas to this topic / thread for what this plugin should collect and how: 


The following KCS are good places to start for collecting data: 

https://access.redhat.com/solutions/1542293

For looking at oc commands as a system:admin you can use the following if you are looking to automate commands.

    # oc get pods --config="/etc/openshift/master/admin.kubeconfig"

For getting a list of pods for node in an OSE environment:

    # for node in $(oc get nodes | awk 'NR!=1{print $1}'); do \ 

        oadm manage-node $node --list-pods; 

    done

The same loop could be used to also get the following:

     # oc describe node

What pods can we see if we are on the "master" and have (system:admin) privileges.

    # oc get pods --all-namespaces

Determine infrastructure version information:

    # oc get dc docker-registry -o yaml | grep image: | tr -d " "

I also feel that running or collecting information presented by the following trello cards is important: 

https://trello.com/c/LdUogKuN/73-3-introduce-openshift-v3-diagnostics
https://trello.com/c/On7sLHVw/152-diagnostics
https://trello.com/c/c3Amaijl/88-5-diagnostics-container
https://trello.com/c/HtaFZbiR/68-13-network-diagnostics-utility-supportability
https://trello.com/c/8OxoAsOT/73-5-openshift-ex-diagnostics-deep-dive

https://trello.com/c/F3U1aWRz/75-8-openshift-diagnostics-for-cluster-admin
https://trello.com/c/mlXbW949/74-8-openshift-diagnostics-for-host

We should also be leveraging or updating the following plugins to collect OSE data (where approprate)

https://github.com/sosreport/sos/blob/master/sos/plugins/docker.py
https://github.com/sosreport/sos/blob/master/sos/plugins/kubernetes.py 
   -- We likely need to modify this to also pick up or trigger have OSE trigger data collection using this plugin as OSE is a distribution of kuberneties.

**Comment by codificat** [comment]
@pmoravec apologies for the delay here, I'm working on an updated plugin and will submit PR asap.

**Comment by codificat** [comment]
#783 should fill in the gap for current OpenShift versions.

Also a significant part of useful troubleshooting information for AP/OSE 3+ depends on #717 , #718 and #782.
