### ISSUE TITLE
[sapnw] Add check if saphostctrl is not present

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#614]
Sosreport tracebacks when explicitly enabling `sapnw` plugin on a system with no SAP NetWeaver installed:

```
sosreport -o sapnw -e sapnw
..
  File "/usr/lib/python2.7/site-packages/sos/plugins/sapnw.py", line 51, in setup
    p = open(inst_out, "r").read().splitlines()
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

That's because execution of:

```
    inst_out = self.get_cmd_output_now("/usr/sap/hostctrl/exe/saphostctrl \
                                       -function ListInstances",
                                       suggest_filename="SAPInstances")
```

fails due to unknown command, and it returns / sets to `inst_out` None.

`open` and whole subsequent loop needs to be conditioned by `if inst_out:` clause.

**Comment by bmr-cymru** [comment]
Ack; anything not testing the return of `get_cmd_output_now` is broken.

**Comment by bmr-cymru** [comment]
Merged.
