### ISSUE TITLE
[xfs] replace xfs_logprint by few other commands

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#621]
It has been suggested to replace `xfs_logprint` (that is invoked by xfs plugin for every xfs filesystem, even mounted where it makes no sense) by:
- xfsprogs version (xfs_repair -V) (I suppose we have this already from rpm data?)
- xfs_info output for all filesystems
- xfs mount options (probably gathered already?)
- xfs_stats output /proc/fs/xfs/stat & /proc/fs/xfs/xqmstat

Some background to this: https://bugzilla.redhat.com/show_bug.cgi?id=1250035

Is there some objection in removing `xfs_logprint` from xfs plugin and having the above info there?

**Comment by badone** [comment]
I have no objections. Looks like we grab xfs_info already looking at the plugin and mount options should be in /proc/mounts or /etc/fstab which we also gather and, of course, xfsprogs version would be in" rpm -Va" output (deb equivalent?) We should probably try to avoid doubling up on information gathering if we can avoid it?

**Comment by bmr-cymru** [comment]
* xfsprogs version (xfs_repair -V) (I suppose we have this already from rpm data?)
Duplicates rpm data: NACK.

* xfs_info output for all filesystems
Ack.

* xfs mount options (probably gathered already?)
NACK: as you say gathered already but more importantly: the only purpose of per-file system plugins is to collect things the generic filesys cannot. The less fs-specific cruft we have to maintain the better.

* xfs_stats output /proc/fs/xfs/stat & /proc/fs/xfs/xqmstat
I'd like some more detail on exactly what this is but it seems like something very XFS-specific so in-principal Ack.

**Comment by j47997** [comment]
On 11/08/15 09:11, Bryn M. Reeves wrote:
> * xfs_stats output /proc/fs/xfs/stat & /proc/fs/xfs/xqmstat
> I'd like some more detail on exactly what this is but it seems like something very XFS-specific so in-principal Ack.

Bzzzt!

Principle, not principal.

**Comment by bmr-cymru** [comment]
One pedant prize coming right up! :+1:
