### ISSUE TITLE
Make generated archive available to person who ran sudo

### ISSUE THREAD

**Issue by BryanQuigley** [sosreport/sos#631]
Despite having it in our instructions many users forget to chown the archive in /tmp, and then get oddly not descriptive enough errors when uploading in browsers.

Could we arrange it so the user that run sudo has permissions over the file?

**Comment by bmr-cymru** [comment]
I'm not really comfortable with that: our disclaimer is based on the fact that you must be the administrative user to run the tool and that you must also have those privileges to change who can access the information.

If we had the ability to separate the sos front and backends (as proposed in the DBUs API idea) and use polit for the privilege management it would be reasonable but I am not really willing to an an arbitrary "do stuff only root can option" (e.g. chown the output file) interface for general use.

If you can propose something more restricted I'm happy to look at it but I think a wrapper script is probably the simpler option (sudo sos_wrapped -> runs sos & chowns the output)

**Comment by BryanQuigley** [comment]
In that case, maybe just alert users who used sudo that they need to change the permissions on it.

**Comment by bmr-cymru** [comment]
```
$ cat sosreport
#!/bin/bash
if [ ! -z "$SUDO_COMMAND" ]; then
    echo "WARNING: running sosreport via sudo. Please ensure you 'chown' output files."
fi
exec sosreport.real
$
```

I don't see any need to put this in sos.

**Comment by karibou** [comment]
Maybe I'm not understanding the request correctly, but if a user needs sudo to run a command (sosreport in that context), it is not uncommon to have to use sudo for the follow-up commands. Here is an example  :  
$ sudo apt-get update
$ sudo apt-get upgrade

I do agree with Bryn, sosreport should not take that responsibility.

**Comment by battlemidget** [comment]
> and then get oddly not descriptive enough errors when uploading in browsers.

Why not just put the info message on whatever website you're using to upload sosreport tarballs?

**Comment by bmr-cymru** [comment]
To be clear: I am fine with well constructed tools to simplify this but I am not willing to introduce hacks and partial solutions upstream even if they do "completely" solve some down-stream problem. A front/back split with polkit authentication would do this but I am not prepared to take the risk of opening up potential security holes for an incomplete fix that may have complex risks we do not understand.

If this is desperately wanted downstream there is nothing to stop distributions patching this in - we're just not going to do it upstream in this way.

**Comment by battlemidget** [comment]
Closing as nacked

**Comment by bmr-cymru** [comment]
Heh, I was going to leave it open for the conversation to continue.. I understand that there is a need for distributions to simplify the collection and transmission of sos data and that crossing OS privilege boundaries is one of the obstacles to that - I'm just going to take a /lot/ of convincing that the Giant Chown Hammer is the best we can do for that.

**Comment by BryanQuigley** [comment]
I'd be happy with it just being a reminder for everyone, something like adding:
The archive is only accessible to root as it can contain root-only accessible information from the system.
-or-
To protect the integrity of system information the sosreport permissions are set to root-only access.

Alternatively change:
Your sosreport has been generated and saved as root-accessible in:

These solve the problem that we never actually tell the user that the sosreport will be only accessible to root.  We also reiterate that we are protecting the security of their system.

If we want to go in a different direction, removing:
Please send this file to your support representative.
*might* help with this issue.  I see that and I immediately think attach to case.   If I just see the rest, I think let me ls it and see how big it is.

**Comment by bmr-cymru** [comment]
That's not a bad idea. Open to suggestions for additions to the disclaimer text or I can draft something when I get a chance.

**Comment by BryanQuigley** [comment]
Add the disclaimer text to the end instead of the beginning:
The generated archive permissions have been set to only allow root access as it may contain data considered sensitive. Its content should be reviewed by the originating organization before being passed to any third party.

**Comment by bmr-cymru** [comment]
How come this got merged when it doesn't seem to have received the acks required by the process? There have been positive comments, but no agreement from other maintainers on the final version of the patch from 25 days ago.

If something needs review, either ask in the thread, or assign someone using the GitHub interface - there are aspects to this patch that need re-thinking.

**Comment by BryanQuigley** [comment]
I certainly could have left it for more comments, but TurboTurtle did ACK it 26 days ago and the most recent push was just a rebase.

I thought your comment on Sept 20th was that I should just work out the other end text changes with TurboTurtle.  pmoravec also LGTM this before that (the changes highlighted were in my original PR from sept).  

In hindsight, I really should have pushed back against including the end text changes together when I realized they aren't touching the same code.

In any case, I'll do more consensus pings in other similar PRs next time, and get a new PR going to fix this one up.
