### ISSUE TITLE
[openstack_nova] replace `nova-manage` with `openstack` or `nova` commands.

### ISSUE THREAD

**Issue by lyarwood** [sosreport/sos#646]
The following commands (or using the unified `openstack` command line tool) would be useful for example :

`nova agent-list`
`nova service-list`
`nova host-list`
`nova version-list`

**Comment by battlemidget** [comment]
Let me know if you can get this patch submitted asap

**Comment by Akasurde** [comment]
PR merged. Issue can be closed.
