### ISSUE TITLE
[Plugin] higher-level collection methods

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#659]
So far we have allowed plugins to collect two primary types of data:
- Files
- Command output

With the advent of things like journald logging we now have lots of plugin code calling essentially the same command, e.g.:

```
    journalctl -u someunit
```

We could generalise this and gain centralised control of these commands by providing a method interface, say:

``` python
    self.add_journalctl_unit("someunit")
```

Just a thought for now - to make this viable we'd need to consider what commands to wrap in this way, how to present them, as well as what to do on legacy distributions that do not support these interfaces.

**Comment by karibou** [comment]
Just another thought : couldn't it just return False if the service is unavailable ?

**Comment by bmr-cymru** [comment]
It's more a question of do we make it `add_system_logs` (with logic to handle both {r,}syslog and journald) or leave plugin authors to handle the distinction.

**Comment by TurboTurtle** [comment]
I'm closing this out as we now have `add_journal()` and `add_service_status()` in `Plugin()` and we have an `InitSystem` class for interacting with the init system of the host for discovering service states and info.
