### ISSUE TITLE
[openstack] option to dump N days of logs

### ISSUE THREAD

**Issue by w-miller** [sosreport/sos#664]
We have a working way of dumping N days of logs in our own plugin, and it wouldn't be too difficult to add this to the OpenStack plugins. It is useful for us because we may want to investigate an incident that occurred several days ago on a given system, and dumping by file extension is not sufficient as different systems have different log rotation frequencies. Also, dumping --all-logs can be impractical if a system doesn't periodically remove older logs, leading to huge dump sizes.

**Comment by bmr-cymru** [comment]
This is actually far more difficult than it sounds. Although modern log facilities (e.g. journald) do provide this sort of indexing it is much harder to do correctly for traditional (`syslog` style) log data.

Before we can add this as a top-level option (like `--all-logs`) we need a mechanism that will work across all log sources.

What's the mechanism you're using for OpenStack? Journald or hand-parsing of log files?

**Comment by w-miller** [comment]
Sorry about the late reply. We're currently just choosing files in /var/log/{package} that have an mtime of <= the number of days specified. So we're not parsing the files at all, just taking all log and rotated log files that have been updated since the date. While it's not as ideal a solution as you could achieve with journald, it works okay as a general mechanism to reduce dump size.

**Comment by TurboTurtle** [comment]
Closing, as the requested functionality exists within sos today via `--since`.
