### ISSUE TITLE
[plugins] Handle log_size and all_logs inside Plugin

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#665]
We still have several plugins not using the global `all_logs` and `log_size` options. We are making progress converting the remaining ones but it may be better to include this logic in the API itself.

This touches on some of the same problems discussed in #281 (still unresolved).

Handling `log_size` this way is relatively trivial - just requires a branch like this inside `add_copy_spec_limit()`:

``` python
        if not sizelimit:
            sizelimit = self.get_option("log_size")
```

(to be honest this is so simple we should have done it when the global log_size was added!)

Handling `all_logs` is harder: currently `add_copy_spec_limit()` does not accept a list so we can't e.g. say if `all_logs=True` collect everything otherwise only collect the first. This inconsistency between `add_copy_spec()` and `add_copy_spec_limit()` is a bit ugly and has caused some minor bugs in the past.

Ideally I'd like to have a single method for adding files that handles all of these cases and requires as little code on the part of plugin authors as possible. An alternative might be to have one method for log data (that implements `all_logs` and `log_size`) and another (for configuration) that does not.

The more plugins we have the more changes like this require plugin updates so I think it's worth thinking about this for a while before making changes.

**Comment by TurboTurtle** [comment]
Between #1120, #1325, and #1360 I believe this is handled, so closing.
