### ISSUE TITLE
[redis] Add new plugin

### ISSUE THREAD

**Issue by lyarwood** [sosreport/sos#667]
Redis is an open source, in-memory data structure store, used as a database, cache and message broker.

- collect `/var/log/redis/redis.log`
- collect useful command output (TBD) http://redis.io/commands

**Comment by pmoravec** [comment]
Hi @lyarwood , could you please provide list of useful command outputs to be collected?

**Comment by lyarwood** [comment]
@pmoravec sorry missed this request, `info` [1] should be enough as this dumps everything in one. 

[1] http://redis.io/commands/info

**Comment by Akasurde** [comment]
PR merged, can close this issue.
