### ISSUE TITLE
tests/test_exe.py fails in a python3 only environment

### ISSUE THREAD

**Issue by karibou** [sosreport/sos#690]
When running the test in a python3 only environment, the shebang : 
# !/usr/bin/python

cannot be resolved.

**Comment by battlemidget** [comment]
How'd you get a python3 only environment? And why wasn't /usr/bin/python symlinked to python3.x or if python3 is the only installed runtime why wasn't it renamed to just python?

**Comment by karibou** [comment]
PEP394[1] indicates that /usr/bin/python should refers to python2.  After checking with some of the python mainainers for Debian/Ubuntu, there is no current plans for that to be changed.

"for the time being, all distributions should ensure that python refers to the same target as python2 ."

The current plans for Ubuntu 16.04 are for a pyhon3 only environment on the image.  And the current package on Debian/Sid fails to build from source partly because of that (aside from other packaging issues).

My current plans is to skip this specific test or patch the test to work correctly on python3.

[1] https://www.python.org/dev/peps/pep-0394/

**Comment by battlemidget** [comment]
I guess im a little confused since we use travis-ci and it tests against python 2.7-3.5 and no issues there. Is this just local testing that youre seeing this?

**Comment by bmr-cymru** [comment]
Presumably the travis-ci sandboxes still *have* python2 even when you are only testing python3 - in that case a py3 test there will not fail (since `/usr/bin/python` resolves to the py2 package).

On a real py3 only install it /will/ fail since there is no `/usr/bin/python` (only `/usr/bin/python3`).

**Comment by bmr-cymru** [comment]
OK, here's a simple solution: let's just get rid of `test_exe.py` completely; it's utter garbage. A simple call to '/bin/echo' is perfectly adequate for the tests that use it.

That way we don't have any shebangs in test code and no dependencies on a particular version of the python runtime.

**Comment by karibou** [comment]
Fine with me. Right now, I've patched the tests/utilities_tests.py with : 

@unittest.skipIf(six.PY3, "Skipped Python2 only test")

**Comment by BryanQuigley** [comment]
This appears to be still be a valid issue - was fixed by changing to a shell script and at some point changed back.

I have no idea how these tests are remotely useful though - just making sure python works?

**Comment by BryanQuigley** [comment]
======================================================================
FAIL: test_output (utilities_tests.ExecutableTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bryan/git/sos/tests/utilities_tests.py", line 62, in test_output
    self.assertEquals(result['status'], 0)
AssertionError: 127 != 0

======================================================================
FAIL: test_shell_out (utilities_tests.ExecutableTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bryan/git/sos/tests/utilities_tests.py", line 80, in test_shell_out
    self.assertEquals("executed\n", shell_out(path))
AssertionError: 'executed\n' != ''
- executed

----------------------------------------------------------------------
Ran 86 tests in 0.794s

FAILED (failures=2)

**Comment by bmr-cymru** [comment]
Did we ever actually change this? The "python" shebang line in `tests/test_exe.py` goes back to 2013:

```
3a2bffa7e (Adam Stokes      2013-04-11 21:55:27 -0400 1) #!/usr/bin/python
8df3d1501 (Sandro Bonazzola 2017-03-29 09:37:05 +0200 2) print("executed")
747189c07 (Bryn M. Reeves   2014-03-26 13:07:13 +0000 3) 
198929b84 (Kamalesh Babulal 2015-07-06 13:28:25 +0100 4) # vim: set et ts=4 sw=4 :
```

**Comment by slashdd** [comment]
There was a proposition that got closed but doesn't seemed to get merged:
https://github.com/sosreport/sos/pull/759

but I'm not convince using shell script is the right way to fix that.

**Comment by bmr-cymru** [comment]
I have a few other things to get done for 3.9, and I'd like to stick to the original plan to release today but I'll have another look at this once I've got everything else done and see if there is something we can do in time.

**Comment by bmr-cymru** [comment]
It's used for a handful of things, none of which really seem to justify a script...

**Comment by TurboTurtle** [comment]
Closing this per 2053810, which removes this file entirely.
