### ISSUE TITLE
sosreport grab /opt directory

### ISSUE THREAD

**Issue by kaushalshriyan** [sosreport/sos#695]
Hi,

I am using sosreport on RHEL 6.6, is there a way to include /opt directory using sosreport where my application is running. I read the man sosreport and did not see any option to do it. Any help will be really appreciable.

Please advise.

Regards,

Kaushal

**Comment by bmr-cymru** [comment]
This isn't really in scope for sos as a whole - if there are particular parts of `/opt` that you think should be collected by specific plugins please open separate issues for those.
