### ISSUE TITLE
[multipath] output of "multipathd show config"?

### ISSUE THREAD

**Issue by lathan** [sosreport/sos#697]
Hello!

In multipath, is it possible to include the output of `multipathd show config`? This output shows the full currently loaded configuration instead of just the user defined options and the defaults.

Cheers
George

**Comment by bmr-cymru** [comment]
Yep, makes sense.

**Comment by bmr-cymru** [comment]
Please test if you can - you should be able to just drop the current [multipath.py](https://github.com/sosreport/sos/blob/master/sos/plugins/multipath.py) from master into an existing sos-3.x installation (backup your original multipath.py if you wish).

**Comment by lathan** [comment]
Tested on RHEL7.2, looks ok. I'm not sure if there would anything different here in RHEL5/6.

**Comment by bmr-cymru** [comment]
Thanks :+1: 

I tested myself on RHEL6 (to make sure that 6's multipathd supports "multipathd <verb> <object>" rather than the old "-k '<verb> <object>\n'" style). For RHEL5 it's not a concern since it will not be updated to a new upstream version as it is already in production3 lifecycle phase.

**Comment by lathan** [comment]
kewl, thnx @bmr-cymru
