### ISSUE TITLE
[apache] factor out common code in RedHatApache

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#704]
Adding support for JBoss web server introduced code duplication in the `RedHatApache` class, e.g.:

``` python
        self.add_copy_spec([
            "/etc/httpd/conf/httpd.conf",
            "/etc/httpd/conf.d/*.conf",
            "/etc/httpd/conf.modules.d/*.conf",
            # JBoss Enterprise Web Server 2.x
            "/etc/httpd22/conf/httpd.conf",
            "/etc/httpd22/conf.d/*.conf",
            # Red Hat JBoss Web Server 3.x
            "/etc/httpd24/conf/httpd.conf",
            "/etc/httpd24/conf.d/*.conf",
            "/etc/httpd24/conf.modules.d/*.conf",
        ])
```

Factor this out to remove the repetition and instead loop over the three possible top-level directories in `/etc`.

**Comment by bmr-cymru** [comment]
btw: attempting to collect e.g. `conf.modules.d/*.conf` for a release (2.2) that does not use it is explicitly not an error in sos - this helps to keep the code simple since there are no harmful side-effects to trying to collect something that is not there.

**Comment by Amitgb14** [comment]
@bmr-cymru, I write some lines to reduce duplication, Please let me know it's correct.

```
paths     = ['/etc/httpd{}/conf/httpd.conf', '/etc/httpd{}/conf.d/*.conf', 
                  '/etc/httpd{}/conf.modules.d/*.conf']
versions  = ['', '22', '24']
conf_path = [path.format(ver) for ver in versions for path in paths]
self.add_copy_spec(conf_path)

example;

for path in conf_path:
    print path

output:
/etc/httpd/conf/httpd.conf
/etc/httpd/conf.d/*.conf
/etc/httpd/conf.modules.d/*.conf
/etc/httpd22/conf/httpd.conf
/etc/httpd22/conf.d/*.conf
/etc/httpd22/conf.modules.d/*.conf
/etc/httpd24/conf/httpd.conf
/etc/httpd24/conf.d/*.conf
/etc/httpd24/conf.modules.d/*.conf
```

**Comment by bmr-cymru** [comment]
When you're making a change like this the important thing is to step back and ask "Is this simpler?", "Is this more readable?", "is there less string duplication?"

Although there is duplication in the original I think the answer to the questions for the above snippet is "no".

We have the option to use globs here, to build strings ourselves etc. but the aim of this is not to be cute or use neat python tricks - it is just to make the code more readable and easier to understand/modify.

What I had in mind was more along the lines of:

```python
etc_dirs = [ "/etc/httpd" + v for v in "", "22", "24"]
for dir in etc_dirs:
    self.add_copy_spec([
        "%s/conf/http.conf",
        "%s/conf.d/*conf",
        "%s/conf.modules.d/*.conf"
    ])
```

It's not perfect but this eliminates the repeated `/etc/httpd` as well as the HTTPD version and configuration structure.

**Comment by Amitgb14** [comment]
It's looking good. I don't know exact but I think `add_copy_spec()` function will call three times.

**Comment by bmr-cymru** [comment]
> but I think add_copy_spec() function will call three times.

And? :-)

That's not a problem - lots of plugins do it either for readability or because (as here) they are driving it from a loop.

In virtually all actual instances only one of the three invocations will actually add any files to the copy spec list for the plugin since the other two possible paths will not exist.

**Comment by Amitgb14** [comment]
:+1:
