### ISSUE TITLE
Is there single file viersion for this soft?

### ISSUE THREAD

**Issue by plutoid** [sosreport/sos#706]
Hi the Authors,

Since our OS haven't installed it as default soft, so I have this question, is there single file/portable  version of this soft? thanks.

BRs,
Hua

**Comment by plutoid** [comment]
Kindly ignore, use the clone version is portable, it's enough.

**Comment by bmr-cymru** [comment]
You can run sos from a git clone but you may wish to see whether your distribution includes a packaged version; this will often have been adapted to better suit other packages in that distribution and may include support and updates that reduce the burden on the administrator to fetch updates from the upstream repository.
