### ISSUE TITLE
How old python version which has no six module run this soft?

### ISSUE THREAD

**Issue by plutoid** [sosreport/sos#707]
Hi the Authors,

We SUSE OS has old python version which has no six module, since we only need run sos soft once time when needed, is there simple way for this case?

~/sos> sudo ./sosreport -a
Traceback (most recent call last):
  File "./sosreport", line 20, in <module>
    from sos.sosreport import main
  File "/home/c5197505/sos/sos/sosreport.py", line 30, in <module>
    from sos.plugins import import_plugin
  File "/home/c5197505/sos/sos/plugins/**init**.py", line 21, in <module>
    from sos.utilities import (sos_get_command_output, import_module, grep,
  File "/home/c5197505/sos/sos/utilities.py", line 30, in <module>
    import six
ImportError: No module named six

BRs,
Hua

**Comment by plutoid** [comment]
And I have six.py module in ./sos directory, no warning info and no  /tmp/sosreport-* gz xz files created, so curious what's happened.

/tmp/sos # ./sosreport -vvv

sosreport (version 3.2.0a1)

no valid plugins were enabled


BRs,
Hua

**Comment by plutoid** [comment]
Should I add sos/policies/suse.py file?

**Comment by bmr-cymru** [comment]
You can remove the dependency on six but only by making code changes; I have done this for some older distributions - for example [RHEL6](https://gist.github.com/bmr-cymru/51e6c95d8ce6e69ee5eb). The patch should apply to sos-3.2 and removes all six references from the tree (at the same time it restricts it to only running on a python2 runtime).

If you are running on SuSE then you will need to either create a policy for the distribution or create `/etc/redhat-release` to trick the Red Hat policy into loading.

If you need an example there is a basic policy for SuSE-like distributions on the branch [bmr-suse-policy](/sosreport/sos/tree/bmr-suse-policy). The policy was added in commit 41f3c62d6cde2df904676cb5ee7d6ae2c39b9d28.

**Comment by bmr-cymru** [comment]
Note that although the "de-six" patch in the gist in the previous comment has been tested and is known to work that it is not currently supported by the sos upstream project (downstream distributions may differ).

**Comment by TurboTurtle** [comment]
Closing per bmr-cymru's comments above and there seems to be no further interest in a six-less sos.
