### ISSUE TITLE
[RFE] Add a sysdeps target to the Makefile for installing package deps for developers

### ISSUE THREAD

**Issue by Amitgb14** [sosreport/sos#729]
requirements.txt file is useful to install all the dependencies.

**Comment by battlemidget** [comment]
Can you explain why this would be a good idea? You have to remember this project is quite mature and deviating from current developer practices is not something I would be in favor for unless absolutely necessary.

**Comment by Amitgb14** [comment]
It is useful for new contributor(developer) and user, before start use 'sosreport' developer or user first install required dependency and install 'sosreport' without any failed.

**Comment by battlemidget** [comment]
How is this better than what we have in our README under **Manual Installation**?

**Comment by Amitgb14** [comment]
README is good, requirements.txt make easy to know which packages is required [https://github.com/sosreport/sos/blob/master/setup.py#L70](https://github.com/sosreport/sos/blob/master/setup.py#L70)

**Comment by battlemidget** [comment]
Sorry, I don't agree with adding a requirements.txt file for a single dependency, however, I'll let @bmr-cymru make that call.

**Comment by bmr-cymru** [comment]
The `requirements.txt` (stupid name but there you go..) file is actually a metadata file used by python pip and `setup.py`.

Given that sos is normally packaged by active maintainers I don't think that this buys us a great deal however it also costs nothing; so long as we can put something reasonably sane in there I don't have any objection to this (by reasonably sane I mean something that will work correctly for users using pip distribution on all supported distributions - for historical reasons pip and distribution package names often differ however I believe pip correctly supports this case).

**Comment by bmr-cymru** [comment]
> README is good, requirements.txt make easy to know which packages is required https://github.com/sosreport/sos/blob/master/setup.py#L70

This doesn't really answer Adam's question. The point is that listing the deps in `requirements.txt` supports automatic dependency resolution for users using the pip packaging system (analogous to a `Requires:` declaration in an RPM spec file).

**Comment by battlemidget** [comment]
Another issue I think people will run into is if the pip install -rrequirements.txt and attempt to install one of the python xml bindings (libxml2 is included in the rpm.spec) then those without those development packages will have to figure that out before the bindings will compile correctly through pip. I guess if we don't use XML for reporting any longer (tbh I haven't looked at that reporting code in ages) then we could drop libxml (lxml python binding IIRC) and just have `six` in the requirements file for py2/3 development work.

**Comment by battlemidget** [comment]
Another thing we could do is add a new target to the Makefile like `make sysdeps` and it'll install required *-dev packages and still bypass the use of pip installing libraries in /usr/local/lib or if using something like pyenv (~/.pyenv/versions/x.y.x/dist-packages) etc

**Comment by bmr-cymru** [comment]
Sadly we do still use the libxml2 bindings.

**Comment by battlemidget** [comment]
Ah, so the requirements.txt file would need to also include `lxml` as a dep and whatever else is not supplied by the python standard library. I'm thinking a `make sysdeps` would be good here to provide the path of least resistance for getting a developers machine in a state to work on the upstream code

**Comment by bmr-cymru** [comment]
:+1:

**Comment by bmr-cymru** [comment]
Actually, I'm not sure I follow? What would the Makefile target do (and how would it DTRT on different distros?)

I don't have an objection to adding a `requirements.txt` if it solves a real problem for people working with pip packaging so long as we're not favouring any one group - i.e. if we add this we need to be able to do it in a way that will work for a user on any supported distribution. Since seems to have its own notion of package names (`lxml` vs. `libxml2` etc.) I don't think this should be a major headache?

**Comment by battlemidget** [comment]
I guess my only thing is if you do a pip install -rrequirements.txt and it contains lxml it still needs the libxml2 headings for it to compile the bindings so you aren't really saving yourself any keystrokes by including the requirements.txt file

**Comment by Amitgb14** [comment]
if lxml required libxml2 then put it before the lxml, installing packages in requirements.txt start from top to bottom.

**Comment by bmr-cymru** [comment]
Ahh, gotcha - I didn't realize a pip install of libxml2 would actually need to compile against the C headers (I thought pip allowed binary distribution).

**Comment by Amitgb14** [comment]
I did small changes, when i install sosreport in virtualenv using ```python setup.py install``` command, it's install required packages like six, earlier is not installed six package. I past patch here.

```
diff --git a/setup.py b/setup.py
index d194d3d..7ba717a 100644
--- a/setup.py
+++ b/setup.py
@@ -1,6 +1,6 @@
 #!/usr/bin/env python
 
-from distutils.core import setup
+from setuptools import setup
 from distutils.command.build import build
 from distutils.command.install_data import install_data
 from distutils.dep_util import newer
@@ -67,7 +67,7 @@ setup(name='sosreport',
         ],
       packages=['sos', 'sos.plugins', 'sos.policies'],
       cmdclass={'build': BuildData, 'install_data': InstallData},
-      requires=['six'],
+      install_requires=['six'],
      )
 
 ```

**Comment by psachin** [comment]
An idea of 'requirements' came to my mind as the contributors guidelines asks to run tests before contributing. My emphasis is mainly on 'nose', 'coverage' dependency, followed by  'sphinx'. For new contributors it is easy to run 'make test'(this should be added in wiki) and ensure that all the tests pass before sending a patch? Wouldn't it be great to make 'sos' a proper Python package? Just a thought.

**Comment by psachin** [comment]
I personally like to have an virtual-environment for each Python project I work on. This also ensures that I have no dependency conflicts with system packages.

**Comment by bmr-cymru** [comment]
> My emphasis is mainly on 'nose', 'coverage' dependency, followed by 'sphinx'. 

The ones that matter for code acceptance are `pep8` and clean `nose` runs for both python 2 and 3 (this is what Travis tests for sos branches).

> Wouldn't it be great to make 'sos' a proper Python package? Just a thought.

Sure but it isn't really a high priority for us since `sos` is packaged by the distributions that we support - the feedback we receive from end users is that this is preferred since in many production environments policy forbids use of things like pip for package installation.

That does not mean that we are opposed to it: just that it is relatively low priority for us. I'm more than happy to review patches and I don't have any objection to this but I don't have spare time to invest in it at the moment - if you can put together a branch with the required changes I'll take a look.

**Comment by psachin** [comment]
Thanx,

Please have a look at #779 
Should not take more than 2 minutes

**Comment by TurboTurtle** [comment]
sos no longer uses `make`, so I am closing this out.

Any remaining issues surrounding the use of setuptools for builds should be brought up in a new issue.
