### ISSUE TITLE
[sosreport] fix capitalisation of --no-report help message

### ISSUE THREAD

**Issue by Amitgb14** [sosreport/sos#730]
When run sosreport --help command, help message print in lower case letter(only --no-report option help message is capitalize).

**Comment by bmr-cymru** [comment]
Could you please try to include a bit more context with your reports? By not including, for example, tool output, when reporting a tool output issue you are saying that your time is more important than everyone else who reads the issue.

If it's not worth the time to report properly it is probably not worth the time to report at all.

And the help output _should_ be in lower-case; they are not sentences so they do not follow the initial capital or closing period rules of grammar - in this case it is the `--no-report` option that has a bug. Compare this to standard and widely-used python packages such as `python-pep8` for example:

```
$ pep8 --help
Usage: pep8 [options] input ...

Options:
  --version            show program's version number and exit
  -h, --help           show this help message and exit
  -v, --verbose        print status messages, or debug with -vv
  -q, --quiet          report only file names, or nothing with -qq
[...]
```
