### ISSUE TITLE
[sosreport] replace deprecated optparse with argparse

### ISSUE THREAD

**Issue by bhavikbhavsar** [sosreport/sos#738]
Link [https://docs.python.org/2/library/optparse.html](https://docs.python.org/2/library/optparse.html)

**Comment by bmr-cymru** [comment]
Yes: it's an almost trivial conversion iirc (there might be a handful of fixups needed) - patches welcome.

**Comment by bmr-cymru** [comment]
One caveat (this might be the reason that we didn't do this already - I know it's been discussed but I don't recall the details right now) may be availability on older python runtimes. We currently support 2.7, 3.4 and 3.5 from the same upstream tree.

**Comment by bmr-cymru** [comment]
Argparse seems to have appeared in 2.7 - as we no longer support anything earlier than this upstream I don't see a problem with converting at this time.
