### ISSUE TITLE
[networking] add `/proc/net/cdp` to forbidden paths

### ISSUE THREAD

**Issue by sbradley7777** [sosreport/sos#740]
Add /proc/net/cdp to forbidden paths forbidden paths in order to prevent collecting possibly gigantic files that can be present in this directory.

**Comment by bmr-cymru** [comment]
Also needs to blacklist `/sys/net/cdp` iirc.

**Comment by bmr-cymru** [comment]
I've tested with net namespaces now and the 'double slash' workaround we used in sos-2.2 is no longer necessary - the trailing `/` is still required (to force `_do_copy_path()` to treat the path as a directory) but since we now build the path for comparison properly the `//` trick isn't needed:

```
With add_copy_spec("/proc/net"):
# sosreport -vv --batch --debug --build -o networking
[...]
2016-02-05 17:47:08,589 DEBUG: [plugin:networking] link 'self/net' is a directory, skipping...
[...]
```

```
With add_copy_spec("/proc/net/") and add_forbidden_path("/proc/net/netfilter"):
# sosreport -vv --batch --debug --build -o networking
[...]
2016-02-05 17:48:48,973 DEBUG: [plugin:networking] skipping forbidden path '/proc/net/netfilter'
[...]
```
