### ISSUE TITLE
sosreport will fail to compress archive is non-utf8 characters are present in rhn username

### ISSUE THREAD

**Issue by sbradley7777** [sosreport/sos#742]
If the username in /etc/sysconfig/rhn/systemid contains non-utf8 characters then the compressed archived will not be created and will not print any errors.

```
# cat /etc/sysconfig/rhn/systemid | grep -C 2 fake
<member>
<name>username</name>
<value><string>faked/testing_user-really:!§@#$%^&gt;._ha_*()=+'"`;/\?~|}{][_ha_ůúěščřžýáíéÁŤŽŠšď_ha_ ha</string></value>
</member>
<member>
```

Run sosreport:
```
# sosreport --batch -o general
sosreport (version 3.2)
[.....]
No changes will be made to system configuration.


 Setting up archive ...
 Setting up plugins ...
 Running plugins. Please wait ...

  Running 1/1: general...        

Creating compressed archive...
```

sosreport fails with no error:
```
# ls -l /tmp/sosreport*fake*
-rw-------. 1 root root 317440 Jun 18 05:07 /tmp/sosreport-fakedtestinguser-really.hahahaha-20150618050730.tar
```
There is no `.xz` file created.

**Comment by sbradley7777** [comment]
The fix is to make sure that the characters are encoded to utf-8 that make up the name in file: `/usr/lib/python2.6/site-packages/sos/policies/redhat.py`.

```
def rhn_username(self):
        try:
            # cfg = config.initUp2dateConfig()

            return rpclib.xmlrpclib.loads(
                up2dateAuth.getSystemId())[0][0]['username'].encode('utf-8', 'ignore')
        except:
            # ignore any exception and return an empty username
            return ""
```

**Comment by bmr-cymru** [comment]
First question is why is our name sanitisation not dealing with this?

**Comment by bmr-cymru** [comment]
What do you mean by non-utf8 characters? What is the character in the above `<string>` that actually causes the problem?

**Comment by battlemidget** [comment]
This got merged without discussion?

**Comment by sbradley7777** [comment]
Q1) First question is why is our name sanitisation not dealing with this?

A1) I think that is better fit for issue with whatever fix we decide. To have `RHELPolicy -> sanitize_report_name()` to handle name issue. 

Q2) What do you mean by non-utf8 characters? What is the character in the above <string> that actually causes the problem?

A2) I believe it is the null byte character. 

Here is output when i print shlex.split() output which is what is throwing an exception to be thrown:
Creating compressed archive...
['x\x00\x00\x00z\x00\x00\x00', '\x00\x00\x00-\x00\x00\x001\x00\x00\x00', '\x00\x00\x00/\x00\x00\x00t\x00\x00\x00m\x00\x00\x00p\x00\x00\x00/\x00\x00\x00s\x00\x00\x00o\x00\x00\x00s\x00\x00\x00.\x00\x00\x00o\x00\x00\x00r\x00\x00\x001\x00\x00\x00Y\x00\x00\x009\x00\x00\x00z\x00\x00\x00/\x00\x00\x00s\x00\x00\x00o\x00\x00\x00s\x00\x00\x00r\x00\x00\x00e\x00\x00\x00p\x00\x00\x00o\x00\x00\x00r\x00\x00\x00t\x00\x00\x00-\x00\x00\x00f\x00\x00\x00a\x00\x00\x00k\x00\x00\x00e\x00\x00\x00d\x00\x00\x00t\x00\x00\x00e\x00\x00\x00s\x00\x00\x00t\x00\x00\x00i\x00\x00\x00n\x00\x00\x00g\x00\x00\x00u\x00\x00\x00s\x00\x00\x00e\x00\x00\x00r\x00\x00\x00-\x00\x00\x00r\x00\x00\x00e\x00\x00\x00a\x00\x00\x00l\x00\x00\x00l\x00\x00\x00y\x00\x00\x00.\x00\x00\x00h\x00\x00\x00a\x00\x00\x00h\x00\x00\x00a\x00\x00\x00h\x00\x00\x00a\x00\x00\x00h\x00\x00\x00a\x00\x00\x00-\x00\x00\x002\x00\x00\x000\x00\x00\x001\x00\x00\x006\x00\x00\x000\x00\x00\x001\x00\x00\x002\x00\x00\x005\x00\x00\x001\x00\x00\x001\x00\x00\x005\x00\x00\x006\x00\x00\x000\x00\x00\x002\x00\x00\x00.\x00\x00\x00t\x00\x00\x00a\x00\x00\x00r\x00\x00\x00']
execv() argument 1 must be encoded string without NULL bytes, not str
['b\x00\x00\x00z\x00\x00\x00i\x00\x00\x00p\x00\x00\x002\x00\x00\x00', '\x00\x00\x00-\x00\x00\x001\x00\x00\x00', '\x00\x00\x00/\x00\x00\x00t\x00\x00\x00m\x00\x00\x00p\x00\x00\x00/\x00\x00\x00s\x00\x00\x00o\x00\x00\x00s\x00\x00\x00.\x00\x00\x00o\x00\x00\x00r\x00\x00\x001\x00\x00\x00Y\x00\x00\x009\x00\x00\x00z\x00\x00\x00/\x00\x00\x00s\x00\x00\x00o\x00\x00\x00s\x00\x00\x00r\x00\x00\x00e\x00\x00\x00p\x00\x00\x00o\x00\x00\x00r\x00\x00\x00t\x00\x00\x00-\x00\x00\x00f\x00\x00\x00a\x00\x00\x00k\x00\x00\x00e\x00\x00\x00d\x00\x00\x00t\x00\x00\x00e\x00\x00\x00s\x00\x00\x00t\x00\x00\x00i\x00\x00\x00n\x00\x00\x00g\x00\x00\x00u\x00\x00\x00s\x00\x00\x00e\x00\x00\x00r\x00\x00\x00-\x00\x00\x00r\x00\x00\x00e\x00\x00\x00a\x00\x00\x00l\x00\x00\x00l\x00\x00\x00y\x00\x00\x00.\x00\x00\x00h\x00\x00\x00a\x00\x00\x00h\x00\x00\x00a\x00\x00\x00h\x00\x00\x00a\x00\x00\x00h\x00\x00\x00a\x00\x00\x00-\x00\x00\x002\x00\x00\x000\x00\x00\x001\x00\x00\x006\x00\x00\x000\x00\x00\x001\x00\x00\x002\x00\x00\x005\x00\x00\x001\x00\x00\x001\x00\x00\x005\x00\x00\x006\x00\x00\x000\x00\x00\x002\x00\x00\x00.\x00\x00\x00t\x00\x00\x00a\x00\x00\x00r\x00\x00\x00']
execv() argument 1 must be encoded string without NULL bytes, not str
['g\x00\x00\x00z\x00\x00\x00i\x00\x00\x00p\x00\x00\x00', '\x00\x00\x00/\x00\x00\x00t\x00\x00\x00m\x00\x00\x00p\x00\x00\x00/\x00\x00\x00s\x00\x00\x00o\x00\x00\x00s\x00\x00\x00.\x00\x00\x00o\x00\x00\x00r\x00\x00\x001\x00\x00\x00Y\x00\x00\x009\x00\x00\x00z\x00\x00\x00/\x00\x00\x00s\x00\x00\x00o\x00\x00\x00s\x00\x00\x00r\x00\x00\x00e\x00\x00\x00p\x00\x00\x00o\x00\x00\x00r\x00\x00\x00t\x00\x00\x00-\x00\x00\x00f\x00\x00\x00a\x00\x00\x00k\x00\x00\x00e\x00\x00\x00d\x00\x00\x00t\x00\x00\x00e\x00\x00\x00s\x00\x00\x00t\x00\x00\x00i\x00\x00\x00n\x00\x00\x00g\x00\x00\x00u\x00\x00\x00s\x00\x00\x00e\x00\x00\x00r\x00\x00\x00-\x00\x00\x00r\x00\x00\x00e\x00\x00\x00a\x00\x00\x00l\x00\x00\x00l\x00\x00\x00y\x00\x00\x00.\x00\x00\x00h\x00\x00\x00a\x00\x00\x00h\x00\x00\x00a\x00\x00\x00h\x00\x00\x00a\x00\x00\x00h\x00\x00\x00a\x00\x00\x00-\x00\x00\x002\x00\x00\x000\x00\x00\x001\x00\x00\x006\x00\x00\x000\x00\x00\x001\x00\x00\x002\x00\x00\x005\x00\x00\x001\x00\x00\x001\x00\x00\x005\x00\x00\x006\x00\x00\x000\x00\x00\x002\x00\x00\x00.\x00\x00\x00t\x00\x00\x00a\x00\x00\x00r\x00\x00\x00']
execv() argument 1 must be encoded string without NULL bytes, not str

**Comment by sbradley7777** [comment]
Did some more troubleshooting on the issue. I think I understand issue better. 

Python expects ascii, the xml file has unicode in it. Python `re.sub()` leaves the unicode or just mangles it(not sure which) or skips characters but leaves them in string, then `shlex` processes the string that still contains unicode data. The `shlex.split()` data i believe is mangled because of the unicode. When the archive process is created it is passed the mangled argument and pukes. Information on regex: https://pypi.python.org/pypi/regex

Did some testing and found out that Python 2.6(RHEL 6) does not handle unicode correctly whereas Python 2.7 (RHEL 7) does. 

The real question I believe is:
 * Do we want to leave patch as is where only this one file's data has encoding set in function `rhn_username()` or should we sanitize this in `sanitize_report_name()` for `RHEL Policy` or `LinuxPolicy`?

**Comment by bmr-cymru** [comment]
Thanks Shane. I'll take a look at this today - I am not sure we've gotten to the bottom of it and it also reminds me that although we have the name validation it's currently happening in policy classes (which may not be the most appropriate place for it).

**Comment by bmr-cymru** [comment]
Regarding RHEL6 vs. 7, are you sure that it's the case that RHEL7 handles this correctly rather than it just never hitting it at all?

I don't expect this specific problem (relating to characters stored in `/etc/sysconfig/rhn/systemid`) to happen on RHEL7 but that's simply because that file does not normally exist (it is never used with `subscription-manager` which replaces the legacy RHN components in RHEL7).

**Comment by bmr-cymru** [comment]
Maybe we should just hard-code the string "johndoe" as the username and be done with it... ;-)

**Comment by bmr-cymru** [comment]
The answer to why this isn't handled by sanitisation is that we don't even make it that far. If a file with the contents @sbradley7777 describes are present we _don't even ask the user their name or case id_:

```
[NORMAL]
# sosreport 

sosreport (version 3.2)

[...]

Press ENTER to continue, or CTRL-C to quit.

Please enter your first initial and last name [rhn-support-bmr]: 
Please enter the case id that you are generating this report for: 
[...]

Creating compressed archive...

Your sosreport has been generated and saved in:
  /tmp/sosreport-rhn-support-bmr-20160127190639.tar.xz

The checksum is: 4e31a3d30fb7a815628e089cb9b48567

Please send this file to your support representative.
```

```
[BROKEN]
# sosreport 

sosreport (version 3.2)

This command will collect diagnostic and configuration information from
this Red Hat Enterprise Linux system and installed applications.

An archive containing the collected information will be generated in
/tmp/sos.1nCz0p and may be provided to a Red Hat support representative.

Any information provided to Red Hat will be treated in accordance with
the published support policies at:

  https://access.redhat.com/support/

The generated archive may contain data considered sensitive and its
content should be reviewed by the originating organization before being
passed to any third party.

No changes will be made to system configuration.

Press ENTER to continue, or CTRL-C to quit.
[...]
Creating compressed archive...
#
```

**Comment by bmr-cymru** [comment]
```python
Traceback (most recent call last):
  File "/usr/sbin/sosreport", line 25, in <module>
    main(sys.argv[1:])
  File "/usr/lib/python2.6/site-packages/sos/sosreport.py", line 1453, in main
    sos.execute()
TypeError: execv() argument 1 must be encoded string without NULL bytes, not str

> /usr/lib/python2.6/site-packages/sos/archive.py(408)_compress()
-> raise last_error
```

**Comment by bmr-cymru** [comment]
There are numerous problems here:

* AWOL input validation (exceptions during policy init/prompting?)
* hand-rolled shellout from archive code
* Possibly some actual unicode mishandling

**Comment by bmr-cymru** [comment]
This is the cleanest fix I have so far - just gets rid of the stupid hand-rolled `Popen` crap from `archive.py` and replace it with a call to `sos_get_command_output()` (which has already been debugged for this case..):

```diff
diff --git a/sos/archive.py b/sos/archive.py
index 0b96851..4251fe0 100644
--- a/sos/archive.py
+++ b/sos/archive.py
@@ -28,6 +28,8 @@ import sys
 # required for compression callout (FIXME: move to policy?)
 from subprocess import Popen, PIPE
 
+from utilities import sos_get_command_output
+
 try:
     import selinux
 except ImportError:
@@ -391,7 +393,7 @@ class TarFileArchive(FileCacheArchive):
         if self.method in methods:
             methods = [self.method]
 
-        last_error = Exception("compression failed for an unknown reason")
+        last_error = Exception("compression failed")
 
         for cmd in methods:
             suffix = "." + cmd.replace('ip', '')
@@ -399,19 +401,14 @@ class TarFileArchive(FileCacheArchive):
             if cmd != "gzip":
                 cmd = "%s -1" % cmd
             try:
-                command = shlex.split("%s %s" % (cmd, self.name()))
-                p = Popen(command,
-                          stdout=PIPE,
-                          stderr=PIPE,
-                          bufsize=-1,
-                          close_fds=True)
-                stdout, stderr = p.communicate()
-                if stdout:
-                    self.log_info(stdout.decode('utf-8', 'ignore'))
-                if stderr:
-                    self.log_error(stderr.decode('utf-8', 'ignore'))
+                r = sos_get_command_output("%s %s" % (cmd, self.name()))
+
+                if r['status']:
+                    self.log_info(r['output'].decode('utf-8', 'ignore'))
+
                 self._suffix += suffix
                 return self.name()
+
             except Exception as e:
                 last_error = e
         raise last_error
```

**Comment by bmr-cymru** [comment]
The problem seems to be to do with `shlex.split()` being handed a `u'string'` that contains non Latin-1 characters - this results in some weird conversion where each character value is padded with several NULLs:

```
['x\x00\x00\x00z\x00\x00\x00', '\x00\x00\x00-\x00\x00\x001\x00\x00\x00', '\x00\x00\x00/\x00\x00\x00t\x00\x00\x00m\x00...

Is:

['xz', '/tmp...
```
