### ISSUE TITLE
[monit_plugin]  Correct the monit plugin profile list. 

### ISSUE THREAD

**Issue by Amitgb14** [sosreport/sos#747]
When user put this command ```./sosreport --list-profiles```, 

```output
  s               
 sap             
 security        auditd, keyutils, openssl, pam, selinux, smartcard, 
                 ssh, sssd
 services        chrony, nis, postgresql, puppet, samba, ssh, sssd, 
                 systemd, sysvipc
 storage         block, ceph, devicemapper, dmraid, fcoe, filesys, 
                 gluster, iscsi, keyutils, logs, lvm2, md, megacli, 
                 multipath, nfs, scsi, xfs
 sysmgmt         general, ldap
 system          abrt, anaconda, anacron, auditd, boot, cgroups, chrony, 
                 cron, dbus, devices, general, hardware, i18n, kdump, 
                 kernel, keyutils, krb5, kvm, last, ldap, libraries, 
                 libvirt, logrotate, logs, lsbrelease, megacli, memory, 
                 multipath, networking, numa, openhpi, pam, pci, ppp, 
                 process, processor, psacct, python, rpm, selinux, 
                 services, system, systemd, sysvipc, udev, virsh
 t               
 virt            ceph, docker, gluster, kvm, libvirt, openshift, virsh, 
                 xen
 webserver       apache, java
 y  
```
s, t, y blank character comes form monit plugin profile.

It was ```profiles = ('system')``` correct to ```profiles = ('system',)```

**Comment by bmr-cymru** [comment]
You don't need `[..._plugin]` in a commit that changes one plugin file - just the name. This is important since for some of the longer plugin names (or when there is a list of plugins) the tag ends up consuming so many characters there are not enough left to properly describe the commit.

**Comment by Amitgb14** [comment]
done it.

**Comment by bmr-cymru** [comment]
Thanks! :+1:

**Comment by bmr-cymru** [comment]
(nice work here too btw!)

**Comment by Amitgb14** [comment]
thanks

**Comment by bmr-cymru** [comment]
It looks like you are committing these on the master branch of your repo? It's easier if you use one branch per-issue - I'm not able to take a clean starting point for this patch from the parent commit:

```
$ git checkout -b bmr-tmp 6d9883a
fatal: Cannot update paths and switch to branch 'bmr-tmp' at the same time.
Did you intend to checkout '6d9883a' which can not be resolved as commit?
```

Commit 6d9883a only exists in your repo but it's a change for an unrelated problem:

https://github.com/Amitgb14/sos/commit/6d9883ac1150d1c3261ae9bd4aba0f52b05e4ffe

**Comment by bmr-cymru** [comment]
and now the commits gone? I'll re-commit this on your behalf; there was nothing wrong with the final patch.

**Comment by bmr-cymru** [comment]
never mind - found it.

**Comment by bmr-cymru** [comment]
Ideally though when you have multiple branches they should only contain the changes for the issue they're submitted for - the extra commit in your trees for the sigterm problem is awkward to deal with (as it's upstream now).
