### ISSUE TITLE
[rhui] Plugin times out

### ISSUE THREAD

**Issue by jeffstoner** [sosreport/sos#765]
The rhui plugin (when run are part of sos) will frequently timeout when run on a pulp server. This is due to the plugin building a file list of the repository directories (/var/lib/pulp or /var/lib/pulp-cds) which may have tens of thousands of files. When the plugin is run independent of sos, it is not constrained and will run to completion.

I've submitted a bug report (and patch) with Red Hat (Bugzilla: 1296237) regarding this issue and included a patch that adds a plugin option governing the generation of the file list (without the option, the file list is _not_ generated.) I can fork+patch and issue a pull request here, too.

**Comment by pmoravec** [comment]
So once `rhui-debug.py` is fixed per bz1296237, no timeouts occur in sos since `/var/lib/[pulp|pulp-cds]` wont be recursivelly listed?

In case rhui plugin should have an option to enable the current behaviour, I suggest patch like:

    diff --git a/sos/plugins/rhui.py b/sos/plugins/rhui.py
    index 1291956..afcd8fa 100644
    --- a/sos/plugins/rhui.py
    +++ b/sos/plugins/rhui.py
    @@ -27,16 +27,20 @@ class Rhui(Plugin, RedHatPlugin):
         packages = ["rh-rhui-tools"]
         files = [rhui_debug_path]
     
    +    option_list = [("genfilelist", "Generate a file list of all repositories",
    +                    "slow", False)]
    +
         def setup(self):
    +        opts = ""
             if self.is_installed("pulp-cds"):
    -            cds = "--cds"
    -        else:
    -            cds = ""
    +            opts = opts + " --cds"
    +        if self.get_option("genfilelist"):
    +            opts = opts + " --genfilelist"
     
             rhui_debug_dst_path = self.get_cmd_output_path()
             self.add_cmd_output(
                 "python %s %s --dir %s"
    -            % (self.rhui_debug_path, cds, rhui_debug_dst_path),
    +            % (self.rhui_debug_path, opts, rhui_debug_dst_path),
                 suggest_filename="rhui-debug")
             return

**Comment by bmr-cymru** [comment]
Do we even need to expose this in `sos`? How often are these file lists actually used?

I wouldn't really object to a new option but I wonder how useful it is: without additional changes then even if this option is used we may hit the command timeout leading to incomplete information being captured.

**Comment by TurboTurtle** [comment]
Closing this as the `rhui` plugin was recently removed entirely.
