### ISSUE TITLE
[networking] blacklist Dialogic Diva ISDN driver pseudo-files

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#777]
```
find /proc/net/eicon/
/proc/net/eicon/
/proc/net/eicon/diva_idi
/proc/net/eicon/adapter1
/proc/net/eicon/adapter1/dynamic_l1_down
/proc/net/eicon/adapter1/group_optimization
/proc/net/eicon/adapter1/info
/proc/net/eicon/divas
/proc/net/eicon/divadidd
```

At least `diva_idi` and `adapterN/dymanic_l1_down` are thought to be problematic in that they return large quantities of data on read (although this contradicts the Dialogic documentation for `dymanic_l1_down`).

We could consider blacklisting everything but those interfaces that are documented [here](https://www.dialogic.com/webhelp/Diva/8.5lin/206-324-08/6336.htm).

**Comment by robert-scheck** [comment]
If you need information from a system with such a driver/card, please let me know. I am also happy to test things, as long as they are not impacting productive systems.

**Comment by bmr-cymru** [comment]
@robert-scheck thanks very much! I'll get something together & I can either provide you replacement files or a package build to test with.
