### ISSUE TITLE
[sosreport] cannot run from git tree without explicit config file path

### ISSUE THREAD

**Issue by gangelop** [sosreport/sos#785]
sosreport cannot be run from git without explicitly specifying config file path.

```
# ./sosreport 
Unable to read configuration file /etc/sos.conf : No such file or directory
```

This issue is likely not very visible assuming that most people already have an `/etc/sos.conf`.

Suggestions:
- sosreport can try to check the cwd for a sos.conf and/or
- sosreport can assume some sane defaults in the absence of a sos.conf

Related to #784

**Comment by psachin** [comment]
@lathan 

You can secify configuration file

`./sosreport --config-file sos.conf`

**Comment by psachin** [comment]
@bmr-cymru Please close this issue.

**Comment by lathan** [comment]
@psachin I know that you can specify the configuration with `--config-file`. The problem I'm reporting is that you *have* to specify the configuration file and I am proposing that this shouldn't be necessary and that sosreport should assume a default configuration.

**Comment by psachin** [comment]
I totally agree, but since sosreport is rolled as RPM package, it is assumed that end-user will install it using yum/dnf. Also developers(and users running sosreport from git) have an option to specify configuration file using --config-file flag. For installed package, `/etc/sos.conf` is already a default file. I think this will only add additional lines of code.

**Comment by psachin** [comment]
Probably the warning message can be fine tuned.

**Comment by bmr-cymru** [comment]
@psachin why?

It's a pretty reasonable request. I'd be happy to review a patch implementing the behaviour discussed.

**Comment by TurboTurtle** [comment]
As of `sos-4.0`, the new config file `/etc/sos/sos.conf` is now optional, and if missing will generate a warning message.
