### ISSUE TITLE
[s390] enable plugin for Debian & Ubuntu

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#788]
The `s390` plugin has historically been Red Hat-only in part due to the difficulty of community testing this for arch (without use of things like Hercules).

There's nothing Red Hat specific in there (one ugly `ls | for` loop that could be cleaned up) so there's no reason to not enable this for other distros beyond a need to get some basic testing carried out.

**Comment by TurboTurtle** [comment]
Closing per 1262cc9
