### ISSUE TITLE
Error reading .swp file

### ISSUE THREAD

**Issue by psachin** [sosreport/sos#796]
[plugin:openstack_neutron] regex substitution failed for '/etc/neutron/.neutron.conf.swp' with: ''utf8' codec can't decode byte 0x84 in position 17: invalid start byte'

**Comment by pmoravec** [comment]
Seems somebody opened `/etc/neutron/neutron.conf` in vi(m) that created the `swp` file.

Reproducer:

    cp /etc/neutron/neutron.conf /etc/neutron/neutron.conf.backup
    echo > /etc/neutron/neutron.conf
    vi /etc/neutron/neutron.conf &
    sosreport --batch -o openstack_neutron
    killall vi
    mv /etc/neutron/neutron.conf.backup /etc/neutron/neutron.conf

**Comment by Amitgb14** [comment]
@pmoravec, better way to skip '.swp' extension files or start with '.' files.

**Comment by pmoravec** [comment]
Skip in collecting them, since skip from password obfuscation would practically make obfuscation of main `/etc/neutron/neutron.conf` ridiculous - the swp file contains whole the file as is..

The skipping makes sense - whenever `do_path_regex_sub` to password obfuscation is called.

**Comment by bmr-cymru** [comment]
Ugh. We need to not collect these at all.

**Comment by bmr-cymru** [comment]
Simpler reproducer:

```
# vim /etc/neutron/neutron.conf
<Ctrl-Z>
# sosreport...
```

**Comment by Amitgb14** [comment]
@pmoravec, @bmr-cymru, I think add extra function to check path extension.

**Comment by psachin** [comment]
It should be universal function to exclude certain file extensions.

**Comment by Amitgb14** [comment]
@psachin @pmoravec @bmr-cymru, My question is to skip collect specified extensions files or hidden files?

**Comment by psachin** [comment]
@Amitgb14  I think we should skip specified extensions. Sometimes hidden file are to be used for analysis(say `.bashrc`/`.profile`) and it is not a good idea to skip all hidden files. I would like inputs from others.

**Comment by bmr-cymru** [comment]
You're looking for Issue #316

**Comment by bmr-cymru** [comment]
(there's a bunch of good discussion in that & the related (closed) PRs - I would like to see this issue revived & the global and policy-based blacklists implemented).

**Comment by Amitgb14** [comment]
@bmr-cymru that's good discussion, here is diff to skip specified extensions file.

```
--- a/sos/plugins/__init__.py
+++ b/sos/plugins/__init__.py
@@ -335,6 +335,11 @@ class Plugin(object):
             path = self.join_sysroot(path)
         return _path_in_path_list(path, self.forbidden_paths)

+    def _is_skipped_extension(self, path):
+        ext = ['.swp']
+        if os.path.splitext(os.path.basename(path))[-1] in ext:
+            return True
+
     def _copy_node(self, path, st):
         dev_maj = os.major(st.st_rdev)
         dev_min = os.minor(st.st_rdev)
@@ -351,6 +356,10 @@ class Plugin(object):
             self._log_debug("skipping forbidden path '%s'" % srcpath)
             return ''

+        if self._is_skipped_extension(srcpath):
+            self._log_debug("skipping extention file '%s'" % srcpath)
+            return ''
+
         if not dest:
             dest = srcpath
```

**Comment by bmr-cymru** [comment]
Nack. Like I said: we are looking for a global blacklisting method that allows for both sos-wide and policy-defined forbidden path patterns.

This is a one-off hack to solve your current problem.
