### ISSUE TITLE
Package API regression

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#80]
The old policy object package query API leaked abstractions into plugin code since it returns RPM header objects from the rpm-python modules.

This was cleaned up during the major updates to sos but has some problems. Currently when a package is queried (via pkgByName(), allPkgsByName(), allPkgsByNameRegex()) the return value is a simple string (or generated array of strings) giving the package name and no other details.

This makes it impossible for modules that want to do package version checks to work; currently this breaks the redhat policy's rhelVersion() and the Gluster module's gluster package version check.

I don't want to lose the improved abstraction of the PM object but I think we need to do better in terms of the information we make available. I'll try a first cut of returning our own dictionary objects that mimic the RPM header names (we need a standard to follow - at least for some core set of fields).

For now I intend to leave the shell-out rpm -qa machinery in place but I'm seeing considerable runtime increases compared to sos-2.2's rpm-python based code so this may need to be revised as well at some point.

**Comment by bmr-cymru** [comment]
Coming back to this I really don't think import failures in policy classes should be something we can't deal with. For non-Red Hat platforms we're not going to be using the policy anyway so an exception in check() (or while loading the policy) shouldn't matter.

**Comment by TurboTurtle** [comment]
Per IRC conversation, closing this.

High-level item to review our PM abstraction as a whole at a later date however.
