### ISSUE TITLE
Caught exception in sosreport at plugin method "logs.collect()"

### ISSUE THREAD

**Issue by anshulbehl** [sosreport/sos#804]
While running sosreport, I came across an issue where I see that logs and lsbrelease plugins are failing with the below error:

Running 43/103: logs...        caught exception in plugin method "logs.collect()"
writing traceback to sos_logs/logs-plugin-errors.txt
  Running 44/103: lsbrelease...        caught exception in plugin method "lsbrelease.collect()"
writing traceback to sos_logs/lsbrelease-plugin-errors.txt
  Running 103/103: yum...  
Creating compressed archive...

While looking at these files I can see that host machine is under a lot of pressure while running these plugins and hence throw an MemoryError, after doing some debugging I have the below observations.

Apparently the output of "journalctl --all --this-boot --no-pager" is too large for python to handle which is causing the exception, After doing some debugging I can see the following data:

179         def add_string(self, content, dest):
180             import pdb; pdb.set_trace()
181  ->     src = dest
182             dest = self.dest_path(dest)
183             self._check_path(dest)
184             f = codecs.open(dest, 'w', encoding='utf-8')
185         f.write(content)
(Pdb) sys.getsizeof(content)
253876652

size of content is around 2GB+ which is being written to destination file as whole.
Please let me know if this issue is being worked at and what are the possible breakages if we try read the object properly using specific buffer sizes and not dumping all the data simultaneously to the file.

Thanks
Anshul Behl

**Comment by pmoravec** [comment]
Something similar but not the same was recently reported in https://bugzilla.redhat.com/show_bug.cgi?id=1326422 .

**Comment by anshulbehl** [comment]
@pmoravec yeah I also saw the bug, just wanted to start a discussion here for the broader audience.

**Comment by bmr-cymru** [comment]
It's a big piece of work: it requires coordinated changes to a number of modules (there is no point in doing any of this work piecemeal).

IO has to be converted to streaming rather than slurping and in-memory objects may need to be replaced with generators.

It is also important to convert all the plugin and archive IO as well as `Plugin` postprocessing hooks at the same time - otherwise you're just moving the exceptions around.

**Comment by Amitgb14** [comment]
Any working on this issue?

**Comment by anshulbehl** [comment]
@Amitgb14 Yes I am working on this issue, will update you if required.

**Comment by TurboTurtle** [comment]
Cycling through on this one - this should be addressed as of sos-3.6 with the size-limiting changes for command collection.

@anshulbehl Have you seen this recently on 3.6 or (the just released) 3.7?

Keeping this open for now, but I believe we can archive this shortly.

**Comment by TurboTurtle** [comment]
Closing due to no response since April 2019.

This kind of exception should be handled now due to our size-limiting changes. If you continue to see issues, please open a new issue.
