### ISSUE TITLE
[docker] plugin calls "docker logs " without container ID

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#813]
Calling docker plugin, it collects also output of "docker logs " command. This is due to the fact that in:

        result = self.get_command_output(ps_cmd)
        if result['status'] == 0:
            result['output'] = result['output'].split("\n")
            for line in result['output'][1:]:
                container_id = line.split(" ")[0]
                self.add_cmd_output([
                    "{0} logs {1}".format(self.docker_bin, container_id)
                ])

`result['output']` is split also to an empty string as the latest item.

Two possible fixes:

    diff --git a/sos/plugins/docker.py b/sos/plugins/docker.py
    index aab558d..0a587d2 100644
    --- a/sos/plugins/docker.py
    +++ b/sos/plugins/docker.py
    @@ -46,7 +46,7 @@ class Docker(Plugin):
     
             result = self.get_command_output(ps_cmd)
             if result['status'] == 0:
    -            for line in result['output'].splitlines()[1:]:
    +            for line in result['output'].splitlines()[1:-1]:
                     container_id = line.split(" ")[0]
                     self.add_cmd_output([
                         "{0} logs {1}".format(self.docker_bin, container_id)

(assumes the empty line is there every time - if not, the latest container wont have collected logs)

or

    diff --git a/sos/plugins/docker.py b/sos/plugins/docker.py
    index aab558d..c6e6262 100644
    --- a/sos/plugins/docker.py
    +++ b/sos/plugins/docker.py
    @@ -47,10 +47,11 @@ class Docker(Plugin):
             result = self.get_command_output(ps_cmd)
             if result['status'] == 0:
                 for line in result['output'].splitlines()[1:]:
    -                container_id = line.split(" ")[0]
    -                self.add_cmd_output([
    -                    "{0} logs {1}".format(self.docker_bin, container_id)
    -                ])
    +                if lines:
    +                    container_id = line.split(" ")[0]
    +                    self.add_cmd_output([
    +                        "{0} logs {1}".format(self.docker_bin, container_id)
    +                    ])
     
     
     class RedHatDocker(Docker, RedHatPlugin):

**Comment by bmr-cymru** [comment]
I would prefer:

```python
        if not lines:
            # empty line in input
            continue
        self.add_cmd_output([
            "{0} logs {1}".format(self.docker_bin, container_id)
        ])
```

I don't like using array slicing for this since it either demands an explanatory comment (for the 'magic' values in the slice), or using a variable for the values to give them descriptive names.

**Comment by pmoravec** [comment]
Update accordingly.

**Comment by pmoravec** [comment]
I apologize, but I was using old sos version. Upstream sos has fixed this in https://github.com/sosreport/sos/commit/ce6cd3ae9dc89dd1de5122add016ce2df60b6cee#diff-2f00a07bb807d7d02ad231c73dfd16e6

Closing then.
