### ISSUE TITLE
[lvm2] lvmdump does not collect any data

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#815]
Calling:

    sosreport -o lvm2 --tmp-dir=. --batch -k lvm2.lvmdump=on

does not collect any data. The cause is, `lvmdump` command requires the directory where to collect data does not exist. While `sos` creates the directory by default.

**Comment by bmr-cymru** [comment]
`--tmp-dir` should not be necessary for this, just a default run w/`lvm2` and the `lvm2.lvmdump` option afaik.

**Comment by pmoravec** [comment]
Agreed, current sos fails also without `--tmp-dir .` and patched one works well in both cases.
