### ISSUE TITLE
[grub2] grub2-mkconfig loads ext4 and brctl kernel modules

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#821]
Invoking grub2-mkconfig command from sos when either ext4 or brctl module is not loaded, both modules remain loaded after the sosreport run.

To resolve:
- Either call the command only when both modules are loaded (cf. 08f5b211dbbf143b3f3ce5e8328947f01adb86cd),
- or finally unload the module(s) not loaded before the call

**Comment by pmoravec** [comment]
Not sure why github marks the today's branch rebase with "May 19" date, but in https://github.com/sosreport/sos/pull/822#commits-pushed-637d96d I just posted a solution for this issue:

1) Enhance `add_cmd_output` by ability to update environment variables
2) Call `grub2-mkconfig` with `GRUB_DISABLE_OS_PROBER=true`

**Comment by bmr-cymru** [comment]
As we run commands without a shell today there isn't an easy way to do this (short of very cryptic ways that launch a shell.. `sh -c 'VAR=var command'` does not work.

**Comment by pmoravec** [comment]
See updated https://github.com/sosreport/sos/pull/822#commits-pushed-91e8370 with `envchange` renamed to better `env_vars`. The branch has both the commits for 1) and 2) from above comment.

**Comment by pmoravec** [comment]
closed this in 57fdeaa on Aug 19, 2016
