### ISSUE TITLE
[foreman] move content of usr, var and etc from sos_commands/foreman/foreman-debug to sos root directory

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#827]
foreman plugin calls `foreman-debug` tool (https://github.com/theforeman/foreman/blob/develop/script/foreman-debug) to collect various foreman/katello/.. information. A lot of config or log files are collected into `sos_commands/foreman/foreman-debug`. A user seeking for some [config|log] file then needs to skip from `sos` root directory into the `foreman-debug` directory and back.

I suggest merging the scattered directory structure to one place by:
- moving all the `/usr`, `/var` and `/etc` content collected within `foreman-debug` from this directory directly to the root `sosreport` directory
- creating symlinks in `foreman-debug` for `usr`, `var` and `etc` to the root `sosreport` directory

Benefits:
- all collected information will be stored just on one place, with symlinks ensuring backward compatibility
- some files won't be collected twice (i.e. by `httpd` and by `foreman` plugins) so final archive will be smaller

For reference: an example content of `sos_commands/foreman/foreman-debug`:

    # cd sos_commands/foreman/foreman-debug/
    # ls
    bundle_list         foreman_filecontexts    gem_list_scl              mongo-task_status  pulp-running_tasks     qpid-stat-q                 usr             virsh_list
    etc                 foreman_packages        katello_pki_dir           plugin_list        puppet_manifests_tree  qpid-stat-resource_manager  var
    facts               foreman_settings_table  katello_ssl_build_dir     ps-awfux           qpid-rpm-qa            qpid-stat-u                 version_puppet
    foreman_auth_table  gem_list                mongo-reserved_resources  ps-elfm            qpid-stat-c            tmp                         version_ruby
    # find etc usr var
    etc
    etc/foreman
    etc/foreman/client_cert.pem
    etc/foreman/client_key.pem
    etc/foreman/database.yml
    etc/foreman/email.yaml
    etc/foreman/encryption_key.rb
    etc/foreman/proxy_ca.pem
    etc/foreman/settings.yaml
    etc/foreman/plugins
    etc/foreman/plugins/katello.yaml
    etc/libvirt
    etc/libvirt/libvirt.conf
    etc/httpd
    etc/httpd/conf
    etc/httpd/conf/httpd.conf
    etc/httpd/conf/magic
    etc/httpd/conf/ports.conf
    etc/httpd/conf.d
    etc/httpd/conf.d/03-crane.conf
    etc/httpd/conf.d/05-foreman-ssl.conf
    etc/httpd/conf.d/05-foreman.conf
    etc/httpd/conf.d/15-default.conf
    etc/httpd/conf.d/25-puppet.conf
    etc/httpd/conf.d/access_compat.load
    etc/httpd/conf.d/actions.load
    etc/httpd/conf.d/alias.conf
    etc/httpd/conf.d/alias.load
    etc/httpd/conf.d/auth_basic.load
    etc/httpd/conf.d/auth_digest.load
    etc/httpd/conf.d/authn_anon.load
    etc/httpd/conf.d/authn_core.load
    etc/httpd/conf.d/authn_dbm.load
    etc/httpd/conf.d/authn_file.load
    etc/httpd/conf.d/authz_core.load
    etc/httpd/conf.d/authz_dbm.load
    etc/httpd/conf.d/authz_groupfile.load
    etc/httpd/conf.d/authz_host.load
    etc/httpd/conf.d/authz_owner.load
    etc/httpd/conf.d/authz_user.load
    etc/httpd/conf.d/autoindex.conf
    etc/httpd/conf.d/autoindex.load
    etc/httpd/conf.d/cache.load
    etc/httpd/conf.d/cgi.load
    etc/httpd/conf.d/dav.load
    etc/httpd/conf.d/dav_fs.conf
    etc/httpd/conf.d/dav_fs.load
    etc/httpd/conf.d/deflate.conf
    etc/httpd/conf.d/deflate.load
    etc/httpd/conf.d/dir.conf
    etc/httpd/conf.d/dir.load
    etc/httpd/conf.d/env.load
    etc/httpd/conf.d/expires.load
    etc/httpd/conf.d/ext_filter.load
    etc/httpd/conf.d/filter.load
    etc/httpd/conf.d/headers.load
    etc/httpd/conf.d/include.load
    etc/httpd/conf.d/log_config.load
    etc/httpd/conf.d/logio.load
    etc/httpd/conf.d/mime.conf
    etc/httpd/conf.d/mime.load
    etc/httpd/conf.d/mime_magic.conf
    etc/httpd/conf.d/mime_magic.load
    etc/httpd/conf.d/negotiation.conf
    etc/httpd/conf.d/negotiation.load
    etc/httpd/conf.d/passenger.conf
    etc/httpd/conf.d/passenger.load
    etc/httpd/conf.d/passenger_extra.conf
    etc/httpd/conf.d/prefork.conf
    etc/httpd/conf.d/prefork.load
    etc/httpd/conf.d/proxy.conf
    etc/httpd/conf.d/proxy.load
    etc/httpd/conf.d/proxy_http.load
    etc/httpd/conf.d/pulp.conf
    etc/httpd/conf.d/pulp_docker.conf
    etc/httpd/conf.d/pulp_nodes.conf
    etc/httpd/conf.d/pulp_puppet.conf
    etc/httpd/conf.d/pulp_rpm.conf
    etc/httpd/conf.d/rewrite.load
    etc/httpd/conf.d/setenvif.conf
    etc/httpd/conf.d/setenvif.load
    etc/httpd/conf.d/socache_shmcb.load
    etc/httpd/conf.d/speling.load
    etc/httpd/conf.d/ssl.conf
    etc/httpd/conf.d/ssl.load
    etc/httpd/conf.d/substitute.load
    etc/httpd/conf.d/suexec.load
    etc/httpd/conf.d/systemd.load
    etc/httpd/conf.d/unixd.load
    etc/httpd/conf.d/usertrack.load
    etc/httpd/conf.d/version.load
    etc/httpd/conf.d/vhost_alias.load
    etc/httpd/conf.d/wsgi.conf
    etc/httpd/conf.d/wsgi.load
    etc/sysconfig
    etc/sysconfig/foreman
    etc/sysconfig/libvirt-guests
    etc/foreman-proxy
    etc/foreman-proxy/foreman_ssl_ca.pem
    etc/foreman-proxy/foreman_ssl_cert.pem
    etc/foreman-proxy/foreman_ssl_key.pem
    etc/foreman-proxy/settings.yml
    etc/foreman-proxy/ssl_ca.pem
    etc/foreman-proxy/ssl_cert.pem
    etc/foreman-proxy/ssl_key.pem
    etc/foreman-proxy/settings.d
    etc/foreman-proxy/settings.d/bmc.yml
    etc/foreman-proxy/settings.d/dhcp.yml
    etc/foreman-proxy/settings.d/discovery.yml
    etc/foreman-proxy/settings.d/dns.yml
    etc/foreman-proxy/settings.d/facts.yml
    etc/foreman-proxy/settings.d/pulp.yml
    etc/foreman-proxy/settings.d/pulpnode.yml
    etc/foreman-proxy/settings.d/puppet.yml
    etc/foreman-proxy/settings.d/puppetca.yml
    etc/foreman-proxy/settings.d/realm.yml
    etc/foreman-proxy/settings.d/templates.yml
    etc/foreman-proxy/settings.d/tftp.yml
    etc/puppet
    etc/puppet/auth.conf
    etc/puppet/fileserver.conf
    etc/puppet/puppet.conf
    etc/puppet/rack
    etc/puppet/rack/config.ru
    etc/katello-installer
    etc/katello-installer/answers.capsule-certs-generate.yaml
    etc/katello-installer/answers.katello-installer.yaml
    etc/katello-installer/capsule-certs-generate.yaml
    etc/katello-installer/config_header.txt
    etc/katello-installer/katello-installer.yaml
    etc/candlepin
    etc/candlepin/candlepin.conf
    etc/tomcat
    etc/tomcat/server.xml
    etc/elasticsearch
    etc/elasticsearch/elasticsearch.yml
    etc/elasticsearch/logging.yml
    etc/pulp
    etc/pulp/nodes.conf
    etc/pulp/repo_auth.conf
    etc/pulp/server.conf
    etc/pulp/server
    etc/pulp/server/plugins.conf.d
    etc/pulp/server/plugins.conf.d/nodes
    etc/pulp/server/plugins.conf.d/nodes/distributor
    etc/pulp/server/plugins.conf.d/nodes/distributor/http.conf
    usr
    usr/share
    usr/share/foreman
    usr/share/foreman/Gemfile.in
    var
    var/log
    var/log/foreman
    var/log/foreman/apipie_cache.log-20160524
    var/log/foreman/cron.log-20160525
    var/log/foreman/db_migrate.log-20160524
    var/log/foreman/db_seed.log-20160524
    var/log/foreman/production.log
    var/log/foreman/production.log-20160524.gz
    var/log/foreman/production.log-20160525.gz
    var/log/foreman/production.log-20160526.gz
    var/log/foreman/production.log-20160527.gz
    var/log/foreman/production.log-20160528.gz
    var/log/foreman/production.log-20160529.gz
    var/log/foreman/production.log-20160530.gz
    var/log/foreman/production.log-20160531.gz
    var/log/foreman/production.log-20160601.gz
    var/log/foreman/production.log-20160602
    var/log/foreman/reindex.log-20160601
    var/log/httpd
    var/log/httpd/error_log
    var/log/httpd/error_log-20160529
    var/log/httpd/foreman-ssl_access_ssl.log
    var/log/httpd/foreman-ssl_access_ssl.log-20160529
    var/log/foreman-proxy
    var/log/foreman-proxy/proxy.log-20160525.gz
    var/log/katello-installer
    var/log/katello-installer/capsule-certs-generate.2.log
    var/log/katello-installer/katello-installer.2.log
    var/log/katello-installer/katello-installer.log
    var/log/candlepin
    var/log/candlepin/audit.log
    var/log/candlepin/audit.log-20160529.gz
    var/log/candlepin/candlepin.log
    var/log/candlepin/candlepin.log-20160529.gz
    var/log/candlepin/cpdb.log
    var/log/candlepin/cpinit.log
    var/log/candlepin/error.log
    var/log/candlepin/error.log-20160529.gz
    var/log/tomcat
    var/log/tomcat/catalina.2016-05-23.log
    var/log/tomcat/catalina.2016-06-01.log
    var/log/tomcat/catalina.out
    var/lib
    var/lib/pgsql
    var/lib/pgsql/data
    var/lib/pgsql/data/pg_hba.conf
    var/lib/pgsql/data/pg_ident.conf
    var/lib/pgsql/data/postgresql.conf
    var/lib/puppet
    var/lib/puppet/ssl
    var/lib/puppet/ssl/certs
    var/lib/puppet/ssl/certs/pmoravec-sat61-rhel7.gsslab.brq.redhat.com.pem
    var/lib/puppet/ssl/certs/ca.pem
    var/lib/puppet/ssl/ca
    var/lib/puppet/ssl/ca/inventory.txt
    # 

(`tmp` directory shall remain in `foreman-debug`, it does not contain anything from `/tmp` but it contains foreman tasks export)

Cc @lzap and @dLobatog as co-maintainers of `foreman-debug` for possible comments.

**Comment by pmoravec** [comment]
Just a note: I suggest the change only in `sosreport`: once `foreman-debug` is collected, do the move and symlink.

No changes in `foreman-debug` itself. Just `foreman-debug` called from `sosreport` will have (just in `sosreport`) some changes inside the `foreman-debug` directory.

**Comment by bmr-cymru** [comment]
No; this is crazy. If Foreman wants to have its own special script then it gets to keep the results. We do not go about attempting to unpick whatever packaging they have done and then pretend that these files were captured by sos - this is just ridiculous make-work where we will forever need to synchronize between the two.

Projects have a choice: they can use and benefit from our infrastructure or they can go their own way and invent their own collection and packaging infrastructure.

The two ARE mutually exclusive. We will collect the results of the latter but we are not on the hook to do any special post-processing to cover over the fact that they are not using a native plugin.
