### ISSUE TITLE
Default to Python3

### ISSUE THREAD

**Issue by BryanQuigley** [sosreport/sos#830]
On Ubuntu 16.04 Cloud and server images there is no python (2) binary by default so running sosreport from git errors out with:
sudo: unable to execute ./sosreport: No such file or directory

Most end users don't end up running from git (right?) so this is mostly the default for developers as packagers will modify it to match what is actually on the system.  

The only alternative option I've found is to make the sosreport execuatble a shell script, that determines what is installed and then runs that.  I can't say I like that approach..

**Comment by battlemidget** [comment]
We should at the very least search for a python3 and python2 binary and use one or the other.

**Comment by bmr-cymru** [comment]
The upstream tree allows you to build for py2 or py3. Distribution maintainers can then choose to build for 2 or 3 as appropriate to particular distributions or distribution versions.

When you say "running from git" I guess you mean straight from the working tree without any installation to system paths?

I'm open to finding a way to make this easier for developers - what are the steps you use now & where does it fail?

**Comment by BryanQuigley** [comment]
>When you say "running from git" I guess you mean straight from the working tree without any installation to system paths?
Exactly.  Specifically I'm doing this to test plugins I'm working on.  Notably Juju.

>I'm open to finding a way to make this easier for developers - what are the steps you use now & where does it fail?

16.04 cloud images don't come with a /usr/bin/python so sudo ./sosreport fails with the error I mention above.

I then change 'sosreport' from #!/usr/bin/python to #!/usr/bin/python3 and it works.  I'm guessing more of us will run into with recent releases of distros as python2 is removed.

There are three ways forward I see:
Make Python version specific binaries:  sospy3.py sospy2.py
Make a shell script that does a search for the python version and then runs it.
Switch to python3 for default - (When older distributions with python2 only by default are less important for development convenience than newer distributions that only ship python3 by default)

**Comment by battlemidget** [comment]
@bmr-cymru we've taken the plunge this release and totally removed python2 from the base install :)

**Comment by karibou** [comment]
The current situation needs to be adressed at a distro level IMHO.

If upstream wants to address it otherwise, I'll be happy to revert the distro-specific patch.

Since 3.3 will come out shortly, I'll address that on the next debian/ubuntu upload. This doesn't mean that this thread should be closed.

**Comment by karibou** [comment]
ok, I thought I would have noticed that : the debian packaging is taking care of that and is already forcing the shebang to be /usr/bin/python3

root@sosreport-py3:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04 LTS
Release:        16.04
Codename:       xenial
root@sosreport-py3:~# head -2 $
head: cannot open '$' for reading: No such file or directory
root@sosreport-py3:~# head -2 $(which sosreport)
#!/usr/bin/python3
# This program is free software; you can redistribute it and/or modify

So as far as I'm concerned, it is already been taken care of at the distro level. BryanQuigley I don't know how you got that behavior in the first place.

**Comment by BryanQuigley** [comment]
I'm only talking about when I pull it from Git directly for testing purposes, like when I'm trying to test the my changes to the Juju plugin on a LOT of machines.

**Comment by bmr-cymru** [comment]
I don't know what you mean by "taken care of at the distro level" - if you're looking for changes in how a checked-out git tree behaves then that CANNOT be done at distro level since it's the naked upstream source tree.

The `sosreport` file that we ship in git has this:

```python
#!/usr/bin/python
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

""" sos entry point. """

import sys
try:
    from sos.sosreport import main
except KeyboardInterrupt:
    raise SystemExit()

if __name__ == '__main__':
    main(sys.argv[1:])

# vim:ts=4 et sw=4
```

AIUI that *IS* correct - if a distro only ships one python version then it should be installed at `/usr/bin/python`. Alternate names are only needed when multiple versions may be installed simultaneously. If a distribution only ships version three but still calls it `python3` that's kinda the distribution's problem (and a bit crazy imho).

That said, while I think we're doing the right thing, I am happy to try to make this easier on people if we can. I would suggest treating this like SOSVERSION and using @..@ substitution to edit the files in the source tree.

It'd still be a bit weird/clunky for a python project but I don't see another way to have this "just work" (and I am not interested in carrying shell scripts or other glue *just* to eliminate a tiny bit of work during set up).

Also, if you are testing on many systems just build an RPM or Deb and push it out to them - this is how I test on RHEL, Fedora, CentOS and SuSE. It's more effort to set up but much less to use.

**Comment by karibou** [comment]
Nope. For now and the forseenable future, /usr/bin/python should point to python2 : 
https://www.python.org/dev/peps/pep-0394/ (just relaying what I've been told)

Now on debian & derivatives, the packaging helper used by battlemidget forces a python3 shebang over the pristine upstream tarball.

HTH,

...Louis

**Comment by bmr-cymru** [comment]
From that link:

```
however, end users should be aware that python refers to python3 on at least Arch Linux  (that change is what prompted the creation of this PEP), so python should be used in the shebang line only for scripts that are source compatible with both Python 2 and 3. 
```

Which I think is the case for our `sosreport`. And further:

```
The more general python command should be installed whenever any version of Python 2 is installed and should invoke the same version of Python as the python2 command (however, note that some distributions have already chosen to have python implement the python3 command; see the Rationale and Migration Notes below). 
```

I thought that Fedora was planning to switch `python` to `python3` with the 3-by-default move but I may be incorrect.

Bottom line is that this seems to be as big a mess as the general python2 - python3 move. I don't think there is much more we can do as we seem to be complying with the general guidelines.

If someone wants to attempt to make that script dynamic or configure-time generated I'd be happy to review but I don't think it's a huge deal.

**Comment by bmr-cymru** [comment]
> packaging helper used by battlemidget forces a python3 shebang over the pristine upstream tarball.

OK; that _is_ papering over a bug. If we're installing we know what version it is and we should be updating that path automatically (via @PYTHONVERSION@ or whatever).

**Comment by BryanQuigley** [comment]
I did make a script that would check installed python versions and try to pick the right one.   But then in testing I realized it doesn't check if python has the required dependencies.. 

Anyway.. updating the docs to mention you have to do something different if you only have python3 installed seems like the easiest thing...
