### ISSUE TITLE
[plugin] add time calculation interface

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#838]
We've a number of plugins doing some form of time / date calculation (tomcat and pacemaker are using datetime and logs does some manual munging of a journalctl `--since` argument).

It's probably a good time to review this and to see whether we can add new interfaces to simplify plugin code that needs to deal with times and dates.

This could be a new interface in the `Plugin` class itself or, likely better (since it at least doesn't make #495 any worse), in a new class that is accessible from all plugins.

**Comment by TurboTurtle** [comment]
I'm closing this out at this point. We've not had all that many plugins added or modified to use time calculations, and beyond that it is likely that any interface we have for this would introduce maintenance overhead for the myriad tools we collect from that all have their "own" way of handling timing.

If anyone has a solid need for an interface like this, or has an idea on an implementation that doesn't have the concerns noted above, by all means please feel free to re-open this for discussion.
