### ISSUE TITLE
[RFE] Time based log inclusion

### ISSUE THREAD

**Issue by beatrubi** [sosreport/sos#849]
Implement the possibility to choosing files out of a directory in a specific time range.

Motivation: PCP creates daily log files in /var/log/pcp/pmlogger/$HOSTNAME which are accumulated over time. The current logic includes the whole directory only in case it's less then 100MBytes. The customer has only a possibility to send those logs using the --all-logs option of sosreport which results in a huge report file.

Ideally the last three days of logs are included. In PCP we would have to option to select the files based on their name, a generic approach of including files based on their timestamp offers a recyclable way to handle other logs as well.

**Comment by valleedelisle** [comment]
Do you think #1678 could solve this? Do you have any suggestion regarding this implementation?

**Comment by TurboTurtle** [comment]
After review, I believe this is in fact handled by #1678, so I am closing this now.

If there is still some need here, please feel free to re-open this issue.
