### ISSUE TITLE
FSF address needs to be updated

### ISSUE THREAD

**Issue by sandrobonazzola** [sosreport/sos#886]
"The Free Software Foundation address in this file seems to be outdated or
misspelled.  Ask upstream to update the address, or if this is a license file,
possibly the entire file with a new copy available from the FSF."

Detected by Fedora 24 rpmlint.

sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/ptp.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/tomcat.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/symcli.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/utilities.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/qpid_dispatch.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/smartcard.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/**init**.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/mrggrid.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/ntp.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/kubernetes.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/azure.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/ssmtp.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/openstack_horizon.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/soundcard.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/landscape.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/maas.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/openstack_neutron.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/openssl.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/vmware.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/python.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/systemd.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/openhpi.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/ovirt.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/openstack_ceilometer.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/iscsi.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/infiniband.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/pcp.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/cgroups.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/radius.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/vulkan.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/haproxy.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/targetcli.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/lilo.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/filesys.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/openstack_instack.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/ds.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/sosreport.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/ceph.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/keyutils.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/docker.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/devices.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/java.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/abrt.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/origin.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/selinux.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/reporting.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/nscd.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/tuned.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/hardware.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/hpasm.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/autofs.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/lxd.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/nis.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/mrgmessg.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/md.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/openstack_keystone.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/omsa.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/kimchi.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/mpt.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/sssd.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/iprconfig.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/pacemaker.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/gfs2.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/vhostmd.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/procenv.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/hts.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/acpid.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/logrotate.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/lstopo.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/kernel.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/cobbler.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/psacct.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/ssh.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/ntb.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/openstack_sahara.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/libraries.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/firewalld.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/**init**.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/insights.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/nfsserver.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/opencl.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/quagga.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/openstack_cinder.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/rhui.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/cman.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/nfs.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/dlm.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/monit.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/upstart.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/block.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/saphana.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/memory.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/ldap.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/pci.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/openstack_glance.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/megacli.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/distupgrade.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/services.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/sendmail.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/dpkg.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/xinetd.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/postgresql.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/sapnw.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/kdump.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/snmp.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/openswan.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/ubuntu.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/yum.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/general.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/gluster.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/etcd.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/archive.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/subscription_manager.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/sanlock.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/vsftpd.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/openstack_swift.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/samba.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/ata.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/kpatch.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/opengl.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/juju.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/corosync.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/rpm.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/chrony.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/postfix.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/xen.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/puppet.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/ppp.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/ipa.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/processor.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/redis.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/policies/redhat.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/ipmitool.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/krb5.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/policies/suse.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/xfs.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/sunrpc.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/qpid.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/dbus.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/dhcp.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/last.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/system.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/x11.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/fcoe.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/kvm.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/apparmor.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/dovecot.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/apport.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/virsh.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/auditd.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/lightdm.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/named.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/openshift.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/manageiq.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/foreman.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/navicli.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/rabbitmq.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/grub2.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/iscsitarget.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/ipsec.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/cron.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/veritas.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/scsi.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/openvswitch.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/udev.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/anacron.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/pxe.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/anaconda.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/sysvipc.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/systemtap.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/devicemapper.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/i18n.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/ipvs.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/powerpath.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/apt.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/multipath.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/openstack_trove.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/networking.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/cups.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/openstack_ironic.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/lvm2.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/process.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/tftpserver.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/grub.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/activemq.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/dmraid.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/mongodb.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/boot.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/openstack_heat.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/s390.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/dnf.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/usb.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/ctdb.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/teamd.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/powerpc.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/mysql.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/sar.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/logs.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/oddjob.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/openstack_nova.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/pam.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/ovirt_hosted_engine.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/squid.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/gdm.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/keepalived.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/satellite.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/numa.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/lsbrelease.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/atomichost.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/cs.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/apache.py
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/libvirt.py
sos.noarch: E: incorrect-fsf-address /usr/sbin/sosreport
sos.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/sos/plugins/unity.py

**Comment by bmr-cymru** [comment]
Thanks. I noticed another problem in the boilerplate this week, so I'll fix both of these at the same time.

**Comment by sandrobonazzola** [comment]
@bmr-cymru Hi, looks like a few weeks passed :-) any update?

**Comment by sandrobonazzola** [comment]
Still an issue in 3.4

**Comment by bmr-cymru** [comment]
It didn't make it - It's not really something we'd consider release critical - there were too many last-minute changes landing for downstream distributions (that wanted to package 3.4 yesterday) for us to make this wide-scale change in time.

Now that 3.4 is out it's a better time to consider this.

**Comment by bmr-cymru** [comment]
Closed in commit  24dc8e52db20bf3333c9a6e1262a7c309473549f, thanks!
