### ISSUE TITLE
process: collect ps -o lstart

### ISSUE THREAD

**Issue by d-hatayama** [sosreport/sos#921]
Please collect ps -o lstat.

process plugin now collects start_time and stime as a starting time of processes but these become less informative for long-running processes. There are other formats representing a starting time of processes, but according to manual page of ps command, only lstart format provides consistent information that doesn't vary depending on how long each process is running.

Here is an example showing various formats, including lstart, representing a starting time of each process:

    # LANG=C ps -p 1 -o pid,ppid,comm,start,stime,start_time,bsdstart,lstart
      PID  PPID COMMAND          STARTED STIME START  START                  STARTED
        1     0 init              Mar 14  2016  2016 Mar 14 Mon Mar 14 09:07:45 2016

Only the concern I have now is that resulted value of lstart format contains spaces and it could make parsing difficult, and so it could be difficult to add it into existing commands in process plugin.

**Comment by knoha-rh** [comment]
I created a pull request. #1004 
Does it satisfy your request?

**Comment by d-hatayama** [comment]
Sorry for delayed response.

As I wrote in the last paragraph of the issue statement, the resulted value of lstart format contains spaces. On the other hand, output of the ps command that your patch modifies is as follows:

    F S   UID   PID  PPID  PGID   SID CLS PRI ADDR    SZ WCHAN  STIME TT           TIME CMD
    4 S     0     1     0     1     1  TS  19    - 48025 ep_pol May31 ?        00:00:21 /usr/lib/systemd/systemd --switched-root --system --deserialize 21
    1 S     0     2     0     0     0  TS  19    -     0 kthrea May31 ?        00:00:00 [kthreadd]
    1 S     0     3     2     0     0  TS  19    -     0 smpboo May31 ?        00:00:00 [ksoftirqd/0]
    1 S     0     6     2     0     0  TS  19    -     0 worker May31 ?        00:00:00 [kworker/u4:0]
    1 S     0     7     2     0     0  FF 139    -     0 smpboo May31 ?        00:00:00 [migration/0]

The value that could containing spaces is only the right-most part, CMD. I guess that this is intentionally done to make the output parsing friendly. The other ps commands by plugin/process.py look similar. It might be better to introduce a new command.

**Comment by d-hatayama** [comment]
Very delayed response...
I confirmed that PR #1004 has been merged, so closing this issue.
Thanks @knoha-rh.
