### ISSUE TITLE
[ceph] wrong forbidden path for mon

### ISSUE THREAD

**Issue by haklein** [sosreport/sos#925]
The forbidden path for the mon is wrong, hence collecting multiple gigabytes in some environments

**Comment by haklein** [comment]
- self.add_forbidden_path("/var/lib/ceph/osd/mon/*")
 + self.add_forbidden_path("/var/lib/ceph/mon/*")

**Comment by badone** [comment]
@haklein oops, how did that get there. Looking into it.

**Comment by TurboTurtle** [comment]
Looks like this was resolved with 6b2e85b, closing.
