### ISSUE TITLE
Ubuntu Package detection issue

### ISSUE THREAD

**Issue by BryanQuigley** [sosreport/sos#935]
Not making this a pull request because I don't understand it - but on Ubuntu Zesty with python3 version 3.5.3 I have to remove the  \* at the end of the dpkg-query line or else it won't properly detect packages.

I used the python plugin as the example to find. 

Tracing though without this change is only comes up with packages man and sosreport. 

The "fix" is below:

> diff --git a/sos/policies/debian.py b/sos/policies/debian.py
> index a785c39..dc7f2e6 100644
> --- a/sos/policies/debian.py
> +++ b/sos/policies/debian.py
> @@ -11,7 +11,7 @@ class DebianPolicy(LinuxPolicy):
>      report_name = ""
>      ticket_number = ""
>      package_manager = PackageManager(
> -        "dpkg-query -W -f='${Package}|${Version}\\n' \*")
> +        "dpkg-query -W -f='${Package}|${Version}\\n'")
>      valid_subclasses = [DebianPlugin]
>      PATH = "/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games" \
>             + ":/usr/local/sbin:/usr/local/bin"
> @@ -21,7 +21,7 @@ class DebianPolicy(LinuxPolicy):
>          self.report_name = ""
>          self.ticket_number = ""
>          self.package_manager = PackageManager(
> -            "dpkg-query -W -f='${Package}|${Version}\\n' \*")
> +            "dpkg-query -W -f='${Package}|${Version}\\n'")
>          self.valid_subclasses = [DebianPlugin]
>  
>      @classmethod`

**Comment by bmr-cymru** [comment]
Does it work on another system (where it doesn't usually break), if you also remove the `\*`?

I don't know `dpkg` well enough to comment in more detail without poking about a bit.

**Comment by BryanQuigley** [comment]
The below commit also partially explains (I can't full grep it, but I'm 50% there) why just creating a filename named sos in the directory I'm running from actually changes this behavior. 

Without the \* appears to work fine on all machines I've tested so far so I'll make a pull request. 

Started happening from commit 04d412816de2e4053f43956adf536272a2ddc19c
Author: Shane Bradley
Date:   Fri Jan 29 12:06:17 2016 -0500

    [utilities] Support glob expansion in command arguments
    
    Historically, when calling an external process, sos relied on the
    use of a shell to perform glob expansion on arguments passed to
    the command.
    
    This potentially exposes sos and its children to the entire gamut
    of shell expansion and all the problems associated with it and
    this is part of the reason that use of a shell in callouts was
    disabled in commit 46b6c3d (Issue #253).
    
    While full shell syntax is undesirable for many reasons the use
    of globs to express path arguments to external commands is very
    useful and widely applied: restore this limited support for
    shell-like syntax using the python glob.glob module and expand
    any argument that is a valid glob into its resulting arguments.

**Comment by bmr-cymru** [comment]
I bet the glob expansion doesn't properly ignore escaped (`\*`) glob chars.
