### ISSUE TITLE
An option to gather relevant info for given package(s)

### ISSUE THREAD

**Issue by sandrobonazzola** [sosreport/sos#940]
Moved from https://bugzilla.redhat.com/show_bug.cgi?id=890541

Description of problem:

ABRT is calling sosreport during crash, with very limited set of plugins. ABRT knows which package contains crashed executable, and could know in future packages with relevant libraries.

Would be neat if ABRT could pass package name(s) when calling sosreport to gather some crash specific info. It could be eg.:

 - config files for given package
 - rpm -V for given package
 - something more?

Maybe, it can even enable some relevant plugins, but this is probably too expensive to implement and manage.

Syntax could be eg:
sosreport --only=anaconda --only... --package=thunderbird

**Comment by bmr-cymru** [comment]
It's a nice idea but it doesn't really fit with the way `sos` is currently designed. Better for now would be if ABRT implemented either profiles, or a better logic for selecting from a fixed plugin set (it's easy to generate a mapping of possible package names to plugins).

This use case "something went wrong but we're not sure what" was really what was in mind when the `system` profile was added - it quickly generates a small report that can be used to start investigations.

**Comment by TurboTurtle** [comment]
Closing this out, as we haven't changed much in the approach/perspective on how to enable plugins. The desired behaviors from ABRT should be implemented within ABRT, as Bryn notes above.
