### ISSUE TITLE
 [RFE] Modules implementing filters for their files

### ISSUE THREAD

**Issue by sandrobonazzola** [sosreport/sos#941]
Moved from https://bugzilla.redhat.com/show_bug.cgi?id=654235

Problem:
- Files such as /etc/passwd are not included
- I don't think anyone is comfortable adding them because the data they contain is particularly sensible.

Approach:
- For /etc/passwd for example, replacing the account field by its SHA-1, every character in the GECOS field by 'x' would still allow a support engineer to determine if a username is defined there, if yes its shell, etc.
- Such filters belong in the module itself and not in the core of sosreport

Proposed solution:

- When including the file, the module should be able to specify a filter method.
- We should allow per-line filters (fast and simple), filters that receive the file contents as a string and return the stored contents as another

**Comment by bmr-cymru** [comment]
I am really not comfortable with collecting even hashed values that end users would consider sensitive; the values we are encoding may be especially vulnerable to dictionary attack and we have no way of knowing this beforehand.

It would also mean we would need to rewrite (and get review for) our legal disclaimer (at least as used for the Red Hat family of distros).

Given an engineer would presumably be in contact with the systems owners I think this class of information belongs to the set that we would expect users to confirm on an as-needed basis - I think this grants the proper level of control to the system's owners.

**Comment by pmoravec** [comment]
+1. Collecting hashes of such sensitive data might cause the data are fully readable within few years, when current hashing algorithms might have been cracked. See what happened to sha1 recently, or how fast are we moving from SSLv2/v3/TLS1.0 due to similar reasons.

**Comment by BryanQuigley** [comment]
Would anyone object to a non-default option to collect sensitive files like /etc/passwd and /etc/group?

I'd also be OK having it have to be explicitly specified (not covered in -a).

**Comment by TurboTurtle** [comment]
I'm not comfortable with the potential to collect sensitive files like that. We already have `--no-postproc` which can be used to avoid processing sensitive keys out of already collected files, but collecting something like `/etc/passwd` or similar is a line in the sand for me.

I'm going to close this out, but if there is solid need/rationale for collecting items like that in the future, feel free to re-open.
