### ISSUE TITLE
RFE: Collect FIPS state in sosreport from running system

### ISSUE THREAD

**Issue by sandrobonazzola** [sosreport/sos#943]
Moved from https://bugzilla.redhat.com/show_bug.cgi?id=871866

Description of problem:

It would be nice if sosreport contains FIPS mode info in some easily parsable format.

- current fips state (/proc/sys/crypto/fips_enabled)
- kernel command line (fips=1, both root= and boot= ... etc)
- installed fips packages (dracut-fips, dracut-fips-aesni, ...)
(+ maybe plus info like prelink disabled etc)

Version-Release number of selected component (if applicable):
sos-2.2-30.fc18.noarch

**Comment by bmr-cymru** [comment]
We already collect the kernel command line (both `kdump` and `kernel` plugins), and the package data is captured by the respective package manager plugin (`rpm` or `dpkg`).

I'll get `fips_enabled` added though - it's a bit silly that we test it during policy loading but do not capture it anywhere in explicit form (although you can always tell if it was set on a Red Hat family distro).

**Comment by bmr-cymru** [comment]
Fixed with a new `crypto` plugin (also grabs the kernel cipher list from `/proc/crypto`).
