### ISSUE TITLE
sos_commands/networking is failing to run commands in network namespaces

### ISSUE THREAD

**Issue by dosaboy** [sosreport/sos#948]
I am using sosreport 3.3-1~16.04.1 and all log files matching sos_commands/networking/ip_netns_exec_* contain the following:

exec of "(id:" failed: No such file or directory

A quick scan of the code would suggest that the following is not quite up to muster:

https://github.com/sosreport/sos/blob/e9458ae0e263ea9997465a46873e9fe7be6ae3c8/sos/plugins/networking.py#L75

**Comment by bmr-cymru** [comment]
Can you paste the output of `ip netns` from your system?

**Comment by dosaboy** [comment]
Ok bit more info, this is breaking with >= Ubuntu Xenial because the output of ip netns is slightly different than before i.e. when listing namepsaces there is additional info after the namespace name e.g.

$ ip netns
qrouter-70231b98-14f9-4480-a761-072e92084e36 (id: 0)

Note the "(id: 0)"

**Comment by bmr-cymru** [comment]
Thanks - unless you've noticed any other changes that should be all that's needed.
