### ISSUE TITLE
[gnocchi]  Plugin crashed 'os' module is missing

### ISSUE THREAD

**Issue by Amitgb14** [sosreport/sos#950]
Hi,
gnocchi is newly added plugin and it's crashed, show below message,

[root@localhost sos_logs]# cat openstack_gnocchi-plugin-errors.txt 
Traceback (most recent call last):
  File "/home/aghadge/Project/OpenSource/sos/sos/sosreport.py", line 1254, in setup
    plug.setup()
  File "/home/aghadge/Project/OpenSource/sos/sos/plugins/gnocchi.py", line 38, in setup
    if os_var not in os.environ:
NameError: global name 'os' is not defined

Easy, 'os' module is missed.

**Comment by Amitgb14** [comment]
@psachin, please have a look.

**Comment by psachin** [comment]
@Amitgb14 Thanks for bringing this up 👍

**Comment by bmr-cymru** [comment]
Please follow commit formatting & other rules from the contributor guidelines (missing Signed-off-by).
