### ISSUE TITLE
[npm] Crashed on Fedora 23

### ISSUE THREAD

**Issue by Amitgb14** [sosreport/sos#951]
Hi, 
I ran the command `./sosreport -a` and found errors in npm plugin,

[root@localhost sos_logs]# cat npm-plugin-errors.txt 
Traceback (most recent call last):
  File "/home/aghadge/Project/OpenSource/sos/sos/sosreport.py", line 1254, in setup
    plug.setup()
  File "/home/aghadge/Project/OpenSource/sos/sos/plugins/npm.py", line 95, in setup
    working_directory=project_path)
UnboundLocalError: local variable 'project_path' referenced before assignment

**Comment by Amitgb14** [comment]
@pmoravec , Please have a look.

**Comment by bmr-cymru** [comment]
Bug in `setup()`. The `project_path` variable is only assigned in the `if self.get_option()` branch.

**Comment by pmoravec** [comment]
Sorry! :)
