### ISSUE TITLE
[gnocchi] Missing "packages = .." causes plugins runs everytime

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#977]
gnocchi plugin is executed every time (until specifically disallowed). It is because the plugin lacks line like:

    packages = ( 'some_package', 'another_package')

to enable the plugin.

This also causes (on systems not having `gnocchi`) `sosreport` output has practically always the warnings:

    OS_USERNAME not found in environment variables which is required to run gnocchi commands
    OS_PASSWORD not found in environment variables which is required to run gnocchi commands
    OS_TENANT_NAME not found in environment variables which is required to run gnocchi commands

**Comment by pmoravec** [comment]
@psachin : could you - as the author of the plugin - advice what packages shall enable this plugin? I.e. "either package X or Y or Z must be present on the system to enable gnocchi plugin".

**Comment by bmr-cymru** [comment]
If we don't have at least a list of packages by the time I am ready to release 3.4 this plugin will have to be removed from the release.

**Comment by pmoravec** [comment]
Typical `gnocchi` deployment in OSP:

    # rpm -qa | grep gnocchi
    openstack-gnocchi-indexer-sqlalchemy-3.0.3-1.el7ost.noarch
    openstack-gnocchi-metricd-3.0.3-1.el7ost.noarch
    puppet-gnocchi-9.4.1-1.el7ost.noarch
    openstack-gnocchi-common-3.0.3-1.el7ost.noarch
    openstack-gnocchi-statsd-3.0.3-1.el7ost.noarch
    python-gnocchiclient-2.6.0-1.el7ost.noarch
    python-gnocchi-3.0.3-1.el7ost.noarch
    openstack-gnocchi-api-3.0.3-1.el7ost.noarch
    openstack-gnocchi-carbonara-3.0.3-1.el7ost.noarch
    #

So the tripple `puppet-gnocchi`, `python-gnocchiclient` and `python-gnocchi` seems to cover any instance of `gnocchi` bits.

**Comment by pmoravec** [comment]
OK, these are rather client packages, PR updated.
