### ISSUE TITLE
nosetests-3 error

### ISSUE THREAD

**Issue by sandrobonazzola** [sosreport/sos#983]
Testing sos with python3-nose:

======================================================================
ERROR: test_output (utilities_tests.ExecutableTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/SOURCES/sos-3.4/tests/utilities_tests.py", line 61, in test_output
    result = sos_get_command_output(path)
  File "/builddir/build/SOURCES/sos-3.4/sos/utilities.py", line 160, in sos_get_command_output
    raise e
  File "/builddir/build/SOURCES/sos-3.4/sos/utilities.py", line 154, in sos_get_command_output
    preexec_fn=_child_prep_fn)
  File "/usr/lib64/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error

======================================================================
ERROR: test_shell_out (utilities_tests.ExecutableTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/SOURCES/sos-3.4/tests/utilities_tests.py", line 81, in test_shell_out
    self.assertEquals("executed\n", shell_out(path))
  File "/builddir/build/SOURCES/sos-3.4/sos/utilities.py", line 192, in shell_out
    chroot=chroot, chdir=runat)['output']
  File "/builddir/build/SOURCES/sos-3.4/sos/utilities.py", line 160, in sos_get_command_output
    raise e
  File "/builddir/build/SOURCES/sos-3.4/sos/utilities.py", line 154, in sos_get_command_output
    preexec_fn=_child_prep_fn)
  File "/usr/lib64/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error

**Comment by bmr-cymru** [comment]
* What distribution and version are you testing on?
* What version of the python interpreter are you using?
* What version of python-nose3 are you using?

**Comment by bmr-cymru** [comment]
From the output you've pasted you seem to be using a Python version that is currently unsupported. To see the versions that we currently test with & support, refer to the Travis configuration in the root of the repository:

```
$ cat .travis.yml 
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - "nightly"
matrix:
  allow_failures:
    - python: 3.5
    - python: "nightly"
sudo: false
notifications:
  email:
    sos-devel@redhat.com
  irc:
    channels:
      - "us.freenode.net#sosreport"
    on_success: change
install:
  - "pip install six nose nose-cov pep8"
  - "python setup.py install"
script:
  - "pep8 sos"
  - "nosetests -v --with-cover --cover-package=sos --cover-html"
```

**Comment by bmr-cymru** [comment]
Guessing by the Python version, but this is rawhide, right? It's probably going to be a minor change, or even something environmental, but it's likely going to take me a little while to get an environment set up to look at this.

**Comment by sandrobonazzola** [comment]
About the versions:
```
 # grep PRETTY_NAME /etc/os-release 
 PRETTY_NAME="Fedora 27 (Rawhide)"

 # rpm -qv python3
 python3-3.6.1-1.fc27.x86_64
```

Preparing the environment for reproducing the issue:
In a terminal:
` $ mock -r fedora-rawhide-x86_64 shell`

In a second terminal:
` $ mock -r fedora-rawhide-x86_64 install python3-nose python3-six python3-devel gettext git`

Within mock shell:
```
 # git clone https://github.com/sandrobonazzola/sos.git
 # cd sos
 # git checkout patch-1
 # nosetests-3 -v --with-cover --cover-package=sos --cover-html

```
The patch is needed for python3 support fix and already opened a pull request for it.

**Comment by bmr-cymru** [comment]
Fixedin commit 8df3d15015796001845c676fc2606a9803da684d.

**Comment by bmr-cymru** [comment]
Thanks - it was the Python version that was most interesting here. I didn't have a machine around at the time with 3.6, so it was the only version I couldn't easily/quicky test.

There's an open PR to add 3.6 to the Travis test set - as Fedora's now shipping it it would be good to get that in soon. It's bundled in with a few other changes that I need to take a closer look at, but it shouldn't be a big deal.
