### ISSUE TITLE
[sos] fix auto-generated versioning for distutils builds

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#985]
Historically the file `sos/__init__.py` was generated at build time by the Makefile based scripts, substituting `@SOSVERSION@` for the current version (as defined in the RPM spec file, for further historical reasons...).

There are two related problems:

* The shipped version of `sos/__init__.py` was not updated for either `3.3` or `3.4`. This is a result of changing maintainer process: the local in-tree build which would mark this as modified (and hence get it committed with the version bump) is now done out-of-tree and I missed the update when checking manually.

* In this situation local builds that use `distutils` will never regenerate this file leading to a stale version number being reported by `sosreport`.

The first has a simple, procedural fix: make sure to update the file.

The second is a bit more complex in that there isn't a direct equivalent in `distutils` to conventional `Makefile`/`autotools` based `@SUBSTITUTION@` notation.

**Comment by TurboTurtle** [comment]
Closing as we no longer use `make`, and the version string will just need to be updated with version bump commits.
