### ISSUE TITLE
[plugins] regression: rpm -Va almost never collected

### ISSUE THREAD

**Issue by pmoravec** [sosreport/sos#986]
`rpm -Va` is not further collected, in case it detects something( * ). The regression is introduced by reasonable commit 77eb4ab and the fact that `rpm -Va` returns 1 if it reports something(*):

    # rpm -Va 2>&1 > rpm.va
    # echo $?
    1
    # wc rpm.va
      1546   3166 130196 rpm.va
    # 

(*) "something" - I would expect `rpm -V` to return 0 regardless whatever it detects, until something is seriously broken (i.e. its database). It is possible it returns nonzero on some types of verify checks only, but that command "failed" the same way on multiple systems. And practically any system has something changed from installed packages (like config files).

As is, I would see it as `rpm` bug but impacting primarily `sos`.

**Comment by bmr-cymru** [comment]
The whole topic of `rpm` exit status is ... complicated :-)

But really: this needs to be controllable by callers of `add_cmd_output()`. I did wonder if we'd see some regressions from 77eb4ab. I'm sure there are other cases too. It's all a bit fragile currently as there is no really clear separation between "collect and store whatever output there is" and "collect output and then parse it" cases.

**Comment by bmr-cymru** [comment]
An ugly but simple workaround for now would be to run the command as: `sh -c "rpm -Va|true"`... :-/

**Comment by pmoravec** [comment]
`rpm -V ..` testing showed it is enough to touch a file belonging to a package to change return value from 0 to 1. Simply, `rpm -V` returns zero only if its output is empty.

That has some logic, taking into account the command performs verification of package(s) and returns the outcome.. (though the return would be false in really many cases).

**Comment by pmoravec** [comment]
Yeah, my idea of ideal-final-fix is to have an option to distinguish between "collect and store whatever output there is" and "collect output and then parse it" cases - in fact it is a matter of one option in few methods.
