### ISSUE TITLE
[Plugins] better source validation for plugin code

### ISSUE THREAD

**Issue by bmr-cymru** [sosreport/sos#994]
Right now there is little validation (beyond Python syntax enforcement) of code in plugins. The `sos` library modules have unit tests which are able to verify the correct behaviour of a function call. Extending this to testing individual `Plugin` classes is somewhat complicated and may not give the desired result since some common plugin errors cannot be detected without some annotation indicating what was intended: e.g. the common `[ "item1", "item2" "item3" ]` list concatenation type of bug: this would need a separate list of the strings the plugin should collect, which both doubles the work and is likely to be just as vulnerable to such typos.

There is a [thread](http://stackoverflow.com/questions/34540634/issue-warning-for-missing-comma-between-list-items-bug) on StackExchange discussing this specific error and discussing ways to detect and report these bugs.

It may be useful to incorporate these types of checks into a "plugin checker" tool to catch these common mistakes.

**Comment by pmoravec** [comment]
+1, and/or maybe add it to TravisCI jobs/checks?

**Comment by bmr-cymru** [comment]
Yep - it would be great to integrate the results of this with both our git hooks and the Travis testing.

**Comment by bmr-cymru** [comment]
We could still use this.

**Comment by bmr-cymru** [comment]
We could still use this.

**Comment by TurboTurtle** [comment]
We now have LGTM integration that does these kinds of python code checks, including the implicit concatenation bugs called out here.

Closing this out at this point. If we find the need to have even more validation beyond LGTM analysis in the future, we can address it then.
